-- schema-v19-descriptions-scuba.sql: 100 scuba challenges description_en (500-1000 chars each)
-- Run after schema-merged-v14-to-v18.sql. Escape single quotes as ''.

UPDATE challenges SET description_en = 'Raja Ampat in Indonesia is consistently ranked the number one dive destination in the world for coral biodiversity. The region holds an estimated 75% of the world''s coral species and over 1,500 species of fish, making it the most species-rich marine environment on Earth. Divers encounter pygmy seahorses, mantas, wobbegongs, and pristine reefs across hundreds of islands. Raja Ampat''s remote location in West Papua has helped preserve its ecosystems. The combination of biodiversity, visibility, and unique marine life places it at the pinnacle of the world''s top 100 dive sites and makes it a once-in-a-lifetime destination for serious divers.' WHERE category = 'scuba' AND title_en = 'Raja Ampat';

UPDATE challenges SET description_en = 'Tubbataha Reefs Natural Park in the Philippines is a UNESCO World Heritage Site and one of the world''s premier remote dive destinations. Located in the middle of the Sulu Sea, the atoll system is accessible only by live-aboard during a short season. The reefs host over 600 species of fish, including whale sharks year-round, and pristine coral walls. Tubbataha was established as a marine park in 1988 and has become a model for marine conservation. Its isolation, biodiversity, and protected status place it firmly in the world top 100 dive sites and make it essential for divers seeking untouched reefs and big animal encounters.' WHERE category = 'scuba' AND title_en = 'Tubbataha Reef';

UPDATE challenges SET description_en = 'Komodo National Park in Indonesia is a UNESCO World Heritage Site and one of the world''s top destinations for manta rays and diverse marine life. Manta Point offers reliable manta aggregations, while the famous hammerhead channel provides thrilling drift dives. The park is also home to the Komodo dragon and features the pink beach reef. Currents can be strong, attracting pelagics and creating nutrient-rich conditions. Komodo''s combination of megafauna, healthy reefs, and unique terrestrial wildlife places it in the world top 100 and makes it a must-dive for those seeking mantas, sharks, and world-class drift diving.' WHERE category = 'scuba' AND title_en = 'Komodo National Park';

UPDATE challenges SET description_en = 'Sipadan Island in Malaysia is often called the turtle capital of the world and ranks among the top five dive sites globally. The island rises from 600 meters and features walls covered in marine life, with barracuda tornadoes of over 1,000 fish and regular hammerhead sightings. Sipadan is a protected marine park with limited daily permits, preserving its pristine condition. The drop-offs, caves, and abundance of turtles and sharks create an unforgettable experience. Sipadan''s unique geology, biodiversity, and strict conservation place it in the world top 100 and make it a bucket-list site for every serious diver.' WHERE category = 'scuba' AND title_en = 'Sipadan Island';

UPDATE challenges SET description_en = 'Milne Bay in Papua New Guinea is a critter paradise and one of the world''s best destinations for macro diving and pygmy seahorses. The region holds world-record densities of pygmy seahorses and is a nudibranch heaven. Milne Bay also offers World War II wreck diving, with planes and ships encrusted in coral. The area''s biodiversity and unique combination of muck diving, reefs, and history place it in the world top 100. Milne Bay appeals to photographers, critter lovers, and history buffs alike, and remains one of the most rewarding and diverse dive destinations in the Pacific.' WHERE category = 'scuba' AND title_en = 'Milne Bay, Papua New Guinea';

UPDATE challenges SET description_en = 'The Mergui Archipelago in Myanmar comprises over 800 largely pristine islands in the Andaman Sea. Access is primarily by live-aboard, and the reefs have remained relatively untouched by mass tourism. Divers encounter healthy coral, reef sharks, and a sense of exploration. The archipelago''s remoteness and unspoiled condition place it in the world top 100. Mergui represents one of the last frontiers of Asian diving and appeals to those seeking adventure, isolation, and the chance to dive reefs that have seen very few divers. Conservation efforts aim to preserve this unique region for future generations.' WHERE category = 'scuba' AND title_en = 'Mergui Archipelago, Myanmar';

UPDATE challenges SET description_en = 'Palau Blue Corner is one of the most famous dives in the world and a defining experience for advanced divers. Divers hook into the reef and drift in the current while grey reef sharks stream past; mantas often join the parade along the wall. The site demands good buoyancy and current handling but rewards with unmatched pelagic action. Blue Corner has shaped the reputation of Palau as a world-class dive destination. Its combination of sharks, current, and drama places it in the world top 100 and makes it a rite of passage for serious divers.' WHERE category = 'scuba' AND title_en = 'Palau Blue Corner';

UPDATE challenges SET description_en = 'Truk Lagoon in Micronesia is the world''s premier wreck diving destination, with over 50 Japanese ships and aircraft sunk in Operation Hailstone in 1944. The lagoon holds intact warships, Zero fighter planes, tanks, and cargo vessels, many encrusted in coral and home to fish and marine life. Truk offers a unique combination of history and diving, with penetration dives possible on many wrecks. The scale and preservation of the fleet place Truk in the world top 100. For wreck enthusiasts and history buffs, Truk Lagoon is the ultimate destination and a living museum of the Pacific War.' WHERE category = 'scuba' AND title_en = 'Truk Lagoon, Micronesia';

UPDATE challenges SET description_en = 'Cocos Island in Costa Rica is a UNESCO World Heritage Site and one of the world''s top destinations for pelagic encounters. The remote island, 500 km offshore, attracts schools of 400 or more hammerhead sharks, whale sharks, and manta rays. Cocos is accessible only by live-aboard and requires a long crossing. The diving is advanced, with strong currents and deep walls, but the reward is some of the most dramatic shark action on Earth. Cocos'' isolation, biodiversity, and big-animal encounters place it in the world top 100 and make it essential for shark lovers and experienced divers.' WHERE category = 'scuba' AND title_en = 'Cocos Island, Costa Rica';

UPDATE challenges SET description_en = 'Darwin Arch in the Galápagos Islands of Ecuador is the pinnacle of Pacific diving, with mass aggregations of whale sharks (40 or more at times), hammerheads, and schools of tuna. The site is advanced, with strong currents and cold water, but offers the best chance in the world to dive with whale sharks in numbers. Darwin and nearby Wolf Island are the crown jewels of Galápagos diving. The unique marine life and the archipelago''s role in conservation place Darwin Arch in the world top 100. It is the ultimate destination for divers seeking the largest fish in the ocean.' WHERE category = 'scuba' AND title_en = 'Darwin Arch, Galápagos';

UPDATE challenges SET description_en = 'Tonga is one of the few places in the world where divers can swim with humpback whales in the water. From August to October, mother-calf pairs and escort males inhabit the warm waters, and licensed operators offer in-water encounters. The experience of being in the water with the largest animals to have ever lived is transformative. Tonga''s strict regulations protect the whales and ensure sustainable tourism. The uniqueness of humpback whale diving places Tonga in the world top 100. For those seeking the ultimate marine mammal encounter, Tonga is the premier destination.' WHERE category = 'scuba' AND title_en = 'Tonga Humpback Whale Dive';

UPDATE challenges SET description_en = 'Palau is home to multiple World War II wrecks in addition to its famous reefs. The Iro tanker, Zero fighters, and Chuyo-Maru are among the vessels that rest in Palauan waters, many encrusted in coral and home to fish and macro life. Palau wreck diving offers a combination of history and marine life, with good visibility and warm water. The wrecks complement the famous reef sites and give divers a full picture of Palau''s underwater world. Palau''s wreck diving places it in the world top 100 and offers something for both reef and wreck enthusiasts.' WHERE category = 'scuba' AND title_en = 'Palau Wrecks, Micronesia';

UPDATE challenges SET description_en = 'Aldabra Atoll in the Seychelles is one of the most remote UNESCO World Heritage Sites and a pristine dive destination. The atoll is home to over 100,000 giant tortoises on land and nurse sharks, Napoleon wrasse, and healthy reefs underwater. Access is limited and carefully managed. Aldabra represents one of the last untouched marine ecosystems and offers a sense of true exploration. The atoll''s remoteness, biodiversity, and conservation status place it in the world top 100. Aldabra is for divers seeking adventure and the chance to dive in one of the world''s most protected and isolated environments.' WHERE category = 'scuba' AND title_en = 'Aldabra Atoll, Seychelles';

UPDATE challenges SET description_en = 'Sodwana Bay in South Africa is part of the iSimangaliso Wetland Park and is famous as the region where the coelacanth was rediscovered. The area offers whale shark encounters, seasonal humpback whales, and diverse reef diving. Sodwana is one of the southernmost tropical dive destinations and attracts divers seeking unique African marine life. The combination of history, megafauna, and reef diving places Sodwana in the world top 100. Sodwana Bay represents the best of South African diving and the opportunity to dive in a UNESCO-recognized marine and terrestrial ecosystem.' WHERE category = 'scuba' AND title_en = 'Sodwana Bay, South Africa';

UPDATE challenges SET description_en = 'Fernando de Noronha in Brazil is a UNESCO Atlantic Marine Park and one of the best dive destinations in the South Atlantic. The archipelago offers spinner dolphins, lemon sharks, and crystal-clear visibility. The marine park is strictly protected, and visitor numbers are limited. Fernando de Noronha combines world-class diving with pristine beaches and a relaxed atmosphere. The island''s unique position in the Atlantic and its conservation success place it in the world top 100. Fernando de Noronha is the premier destination for divers exploring Brazil and the South Atlantic.' WHERE category = 'scuba' AND title_en = 'Fernando de Noronha, Brazil';

UPDATE challenges SET description_en = 'The SS Thistlegorm in the Egyptian Red Sea is the world''s most famous World War II wreck and a bucket-list dive for wreck enthusiasts. Sunk in 1941, the ship holds motorcycles, trucks, and BSA motorcycles in remarkable condition at around 30 meters. The wreck is encrusted in coral and home to fish and barracuda. The Thistlegorm is accessible to intermediate divers and offers multiple dives to explore its holds and deck. Its history, preservation, and marine life place it in the world top 100. The Thistlegorm remains the definitive wreck dive for many divers.' WHERE category = 'scuba' AND title_en = 'SS Thistlegorm, Red Sea';

UPDATE challenges SET description_en = 'The Brothers Islands in Sudan are a remote Red Sea destination in what was once Jacques Cousteau''s territory. The islands offer hammerhead and thresher sharks, oceanic whitetips, and pristine reefs. Access is by live-aboard from Egypt or Sudan, and the diving is advanced due to currents and depth. The Brothers represent the wilder side of the Red Sea and attract experienced divers seeking big sharks and unspoiled conditions. The islands'' reputation and biodiversity place them in the world top 100. The Brothers are for divers who want the Red Sea at its most raw and rewarding.' WHERE category = 'scuba' AND title_en = 'Brothers Islands, Sudan';

UPDATE challenges SET description_en = 'Malpelo Island in Colombia is a UNESCO shark sanctuary and one of the world''s top destinations for hammerhead sharks. Schools of over 1,000 hammerheads, silky sharks, and whale sharks are possible at this remote Pacific island. Malpelo has some of the deepest walls in the region and is accessible only by live-aboard. The island''s protected status has allowed shark populations to thrive. Malpelo''s shark action and isolation place it in the world top 100. For serious shark enthusiasts, Malpelo is one of the premier destinations on Earth.' WHERE category = 'scuba' AND title_en = 'Malpelo Island, Colombia';

UPDATE challenges SET description_en = 'The Great Blue Hole in Belize is a UNESCO-listed giant marine sinkhole nearly 300 meters wide and over 120 meters deep. Jacques Cousteau made it famous, and divers descend past stalactites at around 40 meters. Bull sharks are often seen in the hole. The site is a rite of passage for many divers and one of the most recognizable underwater landmarks. The Great Blue Hole''s geology, history, and iconic status place it in the world top 100. It remains a must-dive for those visiting Belize and one of the most photographed sites in the diving world.' WHERE category = 'scuba' AND title_en = 'Great Blue Hole, Belize';

UPDATE challenges SET description_en = 'Silfra Fissure in Iceland is the only place in the world where you can dive between two tectonic plates (North American and Eurasian). The water is glacial meltwater with 100 meters or more of visibility and temperatures around 2°C. Dry suits are required, and the experience is one of crystal clarity and unique geology. Silfra has become a bucket-list site for divers and snorkelers seeking something truly different. Its uniqueness and visibility place it in the world top 100. Silfra is the definitive cold-water dive and a testament to the variety of the world''s dive sites.' WHERE category = 'scuba' AND title_en = 'Silfra Fissure, Iceland';

UPDATE challenges SET description_en = 'Scapa Flow in Scotland is the premier wreck diving destination in the United Kingdom. In 1919, the German Imperial Fleet was scuttled here, and seven warships remain intact on the bottom. The wrecks are deep and require advanced skills, but they offer a unique window into naval history. Scapa Flow is cold water diving at its best, with clear conditions and historic significance. The site''s place in maritime history and the quality of the wrecks place it in the world top 100. Scapa Flow is essential for wreck divers and anyone interested in World War I history.' WHERE category = 'scuba' AND title_en = 'Scapa Flow, Scotland';

UPDATE challenges SET description_en = 'Tiger Beach in the Bahamas is the tiger shark capital of the world, offering reliable encounters with 3-5 meter tigers in clear, shallow water. Lemon sharks and great hammerheads are also seasonal visitors. The site is a sandy bottom with baited encounters that allow close observation of these apex predators. Tiger Beach has redefined shark diving and is a bucket-list site for shark enthusiasts. The reliability and quality of encounters place it in the world top 100. Tiger Beach is the premier destination for in-water tiger shark experiences.' WHERE category = 'scuba' AND title_en = 'Tiger Beach, Bahamas';

UPDATE challenges SET description_en = 'The SS President Coolidge in Vanuatu is the largest diveable luxury liner wreck in the world. The 22,000-tonne, 180-meter ship sank in 1942 and rests in depths from 20 to 70 meters. Divers can explore Art Deco interiors, the swimming pool, and cargo holds. The wreck is encrusted in coral and home to fish and macro life. The President Coolidge is a multi-dive destination and one of the most impressive wrecks anywhere. Its size, preservation, and diveability place it in the world top 100. The Coolidge is the ultimate wreck for those who want to explore a piece of maritime history.' WHERE category = 'scuba' AND title_en = 'SS President Coolidge, Vanuatu';

UPDATE challenges SET description_en = 'The HMHS Britannic in the Aegean Sea off Kea Island, Greece, is the sister ship of the Titanic and the largest diveable wreck in the world. The 48,000-tonne ship sank in 1916 and rests at depths to 120 meters. Technical divers can explore the wreck, which is largely intact. The Britannic is a piece of maritime history and a pinnacle of wreck diving. Access is restricted and requires advanced certification. The wreck''s size, history, and significance place it in the world top 100. The Britannic is the ultimate goal for many wreck and technical divers.' WHERE category = 'scuba' AND title_en = 'HMHS Britannic Wreck, Aegean';

UPDATE challenges SET description_en = 'Andavadoaka in southwest Madagascar is a pristine and remote dive destination with a whale shark season in June and untouched reefs. The area has worked to balance octopus fishery with conservation and community tourism. Andavadoaka offers the chance to dive in one of the least-visited marine environments in the Indian Ocean. The combination of remoteness, whale sharks, and community-led conservation place it in the world top 100. Andavadoaka is for divers seeking adventure and the chance to support sustainable tourism in a unique part of Madagascar.' WHERE category = 'scuba' AND title_en = 'Andavadoaka, Madagascar';

UPDATE challenges SET description_en = 'Nusa Penida off Bali, Indonesia, is famous for mola-mola (ocean sunfish) encounters from July to November and Manta Point, a cleaning station for manta rays. The island offers drift dives, walls, and the chance to see some of the ocean''s most unusual animals. Currents can be strong, and the diving is best suited to intermediate and advanced divers. Nusa Penida has become a must-do from Bali and complements the island''s cultural and terrestrial attractions. The mola-mola and manta encounters place Nusa Penida in the world top 100 and make it essential for divers visiting Indonesia.' WHERE category = 'scuba' AND title_en = 'Nusa Penida, Bali';

UPDATE challenges SET description_en = 'Richelieu Rock in Thailand is often called Thailand''s best dive site and is famous as a whale shark cleaning station. The pinnacle also hosts seahorses, mantis shrimp, and barracuda schools. Richelieu Rock is in the Andaman Sea and is typically visited on live-aboards or day trips from Phuket or Khao Lak. The site''s biodiversity and the chance of whale sharks place it in the world top 100. Richelieu Rock represents the best of Andaman diving and is a must-dive for anyone visiting Thailand''s west coast.' WHERE category = 'scuba' AND title_en = 'Richelieu Rock, Thailand';

UPDATE challenges SET description_en = 'The Similan Islands in Thailand are a series of granite boulder islands in the Andaman Sea, with diving from November to April. The sites offer leopard sharks, healthy reefs, and clear water. The Similans have been proposed for UNESCO status and are part of a national park. Live-aboards and day trips offer access to the best sites. The islands'' combination of marine life, visibility, and protected status place them in the world top 100. The Similans are the premier destination for divers exploring the Andaman Sea from Thailand.' WHERE category = 'scuba' AND title_en = 'Similan Islands, Thailand';

UPDATE challenges SET description_en = 'Wakatobi in Indonesia is a remote resort and marine national park in Sulawesi, offering pristine house reefs, wall diving, and pygmy seahorses. The tidal channels create nutrient-rich conditions and unique dive experiences. Wakatobi has invested in conservation and sustainable tourism. The resort offers direct access to some of Indonesia''s best reefs without the need for live-aboards. Wakatobi''s combination of quality, accessibility, and conservation place it in the world top 100. It is a top choice for divers seeking world-class Indonesian diving with resort comfort.' WHERE category = 'scuba' AND title_en = 'Wakatobi, Indonesia';

UPDATE challenges SET description_en = 'Bunaken in Indonesia is the wall diving capital of Southeast Asia, with 90-degree vertical walls to 40 meters and beyond. The park features green turtles, barracuda, Napoleon wrasse, and healthy coral. Bunaken is accessible from Manado and offers a range of sites for all levels. The walls are among the most dramatic in the region. Bunaken''s wall diving and biodiversity place it in the world top 100. The park is a must-dive for anyone visiting North Sulawesi and a benchmark for wall diving in the Coral Triangle.' WHERE category = 'scuba' AND title_en = 'Bunaken, Indonesia';

UPDATE challenges SET description_en = 'Apo Island in the Philippines is a community-managed turtle sanctuary and a model for reef recovery. Green sea turtles feed on the coral and are accustomed to divers. The island''s marine reserve has shown how local management can restore fish and coral. Apo Island is accessible from Dumaguete and offers easy diving suitable for all levels. The combination of turtles, community conservation, and healthy reefs place it in the world top 100. Apo Island is essential for divers interested in marine conservation and reliable turtle encounters.' WHERE category = 'scuba' AND title_en = 'Apo Island, Philippines';

UPDATE challenges SET description_en = 'Moalboal in the Philippines is famous for the sardine run, where millions of sardines form a tornado-like ball in shallow water. The site also offers thresher shark encounters nearby and turtle reefs. Moalboal is on Cebu in the Visayas and is accessible to divers of all levels. The sardine tornado is one of the most photogenic and memorable experiences in diving. Moalboal''s unique sardine run and variety of diving place it in the world top 100. It is a must-dive for underwater photographers and anyone seeking a unique schooling fish experience.' WHERE category = 'scuba' AND title_en = 'Moalboal, Philippines';

UPDATE challenges SET description_en = 'Coron Bay in the Philippines is home to a ghost fleet of World War II Japanese wrecks, including 24 vessels. The Irako provisioning ship and the lotus-covered Akitsushima are among the most dived. The wrecks are in relatively shallow water and are encrusted in coral and home to fish. Coron offers a combination of wreck and reef diving and is accessible from Coron town. The concentration of wrecks and the quality of diving place Coron in the world top 100. Coron Bay is the premier wreck diving destination in the Philippines and one of the best in Asia.' WHERE category = 'scuba' AND title_en = 'Coron Bay, Philippines';

UPDATE challenges SET description_en = 'Koh Tao in Thailand is one of the world''s three busiest dive certification destinations and offers accessible diving in the Gulf of Thailand. Whale shark encounters are possible, and the island caters to beginners and advanced divers alike. Koh Tao has helped millions of people discover diving and offers good value and a social atmosphere. The island''s role in dive education and its accessibility place it in the world top 100. Koh Tao represents the gateway to diving for many and remains a popular choice for certification and fun diving in Southeast Asia.' WHERE category = 'scuba' AND title_en = 'Koh Tao, Thailand';

UPDATE challenges SET description_en = 'Malapascua Island in the Philippines is the best place in the world to see thresher sharks on a reliable basis. Divers visit Monad Shoal at sunrise, where threshers come to a cleaning station at around 25 meters. Malapascua is off Cebu and has become a must-dive for shark enthusiasts. The island also offers macro diving and other sites. The thresher shark encounters place Malapascua in the world top 100. For divers seeking this elusive and beautiful shark, Malapascua is the premier destination and a unique experience in the Philippines.' WHERE category = 'scuba' AND title_en = 'Malapascua Island, Philippines';

UPDATE challenges SET description_en = 'Pulau Weh off Sabang, Aceh, Indonesia, offers the Blue Sapphire pinnacle, nudibranch-rich diving, and year-round whale shark potential with visibility to 30 meters. The island is at the northern tip of Sumatra and is less visited than other Indonesian destinations. Pulau Weh combines macro and pelagic opportunities in clear water. The island''s biodiversity and accessibility place it in the world top 100. Pulau Weh is a top choice for divers seeking Indonesian diving off the beaten path with good visibility and variety.' WHERE category = 'scuba' AND title_en = 'Pulau Weh, Indonesia';

UPDATE challenges SET description_en = 'The Solomon Islands offer World War II wreck diving in Iron Bottom Sound, with over 30 wrecks including the USS Aaron Ward. The reefs are pristine and relatively undisturbed, and the combination of history and marine life is unique. Tulagi and surrounding waters attract wreck enthusiasts and those seeking remote Pacific diving. The Solomon Islands'' combination of wrecks, reefs, and isolation place them in the world top 100. The Solomons are for divers seeking adventure and the chance to dive in one of the Pacific''s most historic and unspoiled regions.' WHERE category = 'scuba' AND title_en = 'Solomon Islands';

UPDATE challenges SET description_en = 'Rangiroa in French Polynesia is the world''s second-largest atoll and offers Tiputa Pass, one of the best drift dives in the world. Grey reef sharks parade in the current, and dolphin schools are often seen. Rangiroa is accessible by flight from Tahiti and offers a range of sites. The atoll''s size and the quality of the pass diving place it in the world top 100. Rangiroa represents the best of French Polynesian diving and the chance to experience current diving and sharks in a stunning Pacific setting.' WHERE category = 'scuba' AND title_en = 'Rangiroa, French Polynesia';

UPDATE challenges SET description_en = 'Fakarava in French Polynesia is a UNESCO biosphere reserve and home to the South Pass, where over 700 grey reef sharks have been counted. The pass also hosts grouper spawning and thrilling drift dives. Fakarava offers a combination of shark action and pristine atoll diving. The atoll is accessible by flight from Tahiti. Fakarava''s shark walls and biosphere status place it in the world top 100. Fakarava is the premier destination in French Polynesia for shark lovers and those seeking world-class pass diving.' WHERE category = 'scuba' AND title_en = 'Fakarava, French Polynesia';

UPDATE challenges SET description_en = 'Pacific Harbor in Fiji is home to the Beqa Lagoon bull shark dive, where up to 80 or more bull sharks can be seen in a single dive. The bait-feeding ritual is controversial but has become a landmark of Fijian diving. The area also offers reef sharks and diverse reef diving. Pacific Harbor is on the main island of Viti Levu and is accessible for those who want big shark action without a long live-aboard. The bull shark dive places Pacific Harbor in the world top 100. It is the premier destination in the Pacific for reliable bull shark encounters.' WHERE category = 'scuba' AND title_en = 'Pacific Harbor, Fiji';

UPDATE challenges SET description_en = 'Yap Island in Micronesia is a resident manta ray sanctuary, with mantas present year-round at cleaning stations. Grey reef sharks and mandarin fish are also highlights. Yap is known for its culture and stone money, and the diving complements the cultural experience. The manta encounters are among the most reliable in the world. Yap''s mantas and unique culture place it in the world top 100. Yap is the premier destination for divers seeking guaranteed manta ray encounters in a unique Micronesian setting.' WHERE category = 'scuba' AND title_en = 'Yap Island, Micronesia';

UPDATE challenges SET description_en = 'The Kona Manta Ray Night Dive in Hawaii is the most famous night dive in the world. Divers and snorkelers gather at a site where lights attract plankton, and 20 or more mantas feed in the beam, performing a magical ballet. The experience is suitable for all levels and is run by several operators. The Kona manta dive has become a bucket-list experience and a model for sustainable manta tourism. The uniqueness and reliability of the encounter place it in the world top 100. The Kona manta dive is essential for anyone visiting the Big Island.' WHERE category = 'scuba' AND title_en = 'Kona Manta Ray Night Dive, Hawaii';

UPDATE challenges SET description_en = 'Niue in the South Pacific offers some of the clearest ocean visibility on Earth, with reports of 80 meters or more. The island has sea snakes, seasonal humpback whales, spinner dolphins, and limestone caves. Niue is a small island nation and one of the world''s smallest countries. The diving is accessible from the shore in places and offers a unique combination of clarity and marine life. Niue''s visibility and uniqueness place it in the world top 100. Niue is for divers seeking the clearest water and a truly off-the-beaten-path Pacific experience.' WHERE category = 'scuba' AND title_en = 'Niue, South Pacific';

UPDATE challenges SET description_en = 'North Malé Atoll in the Maldives offers hammerhead pinnacles, tiger sharks, whale sharks, and Napoleon wrasse. Rasdhoo Atoll and its kandu (channel) dives are among the highlights. The Maldives are a classic live-aboard destination, and North Malé is often the start or end of itineraries. The atoll''s combination of pelagics and reef life place it in the world top 100. North Malé represents the best of Maldivian diving and the chance to see big animals in warm, clear water.' WHERE category = 'scuba' AND title_en = 'North Malé Atoll, Maldives';

UPDATE challenges SET description_en = 'Baa Atoll in the Maldives is home to Hanifaru Bay, a UNESCO-recognized site where over 200 manta rays can aggregate to feed, along with whale sharks. The season runs from May to November. Baa Atoll is a biosphere reserve and represents the Maldives at their best for manta and whale shark encounters. Live-aboards and resort stays offer access. Hanifaru Bay and Baa Atoll''s conservation place it in the world top 100. Baa Atoll is the premier destination in the Maldives for manta ray aggregation and big animal encounters.' WHERE category = 'scuba' AND title_en = 'Baa Atoll, Maldives';

UPDATE challenges SET description_en = 'The Andaman Islands of India offer Barracuda City, Pilot Whale Rock, and pristine Bay of Bengal reefs with 12 endemic species. The islands are less visited than many Asian destinations and offer a sense of exploration. The Andamans combine good visibility with unique marine life and cultural interest. Access is from mainland India. The Andamans'' biodiversity and uniqueness place them in the world top 100. The Andaman Islands are the premier dive destination for India and offer a blend of reefs, pelagics, and remoteness.' WHERE category = 'scuba' AND title_en = 'Andaman Islands, India';

UPDATE challenges SET description_en = 'Mafia Island in Tanzania is one of East Africa''s best-kept secrets, with whale sharks from October to March and Chole Bay marine park offering pristine diving with very few visitors. The island is less developed than Zanzibar and offers a more remote experience. Mafia has become a favorite of those seeking whale sharks without the crowds. The island''s whale shark season and pristine reefs place it in the world top 100. Mafia Island is the premier destination for divers seeking East African whale sharks and untouched reefs.' WHERE category = 'scuba' AND title_en = 'Mafia Island, Tanzania';

UPDATE challenges SET description_en = 'Tofo Beach in Mozambique is famous for manta ray aggregations, daily whale shark encounters, dugong grassbeds, and 30-meter wall dives. The area is in Inhambane province and has become a hub for East African diving. Tofo offers a combination of megafauna and reef diving at good value. The whale shark and manta action place Tofo in the world top 100. Tofo Beach is the premier destination for divers exploring Mozambique and one of the best places in the world for whale shark encounters from the shore.' WHERE category = 'scuba' AND title_en = 'Tofo Beach, Mozambique';

UPDATE challenges SET description_en = 'Mayotte in the Indian Ocean is a French territory offering hammerhead schools, whale sharks, dugongs, and turtle nesting. The island is between Madagascar and the Comoros and has a unique blend of French and local culture. Mayotte''s marine life is diverse and the island is less visited than many Indian Ocean destinations. The combination of species and isolation place Mayotte in the world top 100. Mayotte is for divers seeking Indian Ocean megafauna and the chance to dive in a little-known but rewarding destination.' WHERE category = 'scuba' AND title_en = 'Mayotte, Indian Ocean';

UPDATE challenges SET description_en = 'Nosy Be in Madagascar offers whale shark aggregation in October and pristine reefs, with the chance to combine diving with lemur viewing on land. The island is Madagascar''s main tourist destination and has developed dive infrastructure. Nosy Be offers a unique combination of marine and terrestrial wildlife. The whale shark season and the island''s biodiversity place it in the world top 100. Nosy Be is the premier destination for divers visiting Madagascar and seeking whale sharks and island adventure.' WHERE category = 'scuba' AND title_en = 'Nosy Be, Madagascar';

UPDATE challenges SET description_en = 'Ras Mohammed in Egypt is the flagship marine park of the Red Sea and one of the world''s most famous dive destinations. Shark and Yolanda Reef offer walls to 60 meters, glassfish tunnels, and jackfish tornadoes. The park is at the tip of the Sinai Peninsula and is easily accessible from Sharm el-Sheikh. Ras Mohammed has been protected since 1983 and remains in good condition. The park''s reefs and marine life place it in the world top 100. Ras Mohammed is essential for anyone diving the Egyptian Red Sea.' WHERE category = 'scuba' AND title_en = 'Ras Mohammed, Egypt';

UPDATE challenges SET description_en = 'The Blue Hole in Dahab, Egypt, is a famous sinkhole and one of the Red Sea''s most iconic sites. The hole is over 130 meters deep, with a 52-meter arch that tempts freedivers and technical divers. The canyon entry is a classic Dahab dive. The Blue Hole has a sobering history of diver fatalities, and respect for depth and training is essential. The site''s fame and unique geology place it in the world top 100. The Blue Hole is a rite of passage for many Red Sea divers and a symbol of the Sinai''s underwater beauty.' WHERE category = 'scuba' AND title_en = 'Blue Hole Dahab, Egypt';

UPDATE challenges SET description_en = 'Djibouti offers seasonal whale shark aggregation in the Bay of Tadjoura from November to January. The warm waters attract whale sharks that can be encountered by snorkelers and divers. Djibouti is one of the warmest seas for whale shark encounters and offers a unique East African experience. The country is less visited than many dive destinations but is developing its marine tourism. Djibouti''s whale shark season places it in the world top 100. Djibouti is the premier destination for divers seeking whale sharks in the Horn of Africa.' WHERE category = 'scuba' AND title_en = 'Djibouti Whale Shark, Djibouti';

UPDATE challenges SET description_en = 'Eilat in Israel offers Red Sea diving with year-round 21°C water and accessibility for European and Israeli divers. Moses Rock and the Japanese Gardens are among the best sites, with undercut reefs and diverse marine life. Eilat is one of the most accessible Red Sea destinations and has developed a strong dive industry. The combination of accessibility and Red Sea quality place Eilat in the world top 100. Eilat is the premier destination for divers seeking Red Sea diving without traveling to Egypt or Jordan.' WHERE category = 'scuba' AND title_en = 'Eilat, Israel';

UPDATE challenges SET description_en = 'Aqaba in Jordan is the Red Sea''s affordable gateway, with the Cedar Pride wreck at 30 meters, a tank wreck at 10 meters, and Rainbow Reef walls. Aqaba offers a combination of wreck and reef diving and is easily combined with visits to Petra and Wadi Rum. The Jordanian Red Sea is less crowded than the Egyptian side. Aqaba''s accessibility and variety place it in the world top 100. Aqaba is the premier destination for divers combining Middle Eastern culture and Red Sea diving.' WHERE category = 'scuba' AND title_en = 'Aqaba, Jordan';

UPDATE challenges SET description_en = 'Aliwal Shoal in South Africa is a ragged-tooth (sand tiger) shark sanctuary and one of the best shark diving destinations in the world. Oceanic blacktip and tiger sharks are also possible. The shoal has three wrecks offshore and is in KwaZulu-Natal. Aliwal is a year-round destination and offers both reef and shark dives. The ragged-tooth aggregations place Aliwal in the world top 100. Aliwal Shoal is essential for shark enthusiasts visiting South Africa and one of the best places to see sand tiger sharks in the world.' WHERE category = 'scuba' AND title_en = 'Aliwal Shoal, South Africa';

UPDATE challenges SET description_en = 'Watamu Marine Park in Kenya is East Africa''s coral garden and offers whale shark season, sea turtles, and Turtle Bay protected marine area. The park is part of Kenya''s effort to protect its coastline and develop sustainable tourism. Watamu offers a combination of reef diving and the chance to see megafauna. The park''s conservation and marine life place it in the world top 100. Watamu is the premier destination for divers exploring Kenya''s coast and seeking East African marine life in a protected setting.' WHERE category = 'scuba' AND title_en = 'Watamu Marine Park, Kenya';

UPDATE challenges SET description_en = 'Mnemba Atoll off Zanzibar, Tanzania, offers East African turtle cleaning stations, spinner dolphins, manta rays, and a pristine lagoon. The atoll is associated with an exclusive island resort but can be dived from Zanzibar. Mnemba combines clear water with diverse marine life and is one of the best sites in the Zanzibar region. The atoll''s quality and variety place it in the world top 100. Mnemba is the premier destination for divers seeking the best of Zanzibar and East African island diving.' WHERE category = 'scuba' AND title_en = 'Mnemba Atoll, Zanzibar';

UPDATE challenges SET description_en = 'The cenotes of the Yucatán in Mexico are an underwater cave system with crystal freshwater, stalactites, and the famous halocline curtain where fresh and salt water meet. The cenotes are part of the Riviera Maya and offer a unique diving experience unlike any ocean dive. Training and guided dives are essential. The cenotes'' uniqueness and beauty place them in the world top 100. The Yucatán cenotes are the premier destination for cavern and cave diving and one of the most memorable experiences in the diving world.' WHERE category = 'scuba' AND title_en = 'Cenotes Yucatan, Mexico';

UPDATE challenges SET description_en = 'Cozumel in Mexico is the Caribbean drift diving classic, with Palancar Reef wall, Santa Rosa Canyon, and turtle cleaning stations. The island has been a dive destination for decades and offers reliable visibility and warm water. Cozumel is suitable for all levels and is one of the most accessible Caribbean destinations. The island''s reefs and drift diving place it in the world top 100. Cozumel remains the benchmark for Caribbean diving and a must-visit for anyone exploring the Mesoamerican reef.' WHERE category = 'scuba' AND title_en = 'Cozumel, Mexico';

UPDATE challenges SET description_en = 'Jardines de la Reina in Cuba is a pristine Caribbean coral reef system accessible only by live-aboard. The gardens offer permit, tarpon, silky sharks, and exceptional grouper density. Cuba''s isolation has helped preserve the reefs, and the area is now a model for sustainable marine tourism. Jardines de la Reina is for experienced divers seeking untouched Caribbean reefs. The archipelago''s pristine condition and marine life place it in the world top 100. Jardines de la Reina is the premier destination for divers seeking the best of Cuba and the Caribbean.' WHERE category = 'scuba' AND title_en = 'Jardines de la Reina, Cuba';

UPDATE challenges SET description_en = 'Roatan in Honduras is part of the Bay Islands and the Mesoamerican Barrier Reef, the second-largest reef system in the world. The island offers whale shark encounters, wall diving, and accessible Caribbean conditions. Roatan has developed as a dive destination with good value and variety. The island''s combination of reefs and megafauna place it in the world top 100. Roatan is a top choice for divers seeking Caribbean diving with the chance of whale sharks and a relaxed island atmosphere.' WHERE category = 'scuba' AND title_en = 'Roatan, Honduras';

UPDATE challenges SET description_en = 'The Belize Barrier Reef is the second-largest reef system in the world and a UNESCO World Heritage Site. The reef offers nurse sharks sleeping in caves, manatees, and over 500 species of fish along the coast. Belize has invested in marine protection and offers a range of sites from the Great Blue Hole to shallow reefs. The barrier reef''s size and biodiversity place it in the world top 100. Belize is essential for divers exploring the western Caribbean and seeking a combination of reefs, sharks, and the Blue Hole.' WHERE category = 'scuba' AND title_en = 'Belize Barrier Reef';

UPDATE challenges SET description_en = 'The Bat Islands in Costa Rica offer a bull shark congregation in strong currents off Guanacaste, with 50 or more bulls possible from July to December. The diving is advanced due to currents and depth. The Bat Islands have become one of the best places in the world for reliable bull shark encounters. The site complements Costa Rica''s other diving, including Cocos Island. The Bat Islands'' bull shark action places them in the world top 100. The Bat Islands are the premier destination for divers seeking bull sharks in the eastern Pacific.' WHERE category = 'scuba' AND title_en = 'Bat Islands, Costa Rica';

UPDATE challenges SET description_en = 'Coiba Island in Panama is a UNESCO World Heritage Site in the Pacific, offering whale sharks, humpback whales, and endemic species in a pristine and isolated setting. Coiba was a penal colony until 2004, which helped preserve the marine environment. The island is accessible by live-aboard or day trip and offers a combination of pelagics and reefs. Coiba''s isolation and biodiversity place it in the world top 100. Coiba Island is the premier destination for divers seeking Pacific Panama and the chance to dive in one of the region''s most protected environments.' WHERE category = 'scuba' AND title_en = 'Coiba Island, Panama';

UPDATE challenges SET description_en = 'The Azores in Portugal offer blue shark cage diving, sperm whale snorkeling, and six species of sharks in a mid-Atlantic volcanic setting. The islands are a stepping stone between Europe and North America and have unique marine life. The Azores have developed responsible shark and whale tourism. The combination of sharks, whales, and volcanic geology place the Azores in the world top 100. The Azores are the premier destination for divers and snorkelers seeking cold-water megafauna in the Atlantic.' WHERE category = 'scuba' AND title_en = 'Azores, Portugal';

UPDATE challenges SET description_en = 'El Hierro Marine Reserve in Spain was Europe''s first biosphere reserve and offers diving with angel sharks, barracuda, and endemic fish in lava tube formations. The island is the smallest of the Canaries and has invested in marine protection. El Hierro offers a unique combination of volcanic geology and marine life. The reserve''s status and biodiversity place it in the world top 100. El Hierro is the premier destination for divers seeking the best of Canary Islands diving and angel shark encounters.' WHERE category = 'scuba' AND title_en = 'El Hierro Marine Reserve, Spain';

UPDATE challenges SET description_en = 'Norway fjord diving offers cold-water clarity of 30 meters or more, with Atlantic halibut, wolf fish, and plumose anemone walls. The fjords are accessible from towns like Bergen and offer a unique cold-water experience. Dry suits are required, and the diving is suitable for those with cold-water experience. Norway''s fjord diving places it in the world top 100. Norway is the premier destination for divers seeking cold-water diving in stunning Scandinavian scenery and the chance to see species not found in tropical waters.' WHERE category = 'scuba' AND title_en = 'Norway Fjord Diving, Norway';

UPDATE challenges SET description_en = 'Kosterfjorden in Sweden is Sweden''s deepest point and offers sea fan meadows, nudibranchs in September, and cold Nordic fjord diving. The area is in the Koster Islands and has been protected. Kosterfjorden offers a unique cold-water experience in the North Sea. The fjord''s depth and marine life place it in the world top 100. Kosterfjorden is the premier destination for divers seeking Scandinavian cold-water diving and the chance to explore Sweden''s underwater wilderness.' WHERE category = 'scuba' AND title_en = 'Kosterfjorden, Sweden';

UPDATE challenges SET description_en = 'Easter Island in Chile offers some of the clearest water in the Pacific, an underwater Moai sculpture garden, and over 100 species of fish including endemics. The island is one of the most remote inhabited places on Earth. Diving Easter Island is a combination of culture and marine life. The island''s uniqueness and clarity place it in the world top 100. Easter Island is the premier destination for divers seeking the ultimate Pacific adventure and the chance to dive in one of the world''s most iconic and isolated locations.' WHERE category = 'scuba' AND title_en = 'Easter Island, Chile';

UPDATE challenges SET description_en = 'The Great Barrier Reef in Australia is the world''s largest reef system, stretching 2,300 km and listed as a UNESCO World Heritage Site. The reef offers Cod Hole with potato grouper, winter Minke whale encounters, and countless reefs and species. The Great Barrier Reef has faced challenges but remains one of the most diverse marine ecosystems on Earth. The reef''s scale and biodiversity place it in the world top 100. The Great Barrier Reef is the definitive reef diving destination and a natural wonder that every diver should experience.' WHERE category = 'scuba' AND title_en = 'Great Barrier Reef, Australia';

UPDATE challenges SET description_en = 'Ningaloo Reef in Western Australia offers whale shark snorkeling from March to July and manta ray cleaning stations. The reef is one of the best places in the world for reliable whale shark encounters from the shore. Ningaloo is less developed than the Great Barrier Reef and offers a more remote experience. The reef''s whale shark season and marine life place it in the world top 100. Ningaloo is the premier destination for divers and snorkelers seeking whale sharks in Australia and one of the best shore-based whale shark experiences globally.' WHERE category = 'scuba' AND title_en = 'Ningaloo Reef, Australia';

UPDATE challenges SET description_en = 'Lord Howe Island in Australia has the world''s southernmost coral reef and offers Ball''s Pyramid, garibaldi fish, and clear subtropical water. The island is a UNESCO World Heritage Site and has limited visitor numbers. Lord Howe offers a unique combination of temperate and tropical species. The island''s uniqueness and protection place it in the world top 100. Lord Howe Island is the premier destination for divers seeking Australian island diving and the chance to explore the world''s southernmost coral reef.' WHERE category = 'scuba' AND title_en = 'Lord Howe Island, Australia';

UPDATE challenges SET description_en = 'New Caledonia Shark Bay is part of the Pacific''s largest lagoon, a UNESCO site, and offers bull shark feeding at Boulari Pass and Napoleon wrasse. New Caledonia is a French territory with a unique blend of Pacific and French culture. The lagoon''s size and the shark feeding place New Caledonia in the world top 100. New Caledonia is the premier destination for divers seeking French Pacific diving and the chance to see bull sharks in a stunning lagoon setting.' WHERE category = 'scuba' AND title_en = 'New Caledonia Shark Bay';

UPDATE challenges SET description_en = 'Norfolk Island in the Pacific offers the wreck of HMAS Sirius from 1790, big fish aggregations, coral-covered reefs, and remote Pacific clarity. The island is between Australia and New Zealand and has a small population. Norfolk Island diving is for those seeking history and isolation. The wreck and the island''s uniqueness place it in the world top 100. Norfolk Island is the premier destination for divers seeking Pacific wreck diving and the chance to dive in one of the region''s most remote locations.' WHERE category = 'scuba' AND title_en = 'Norfolk Island, Pacific';

UPDATE challenges SET description_en = 'Saipan Blue Hole in the Northern Mariana Islands is a vertical sinkhole of 27 meters with a World War II Japanese Zero fighter at 30 meters and grotto formations in crystal-clear water. Saipan is a U.S. territory in the western Pacific. The Blue Hole and the wreck offer a unique combination of geology and history. The site''s uniqueness and clarity place it in the world top 100. Saipan Blue Hole is the premier destination for divers seeking Pacific island diving and the chance to dive a sinkhole and historic wreck in one site.' WHERE category = 'scuba' AND title_en = 'Saipan Blue Hole, Northern Marianas';

UPDATE challenges SET description_en = 'Jellyfish Lake in Palau is a snorkeling site where millions of stingless jellyfish drift in a unique lake ecosystem on Eil Malk Island. The lake is a UNESCO site and the jellyfish have evolved without stinging cells in the absence of predators. Snorkeling among the jellyfish is a once-in-a-lifetime experience. Access is regulated to protect the lake. Jellyfish Lake''s uniqueness places it in the world top 100. Jellyfish Lake is essential for anyone visiting Palau and one of the most unusual snorkeling experiences in the world.' WHERE category = 'scuba' AND title_en = 'Jellyfish Lake, Palau';

UPDATE challenges SET description_en = 'Subic Bay in the Philippines holds World War II U.S. Navy wrecks including the El Capitan and Oryoku Maru, with octopus colonies and easy dive training conditions. Subic is accessible from Manila and offers a combination of history and accessibility. The wrecks are in relatively shallow water and suitable for a range of certification levels. Subic Bay''s wrecks and accessibility place it in the world top 100. Subic Bay is the premier destination for divers seeking Philippine wreck diving and the chance to explore World War II history close to Manila.' WHERE category = 'scuba' AND title_en = 'Subic Bay Wrecks, Philippines';

UPDATE challenges SET description_en = 'Green Island in Taiwan is Taiwan''s best diving, with a rare underwater hot spring, 230 species of coral, and manta cleaning stations. The island is off the east coast of Taiwan and offers a unique combination of volcanic activity and marine life. Green Island has developed as a dive destination with good infrastructure. The island''s hot spring and biodiversity place it in the world top 100. Green Island is the premier destination for divers exploring Taiwan and seeking a unique combination of geothermal and marine environments.' WHERE category = 'scuba' AND title_en = 'Green Island, Taiwan';

UPDATE challenges SET description_en = 'Koh Lipe in Thailand offers Andaman Sea clarity, leopard sharks, giant clams, and soft coral in the Adang Island archipelago. Koh Lipe has developed from a backpacker destination to a popular dive base. The island offers day trips and live-aboards to the best sites. Koh Lipe''s clarity and marine life place it in the world top 100. Koh Lipe is a top choice for divers seeking Andaman diving with a relaxed island atmosphere and good visibility.' WHERE category = 'scuba' AND title_en = 'Koh Lipe, Thailand';

UPDATE challenges SET description_en = 'Mauritius offers an underwater sand waterfall illusion, whale shark season, and the 25-meter Cathedral dive wall. The island is in the Indian Ocean and has a mix of reef and pelagic diving. Mauritius has developed as a dive destination with good infrastructure and variety. The sand waterfall and whale sharks place Mauritius in the world top 100. Mauritius is the premier destination for divers seeking Indian Ocean diving with unique geological features and megafauna.' WHERE category = 'scuba' AND title_en = 'Mauritius';

UPDATE challenges SET description_en = 'The Comoro Islands are a coelacanth sanctuary, where the living fossil fish (400 million years old) can be found in Mohéli Marine Park. The islands also offer whale shark encounters. The Comoros are one of the world''s least-developed nations and offer a sense of exploration. The coelacanth and whale sharks place the Comoros in the world top 100. The Comoro Islands are the premier destination for divers seeking the coelacanth and the chance to dive in one of the Indian Ocean''s most unique and little-visited regions.' WHERE category = 'scuba' AND title_en = 'Comoro Islands';

UPDATE challenges SET description_en = 'The Lakshadweep Islands of India are a pristine Indian Ocean atoll system with manta rays, barracuda, and 36 atolls with untouched reefs. Access to the islands is restricted, helping preserve the marine environment. The Lakshadweep offer a unique combination of Indian culture and pristine diving. The atolls'' condition and marine life place them in the world top 100. The Lakshadweep Islands are the premier destination for divers seeking Indian Ocean atoll diving and the chance to explore one of India''s most remote and protected marine areas.' WHERE category = 'scuba' AND title_en = 'Lakshadweep Islands, India';

UPDATE challenges SET description_en = 'Muscat and the Daymaniyat Islands in Oman offer a marine reserve with green turtle nesting, spinner dolphins, and seasonal dugong sightings. Oman has invested in marine protection and is developing as a dive destination. The Daymaniyat Islands are accessible from Muscat and offer a range of sites. Oman''s marine reserve and wildlife place it in the world top 100. Muscat and Daymaniyat are the premier destination for divers seeking Arabian Peninsula diving and the chance to see turtles and dugongs in a protected setting.' WHERE category = 'scuba' AND title_en = 'Muscat Daymaniyat, Oman';

UPDATE challenges SET description_en = 'NEOM Red Sea in Saudi Arabia is an untouched section of the Red Sea that is opening for diving, with pristine reefs, endemic species, and pristine visibility. Saudi Arabia is investing in tourism and NEOM is at the forefront. The Red Sea coast has some of the best reefs in the region. NEOM''s pristine condition and potential place it in the world top 100. NEOM is the premier destination for divers seeking to be among the first to explore a new Red Sea frontier and untouched Saudi reefs.' WHERE category = 'scuba' AND title_en = 'NEOM Red Sea, Saudi Arabia';

UPDATE challenges SET description_en = 'Tyre Marine Reserve in Lebanon offers Byzantine columns at 10 meters, Phoenician anchors, and amphora fields in the Mediterranean. Tyre is one of the oldest continuously inhabited cities and has a rich maritime history. The reserve protects both cultural and natural heritage. Tyre''s combination of history and diving place it in the world top 100. Tyre Marine Reserve is the premier destination for divers seeking Mediterranean diving and the chance to explore ancient history underwater.' WHERE category = 'scuba' AND title_en = 'Tyre Marine Reserve, Lebanon';

UPDATE challenges SET description_en = 'The Zenobia wreck in Cyprus is the best wreck in the Mediterranean, a 178-meter Swedish ferry that sank on its maiden voyage in 1980 and rests at 42 meters. The wreck is intact and can be penetrated in many areas. The Zenobia has become a rite of passage for Mediterranean wreck divers. The wreck''s size, condition, and accessibility place it in the world top 100. The Zenobia is the premier destination for wreck divers in Europe and one of the best wreck dives in the world.' WHERE category = 'scuba' AND title_en = 'Zenobia, Cyprus';

UPDATE challenges SET description_en = 'Lanzarote MUSA in Spain is an underwater sculpture museum with over 300 artworks that have been colonized by sea life. The museum is in the Canary Islands and was created to create an artificial reef and draw visitors away from stressed natural sites. The sculptures have become home to fish and marine life. MUSA''s uniqueness and art place it in the world top 100. Lanzarote MUSA is the premier destination for divers seeking something different and the chance to dive among art and marine life in the Canary Islands.' WHERE category = 'scuba' AND title_en = 'Lanzarote MUSA, Spain';

UPDATE challenges SET description_en = 'Marseille Calanques in France is a marine park with fan corals, octopus, gorgonians, and a World War II landing craft wreck, plus rare moray eels. The calanques are dramatic limestone inlets along the Mediterranean coast. The park has been established to protect the marine environment. The calanques'' beauty and marine life place them in the world top 100. Marseille Calanques is the premier destination for divers seeking Mediterranean France and the chance to dive in a stunning national park.' WHERE category = 'scuba' AND title_en = 'Marseille Calanques, France';

UPDATE challenges SET description_en = 'Hvar in Croatia offers Adriatic sea caves, Vis Island World War II wrecks, and the blue cave with bioluminescence in clear Adriatic water. Croatia has developed as a dive destination with a mix of history and natural sites. Hvar is one of the most popular islands and offers good infrastructure. Croatia''s caves and wrecks place it in the world top 100. Hvar is the premier destination for divers seeking Adriatic diving and the chance to explore caves and wrecks in clear, historic waters.' WHERE category = 'scuba' AND title_en = 'Hvar, Croatia';

UPDATE challenges SET description_en = 'Santorini Caldera in Greece offers volcanic diving with fumarole bubbles, Roman amphora fields, and unique Mediterranean geology. The caldera was formed by one of the largest volcanic eruptions in history. Santorini is one of the most visited islands in Greece and offers a unique underwater experience. The caldera''s geology and history place it in the world top 100. Santorini is the premier destination for divers seeking volcanic diving and the chance to explore the underwater legacy of one of the world''s most famous islands.' WHERE category = 'scuba' AND title_en = 'Santorini Caldera, Greece';

UPDATE challenges SET description_en = 'Bodrum wrecks in Turkey offer Aegean ancient wrecks including 7th-century Byzantine ships, amphora trails, and the Castle of St. Peter as a backdrop. Bodrum is on the Turkish coast and has a rich maritime history. The wrecks are accessible and offer a combination of history and marine life. Turkey''s ancient wrecks place it in the world top 100. Bodrum is the premier destination for divers seeking ancient Mediterranean wrecks and the chance to dive in one of the birthplaces of Western civilization.' WHERE category = 'scuba' AND title_en = 'Bodrum Wrecks, Turkey';

UPDATE challenges SET description_en = 'Menorca sea caves in Spain offer Mediterranean sea caves, a 7th-century Byzantine wreck at San Nicolau, and posidonia meadows. Menorca is the quieter sister of Mallorca and has protected much of its coast. The caves and wreck offer a combination of geology and history. Menorca''s caves and history place it in the world top 100. Menorca is the premier destination for divers seeking Mediterranean cave diving and the chance to explore historic wrecks in the Balearic Islands.' WHERE category = 'scuba' AND title_en = 'Menorca Sea Caves, Spain';

UPDATE challenges SET description_en = 'The Florida Keys in the USA are home to John Pennekamp Coral Reef State Park, the first underwater park in America, and the Christ of the Abyss statue at 25 meters. The Keys offer reef diving along the only living coral barrier reef in the continental United States. The Keys are accessible and offer a range of sites for all levels. The Keys'' history and reefs place them in the world top 100. The Florida Keys are the premier destination for American divers seeking Caribbean-style diving without leaving the United States.' WHERE category = 'scuba' AND title_en = 'Florida Keys, USA';

UPDATE challenges SET description_en = 'Florida Springs in the USA offer Crystal River and other cave springs with 22°C year-round water, manatee winter sanctuary, and 30 meters of clarity. The springs are a unique freshwater environment and one of the best places in the world to swim with manatees. Cave diving training is available for qualified divers. The springs'' clarity and manatees place them in the world top 100. Florida Springs are the premier destination for divers and snorkelers seeking manatees and the chance to explore one of the world''s most extensive spring systems.' WHERE category = 'scuba' AND title_en = 'Florida Springs, USA';

UPDATE challenges SET description_en = 'Baja California Sea of Cortez in Mexico offers Cabo Pulmo Marine Park, mobula ray tornadoes, playful sea lions, and whale shark season. The Sea of Cortez is often called the aquarium of the world. Baja has become a premier destination for marine mammal encounters and pelagic action. The sea''s biodiversity and Cabo Pulmo place it in the world top 100. Baja California is the premier destination for divers seeking the Sea of Cortez and the chance to dive with sea lions and mobula rays in one of the world''s most productive seas.' WHERE category = 'scuba' AND title_en = 'Baja California Sea of Cortez';

UPDATE challenges SET description_en = 'The RMS Rhone in the British Virgin Islands is a classic Caribbean wreck, the 1867 HMS Rhone with 120 years of coral growth, the bow at 8 meters and the stern at 24 meters. The wreck is one of the most dived in the Caribbean and was featured in the film The Deep. The Rhone offers a combination of history and marine life. The wreck''s fame and condition place it in the world top 100. The RMS Rhone is the premier wreck dive in the Caribbean and a must-do for anyone visiting the British Virgin Islands.' WHERE category = 'scuba' AND title_en = 'RMS Rhone, British Virgin Islands';

UPDATE challenges SET description_en = 'Campbell River in Canada offers giant Pacific octopus, wolf eels, plumose anemones, and nudibranchs in cold Pacific diving. British Columbia is one of the best cold-water dive destinations in the world. Campbell River is known for its octopus and the chance to see some of the largest octopus species. Dry suits are required. Campbell River''s cold-water life place it in the world top 100. Campbell River is the premier destination for divers seeking cold-water Pacific diving and the chance to see giant octopus and wolf eels.' WHERE category = 'scuba' AND title_en = 'Campbell River, Canada';

UPDATE challenges SET description_en = 'Bermuda offers over 300 Atlantic wrecks, Bermuda Triangle mystique, moray eels, and clear water wreck diving. The island has been a shipwreck hotspot for centuries due to its reefs and storms. Bermuda has developed as a dive destination with good infrastructure and a range of wrecks from different eras. Bermuda''s wreck concentration and clarity place it in the world top 100. Bermuda is the premier destination for divers seeking Atlantic wreck diving and the chance to explore one of the world''s most famous wreck graveyards.' WHERE category = 'scuba' AND title_en = 'Bermuda';

UPDATE challenges SET description_en = 'Stingray City in the Cayman Islands is a Grand Cayman sandbar where hundreds of friendly southern stingrays gather and can be fed and touched by snorkelers. The site is one of the most famous snorkel and first-dive experiences in the world. Stingray City has been operating for decades and the rays are accustomed to people. The site''s accessibility and uniqueness place it in the world top 100. Stingray City is essential for anyone visiting the Cayman Islands and one of the best places in the world for a first encounter with stingrays.' WHERE category = 'scuba' AND title_en = 'Stingray City, Cayman Islands';
