-- schema-v19-descriptions-festivals.sql: Extended English descriptions for festivals category (world 100)
-- Each description_en 500-700 characters: why world 100, origin, what happens, when and where to experience.

UPDATE challenges SET description_en = 'Rio Carnival is the world''s biggest carnival: samba schools parade in the Sambadrome, and millions dance in the street blocos. The party runs from Friday before Ash Wednesday until the following Tuesday. Rio de Janeiro becomes a city of costume, music, and celebration. Tickets for the Sambadrome parades sell out; street parties are free. Rio Carnival is the ultimate expression of Brazilian joy and one of the world''s top 100 festivals.' WHERE category = 'festivals' AND title_en = 'Rio Carnival';

UPDATE challenges SET description_en = 'Oktoberfest in Munich is the world''s largest beer festival, drawing over six million visitors each year. It runs from late September to the first Sunday in October. Massive tents serve beer by the litre; dirndl and lederhosen are the dress code. Brass bands, roast chicken, and pretzels complete the scene. Book tables months ahead or arrive early for space. Oktoberfest is a bucket-list celebration and one of the world''s most famous festivals.' WHERE category = 'festivals' AND title_en = 'Oktoberfest';

UPDATE challenges SET description_en = 'La Tomatina is Spain''s tomato fight, held in Buñol on the last Wednesday of August. About 150 tonnes of tomatoes are thrown in an hour of chaos. Participants wear old clothes and goggles; the town runs red. The event is tightly regulated; tickets are required. La Tomatina is one of the world''s messiest and most photogenic festivals. Join the crowd for a once-in-a-lifetime food fight.' WHERE category = 'festivals' AND title_en = 'La Tomatina';

UPDATE challenges SET description_en = 'Diwali, the Festival of Lights, is India''s biggest Hindu celebration. Clay diyas (lamps), fireworks, Rangoli designs, and Lakshmi worship mark the triumph of light over darkness. The date follows the lunar calendar (usually October or November). Families gather, sweets are shared, and cities glow. Experience it in Varanasi, Jaipur, or Amritsar for maximum spectacle. Diwali is one of the world''s most beautiful and spiritually significant festivals.' WHERE category = 'festivals' AND title_en = 'Diwali';

UPDATE challenges SET description_en = 'Holi is the Hindu Festival of Colours, celebrating spring and the victory of good over evil. People throw gulaal (coloured powder) and water; the streets become a rainbow. Mathura and Vrindavan host the most traditional celebrations. The eve features bonfires. Holi falls in March; wear clothes you can discard. Holi is one of the world''s most joyful and photogenic festivals and a bucket-list experience.' WHERE category = 'festivals' AND title_en = 'Holi';

UPDATE challenges SET description_en = 'Naadam Festival in Mongolia celebrates the three manly games: wrestling, horse racing, and archery. It takes place in Ulaanbaatar on July 11–12 (National Day). Wrestlers wear traditional costume; child jockeys race across the steppe. Naadam is the soul of Mongolian culture and a window into nomadic heritage. Attend the opening ceremony and stadium events for the full experience. It is one of the world''s most unique festivals.' WHERE category = 'festivals' AND title_en = 'Naadam Festival';

UPDATE challenges SET description_en = 'Songkran is the Thai New Year water festival in mid-April. Water fights fill the streets; Thais wash Buddha images and elders'' hands for blessing. Chiang Mai hosts the biggest celebrations, with parades and traditional ceremonies. Expect to get soaked; protect phones and cameras. Songkran is Thailand''s most famous festival and one of the world''s most fun and inclusive water celebrations.' WHERE category = 'festivals' AND title_en = 'Songkran';

UPDATE challenges SET description_en = 'Guy Fawkes Night on November 5 commemorates the failed Gunpowder Plot of 1605. Bonfires and fireworks light the UK; Lewes in Sussex holds one of the largest and most dramatic events. Effigies and processions add to the atmosphere. Wrap up warm and join a local display. Guy Fawkes Night is a quintessential British tradition and one of the world''s most atmospheric fire festivals.' WHERE category = 'festivals' AND title_en = 'Guy Fawkes Night';

UPDATE challenges SET description_en = 'The Edinburgh Festival Fringe is the world''s largest arts festival: thousands of performances in August across comedy, theatre, dance, and more. Many shows are free or pay-what-you-want. The Royal Mile is packed with flyers and street performers. Book popular acts in advance or take a chance on unknowns. The Fringe is a celebration of creativity and one of the world''s top 100 festivals.' WHERE category = 'festivals' AND title_en = 'Edinburgh Fringe';

UPDATE challenges SET description_en = 'Venice Carnival is two weeks of masks and costumes in February, centred on Piazza San Marco. Elaborate period dress and masquerade balls evoke the Serenissima. The flight of the angel and other events are iconic. Masks are mandatory in some venues. Venice Carnival is one of the world''s most romantic and visually stunning festivals. Book accommodation and balls well ahead.' WHERE category = 'festivals' AND title_en = 'Venice Carnival';

UPDATE challenges SET description_en = 'WOMAD (World of Music, Arts and Dance) was founded by Peter Gabriel and brings artists from over 50 countries to Charlton Park in England. The festival combines world music, arts, and dance in a family-friendly setting. It has spawned WOMAD festivals worldwide. Summer dates; camping and day tickets available. WOMAD is a pioneer of global music festivals and one of the world''s most diverse cultural events.' WHERE category = 'festivals' AND title_en = 'WOMAD';

UPDATE challenges SET description_en = 'Día de los Muertos (Day of the Dead) in Mexico is when families honour the deceased with altars, marigolds, sugar skulls, and offerings. Oaxaca is the epicentre: cemetery vigils, parades, and street art. The celebration runs October 31–November 2 and is UNESCO-recognised. It is joyful, not morbid. Día de los Muertos is one of the world''s most beautiful and meaningful festivals.' WHERE category = 'festivals' AND title_en = 'Día de los Muertos';

UPDATE challenges SET description_en = 'The Lantern Festival (Yi Peng in Thailand) marks the 15th day of the lunar month with thousands of sky lanterns released in Chiang Mai. The sight is romantic and photogenic. Loy Krathong often coincides, with floating baskets on water. Respect local rules and the environment. The Lantern Festival is one of the world''s most magical and Instagram-famous celebrations.' WHERE category = 'festivals' AND title_en = 'Lantern Festival';

UPDATE challenges SET description_en = 'Hanukkah, the Jewish Festival of Lights, lasts eight nights. A menorah is lit each night; dreidel, latkes, and sufganiyot are traditional. Jerusalem''s Old City and Jewish quarters worldwide celebrate. The dates follow the Hebrew calendar (usually December). Hanukkah is a family-centred celebration and one of the world''s most enduring religious festivals.' WHERE category = 'festivals' AND title_en = 'Hanukkah';

UPDATE challenges SET description_en = 'Hanami (cherry blossom viewing) in Japan is spring picnic parties under the sakura. Kyoto''s Maruyama Park and Tokyo''s Ueno Park are famous. The bloom moves north from late March to May; timing is critical. Hanami is casual and celebratory. It is one of Japan''s most beloved traditions and one of the world''s most beautiful seasonal festivals.' WHERE category = 'festivals' AND title_en = 'Hanami Cherry Blossom';

UPDATE challenges SET description_en = 'The Pushkar Camel Fair in Rajasthan draws tens of thousands of camels, traders, and visitors to the desert town. Hot air balloons, musicians, and competitions fill the week. The fair coincides with Kartik Purnima (November). Pushkar is sacred; respect local customs. The camel fair is one of India''s most colourful and photogenic events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Pushkar Camel Fair';

UPDATE challenges SET description_en = 'Glastonbury Festival at Worthy Farm in England is the world''s most famous music festival. The Pyramid Stage, 200,000 attendees, and a mix of rock, pop, and alternative define it. Tickets sell out in minutes. June dates; prepare for mud and crowds. Glastonbury is a cultural institution and one of the world''s top 100 festivals.' WHERE category = 'festivals' AND title_en = 'Glastonbury Festival';

UPDATE challenges SET description_en = 'Coachella in the California desert is a two-weekend arts and music festival at the Empire Polo Club in April. Headliners span rock, hip-hop, and electronic; art installations and celebrity sightings are part of the scene. Desert heat and fashion define the vibe. Coachella has shaped festival culture worldwide and is one of the world''s most influential and glamorous festivals.' WHERE category = 'festivals' AND title_en = 'Coachella';

UPDATE challenges SET description_en = 'Burning Man in Nevada''s Black Rock Desert is a temporary city of art, radical self-reliance, and community. The Man and Temple are burned; participants bring everything they need. No commerce except ice and coffee. The event runs late August–early September. Burning Man is one of the world''s most unique and transformative festivals. Prepare thoroughly and leave no trace.' WHERE category = 'festivals' AND title_en = 'Burning Man';

UPDATE challenges SET description_en = 'Oruro Carnival in Bolivia is UNESCO-listed: the Diablada (devil dance) and 400 years of tradition. The procession in February features 48 folk groups and 28,000 dancers over 10 km. Masks, costumes, and music blend indigenous and Catholic tradition. Oruro is high altitude; acclimatise. Oruro Carnival is one of the Andes'' greatest celebrations and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Oruro Carnival';

UPDATE challenges SET description_en = 'Inti Raymi in Cusco re-enacts the Inca Festival of the Sun on June 24. Thousands gather at Sacsayhuaman for the ceremony; actors play the Sapa Inca and priests. The ritual marks the winter solstice. Tickets and seating are available. Inti Raymi is Peru''s biggest cultural festival and one of the world''s most dramatic historical re-enactments.' WHERE category = 'festivals' AND title_en = 'Inti Raymi';

UPDATE challenges SET description_en = 'The Dakar Rally is the world''s most gruelling off-road race: motorcycles, cars, and trucks cross dunes and mud. It was held in Africa and South America; since 2020 it has run in Saudi Arabia. January dates; the Empty Quarter and desert stages are epic. The Dakar is a test of endurance and one of the world''s top 100 festivals for adventure and motorsport.' WHERE category = 'festivals' AND title_en = 'Dakar Rally';

UPDATE challenges SET description_en = 'The Tour de France is a 23-stage cycling race in July, ending on the Champs-Élysées. The Alps and Pyrenees, including Alpe d''Huez, define the mountain stages. Millions line the roads; watch from a climb or a village. The Tour is the world''s greatest cycling race and a French national obsession. It is one of the world''s top 100 sporting and cultural events.' WHERE category = 'festivals' AND title_en = 'Tour de France';

UPDATE challenges SET description_en = 'Carnival of Trinidad is Caribbean mas at its finest: J''Ouvert with steel pan and mud, and the Monday and Tuesday parade in Port of Spain. Costume bands, soca music, and fêtes build for months. February or March dates. Trinidad Carnival is the mother of Caribbean carnival and one of the world''s most energetic and creative festivals.' WHERE category = 'festivals' AND title_en = 'Carnival of Trinidad';

UPDATE challenges SET description_en = 'The Bocelli Concert at Teatro del Silenzio in Lajatico, Tuscany, is an annual July event in an amphitheatre in the hills. Andrea Bocelli performs in his hometown; the setting is magical. Tickets are highly sought. The concert is one of the world''s most atmospheric open-air classical and pop events. Book early for this unique Italian experience.' WHERE category = 'festivals' AND title_en = 'Bocelli Concert';

UPDATE challenges SET description_en = 'The Elephant Festival in Surin, Thailand, each November features 200 elephants in parade, tug-of-war, and ancient battle re-enactments. The province has a long elephant-keeping tradition. Animal welfare concerns have led to changes; choose responsible operators. The festival is one of Thailand''s most unusual and controversial events. Visit with awareness.' WHERE category = 'festivals' AND title_en = 'Elephant Festival';

UPDATE challenges SET description_en = 'The Shanghai International Film Festival is one of Asia''s largest, with a competitive section and the Golden Goblet award. It runs in June and has been a fixture for over 30 years. Screenings, premieres, and industry events fill the city. SIFF is a gateway to Chinese and Asian cinema and one of the world''s top 100 film festivals.' WHERE category = 'festivals' AND title_en = 'Shanghai International Film Festival';

UPDATE challenges SET description_en = 'The Royal Edinburgh Military Tattoo on the Castle esplanade brings global military bands and performers to Edinburgh in August. Over 220,000 attend; the setting with the castle lit at night is unforgettable. Book early; dress for Scottish weather. The Tattoo is one of the world''s most iconic military and cultural displays and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Royal Edinburgh Military Tattoo';

UPDATE challenges SET description_en = 'Nuremberg Christkindlesmarkt is Germany''s most famous Christmas market. About 200 stalls sell gingerbread, lebkuchen, toys, and Glühwein. The market opens in late November and runs until Christmas. The Christkind opens it; the atmosphere is medieval and festive. Nuremberg is a winter highlight and one of the world''s top 100 Christmas markets.' WHERE category = 'festivals' AND title_en = 'Nuremberg Christkindlesmarkt';

UPDATE challenges SET description_en = 'Kumbh Mela is the world''s largest human gathering: hundreds of millions of pilgrims bathe in the Ganges at Prayagraj (Allahabad) every 12 years (with smaller editions in between). Sadhus, tents, and devotion define the scene. The festival is UNESCO-recognised. Attend with preparation and respect. Kumbh Mela is one of the world''s most profound religious festivals.' WHERE category = 'festivals' AND title_en = 'Kumbh Mela';

UPDATE challenges SET description_en = 'Tomorrowland in Boom, Belgium, is one of the world''s biggest EDM festivals. Fantasy stages, 400,000 attendees, and top DJs define the two weekends in July. The theme changes each year; the production is spectacular. Tickets sell out quickly. Tomorrowland is a pilgrimage for dance music fans and one of the world''s top 100 festivals.' WHERE category = 'festivals' AND title_en = 'Tomorrowland';

UPDATE challenges SET description_en = 'Basel Carnival (Fasnacht) is Switzerland''s largest carnival. Morgestraich at 4 am opens it: drums and lanterns fill the dark streets. Larven (masks) and Guggenmusik define the three days after Ash Wednesday. Basel becomes a city of satire and sound. Fasnacht is one of Europe''s most distinctive carnivals and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Basel Carnival';

UPDATE challenges SET description_en = 'Harbin Ice Festival in January transforms the city into a sculpture park of ice and snow. Palaces, dinosaurs, and slides are carved from ice; temperatures can reach -30°C. The festival runs into February with light shows. Harbin is in northeast China. The Ice Festival is one of the world''s most spectacular winter events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Harbin Ice Festival';

UPDATE challenges SET description_en = 'Concerts in the Wieliczka Salt Mine take place 300 m underground in chambers with chandeliers and stalactites. Classical music in this setting is unique. The mine near Kraków is UNESCO-listed. Book a concert and tour together. The Wieliczka concert is one of the world''s most unusual and atmospheric musical experiences.' WHERE category = 'festivals' AND title_en = 'Wieliczka Salt Mine Concert';

UPDATE challenges SET description_en = 'The Merrie Monarch Festival in Hilo, Hawaii, is the world''s premier hula competition. Week-long events include kahiko (ancient) and ʻauana (modern) categories; royalty and tradition are honoured. April dates; tickets are highly sought. The festival is the soul of Hawaiian culture and one of the world''s top 100 indigenous and dance festivals.' WHERE category = 'festivals' AND title_en = 'Merrie Monarch Festival';

UPDATE challenges SET description_en = 'Secret Solstice in Reykjavik uses 24-hour daylight for music inside a glacier, at a geothermal lagoon, and by a volcano. June dates; the lineup is international. Iceland''s midnight sun and otherworldly venues make it unique. Secret Solstice is one of the world''s most unusual and scenic festivals. Dress for changeable weather.' WHERE category = 'festivals' AND title_en = 'Secret Solstice Iceland';

UPDATE challenges SET description_en = 'Bermuda Day on the first Friday of June is the island''s first public holiday. The half marathon, fitted dinghy races, and heritage parade celebrate Bermudian culture. The atmosphere is family-friendly and proud. Bermuda Day is the island''s biggest annual celebration and one of the Caribbean-Atlantic''s top 100 festivals.' WHERE category = 'festivals' AND title_en = 'Bermuda Day';

UPDATE challenges SET description_en = 'Cinema Paradiso Festival at Somerset House in London offers outdoor rooftop cinema in summer. Deckchairs, big screen, and London skyline define the experience. The programme mixes classics and new releases. Book in advance for popular screenings. Cinema Paradiso is one of London''s most beloved summer events and a top 100 open-air cinema festivals.' WHERE category = 'festivals' AND title_en = 'Cinema Paradiso Festival';

UPDATE challenges SET description_en = 'The Full Moon Party on Koh Phangan''s Haad Rin beach is a monthly night rave. Fire shows, paint, and 30,000 revellers define the scene. The party has drawn criticism for safety and environment; go with care. Other Thai islands offer alternatives. The Full Moon Party is one of the world''s most famous beach parties. Respect local rules and yourself.' WHERE category = 'festivals' AND title_en = 'Full Moon Party';

UPDATE challenges SET description_en = 'The Colombian Coffee Festival in Buenavista, Quindío, celebrates coffee with picking demonstrations, donkey parades, and bamboo crafts. The region is the heart of coffee country. The festival promotes Colombian coffee culture and rural life. Visit for a taste of the real coffee axis. It is one of the world''s top 100 food and drink festivals.' WHERE category = 'festivals' AND title_en = 'Colombian Coffee Festival';

UPDATE challenges SET description_en = 'The Sahara International Festival in Douz, Tunisia, features horseback fantasia, camel racing, and traditional Saharan music. The desert town comes alive with Tuareg and Bedouin culture. Winter dates. The festival is a window into Saharan life and one of the world''s most atmospheric desert festivals. Check travel advice for the region.' WHERE category = 'festivals' AND title_en = 'Sahara International Festival';

UPDATE challenges SET description_en = 'The Nikko Toshogu Festival in May features a thousand samurai in procession at the Tokugawa shrine. Armour, horses, and drums honour the shogun. Nikko is north of Tokyo; the shrine is UNESCO-listed. The festival is one of Japan''s most spectacular historical re-enactments and a top 100 festival. Book accommodation early.' WHERE category = 'festivals' AND title_en = 'Nikko Toshogu Festival';

UPDATE challenges SET description_en = 'The Battle of Flowers in Zundert, Netherlands, is a parade of giant dahlia sculptures in September. Each float uses hundreds of thousands of flowers. The town competes between neighbourhoods. Zundert is in Brabant. The Battle of Flowers is one of the world''s most impressive floral parades and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Battle of Flowers';

UPDATE challenges SET description_en = 'Pride Amsterdam in August is one of the world''s largest Pride events, with a canal boat parade of 500 boats. The city celebrates diversity; the parade on the canals is unique. Parties and cultural events fill the week. Pride Amsterdam is a landmark of LGBTQ+ visibility and one of the world''s top 100 Pride festivals.' WHERE category = 'festivals' AND title_en = 'Pride Amsterdam';

UPDATE challenges SET description_en = 'Inti Raymi Cusco re-enacts the Inca winter solstice ceremony at Sacsayhuaman on June 24. Firelight and traditional dress evoke the Inca empire. The ceremony is the same date as the main Inti Raymi; Cusco is the heart of the celebration. It is one of Peru''s most important cultural events and a top 100 festival for history and spectacle.' WHERE category = 'festivals' AND title_en = 'Inti Raymi Cusco';

UPDATE challenges SET description_en = 'Sydney New Year Fireworks over the Harbour Bridge draw a billion TV viewers. Over 8.5 tonnes of fireworks light the harbour at midnight. View from the water, the bridge, or vantage points; plan for crowds. Sydney NYE is one of the world''s most watched and celebrated New Year events. Book early for the best experience.' WHERE category = 'festivals' AND title_en = 'Sydney New Year Fireworks';

UPDATE challenges SET description_en = 'Bastille Day (July 14) is France''s national day. The military parade on the Champs-Élysées and the Eiffel Tower light show are the highlights. Fireworks and parties fill the country. Paris is the centre; book restaurants and views in advance. Bastille Day is one of the world''s most iconic national celebrations and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Bastille Day Paris';

UPDATE challenges SET description_en = 'The Sapporo Snow Festival in February fills Odori Park with 200 snow and ice sculptures. Two million visitors see replicas of buildings and characters. The festival has run for decades. Sapporo is on Hokkaido; dress very warm. The Snow Festival is one of the world''s largest and most beautiful winter festivals.' WHERE category = 'festivals' AND title_en = 'Sapporo Snow Festival';

UPDATE challenges SET description_en = 'Whale Festival Baja celebrates gray whales in their mating lagoons. San Ignacio and other lagoons offer boat trips where mothers bring calves close. The season runs winter into spring. Baja California is the gateway. The festival is one of the world''s best opportunities to encounter whales and a top 100 wildlife and culture festival.' WHERE category = 'festivals' AND title_en = 'Whale Festival Baja';

UPDATE challenges SET description_en = 'Celtic Connections in Glasgow each January is the world''s largest winter Celtic music festival. Over 2,000 artists perform in trad sessions, concerts, and free events. The city becomes a hub for Scottish, Irish, and international Celtic music. Celtic Connections is one of the world''s top 100 folk and roots festivals. Book tickets for headline acts.' WHERE category = 'festivals' AND title_en = 'Celtic Connections Glasgow';

UPDATE challenges SET description_en = 'The Pirarucu Festival in the Brazilian Amazon celebrates the giant river fish (up to 250 kg) with canoe races and indigenous dance. The festival supports sustainable fishing and local culture. The Amazon setting is unique. Visit with a responsible operator. The Pirarucu Festival is one of the world''s most distinctive river and indigenous festivals.' WHERE category = 'festivals' AND title_en = 'Pirarucu Festival';

UPDATE challenges SET description_en = 'Bun Bang Fai (Rocket Festival) in Yasothon, Thailand, sees villages launch bamboo rockets to ask for rain. The rockets can reach 20 km; the festival is loud and colourful. May dates. The event blends animist tradition with Buddhist merit-making. Bun Bang Fai is one of Thailand''s most explosive and unique festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Bun Bang Fai Rocket Festival';

UPDATE challenges SET description_en = 'The San Fermín Bull Run in Pamplona sees runners race 800 m ahead of bulls at 8 am from July 7. The tradition is centuries old; red scarves and white clothes are the dress. The run is dangerous; injuries occur. The festival includes processions and parties. San Fermín is one of the world''s most controversial and famous festivals. Participate or watch with full awareness of risk.' WHERE category = 'festivals' AND title_en = 'San Fermin Bull Run';

UPDATE challenges SET description_en = 'Halloween in Salem, Massachusetts, embraces the town''s witch trial history with costume parades, haunted tours, and October events. Museums and re-enactments tell the dark story. Salem is packed in October; book early. Halloween Salem is one of the world''s most atmospheric and historically rooted Halloween destinations.' WHERE category = 'festivals' AND title_en = 'Halloween Salem';

UPDATE challenges SET description_en = 'The Puri Sand Art Festival on Odisha''s coast in November brings 80 sand artists together; master Sudarsan Pattnaik has put the festival on the map. Intricate sculptures line the beach. Puri is a pilgrimage town. The festival is one of India''s most creative and photogenic events and a top 100 sand art festival.' WHERE category = 'festivals' AND title_en = 'Puri Sand Art Festival';

UPDATE challenges SET description_en = 'The Yanagawa Lantern Boat in Fukuoka in June sees 3,000 lanterns float on the canal. Gondola songs and fireflies add to the evening. Yanagawa is a short trip from Fukuoka. The event is romantic and traditional. The Lantern Boat is one of Japan''s most beautiful summer festivals and a top 100 night-time events.' WHERE category = 'festivals' AND title_en = 'Yanagawa Lantern Boat';

UPDATE challenges SET description_en = 'The Highland Games across Scotland feature caber tossing, stone putting, and pipe bands. The Braemar Gathering in September is the most famous; the Royal Family attends. Heavy events, dancing, and athletics define the day. The Highland Games are the soul of Scottish tradition and one of the world''s top 100 cultural and sporting festivals.' WHERE category = 'festivals' AND title_en = 'Highland Games';

UPDATE challenges SET description_en = 'Inti Raymi Bolivia at Tiwanaku on June 21 marks the winter solstice at the Gate of the Sun. Pre-Inca and Aymara ceremonies welcome the sun. The site is UNESCO-listed. Dress for cold at dawn. Inti Raymi Bolivia is one of the Andes'' most ancient and spiritual festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Inti Raymi Bolivia';

UPDATE challenges SET description_en = 'Festival in the Desert (Essakane, near Timbuktu, Mali) brought Tuareg music, camel races, and fires under the stars to the world. Security has interrupted the event in recent years; when it returns, it is one of the world''s most remote and magical festivals. Tuareg culture and the Sahara are the stars. Check travel advice before considering a visit.' WHERE category = 'festivals' AND title_en = 'Festival in the Desert';

UPDATE challenges SET description_en = 'Roskilde Festival in Denmark is one of Europe''s largest music festivals. Run by a humanitarian organisation, it features a camping village and 130,000 attendees. The lineup is broad; the spirit is communal. Late June–early July. Roskilde is a model of festival organisation and one of the world''s top 100 music festivals.' WHERE category = 'festivals' AND title_en = 'Roskilde Festival';

UPDATE challenges SET description_en = 'Nagasaki Kunchi Festival on October 7–9 reflects the city''s history: Chinese and Dutch influences appear in dragon dance and daimyo parade. The festival has run for centuries. Nagasaki is in Kyushu. Kunchi is one of Japan''s most distinctive regional festivals and a top 100 event for history and spectacle.' WHERE category = 'festivals' AND title_en = 'Nagasaki Kunchi Festival';

UPDATE challenges SET description_en = 'Country Music CMA Fest in Nashville in June brings 100 acts to Nissan Stadium and downtown. Four days of fan events, boots, and country music define it. Nashville is Music City; the fest is the peak. CMA Fest is the world''s largest country music festival and one of the top 100 music events. Book early for hotels and tickets.' WHERE category = 'festivals' AND title_en = 'Country Music CMA Fest';

UPDATE challenges SET description_en = 'FESPAM in Brazzaville, Congo, is a biennial Pan-African music festival. Artists from 30 countries perform; the Congo River and local beat define the vibe. The festival promotes African music and unity. FESPAM is one of Africa''s most important cultural festivals and a top 100 event for African music. Check dates and travel advice.' WHERE category = 'festivals' AND title_en = 'FESPAM';

UPDATE challenges SET description_en = 'The Fado Festival in Lisbon in September fills Alfama and fado houses with Portugal''s most soulful music. Fado is the sound of saudade (longing). Concerts and intimate casas de fado offer the full experience. Lisbon is the capital of fado. The festival is one of the world''s top 100 music festivals for emotion and tradition.' WHERE category = 'festivals' AND title_en = 'Fado Festival Lisbon';

UPDATE challenges SET description_en = 'Cycle Festival Amsterdam in May celebrates the bike with the flower parade, fietsvierdaagse (four-day ride), and 40,000 cyclists on the route. Amsterdam is the world''s cycling city. The festival is family-friendly and green. Cycle Festival is one of the world''s top 100 cycling and urban festivals. Join a ride or enjoy the spectacle.' WHERE category = 'festivals' AND title_en = 'Cycle Festival Amsterdam';

UPDATE challenges SET description_en = 'The Giants of Mechelen (Ommegang) in Belgium sees medieval giant puppets parade through the city. The procession dates back centuries; summer July dates. Mechelen is between Brussels and Antwerp. The Giants are one of Belgium''s most beloved traditions and a UNESCO-recognised event. It is one of the world''s top 100 processional festivals.' WHERE category = 'festivals' AND title_en = 'Giants of Mechelen';

UPDATE challenges SET description_en = 'Keukenhof Tulip Festival in Lisse, Netherlands, runs March–May. Seven million bulbs and 800 varieties fill the park; windmills and a kilometre of colour define it. Keukenhof is the world''s largest flower garden. Spring dates are weather-dependent. Keukenhof is one of the world''s most beautiful floral festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Keukenhof Tulip Festival';

UPDATE challenges SET description_en = 'The Prague Spring Music Festival in May opens with Smetana''s My Homeland. Classical concerts fill Prague; the 1968 Prague Spring is part of the memory. The festival has run for decades. Prague in spring is magical. Prague Spring is one of Europe''s premier classical festivals and a top 100 music event.' WHERE category = 'festivals' AND title_en = 'Prague Spring Music Festival';

UPDATE challenges SET description_en = 'Maya Winter Solstice at Chichen Itza on December 21 marks the serpent shadow on El Castillo: the pyramid''s design creates a play of light and shadow. Thousands gather at dawn. The site is UNESCO-listed. The solstice is one of the world''s most dramatic archaeo-astronomical events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Maya Winter Solstice';

UPDATE challenges SET description_en = 'Zurich Street Parade in August is one of the world''s biggest techno raves: 200,000 ravers, love mobiles, and stages around the lake. The parade is free and peaceful. Zurich becomes a open-air club. The Street Parade is a landmark of European electronic music culture and one of the world''s top 100 dance festivals.' WHERE category = 'festivals' AND title_en = 'Zurich Street Parade';

UPDATE challenges SET description_en = 'The Iditarod is a 1,600 km sled dog race from Anchorage to Nome in March. It commemorates the 1925 serum run. Mushers and husky teams face extreme conditions. Nome welcomes the finishers; the race is Alaska''s biggest event. The Iditarod is one of the world''s most gruelling and iconic races and a top 100 festival of endurance.' WHERE category = 'festivals' AND title_en = 'Iditarod';

UPDATE challenges SET description_en = 'Feria de Abril in Seville is two weeks of flamenco, sherry, and caseta tents in April. Women wear ruffled dresses; the fairground is a village of tents. The atmosphere is Andalusian at its best. Book accommodation and caseta access early. Feria de Abril is one of Spain''s most beautiful and festive events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Feria de Abril';

UPDATE challenges SET description_en = 'Festival of the Nomads in Atar, Mauritania, brings Moorish poetry, music, silver jewellery, and camel beauty contests to the oasis. The Sahara and Berber culture define it. Atar is in the Adrar. The festival is one of the Sahara''s most authentic cultural events. Check travel advice for Mauritania before planning.' WHERE category = 'festivals' AND title_en = 'Festival of the Nomads';

UPDATE challenges SET description_en = 'Reindeer Racing in Inari, Finland, in March features Sami joik, lasso competition, and pulka sleigh races on snow. Inari is in Lapland; the event celebrates Sami culture. The races are thrilling and traditional. Reindeer Racing is one of the Arctic''s most unique winter festivals and a top 100 event for indigenous culture.' WHERE category = 'festivals' AND title_en = 'Reindeer Racing Inari';

UPDATE challenges SET description_en = 'Día de la Lluvia in Mexico honours Tlaloc, the Aztec rain god. Tlalocan priests dance; cacao offerings are made. The ceremony is in March. The event connects to pre-Hispanic tradition. Día de la Lluvia is one of Mexico''s most ancient and lesser-known festivals. Experience it with respect for indigenous spirituality.' WHERE category = 'festivals' AND title_en = 'Día de la Lluvia';

UPDATE challenges SET description_en = 'Buenos Aires Tango Festival in August makes the city the world capital of tango. Milongas (dance events), outdoor stages, the championship, and 500 teachers fill the programme. The festival is free and open. Buenos Aires is the home of tango. The festival is one of the world''s top 100 dance and music events.' WHERE category = 'festivals' AND title_en = 'Buenos Aires Tango Festival';

UPDATE challenges SET description_en = 'Vesak Full Moon in Sri Lanka marks the Buddha''s birthday. White-clad devotees, dansala (free food giving), and lanterns fill the island. The date follows the lunar calendar (usually May). Temples and processions are the focus. Vesak is one of the world''s most beautiful Buddhist festivals and a top 100 religious event.' WHERE category = 'festivals' AND title_en = 'Vesak Full Moon';

UPDATE challenges SET description_en = 'Jinja Festival in Uganda in October celebrates the source of the Nile with boat races, tribal dances, and cultural convergence. Jinja is the town at the Nile''s source. The festival promotes unity and heritage. Jinja Festival is one of East Africa''s most significant cultural events and a top 100 festival. Visit for sport and culture.' WHERE category = 'festivals' AND title_en = 'Jinja Festival Uganda';

UPDATE challenges SET description_en = 'Istanbul Jazz Festival in July brings jazz to the Bosphorus: concerts on two continents, ferry sunset gigs, and world-class artists. Istanbul is a bridge of cultures; the festival reflects that. Venues include historic sites. The festival is one of the world''s most atmospheric jazz events and a top 100 music festival.' WHERE category = 'festivals' AND title_en = 'Istanbul Jazz Festival';

UPDATE challenges SET description_en = 'The Dakar Rally moved to Saudi Arabia in 2020; the Empty Quarter and Middle East dunes offer a new kind of epic. January dates; motorcycles, cars, and trucks race through the desert. The Saudi edition has redefined the route. The Dakar remains one of the world''s top 100 motorsport and adventure festivals.' WHERE category = 'festivals' AND title_en = 'Dakar Rally';

UPDATE challenges SET description_en = 'Kyiv Street Music Festival in May fills the city with buskers, Ukrainian folk, and eclectic genres. Stages and street corners come alive. Kyiv is the heart of Ukrainian culture. The festival has continued to adapt despite challenges. It is one of Eastern Europe''s most vibrant street music events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Kyiv Street Music Festival';

UPDATE challenges SET description_en = 'The Rose Festival in Morocco''s Dades Valley (Kelaa M''Gouna) in May celebrates the harvest with rose water blessing, petal carpets, and a princess and queen. The valley is famous for damask roses. The festival is fragrant and photogenic. It is one of Morocco''s most beautiful and unique festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Rose Festival Dades Valley';

UPDATE challenges SET description_en = 'The Vegetarian Festival in Phuket in October honours the Nine Emperor Gods. Firewalking, cheek piercing, and white clothes define the intense rituals. The festival is not for the faint-hearted. Phuket Town is the centre. The Vegetarian Festival is one of Thailand''s most dramatic and spiritual events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Vegetarian Festival Phuket';

UPDATE challenges SET description_en = 'The Sumo Grand Tournament in Tokyo (January at Ryogoku Kokugikan) runs 15 days. The makuuchi (top division) and Shinto ritual define sumo. Tickets are in demand. Tokyo has three annual tournaments; January is the first. Sumo is Japan''s national sport and one of the world''s top 100 traditional sporting events.' WHERE category = 'festivals' AND title_en = 'Sumo Grand Tournament Tokyo';

UPDATE challenges SET description_en = 'Uluru Song Lines in September celebrates Aboriginal culture at Uluru: dance, story, dot painting, and didgeridoo. The Anangu share culture and country. The event is respectful and profound. Uluru is sacred; the festival is a window into the world''s oldest living culture. It is one of the world''s top 100 indigenous festivals.' WHERE category = 'festivals' AND title_en = 'Uluru Song Lines';

UPDATE challenges SET description_en = 'Geilo Ice Music Festival in Norway in February features instruments carved from ice; concerts take place in a snow dome. The sound is unique and ephemeral. Geilo is a ski resort. The festival is one of the world''s most unusual and beautiful winter music events and a top 100 festival. Dress very warm.' WHERE category = 'festivals' AND title_en = 'Geilo Ice Music Festival';

UPDATE challenges SET description_en = 'Esala Perahera in Kandy, Sri Lanka, in August is a night procession of the Sacred Tooth Relic. Eighty elephants, dancers, and drummers parade through the city. The festival runs for days. Kandy is the cultural heart of the island. Esala Perahera is one of the world''s most spectacular Buddhist festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Esala Perahera';

UPDATE challenges SET description_en = 'Carnaval de Oruro (same as Oruro Carnival) is the UNESCO-listed Bolivian festival: 48 folk groups, 28,000 dancers, and a 10 km procession in the Andes. The Diablada and other dances blend indigenous and Catholic tradition. February dates. Carnaval de Oruro is one of the Americas'' greatest cultural spectacles and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Carnaval de Oruro';

UPDATE challenges SET description_en = 'Lake Retba Festival in Senegal celebrates the pink lake with Wolof dance, tom-tom drums, and salt harvesting ceremony. Lake Retba (Lac Rose) is near Dakar; the colour comes from algae. The festival honours the salt workers. It is one of West Africa''s most colourful and unique festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Lake Retba Festival';

UPDATE challenges SET description_en = 'The Hogwarts Express Experience is the Jacobite steam train in Scotland: it crosses the Glenfinnan Viaduct (as in the Harry Potter films). The route runs between Fort William and Mallaig (or similar). Book early; the train is hugely popular. The experience is one of the world''s most iconic railway journeys and a top 100 film and travel experiences.' WHERE category = 'festivals' AND title_en = 'Hogwarts Express Experience';

UPDATE challenges SET description_en = 'Aurora Festival Tromso in January combines aurora hunting, reindeer sledding, and Sami culture in the icy fjord. Tromso is in the Arctic; winter is dark and ideal for northern lights. The festival offers guided hunts and cultural events. It is one of the world''s best aurora and winter festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Aurora Festival Tromso';

UPDATE challenges SET description_en = 'Venice Opera Barge brings summer concerts to the canals: gondola serenade, La Fenice history, and Vivaldi''s city. Opera and classical music on the water are unforgettable. Venice is the stage. The experience is one of the world''s most romantic and unique musical settings and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Venice Opera Barge';

UPDATE challenges SET description_en = 'Reykjavik Winter Lights in February bathes the city in art light; swimming pools and dark-season events are part of the programme. Reykjavik uses the long night for installations and culture. The festival is family-friendly. It is one of the world''s most atmospheric winter light festivals and a top 100 event.' WHERE category = 'festivals' AND title_en = 'Reykjavik Winter Lights';

UPDATE challenges SET description_en = 'The Rajasthan Desert Festival in Jaisalmer in February features camel races, folk music, turban tying, and sand dunes. The Thar Desert is the backdrop. The festival showcases Rajasthani culture and desert life. Jaisalmer is the golden city. The Desert Festival is one of India''s most colourful and photogenic events and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Rajasthan Desert Festival';

UPDATE challenges SET description_en = 'Homowo Festival in Ghana is the Ga people''s harvest thanksgiving in August. Pork sharing, ancestral libation, and storytelling honour the past. Accra and coastal Ga communities celebrate. Homowo means hooting at hunger. The festival is one of West Africa''s most important harvest celebrations and a top 100 festival.' WHERE category = 'festivals' AND title_en = 'Homowo Festival Ghana';
