-- schema-v6-fix.sql
-- schema-v6 실행 중 CHECK 오류로 누락된 7개 카테고리 재삽입
-- (surfing, skiing, scuba, nature, animals, festivals, countries)

-- 기존 중복 방지: 이미 있는 카테고리는 삭제 후 재삽입
DELETE FROM public.challenge_certifications WHERE challenge_id IN (
  SELECT id FROM public.challenges WHERE category IN ('surfing','skiing','scuba','nature','animals','festivals','countries')
);
DELETE FROM public.challenges WHERE category IN ('surfing','skiing','scuba','nature','animals','festivals','countries');

-- COUNTRIES
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('countries','일본','Japan','JP','Ancient tradition meets ultra-modern; samurai history, anime, ramen',10),
('countries','이탈리아','Italy','IT','Art history food wine; Rome Florence Venice Amalfi all in one',10),
('countries','프랑스','France','FR','Eiffel Tower, Louvre, Loire Valley, Riviera, gastronomy, wine',10),
('countries','스페인','Spain','ES','Flamenco, tapas, Gaudi, Costa del Sol, Camino de Santiago',10),
('countries','그리스','Greece','GR','Santorini sunsets, Athens history, 6,000 islands to explore',10),
('countries','포르투갈','Portugal','PT','Fado music, Douro wine, Lisbon trams, Algarve cliffs, Azores',10),
('countries','터키','Turkey','TR','East meets West; Cappadocia, Istanbul Bazaar, Turkish coast',10),
('countries','모로코','Morocco','MA','Sahara dunes, Fes medina, Marrakech souks, Atlas Mountains',10),
('countries','이집트','Egypt','EG','Pyramids, Nile cruise, Red Sea diving, Abu Simbel temples',10),
('countries','인도','India','IN','Taj Mahal, Tiger reserves, Kerala backwaters, Rajasthan palaces',10),
('countries','태국','Thailand','TH','Thai temples, street food, Islands, Chiang Mai trekking',10),
('countries','인도네시아','Indonesia','ID','Bali temples, Komodo dragons, Raja Ampat diving, Borobudur',10),
('countries','베트남','Vietnam','VN','Ha Long Bay, Hoi An lanterns, Pho, Mekong Delta cruise',10),
('countries','캄보디아','Cambodia','KH','Angkor Wat, floating villages, silk weaving, genocide history',10),
('countries','미얀마','Myanmar','MM','Bagan temples at sunrise, Inle Lake, Shwedagon Pagoda, teak bridge',15),
('countries','네팔','Nepal','NP','Everest Base Camp trek, Kathmandu temples, Pokhara lakes',15),
('countries','부탄','Bhutan','BT','Happiness kingdom; Tiger Nest, archery, GNH policy, mountain peaks',20),
('countries','스리랑카','Sri Lanka','LK','Sigiriya fortress, elephant safaris, Ceylon tea, surf beaches',10),
('countries','몰디브','Maldives','MV','Overwater bungalows, whale sharks, coral atolls, gin-clear lagoons',15),
('countries','아랍에미리트','UAE','AE','Burj Khalifa, desert safaris, gold souks, futuristic architecture',10),
('countries','요르단','Jordan','JO','Petra rose city, Wadi Rum desert, Dead Sea float, Aqaba reef',10),
('countries','이스라엘','Israel','IL','Jerusalem holy sites, Masada, Tel Aviv beaches, Negev desert',10),
('countries','사우디아라비아','Saudi Arabia','SA','Nabataean Hegra, Diriyah, Aseer mountains, Red Sea reef opening',15),
('countries','이란','Iran','IR','Persian Empire history, Isfahan tile mosques, Yazd Fire Temples',15),
('countries','오만','Oman','OM','Wahiba Sands, Musandam fjords, frankincense trade, turtle beaches',10),
('countries','케냐','Kenya','KE','Masai Mara migration, Samburu camels, Lamu dhows, Malindi reef',10),
('countries','탄자니아','Tanzania','TZ','Serengeti, Kilimanjaro, Zanzibar, Ngorongoro Crater, Pemba Island',10),
('countries','남아프리카','South Africa','ZA','Cape Town Table Mountain, Kruger Park, Garden Route, wine estates',10),
('countries','르완다','Rwanda','RW','Gorilla trekking, genocide memorial, fastest growing Africa economy',15),
('countries','에티오피아','Ethiopia','ET','Lalibela rock churches, Simien Mountains, Danakil Depression lava lake',15),
('countries','짐바브웨','Zimbabwe','ZW','Victoria Falls, Great Zimbabwe ruins, rhino sanctuary Matobo Hills',10),
('countries','보츠와나','Botswana','BW','Okavango Delta mokoro, Chobe elephant river, pristine wilderness',15),
('countries','나미비아','Namibia','NA','Skeleton Coast, Sossusvlei dunes, Fish River Canyon, Etosha NP',15),
('countries','마다가스카르','Madagascar','MG','90% endemic species; lemurs, baobabs, spiny forest, tsingy karst',20),
('countries','모잠비크','Mozambique','MZ','Bazaruto diving, Tofo whale sharks, dhow sailing, deserted beaches',15),
('countries','세네갈','Senegal','SN','Pink Lake Retba, Goree slavery island, jazz music, Saloum Delta',10),
('countries','가나','Ghana','GH','Slave forts, Ashanti palaces, hippos Wechiau, Kakum canopy walk',10),
('countries','멕시코','Mexico','MX','Chichen Itza, cenotes, tacos, Oaxacan culture, Copper Canyon',10),
('countries','쿠바','Cuba','CU','Havana vintage cars, salsa, cigars, Trinidad cobblestones, Bay of Pigs',10),
('countries','페루','Peru','PE','Machu Picchu, Nazca lines, ceviche, Amazon headwaters, Lake Titicaca',10),
('countries','볼리비아','Bolivia','BO','Salar de Uyuni mirror, Death Road cycling, Potosi silver mines',15),
('countries','칠레','Chile','CL','Torres del Paine, Atacama stars, Easter Island moai, Patagonia ice',15),
('countries','아르헨티나','Argentina','AR','Patagonia, Buenos Aires tango, Iguazu Falls, wine Mendoza Malbec',10),
('countries','브라질','Brazil','BR','Rio carnival, Amazon river dolphin, Fernando de Noronha, Pantanal',10),
('countries','콜롬비아','Colombia','CO','Cano Cristales rainbow river, Cartagena walls, coffee region, salsa Cali',10),
('countries','에콰도르','Ecuador','EC','Galapagos evolution, Quito colonial, Amazon Yasuni, Cotopaxi volcano',15),
('countries','파라과이','Paraguay','PY','Jesuit missions, Pantanal wetlands, terere tea, traditional lace',10),
('countries','우루과이','Uruguay','UY','Colonia del Sacramento, Punta del Este beach parties, gaucho culture',10),
('countries','코스타리카','Costa Rica','CR','Pura Vida wildlife, ziplining, Arenal volcano, surfing, Corcovado NP',10),
('countries','파나마','Panama','PA','Canal engineering wonder, San Blas Kuna Yala islands, cloud forest',10),
('countries','자메이카','Jamaica','JM','Bob Marley culture, Blue Mountains coffee, seven mile beach, jerk',10),
('countries','바르바도스','Barbados','BB','Coral architecture, flying fish, rum distilleries, cricket grounds',10),
('countries','트리니다드 토바고','Trinidad and Tobago','TT','Carnival, calypso, roti, Asa Wright birdwatching, leatherback turtles',10),
('countries','아이슬란드','Iceland','IS','Northern lights, geysers, waterfalls, glaciers, midnight sun',15),
('countries','노르웨이','Norway','NO','Fjords, midnight sun, Arctic wolf, Bergen fish market, trolltunga',10),
('countries','스웨덴','Sweden','SE','Stockholm archipelago, ABBA museum, Icehotel Jukkasjarvi',10),
('countries','핀란드','Finland','FI','Sauna culture, reindeer Lapland, Northern Lights, Nokia forests',10),
('countries','덴마크','Denmark','DK','Noma, Little Mermaid, cycling culture, Legoland, Bornholm island',10),
('countries','네덜란드','Netherlands','NL','Tulip fields, windmills, canals, Rijksmuseum, cycling everywhere',10),
('countries','벨기에','Belgium','BE','Chocolate, waffles, Bruges medieval, Brussels EU quarter, Trappist beer',10),
('countries','스위스','Switzerland','CH','Alpine skiing, fondue, precision watches, Interlaken adventure sports',10),
('countries','오스트리아','Austria','AT','Vienna opera, Salzburg Mozart, Hallstatt village, Viennese coffee',10),
('countries','독일','Germany','DE','Neuschwanstein Castle, Oktoberfest, Berlin Wall, Rhine castles',10),
('countries','체코','Czech Republic','CZ','Prague astronomical clock, Cesky Krumlov, Bohemian spa circuit',10),
('countries','헝가리','Hungary','HU','Budapest Danube views, thermal baths, tokaji wine, Great Plain',10),
('countries','폴란드','Poland','PL','Auschwitz memorial, Krakow royal city, Wieliczka salt mine',10),
('countries','크로아티아','Croatia','HR','Dubrovnik Old Town, Plitvice lakes, Dalmatian coast sailing',10),
('countries','슬로베니아','Slovenia','SI','Lake Bled fairy tale, Triglav NP, Skocjan caves, Piran Venetian port',10),
('countries','보스니아 헤르체고비나','Bosnia and Herzegovina','BA','Mostar bridge, Sarajevo siege history, Pocitelj Ottoman town',10),
('countries','알바니아','Albania','AL','Gjirokaster UNESCO, Albanian Riviera untouched beaches, Berat castle',10),
('countries','몬테네그로','Montenegro','ME','Bay of Kotor medieval, Durmitor rafting, Lovcen National Park',10),
('countries','불가리아','Bulgaria','BG','Sofia Alexander Nevsky, Rila Monastery, Rose Valley, Black Sea',10),
('countries','루마니아','Romania','RO','Transylvania Dracula, painted monasteries, Danube Delta biosphere',10),
('countries','세르비아','Serbia','RS','Belgrade fortress and nightlife, Tara NP, Drina River house on rock',10),
('countries','조지아','Georgia','GE','Caucasus mountains, wine cave cellars, Tbilisi sulfur baths, Gori',10),
('countries','아르메니아','Armenia','AM','Oldest Christian nation, monastery cliffs, Debed canyon, Ararat view',10),
('countries','아제르바이잔','Azerbaijan','AZ','Baku futurist Flame Towers, mud volcanoes, silk road caravanserai',10),
('countries','우즈베키스탄','Uzbekistan','UZ','Silk Road Samarkand, Bukhara bazaars, Khiva walled city',15),
('countries','키르기스스탄','Kyrgyzstan','KG','Tian Shan nomad culture, Eagle hunting, Song Kol yurt camp',15),
('countries','카자흐스탄','Kazakhstan','KZ','Almaty Shymbulak skiing, Charyn Canyon, steppe eagle hunting',10),
('countries','몽골','Mongolia','MN','Gobi Desert camel trek, Naadam festival, ger nomad stay, eagle hunter',15),
('countries','러시아','Russia','RU','Trans-Siberian Railway, Baikal ice, Kremlin, Kamchatka volcanoes',10),
('countries','그린란드','Greenland','GL','Ilulissat Icefjord UNESCO, dog sledding, iceberg kayaking, aurora',20),
('countries','바누아투','Vanuatu','VU','Volcano trekking Tanna, kastom villages, bungee jumping ni-Vanuatu',15),
('countries','팔라우','Palau','PW','Jellyfish Lake, Blue Corner, pristine WWII wrecks, manta rays',15),
('countries','피지','Fiji','FJ','Cloudbreak surfing, kava ceremony, coral coast, Yasawa boat trip',10),
('countries','사모아','Samoa','WS','Robert Louis Stevenson home, fa afafine culture, To Sua trench swim',10),
('countries','통가','Tonga','TO','Humpback whale snorkel, kava ceremony, Ha apai islands paradise',15),
('countries','솔로몬 제도','Solomon Islands','SB','WWII Guadalcanal, undiscovered reefs, Melanesian culture, mantas',20),
('countries','파푸아 뉴기니','Papua New Guinea','PG','Sing-sing tribal gathering, Kokoda Track, Birds of Paradise forest',20),
('countries','동티모르','Timor-Leste','TL','Youngest nation; Cristo Rei, Atauro Island diving, resistance history',15),
('countries','가봉','Gabon','GA','Lope NP forest elephants, Loango NP surfing hippos, untouched coast',20),
('countries','카보 베르데','Cape Verde','CV','Ponta Preta surfing, Fogo volcano, morna music, Sal island beach',10),
('countries','상투메 프린시페','Sao Tome and Principe','ST','Cacao farms, untouched beaches, equatorial forest, rocas ruins',15),
('countries','코모로','Comoros','KM','Karthala volcano active, coelacanth fish, ylang ylang perfume island',15),
('countries','레소토','Lesotho','LS','Kingdom in the sky; Maluti Mountains, Sani Pass 4WD, Basotho culture',10),
('countries','에스와티니','Eswatini','SZ','Umhlanga Reed Dance ceremony, Hlane rhino, traditional craft Manzini',10),
('countries','한국','South Korea','KR','K-pop, K-drama, palaces, BBQ, hiking, DMZ, Jeju volcanic island',10),
('countries','중국','China','CN','Great Wall, Yangtze, pandas, Shanghai skyline, terracotta warriors',10),
('countries','호주','Australia','AU','Sydney Opera House, Great Barrier Reef, Uluru, Tasmania wilderness',10),
('countries','뉴질랜드','New Zealand','NZ','Fiordland, hobbit country, Maori culture, geothermal, adventure sports',10),
('countries','캐나다','Canada','CA','Niagara, Rocky Mountains, aurora Yukon, Quebec old city, whale watching',10),
('countries','미국','United States','US','Grand Canyon, NYC, Yellowstone, Route 66, Hawaii, national parks',10);

-- NATURE
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('nature','아마존 열대우림','Amazon Rainforest','BR','Largest tropical forest; 10% of Earth species, pink dolphins, anacondas',15),
('nature','그랜드 캐니언','Grand Canyon','US','1.8 billion years of geology carved by Colorado River, 1.6km deep',10),
('nature','이과수 폭포','Iguazu Falls','AR','275 waterfalls spanning 2.7km; wider than Niagara, jaguar territory',10),
('nature','빅토리아 폭포','Victoria Falls','ZW','Worlds largest curtain of water; thunder smoke rises 300m in air',10),
('nature','갈라파고스 제도','Galapagos Islands','EC','Evolution living lab; blue-footed boobies, tortoises, marine iguanas',15),
('nature','세렝게티','Serengeti','TZ','Great Migration 1.5 million wildebeest, lions, cheetahs on open savanna',10),
('nature','옐로스톤','Yellowstone','US','Supervolcano; Old Faithful geyser, hot springs, bison herds, wolf packs',10),
('nature','파타고니아','Patagonia','CL','End of the Earth; Torres del Paine granite towers, glaciers, pumas',15),
('nature','살라르 데 우유니','Salar de Uyuni','BO','12,000 km2 salt flat; perfect mirror reflection in rainy season',15),
('nature','앙헬 폭포','Angel Falls','VE','Worlds highest waterfall 979m; accessible only by small plane or boat',15),
('nature','소수스플레이','Sossusvlei','NA','Worlds tallest red sand dunes 300m; Dead Vlei petrified trees ghost forest',10),
('nature','크루거 국립공원','Kruger National Park','ZA','Big Five; 500 birds, 147 mammals, legendary old tuskster elephants',10),
('nature','아이슬란드 오로라','Northern Lights Iceland','IS','Aurora borealis dancing over glaciers, waterfalls and lava fields',15),
('nature','알프스','Swiss Alps','CH','Mont Blanc 4808m, Matterhorn; skiing, glaciers, ibex mountain climbing',10),
('nature','히말라야','Himalayas','NP','8 of worlds 14 eight-thousanders; trekking, yaks, sherpa culture',15),
('nature','그레이트 배리어 리프','Great Barrier Reef','AU','Worlds largest coral system; 1,500 fish species, turtles, dugongs',15),
('nature','나미브 사막','Namib Desert','NA','Oldest desert 55 million years; Quiver tree forests, oryx, fairy circles',10),
('nature','사하라 사막','Sahara Desert','MA','Worlds largest hot desert; Saharan silver ant, camel caravans, Tuareg',10),
('nature','보르네오 열대우림','Borneo Rainforest','MY','Orangutans, pygmy elephants, proboscis monkeys in ancient forest',15),
('nature','카카두 국립공원','Kakadu National Park','AU','50,000-year Aboriginal rock art, saltwater crocs, monsoon wetlands',10),
('nature','죠슈아 트리','Joshua Tree','US','Surreal desert landscape; boulders, unique yucca trees, Milky Way skies',10),
('nature','돌로미테','Dolomites','IT','UNESCO pale mountain spires; via ferrata, dramatic sunset alpenglow',10),
('nature','피오르드랜드','Fiordland','NZ','Milford Sound sheer cliffs, Doubtful Sound wilderness, dolphins, penguins',15),
('nature','소코트라 섬','Socotra Island','YE','Alien landscape; Dragon Blood Trees only here, endemic 700 species',20),
('nature','블루 마운틴','Blue Mountains','AU','Eucalyptus oil haze creates blue tint; Three Sisters, cockatoos',10),
('nature','포마레 계곡','Pomerape Valley','CL','Atacama high-altitude flamingos, geysers at 4200m, altiplano lakes',15),
('nature','바이칼 호수','Lake Baikal','RU','Worlds deepest lake 1642m; 20% of unfrozen surface freshwater on Earth',15),
('nature','와이포우아 숲','Waipoua Forest','NZ','Ancient kauri trees; Tane Mahuta god of the forest, 2000 years old',15),
('nature','천산 산맥','Tian Shan Mountains','KG','Nomad summer pastures, eagle hunters, pristine alpine lakes, snow leopard',15),
('nature','에토샤 국립공원','Etosha National Park','NA','3,000 lions around the salt pan; black rhino, giraffe, elephant herds',10),
('nature','봉오보 숲','Bwindi Impenetrable Forest','UG','Half of worlds mountain gorillas; 640+ gorillas in mist trek',20),
('nature','동 팡녹 국립공원','Dong Phayayen Forest','TH','UNESCO wildlife corridor; Siamese crocodile, gaur, Asiatic black bear',10),
('nature','태즈메이니아 야생지대','Tasmanian Wilderness','AU','Gondwana rainforest; Tasmanian devil, wombats, pristine rivers',15),
('nature','우림이 있는 산','Mount Kinabalu','MY','Borneo roof at 4095m; pitcher plants, rhododendrons, endemic squirrel',10),
('nature','로라임아 산','Mount Roraima','VE','Table-top tepui; lost world plateau inspires Arthur Conan Doyle novel',15),
('nature','프리토리아 꽃 거리','Namaqualand','ZA','Wildflower desert bloom; 3000 endemic plants turn desert orange in spring',10),
('nature','핑크 레이크','Lake Hillier','AU','Flamingo-pink lake next to blue sea; Dunaliella salina algae pigment',15),
('nature','나이아가라 폭포','Niagara Falls','CA','6 million cubic feet water/minute; boat Maid of Mist, illumination shows',10),
('nature','플리트비체 호수','Plitvice Lakes','HR','16 terraced cascading lakes UNESCO; floating boardwalks, turquoise water',10),
('nature','돌핀워터 스프링','Hamelin Pool','AU','Worlds oldest living organisms; 3-billion-year stromatolites in hypersaline bay',20),
('nature','아콩카과','Aconcagua','AR','Americas highest peak 6962m; technical climb, condors soaring thermals',20),
('nature','베수비오 화산','Mount Vesuvius','IT','Active stratovolcano; destroyed Pompeii 79AD; hike to 1281m crater',10),
('nature','아리조나 광야','Antelope Canyon','US','Slot canyon light beams; Navajo sacred site, wave-formed sandstone walls',10),
('nature','알래스카 오로라','Aurora Borealis Alaska','US','Fairbanks aurora oval; dog sledding, moose, wolves under dancing lights',15),
('nature','코르코바도 공원','Corcovado National Park','CR','Most biodiverse park on Earth; tapirs, harpy eagles, jaguars',15),
('nature','보 핀란드 국립공원','Urho Kekkonen NP','FI','Lapland wilderness; golden eagles, wolverines, reindeer herding Sami',15),
('nature','독도','Dokdo Island','KR','Volcanic rock island; pristine sea bird nesting, turquoise waters',10),
('nature','한라산','Hallasan Volcano','KR','South Korea highest; UNESCO biosphere, endemic Jeju orchid, roe deer',10),
('nature','백두산','Paektu Mountain','KP','Sacred volcano lake Cheonji; Korea spiritual heartland, Siberian tigers',15),
('nature','에베레스트','Mount Everest','NP','Worlds highest peak 8849m; Sherpa culture, prayer flags, Khumbu icefall',20),
('nature','칸첸중가','Kangchenjunga','IN','Third highest; remote trekking, red panda, snow leopard, pristine circuit',20),
('nature','아마다블람','Ama Dablam','NP','Most beautiful Himalayan peak; technical climbing, sherpa mountaineering',20),
('nature','에트나 화산','Mount Etna','IT','Europes most active volcano; lava flow tours, ash cloud, ski slopes',10),
('nature','고비 사막','Gobi Desert','MN','Flaming Cliffs dinosaur eggs, Bactrian camels, snow leopards, gers',15),
('nature','당가르 칼데라','Ngorongoro Crater','TZ','Worlds largest intact caldera; 30,000 animals including black rhino',10),
('nature','오카방고 델타','Okavango Delta','BW','Desert river delta; mokoro canoe through water lilies, hippos, leopards',15),
('nature','퀸즐랜드 열대우림','Daintree Rainforest','AU','Worlds oldest tropical rainforest 135 million years; cassowary, green sea turtle',15),
('nature','갠지스강','Ganges River','IN','Sacred river; dawn cremation ghats, sadhus, Varanasi Hindu rituals',10),
('nature','마추픽추 성스러운 계곡','Sacred Valley','PE','Inca agricultural terraces, Andean condors soaring, traditional weavers',10),
('nature','아이어스 록','Uluru-Kata Tjuta','AU','Sacred Anangu rock changes colour sunset; world navel, 550 million years',15),
('nature','화이트샌즈','White Sands','US','Gypsum dune sea; world largest gypsum dune field, kit fox, missile range',10),
('nature','마사이 마라','Masai Mara','KE','Big Five year-round; Great Migration river crossing, Masai warriors',10),
('nature','수마트라 열대우림','Sumatra Rainforest','ID','Last place orangutans, tigers, rhinos, elephants coexist; Leuser NP',15),
('nature','엘 카피탄','Yosemite Valley','US','El Capitan granite, Half Dome, firefall; rock climbing mecca',10),
('nature','브라이스 캐니언','Bryce Canyon','US','Hoodoo spires; worlds biggest concentration, 200,000 years erosion',10),
('nature','파로 아탈링','Fjadrargljufur Canyon','IS','Dragon canyon 100m deep; Game of Thrones location, hidden Iceland gem',15),
('nature','스코켕','Skocjan Caves','SI','UNESCO underground canyon; Reka River drops 160m into Earth''s crust',10),
('nature','제주 용두암','Jeju Lava Tube','KR','UNESCO natural heritage; 160km tube network, 7000-year stalagmites',10),
('nature','글레이셔 국립공원','Glacier National Park','US','Crown of the Continent; 700 lakes, grizzly bears, ptarmigan, mountain goats',10),
('nature','주자이거우','Jiuzhaigou','CN','Five-colour lakes, cascades, pandas, Tibetan culture in Sichuan mountains',10),
('nature','황룽','Huanglong','CN','UNESCO; multi-colour travertine pools, snow leopard, golden snub-nosed monkey',15),
('nature','장가계','Zhangjiajie','CN','Floating Avatar mountains; quartz-sandstone pillars, cloud inversion, glass bridge',10),
('nature','하롱베이','Ha Long Bay','VN','2000 limestone karsts; UNESCO treasure, kayaking, floating villages',10),
('nature','코모도 국립공원','Komodo National Park','ID','Monitor lizard dragons, pink sand beach, manta rays, Wallace Line ecology',15),
('nature','마운트 피나투보','Mount Pinatubo','PH','1991 eruption crater lake turquoise; one of 20th century biggest eruptions',10),
('nature','로라이마 테푸이','Roraima Tepui','VE','Lost World plateau; carnivorous plants, black frogs, endemic species',15),
('nature','스피츠베르겐','Svalbard','NO','Polar bear kingdom; midnight sun, bird cliffs, Arctic fox, blue glacier',20),
('nature','프란츠 요제프 빙하','Franz Josef Glacier','NZ','Southern Alps glacier descends to rainforest; rare temperate ice meeting rain',15),
('nature','에클로그 빙하','Perito Moreno Glacier','AR','One of few advancing glaciers; thunderous calving into Lake Argentino',10),
('nature','아타카마 사막','Atacama Desert','CL','Driest non-polar desert; flower bloom every 5-7 years, ALMA telescope',10),
('nature','카카오 해변','Kakapo Fiordland','NZ','Rarest parrot world; flightless, nocturnal, found only Codfish Island',20),
('nature','코르디예라 블랑카','Cordillera Blanca','PE','Worlds highest tropical mountain range; turquoise glacial lakes, condors',15),
('nature','드라켄스버그 산맥','Drakensberg Mountains','ZA','UNESCO; Bushman rock art, Amphitheatre cliff, Cape vulture colony',10),
('nature','에어 록','Ayers Rock (Uluru)','AU','Sacred red sandstone monolith; sunrise pilgrimage, Anangu culture',15),
('nature','그레이트 블루 홀','Great Blue Hole','BZ','Marine sinkhole 300m wide; stalactites, bull sharks, crystal-clear water',15),
('nature','호르무즈 섬','Hormuz Island','IR','Rainbow Island; colorful mineral soil, unique geology, red beach',15),
('nature','크림 반도 동굴','Crimean Caves','UA','Marble cave; 2km of gallery, crystal formations, underground lake',10),
('nature','세이셸 조류 섬','Aldabra Atoll','SC','UNESCO; world largest land tortoise 200,000 individuals, undisturbed reef',20),
('nature','마젤란 펭귄 군집지','Punta Tombo','AR','Americas largest penguin colony; 500,000 Magellanic penguins gather',10),
('nature','발데스 반도','Peninsula Valdes','AR','UNESCO; orca beach hunting, southern right whale nursery, Patagonian hares',15),
('nature','나가르홀레 국립공원','Nagarhole National Park','IN','Indian leopard, Asiatic wild dog, gaur, elephants in coffee estate forest',10),
('nature','안나푸르나 트레킹','Annapurna Circuit','NP','World famous trek; 230km, 8 ecosystems, Thorung La 5416m pass',15),
('nature','생 줄리앙 폭포','Pulo Cinta Falls','PH','Heart-shaped lake atop Mindanao mountain; remote trekking through jungle',15),
('nature','샴페인 풀','Champagne Pool','NZ','Geothermal orange-rimmed pool 74C; arsenic edge, Wai-O-Tapu thermal park',10),
('nature','삼청각 협곡','Taroko Gorge','TW','Marble canyon; Liwu River threading through Taiwan east coast mountains',10);

-- ANIMALS
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('animals','아프리카 사자','African Lion','KE','Masai Mara prides; best seen at dawn, June-October Great Migration season',10),
('animals','아프리카 코끼리','African Elephant','TZ','Amboseli herds against Kilimanjaro backdrop; matriarch-led society',10),
('animals','아프리카 표범','Leopard','ZA','Sabi Sands nocturnal hunting; most adaptable big cat, tree hoisting kills',15),
('animals','치타','Cheetah','KE','Worlds fastest land animal; Mara cubs seen with famous mother cheetahs',10),
('animals','코뿔소','White Rhino','ZA','Kruger conservation success; 5-tonne tank grazers, mud wallow social',10),
('animals','하마','Hippopotamus','ZM','Luangwa River at sunset; surprisingly fast, most dangerous African mammal',10),
('animals','기린','Giraffe','TZ','Tallest animal 5.5m; Maasai Giraffe endangered, tongue purple 45cm',10),
('animals','고릴라','Mountain Gorilla','RW','Volcanoes NP silver-backs; 99% human DNA, playful infants, knuckle walk',20),
('animals','오랑우탄','Bornean Orangutan','MY','Semengoh sanctuary; 97% DNA human, tool use, oil palm crisis',15),
('animals','거대 판다','Giant Panda','CN','Chengdu Research Base; bamboo-only diet, twin cubs, conservation icon',15),
('animals','눈표범','Snow Leopard','IN','Hemis NP Ladakh; most elusive big cat, Himalayan ghost, long tail balance',20),
('animals','호랑이','Bengal Tiger','IN','Ranthambhore lakes; ambush predator, territory 100km2, IUCN vulnerable',15),
('animals','코모도 왕도마뱀','Komodo Dragon','ID','Rinca and Komodo Islands; venomous saliva, 3m long, ambush antelope',15),
('animals','왕홍학','Greater Flamingo','KE','Lake Nakuru millions; pink from algae shrimp diet, running takeoff',10),
('animals','혹등고래','Humpback Whale','TO','Tonga Ha apai swimming; 40-tonne acrobat, bubble net feeding, song',15),
('animals','향유고래','Sperm Whale','PT','Azores year-round; biggest toothed predator, dives 3km, clicks echolocate',15),
('animals','범고래','Orca','NO','Andfjorden winter herring; cooperative pod hunting, matriarchal culture',15),
('animals','흰수염고래','Blue Whale','MX','Sea of Cortez; largest animal ever, 190 tonnes, 30m, heart size car',20),
('animals','쥐가오리','Manta Ray','MV','Hanifaru Bay feeding aggregations; wingspan 7m, brain-to-body ratio high',15),
('animals','고래상어','Whale Shark','AU','Ningaloo Reef; largest fish 12m, filter feeder, gather March-July',15),
('animals','나일 악어','Nile Crocodile','TZ','Grumeti River wildebeest crossing; 1000kg ambush, mothers carry young',10),
('animals','해마','Seahorse','PH','Tubbataha Reef; only species where male pregnant, 1000 eggs, slow drift',10),
('animals','도깨비 가오리','Mobula Ray','MX','La Paz mass jumping; up to 10,000 gather, breach 2m above water',15),
('animals','아델리 펭귄','Adelie Penguin','AQ','Antarctic colony; Tuxedo birds march, fastest underwater penguin swim',20),
('animals','왕펭귄','Emperor Penguin','AQ','Antarctic winter breeding; -60C dedication, huddle warmth, 115-day fast',20),
('animals','흰배오리','Albatross','GS','South Georgia colony; longest wingspan 3.7m, mate for life 60 years',15),
('animals','파충류 이구아나','Marine Iguana','EC','Galapagos only sea lizard; sneezes salt, swims 10m deep, solar basking',15),
('animals','자이언트 거북','Galapagos Tortoise','EC','150 years old; distinct subspecies each island, Darwin evolution evidence',15),
('animals','하피 독수리','Harpy Eagle','BR','Amazon canopy; 2m wingspan, sloth monkey hunter, biggest eagle Americas',20),
('animals','퀘찰','Resplendent Quetzal','GT','Cloud forest Guatemala; 1m tail, sacred Mayan bird, avocado disperser',15),
('animals','아나콘다','Green Anaconda','BR','Amazon largest snake 9m, 250kg; ambush caiman, silent river predator',15),
('animals','피그미 하마','Pygmy Hippo','LR','West Africa forest; nocturnal, secretive, solitary, critically endangered',20),
('animals','아프리카 들개','African Wild Dog','BW','Okavango pack; 80% hunt success rate, regurgitation share, endangered',15),
('animals','가오리','Stingray','AU','Lady Elliot Island; hundreds gather at cleaning stations, docile reef glide',10),
('animals','피그미 문어','Blue-Ringed Octopus','AU','Sydney rock pools; rings glow warning, venom kills 26 humans, no antidote',15),
('animals','큰 바다사자','Galapagos Sea Lion','EC','Fernandina Island; surf-riding, belly-rub rocks, pups curious about snorkelers',10),
('animals','비버','Beavers','CA','Algonquin Park; dam engineers, night lodge builders, winter food cache',10),
('animals','그리즐리 곰','Grizzly Bear','CA','Khutzeymateen salmon catch; 400kg, cubs play, fat-building before hibernate',15),
('animals','북극곰','Polar Bear','NO','Svalbard sea ice hunt; largest land carnivore, black skin under white fur',20),
('animals','일각고래','Narwhal','CA','Hudson Bay Arctic; spiral ivory tusk 3m, canary of the sea call',20),
('animals','해달','Sea Otter','US','Monterey Bay holding hands; tool-using, marine mammal conservation icon',10),
('animals','순록','Reindeer','NO','Svalbard migration; herd travel 5000km, velvet antlers, both sexes antlers',10),
('animals','울버린','Wolverine','FI','Scandinavia forest; most fearless animal, 15kg attacks moose, mustelid',20),
('animals','리라새','Superb Lyrebird','AU','Royal NP Sydney; mimics 20 species, chainsaw camera, 7 year tail grow',15),
('animals','카수아리','Cassowary','AU','Daintree rainforest; most dangerous bird, 50mm dagger claw, casque helmet',15),
('animals','코카투','Black Cockatoo','AU','Perth hills; rare Baudin''s species, banksia seeds, slow decline',15),
('animals','안데스 콘도르','Andean Condor','CL','Torres del Paine thermals; 3.3m wingspan largest flying bird, 75 years',15),
('animals','재규어','Jaguar','BR','Pantanal boat tours; swim, bite through turtle shells, apex predator',15),
('animals','맥','Tapir','CR','Corcovado forest trails; gentle browser, 6000 year lineage, endangered',15),
('animals','카피바라','Capybara','BR','Pantanal river banks; worlds largest rodent 65kg, sociable, herd 100',10),
('animals','아르마딜로','Giant Armadillo','BR','Cerrado burrow; 60cm carapace, critically endangered, night digger',20),
('animals','토케이 도마뱀붙이','Tokay Gecko','TH','Southeast Asia; loudest gecko call, medicinal trade pressure, bark camouflage',10),
('animals','임팔라','Impala','KE','Amboseli herds; red-oat grass grazer, male harem fights, alarm sneeze',10),
('animals','누','Wildebeest','TZ','Serengeti crossing; 1.5 million strong, Mara River crocodiles, July-October',10),
('animals','제브라','Plains Zebra','KE','Ngorongoro individual stripe patterns; lion confusion tactic, dust bath',10),
('animals','오릭스','Gemsbok Oryx','NA','Namib desert adapted; reflects sunlight, 45C body temp tolerance, sword horn',10),
('animals','웜배트','Wombat','AU','Tasmania cube poos; backwards pouch, bulldozer burrow, koala relative',10),
('animals','쿼카','Quokka','AU','Rottnest Island; happiest animal smiles, hop joey, tourists selfie spot',10),
('animals','태즈메이니아 데빌','Tasmanian Devil','AU','Healesville; facial tumour disease, strongest bite per body, night scavenger',15),
('animals','쿼알라','Koala','AU','Kangaroo Island eucalyptus; sleeps 22hrs, fingerprint like human, toxic leaves',10),
('animals','캥거루','Red Kangaroo','AU','Flinders Ranges mob; 70 km/h, joey pouch, sparring males, arid adapted',10),
('animals','플라타너스 오리','Platypus','AU','Eungella NP; electroreception bill, mammal lays eggs, venomous spur male',15),
('animals','에뮤','Emu','AU','Outback wanderer; 2m flightless, male broods eggs, 3-toed sprint 50km/h',10),
('animals','클로운피쉬','Clownfish','AU','Great Barrier Reef anemone; protandrous hermaphrodite, Nemo inspiration',10),
('animals','피그미 슬로우 로리스','Pygmy Slow Loris','VN','Vietnam forest; toxic bite, big eyes night, illegal pet trade pressure',15),
('animals','긴코 돌고래','Long-snouted Spinner Dolphin','MX','Baja 360 spins; pod 1000 synchronised jumps, tuna fishing net bycatch',10),
('animals','블루 모핀','Blue Morpho Butterfly','CR','Costa Rica cloud forest; 20cm iridescent wings, 115 species rainforest',10),
('animals','황금 독화살 개구리','Golden Poison Frog','CO','Pacific Colombia; 2cm deadliest animal on Earth, Embera people arrow tips',15),
('animals','아프리카 왕관 독수리','African Crowned Eagle','ZA','Most powerful; kill prey 4x its weight, monkey hunter, elaborate display',15),
('animals','월러비','Wallaby','AU','Grampians NP Victoria; red-necked species joey, kangaroo relative smaller',10),
('animals','갈라파고스 핀치','Darwin''s Finch','EC','13 species beak shapes; evolution evidence Darwin 1835, tool use woodpecker',15),
('animals','코뿔새','Rhinoceros Hornbill','MY','Borneo rainforest; casque amplifies call, fruit disperser, nest cement-seal',15),
('animals','만드릴','Mandrill','GA','Gabon Lopé NP; most colorful mammal, group 800 horde, male face status',15),
('animals','올빼미','Snowy Owl','CA','Nunavut tundra; wingspan 1.6m, lemmings, Harry Potter Hedwig inspiration',10),
('animals','불꽃 해파리','Lion''s Mane Jellyfish','NO','Arctic waters; tentacles 37m, largest invertebrate, ocean giants',15),
('animals','멸종위기 오카피','Okapi','CD','Congo forest; giraffe relative, tongue cleans eye, only in DRC reserves',20),
('animals','검은 재규어','Black Jaguar','BR','Pantanal melanistic; same species as spotted, camera trap photography prize',20),
('animals','코끼리 거북','Aldabra Tortoise','SC','Seychelles; second largest tortoise 250kg, 200 year lifespan candidates',15),
('animals','일본 원숭이','Japanese Macaque','JP','Jigokudani Snow Monkey; hot spring bathing, infant play, -15C survival',10),
('animals','한국 반달가슴곰','Asiatic Black Bear','KR','Jirisan NP; conservation program, V-chest mark, bamboo shoots diet',15),
('animals','인도 코뿔소','Indian One-horned Rhino','IN','Kaziranga Assam; comeback from 200 to 3000, tallest grass meadow swim',10),
('animals','사이가 영양','Saiga Antelope','KZ','Kazakhstan steppe; proboscis filter dust, 2015 mass die-off, recovery effort',15),
('animals','스라소니','Eurasian Lynx','CH','Swiss Jura; reintroduced 1971, tufted ears, snowshoe paws, roe deer',15),
('animals','이베리아 스라소니','Iberian Lynx','ES','Andujar Sierra; most endangered cat 400 remain, rabbit dependence, amber eyes',20),
('animals','늑대','Gray Wolf','YS','Yellowstone reintroduction 1995; changed rivers trophic cascade, howl territory',15),
('animals','불곰','Brown Bear','RU','Kamchatka salmon river; 600kg salmon catch acrobatics, autumn fat-up',15),
('animals','마코 상어','Shortfin Mako Shark','PT','Azores pelagic; fastest shark 74km/h, leaps 6m, blue water encounters',15),
('animals','검돌고래','Common Dolphin','PT','Algarve bow-riding; 1000 super-pod, acrobatic, common but fascinating shoal',10),
('animals','바다뱀','Sea Krait','PH','Palawan coral reef; beautiful banded, highly venomous but docile, air breath',10),
('animals','아메리카 들소','American Bison','US','Badlands herd; 30 million to 500,000; Yellowstone plains thundering hooves',10),
('animals','프레리 도그','Black-tailed Prairie Dog','US','South Dakota towns; sentinel bark warning, kiss greeting, ecosystem keystone',10);

-- FESTIVALS
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('festivals','리우 카니발','Rio Carnival','BR','Worlds biggest carnival; Sambadrome parade, 2 million street dancers',10),
('festivals','옥토버페스트','Oktoberfest','DE','Munich beer festival 6M visitors; dirndl lederhosen, brass band tents',10),
('festivals','토마티나','La Tomatina','ES','Bunol tomato fight; 150 tonnes crushed tomatoes, last Wednesday August',10),
('festivals','디왈리','Diwali','IN','Festival of Lights; clay diyas, fireworks, Rangoli, Lakshmi worship',10),
('festivals','홀리','Holi','IN','Festival of Colours; spring celebration, gulaal powder, Mathura Vrindavan',10),
('festivals','나아담','Naadam Festival','MN','Three manly games; wrestling horse archery Ulaanbaatar July 11-12',10),
('festivals','쏭크란','Songkran','TH','Thai New Year water fight; April 13, Buddha washing, Chiang Mai streets',10),
('festivals','불꽃 축제','Guy Fawkes Night','GB','Bonfire and fireworks; Parliament plot 1605, November 5, Lewes biggest',10),
('festivals','에딘버러 프린지','Edinburgh Fringe','GB','Worlds largest arts festival; 50,000 performances, August, free shows',10),
('festivals','카르나발 베네치아','Venice Carnival','IT','Masks and costumes; 2-week February festival, Piazza San Marco parade',10),
('festivals','에비앙 페스티발','WOMAD','GB','World music arts dance; 50 countries, Peter Gabriel founded, Charlton Park',10),
('festivals','다야 데 무에르토스','Día de los Muertos','MX','Day of the Dead; Oaxaca cemetery altar, marigold roads, sugar skulls',10),
('festivals','란턴 페스티발','Lantern Festival','TW','Yi Peng Chiang Mai sky lanterns; 15th lunar month, romantic floating lights',10),
('festivals','하누카','Hanukkah','IL','Festival of Lights; menorah 8 candles, dreidel, latkes, Jerusalem old city',10),
('festivals','체리 블로섬','Hanami Cherry Blossom','JP','Sakura picnic parties; Maruyama Park Kyoto, Ueno Tokyo, April bloom',10),
('festivals','나타르 수확제','Pushkar Camel Fair','IN','Rajasthan camel trade; 50,000 camels, musicians, hot air balloons, dunes',10),
('festivals','파묵칼레 자연 축제','Glastonbury Festival','GB','Worlds most famous music festival; Pyramid Stage, Worthy Farm, 200,000',15),
('festivals','코아첼라','Coachella','US','California desert arts music; Empire Polo Club, April, celebrity sightings',15),
('festivals','블랙 록 시티','Burning Man','US','Black Rock Desert art community; radical self-reliance, effigy burn night',20),
('festivals','카르나발 오루로','Oruro Carnival','BO','UNESCO; devil dance Diablada, 400 years tradition, February procession',15),
('festivals','인티 라이미','Inti Raymi','PE','Inca Sun Festival; Sacsayhuaman Cusco June 24, 10,000 spectators',15),
('festivals','다카르 랠리','Dakar Rally','SA','Worlds most grueling off-road race; dunes mud, Jan, motorcycles trucks',15),
('festivals','투르 드 프랑스','Tour de France','FR','23-stage cycling epic; July, Champs-Elysees finish, alpe d huez climb',10),
('festivals','멀티 문화 축제','Carnival of Trinidad','TT','Caribbean mas; J ouvert steel pan, Mon repos jump up, soca fete',15),
('festivals','보첼리 팜콘서트','Bocelli Concert','IT','Lajatico Teatro del Silenzio; amphitheatre in Tuscany hills, annual July',15),
('festivals','엘레판트 마할라','Elephant Festival','TH','Surin November; 200 elephants parade, tug-of-war, ancient battle reenact',10),
('festivals','상하이 국제영화제','Shanghai International Film Festival','CN','Asia largest; competitive section, Golden Goblet award, June, 30 years',10),
('festivals','에든버러 군악 퍼레이드','Royal Edinburgh Military Tattoo','GB','Castle esplanade; 220,000 attend, global military bands, August nights',10),
('festivals','크리스마스 마켓','Nuremberg Christkindlesmarkt','DE','Most famous Christmas market; 200 stalls, gingerbread, lebkuchen, Gluhwein',10),
('festivals','쿰브 멜라','Kumbh Mela','IN','Worlds largest human gathering 400M; Prayagraj Ganga bath, every 12 yrs',15),
('festivals','살가도 페스티벌','Tomorrowland','BE','Worlds biggest EDM festival; Boom Belgium, 400,000 attendees, fantasy stage',10),
('festivals','리조베르 카니발','Basel Carnival','CH','Switzerland largest; Morgestraich 4am drums lanterns, Larven masks, March',10),
('festivals','하르에 미 뒤베라','Harbin Ice Festival','CN','January sculpture city; palace and dinosaur in ice, -30C, light show',10),
('festivals','동굴 소금상','Wieliczka Salt Mine Concert','PL','Underground church; chandeliers stalactites, classical music 300m deep',10),
('festivals','와이올레아 훌라','Merrie Monarch Festival','US','Hawaii hula competition; Hilo, week-long, kahiko modern, royalty honor',10),
('festivals','아이슬란드 비킹 축제','Secret Solstice Iceland','IS','24-hour daylight music; inside glacier, geothermal lagoon, volcano concerts',20),
('festivals','버뮤다 트라이애슬론','Bermuda Day','BM','First public holiday; half marathon race, fitted dinghy, heritage parade',10),
('festivals','파다에 시네마','Cinema Paradiso Festival','GB','Outdoor rooftop cinema; Somerset House, deckchairs, London summer series',10),
('festivals','보름달 파티','Full Moon Party','TH','Koh Phangan Haad Rin; monthly night beach rave, fire shows, 30,000 gather',10),
('festivals','커피 수확 축제','Colombian Coffee Festival','CO','Buenavista Quindio; coffee picking demonstration, donkey parade, bamboo craft',10),
('festivals','씨마무루 사막 축제','Sahara International Festival','DZ','Douz Tunisia; horseback fantasia, camel racing, traditional Saharan music',10),
('festivals','오에리 시사무라이 축제','Nikko Toshogu Festival','JP','1000 samurai procession; Tokugawa shrine May, armor, horses, drum',10),
('festivals','꽃 카니발','Battle of Flowers','NL','Zundert dahlia sculptures; September Netherlands, 900,000 flowers per float',10),
('festivals','퀴어 퍼레이드','Pride Amsterdam','NL','Canal boat parade; August, 500 boats, world largest Pride event on water',10),
('festivals','반리 투뿌 잉카 축제','Inti Raymi Cusco','PE','Inca winter solstice; Sacsayhuaman fortress June 24, firelight ceremony',10),
('festivals','새해맞이 불꽃','Sydney New Year Fireworks','AU','Harbour Bridge midnight; 8.5 tonnes fireworks, 1 billion TV viewers',10),
('festivals','에펠탑 불꽃 축제','Bastille Day Paris','FR','July 14 national day; Champs-Elysees military parade, Eiffel Tower lights',10),
('festivals','나가노 설원 축제','Sapporo Snow Festival','JP','February Odori Park; 200 snow ice sculptures, 2 million visitors, replica buildings',10),
('festivals','고래 죽제 축제','Whale Festival Baja','MX','Gray whale mating lagoons; San Ignacio, mothers bring calves to boats',15),
('festivals','켈트 음악 축제','Celtic Connections Glasgow','GB','January world Celtic music hub; 2000 artists, trad sessions, free events',10),
('festivals','아마존 낚시 축제','Pirarucu Festival','BR','Amazon river fish festival; giant 250kg fish, canoe races, indigenous dance',10),
('festivals','라오 무용 축제','Bun Bang Fai Rocket Festival','LA','Yasothon Thailand rockets; prayer for rain, bamboo rockets 20km sky',10),
('festivals','팜플로나 소몰이','San Fermin Bull Run','ES','Pamplona July 7; 8 am 800m race, 500 year tradition, red scarves',10),
('festivals','알로아 할로윈','Halloween Salem','US','Massachusetts October; witch trial history, costume parades, haunted tours',10),
('festivals','모래 예술 축제','Puri Sand Art Festival','IN','Odisha beach November; 80 sand artists, Sudarsan Pattnaik master,',10),
('festivals','야나가와 등불 축제','Yanagawa Lantern Boat','JP','Fukuoka canal float; 3,000 lanterns, gondola song, firefly June evening',10),
('festivals','스코틀랜드 게임스','Highland Games','GB','Caber toss stone put; Braemar Gathering, September, Royal attendance',10),
('festivals','화이트 위크','Inti Raymi Bolivia','BO','Tiwanaku site solstice; Pre-Inca ceremony at gate of sun, June 21',10),
('festivals','말리 투마니 사미아 축제','Festival in the Desert','ML','Essakane near Timbuktu; Tuareg music, camel races, fires under stars',20),
('festivals','웨이브 뮤직 페스티벌','Roskilde Festival','DK','Denmark Eurasian; humanitarian org run, camping village, 130,000 attend',10),
('festivals','쿠로베 축제','Nagasaki Kunchi Festival','JP','October 7-9; Chinese Dutch influence dance, dragon dance, daimyo parade',10),
('festivals','미국 컨트리 뮤직','Country Music CMA Fest','US','Nashville June; 100 acts, Nissan stadium, 4 day fan event, boots line',10),
('festivals','아프리카 뮤직 페스티벌','FESPAM','CG','Brazzaville biennial; Pan African music, 30 countries, Congo River beat',10),
('festivals','파디냐 음악 축제','Fado Festival Lisbon','PT','Alfama September; most soulful music Portugal, fado houses, saudade',10),
('festivals','자전거 축제','Cycle Festival Amsterdam','NL','May bike month; flower parade fietsvierdaagse, 40,000 cyclists, route',10),
('festivals','거인 인형 축제','Giants of Mechelen','BE','Ommegang procession; medieval giant puppets, 30 countries, summer July',10),
('festivals','봄꽃 축제','Keukenhof Tulip Festival','NL','Lisse March-May; 7 million bulbs, 800 varieties, windmill, 1 km2 park',10),
('festivals','프라하 봄 음악제','Prague Spring Music Festival','CZ','May classical; opening Smetana My Homeland, Prague Spring 1968 memory',10),
('festivals','와이나피추 태양 축제','Maya Winter Solstice','MX','Chichen Itza December 21; serpent shadow El Castillo pyramid light play',10),
('festivals','스위스 올드 타운 축제','Zurich Street Parade','CH','World''s biggest techno rave; August 200,000 ravers, Zurich Lake, love mobiles',10),
('festivals','알래스카 개썰매 축제','Iditarod','US','Nome 1600km sled race; March, 1925 serum run, mushers, husky teams',15),
('festivals','안달루시아 페리아','Feria de Abril','ES','Seville April; flamenco ruffled dresses, sherry, papeles, caseta tents',10),
('festivals','모리타니아 나다','Festival of the Nomads','MR','Atar oasis; Moorish poetry music, silver jewellery, camel beauty contest',15),
('festivals','라플란드 순록 경주','Reindeer Racing Inari','FI','March Inari; Sami joik song, lasso competition, pulka sleigh races snow',10),
('festivals','아즈텍 비','Día de la Lluvia','MX','Tlaloc rain god ceremony; Tlalocan priests dance, cacao offerings, March',10),
('festivals','탱고 축제','Buenos Aires Tango Festival','AR','August world capital; milongas outdoor, championship, 500 teachers',10),
('festivals','보름달 기도','Vesak Full Moon','LK','Buddha birthday Lanka; white dress dansala food giving, lanterns everywhere',10),
('festivals','진자 축제','Jinja Festival Uganda','UG','Source of Nile October; boat races, tribal dances, cultural convergence',10),
('festivals','이스탄불 재즈 축제','Istanbul Jazz Festival','TR','July Bosphorus concerts; jazz on two continents, ferry sunset concerts',10),
('festivals','리오 프레타 쿠두로','Rio Loco Festival','FR','Toulouse world music; 5 days June, 200,000, free stages Garonne riverside',10),
('festivals','키예프 마술 축제','Kyiv Street Music Festival','UA','May city stages; buskers world, Ukraine folk trad, eclectic genres',10),
('festivals','모로코 로즈 축제','Rose Festival Dades Valley','MA','Kelaa M Gouna May; rose water blessing, petals carpet, princess queen',10),
('festivals','방콕 채식 축제','Vegetarian Festival Phuket','TH','9 Emperor Gods October; firewalking, cheek piercing, white clothes',10),
('festivals','도쿄 스모 토너먼트','Sumo Grand Tournament Tokyo','JP','Ryogoku Kokugikan January; 15 days, highest makuuchi rank, shinto ritual',10),
('festivals','울룰루 문화 축제','Uluru Song Lines','AU','September; Aboriginal dance and story, dot painting, didgeridoo ceremony',15),
('festivals','아이스 뮤직 축제','Geilo Ice Music Festival','NO','February; instruments carved from ice, concert in snow dome, unique sound',15),
('festivals','야간 코끼리 퍼레이드','Esala Perahera','LK','Kandy August; Sacred Tooth Relic, 80 elephants, dancers drummers night',10),
('festivals','라 메르세드 카니발','Carnaval de Oruro','BO','UNESCO Bolivian Andes; 48 folk groups, 28,000 dancers, 10km procession',15),
('festivals','분홍 소금 호수 축제','Lake Retba Festival','SN','Pink lake music; Wolof dance, tom-tom drums, salt harvesting ceremony',10),
('festivals','해리 포터 이벤트','Hogwarts Express Experience','GB','ScotRail Jacobite train; Glenfinnan Viaduct, North Berwick to Mallaig steam',10),
('festivals','우주 탐구 축제','Aurora Festival Tromso','NO','January Tromso; aurora hunt reindeer sled, sami culture, icy fjord',15),
('festivals','물 위의 음악','Venice Opera Barge','IT','Summer canal concert; gondola serenade, La Fenice history, Vivaldi land',10),
('festivals','아이슬란드 빛 축제','Reykjavik Winter Lights','IS','February; city bathed in art light, swimming pool special event, dark season',10),
('festivals','사막의 춤','Rajasthan Desert Festival','IN','Jaisalmer February; camel races, folk music, turban tying contest, sand dunes',10),
('festivals','가나 케파 축제','Homowo Festival Ghana','GH','Harvest thanksgiving; Ga people August, pork sharing, ancestral libation',10),
('festivals','마디 그라','Mardi Gras New Orleans','US','New Orleans Fat Tuesday; French Quarter beads, parades, jazz, purple green gold',10),
('festivals','노팅힐 카니발','Notting Hill Carnival','GB','London August; Caribbean carnival, 2 million, steel pan, jerk chicken',10),
('festivals','칸 영화제','Cannes Film Festival','FR','Riviera May; Palme d Or red carpet, Croisette, world cinema premieres',15),
('festivals','몽트뢰 재즈 페스티벌','Montreux Jazz Festival','CH','Lake Geneva July; 2 weeks, Queen recorded, free lakeside stages',10),
('festivals','시게트 페스티벌','Sziget Festival','HU','Budapest Obuda Island August; week-long camp, 400,000, multi-genre',10);

-- SURFING
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('surfing','파이프라인','Banzai Pipeline','US','North Shore Oahu; hollow tubes December-February, biggest pro surfing event',20),
('surfing','뚜아포','Teahupoo','PF','Tahiti heaviest wave; slabs over shallow reef, brutal, Billabong Pro host',20),
('surfing','재프스','Jaws (Pe''ahi)','US','Maui tow-in wave; 20m faces, winter swell, tow-in surfing pioneer spot',20),
('surfing','게리 호드게스','Nazare','PT','Atlantic swell funnelling; 100ft+ big wave record, Praia do Norte cliff view',20),
('surfing','마베릭스','Mavericks','US','Half Moon Bay winter; cold water big wave, Eddie Aikau hold-down legend',15),
('surfing','벨스 비치','Bells Beach','AU','Rincon Point Victoria; Rip Curl Pro every Easter, iconic right-hander',10),
('surfing','스낵스','Snapper Rocks','AU','Gold Coast superbank; 2km right-hander, Quiksilver Pro opening WCT event',10),
('surfing','라가디르','Uluwatu','ID','Bali sea cave entry; long left-hander, offshore Balinese temple backdrop',10),
('surfing','오피셜','Mundaka','ES','Basque Country; estuary left barrel, only works big swells, Rip Curl Pro',15),
('surfing','클라우드 브레이크','Cloudbreak','FJ','Tavarua Fiji boat-access; 2km left, Volcom Pipe Pro historic, warm water',15),
('surfing','수페르투부스','Supertubes','ZA','Jeffreys Bay right-hander; J-Bay Open WCT host, June-July swell season',10),
('surfing','케이프타운 포인트','Cape Town Crayfish Factory','ZA','Cold Benguela Current swell; kelp beds, seals, right tube Kommetjie area',15),
('surfing','하와이 선샤인','Honolua Bay','US','Maui winter right; protected inside bay, overhead barrels, no crowds',10),
('surfing','코스타리카 플라야','Playa Hermosa','CR','Jacó perfect beach break; consistent barrels, black sand, less crowds',10),
('surfing','멘도사 칠레','Pichilemu','CL','Punta de Lobos; South American big wave, Chile WSL event, cold Pacific',10),
('surfing','발리 차랑간','Padang Padang','ID','Little Bali pipeline; June-August only works, Eat Pray Love film location',10),
('surfing','마무드','G-Land (Grajagan)','ID','Java jungle point; 3km left, boat access jungle camp, perfect season May-Oct',15),
('surfing','죠스 인도양','Shipstern Bluff','AU','Tasmania remote; mutant step waves, thick lips, shark territory, helicopter in',20),
('surfing','뉴질랜드 래글란','Raglan','NZ','NZ best left-hander; Manu Bay consistent, filming location Endless Summer II',10),
('surfing','프랑스 바이욘','Hossegor','FR','Landes beach breaks; multiple peaks, Quiksilver Pro Europe, October swell',10),
('surfing','스리랑카 힉카두와','Hikkaduwa','LK','Sri Lanka reef breaks; December-March north swell, turtles surfing same wave',10),
('surfing','포르투갈 페니체','Peniche','PT','Supertubos beach break; Medewi-style barrels, Rip Curl Pro host, October',10),
('surfing','모로코 아가디르','Anchor Point','MA','Taghazout right-hander; constant swell, cheap surf camp culture, Atlas view',10),
('surfing','멕시코 투흐파고','Puerto Escondido','MX','Mexican Pipeline; aggressive beach break, shorebreak slabs, August-September',15),
('surfing','니카라과 포포요','Popoyo','NI','Off-shore double peaks; consistent all year, warm water, volcano backdrop',10),
('surfing','인도네시아 망구닛','Desert Point','ID','Lombok legendary left; 200m barrel, offshore wind essential, remote boat',20),
('surfing','모잠비크 토포','Tofinho','MZ','Ponta do Ouro; Indian Ocean right-hander, dolphins, whale season July-Aug',10),
('surfing','하와이 라니아케아','Laniakea Beach','US','North Shore beginner legend; turtles on beach, gentle longboard waves',10),
('surfing','피지 타바루아','Tavarua Island','FJ','Private island resort breaks; Restaurants left and right, beginner waves too',10),
('surfing','브라질 가르사','Itacaré','BR','Bahia jungle waves; 15 breaks in 12km, Engenhoca barrel, warm water',10),
('surfing','아르헨티나 마르델플라타','Mar del Plata','AR','South American cold surf; consistent reef breaks, Argentine WSL events',10),
('surfing','남아공 던스버러','Dungeons','ZA','Hout Bay big wave; granite boulders, south swell, shark cage diving nearby',15),
('surfing','스페인 칸타브리아','El Gorrión','ES','Cantabrian season gem; October-March consistent long rights, basque country',10),
('surfing','인도 코박람','Kovalam','IN','Kerala longboard waves; Indian Ocean November-March season, warm water',10),
('surfing','파나마 산타카탈리나','Santa Catalina','PA','Remote Central America gem; consistent reef breaks, June-December swells',10),
('surfing','멕시코 케이프','Todos Santos Island','MX','Baja big wave; January-February, 20m waves, Todos Santos Big Wave Classic',15),
('surfing','스페인 카나리아','El Hierro','ES','Secret Canary Islands gem; Jacks and other consistent spots, volcanic reef',10),
('surfing','미국 산타크루즈','Steamer Lane','US','California reef right; Cold Water Classic, seals in lineup, classic venue',10),
('surfing','하와이 키아후루','Sunset Beach','US','North Shore big wave classic; December-February, Eddie Invitational location',15),
('surfing','호주 퍼스 인도양','The Box','AU','Margaret River WA; square tube, deep-water slab, hold-down consequence',15),
('surfing','멕시코 오아사가','Barra de la Cruz','MX','Oaxaca right-hander; rock reef barrels, local secret revealed, clear water',10),
('surfing','베트남 다낭','Da Nang','VN','China Beach; September-November typhoon swells, kite and surf school area',10),
('surfing','인도네시아 수마트라','Nias','ID','Lagundri Bay right-hander; cobblestone bottom, long rides, 1970s pioneer',15),
('surfing','캘리포니아 핸버거','Blacks Beach','US','La Jolla nudist beach; powerful south swell reef break, cliff access hike',10),
('surfing','아이슬란드 빙하 서핑','Kaldbakur Iceland','IS','Arctic island surfing; sub-zero water, lava reefs, northern lights possible',20),
('surfing','로빈 아일랜드','Skeleton Bay','NA','Namibia 3km+ left point; perfect offshore SE wind, rarely breaks big swell',20),
('surfing','마다가스카르 릴리','Anakao','MG','Southern Madagascar reef; uncrowded Indian Ocean breaks, zebu cart',15),
('surfing','이스터섬','Easter Island','CL','Moai monument surf; consistent Pacific swell, isolated island, clear blue',15),
('surfing','보르네오 서핑','Pulau Mantanani','MY','Sabah Borneo; clear water reef breaks, turtles, sunrise surf sessions',10),
('surfing','남극 서핑','Antarctica Surfing','AQ','King George Island; icebergs in lineup, drysuits essential, penguin audience',20),
('surfing','가나 부스아','Busua','GH','West Africa consistent; warm water year-round, novice friendly beach break',10),
('surfing','리오 스타 포인트','Saquarema','BR','Rio state right-hander; ISA World Games host, October-November swell',10),
('surfing','홍콩 빅 웨이브','Big Wave Bay','HK','HK surf spot; typhoon swell magnet, longboard community, August season',10),
('surfing','태국 서핑','Nai Harn Beach','TH','Phuket September-November; Thailand surfing hub, kite season overlap',10),
('surfing','일본 치바','Chiba Tsurigasaki','JP','Tokyo Olympics venue; 2021 first Olympic surfing, Japanese pro tour',10),
('surfing','한국 양양','Yangyang','KR','Korea surf mecca; consistent beach break, July typhoon swells, Seoul 2hrs',10),
('surfing','인도네시아 반팅','Krui Left','ID','Sumatra southwest coast; long points, empty jungles, right too at Some',10),
('surfing','필리핀 시아르가오','Cloud 9','PH','Siargao Island perfect; hollow right-hander, Philippine Surfing Cup host',10),
('surfing','말디브','Pasta Point','MV','Maldives surf resort-only; left-hander Cokes area, uncrowded atolls',15),
('surfing','프랑스 기아리','La Gravière','FR','Capbreton beach break; winter barrels, powerful shorepound, Hossegor area',10),
('surfing','레위니옹 섬','Saint-Leu','RE','Reunion Island right-hander; perfect wall, warm water, bull shark history',15),
('surfing','칠레 피치레무','Lobos Point','CL','Pichilemu bigwave satellite; Lobos competition platform, cold Pacific',10),
('surfing','갈라파고스','Galapagos Surf','EC','Remote Pacific breaks; marine iguana audience, sea lions in lineup, epic',15),
('surfing','멕시코 바하','Scorpion Bay','MX','Baja 8-point stretch; 10 consecutive rights, consistent NW swell season',10),
('surfing','호주 퀸즐랜드','Kirra Point','AU','Gold Coast classic; sand-covered reef right, Superbank adjacent, WCT history',10),
('surfing','카나리아 란사로테','Lanzarote Chicama','ES','Canary Island reef; year-round swell, consistent east swell, volcanic lava',10),
('surfing','페루 치카마','Chicama','PE','Worlds longest left wave 4km; rare conditions needed, port breaks chain',20),
('surfing','페루 파카스마요','Pacasmayo','PE','Peru left-hander; works SE trade winds only, low tide slab, town pier',10),
('surfing','팔라우','Palau Surf','PW','Micronesian reef breaks; warm water, pristine coral, diverse breaks',10),
('surfing','쿡 제도','Rarotonga','CK','South Pacific reef break; Raemaru Right, warm water, uncrowded paradise',10),
('surfing','사모아','Boulders Samoa','WS','Upolu Island right-hander; dangerous shallow reef, world-class but risky',15),
('surfing','타히티 무루로아','Hava i Nui','PF','French Polynesia; Olympic surfing test event Teahupo''o 2024, crystal clear',15),
('surfing','아라비아해 서핑','Oman Surf','OM','Monsoon season June-Sept; consistent beach reef breaks, empty waves',10),
('surfing','이스라엘 텔아비브','Hilton Beach','IL','Mediterranean swell; autumn-winter season, city skyline backdrop surfing',10),
('surfing','알제리 알제','Ain El Turck','DZ','North Africa undiscovered; Mediterranean swell, autumn perfect, surf culture',10),
('surfing','튀니지 서핑','Tabarka','TN','Mediterranean season surf; October-March swells, cedar forest backdrop',10),
('surfing','파키스탄 과다르','Gwadar','PK','Arabian Sea; rare surfing frontier, CPEC coast, remote adventure wave',15),
('surfing','아일랜드 슬라이고','Strandhill','IE','Wild Atlantic Way; heavy shore break, Donegal right-handers, autumn',10),
('surfing','노르웨이 라플란드','Unstad Arctic Surf','NO','Norway Lofoten; -5C surf, Northern Lights possible, fishing village charm',15),
('surfing','아이슬란드 힘카후에르','Gardar','IS','Remote Iceland reef; sub-zero suits, unpredictable katabatic, commitment',20),
('surfing','캐나다 토피노','Tofino','CA','BC Vancouver Island; winter swells, whale watching, cedar forest backdrop',10),
('surfing','스코틀랜드 서나이','Thurso East','GB','Scotland cold right-hander; Caithness flag reef, November-February best',10),
('surfing','아이리시해 서핑','Mullaghmore','IE','Ireland big wave; 20m+ swell, Mullaghmore Head castle background, UK Bigwave',15),
('surfing','에콰도르 만타','Montañita','EC','Ecuador surf and party; left point consistent, backpacker scene, warm Pacific',10),
('surfing','콜롬비아 비야','El Valle','CO','Pacific Colombia remote; whale season watch surfing, Chocó jungle access',10),
('surfing','우루과이 카보','Cabo Polonio','UY','Off-grid Uruguay; sea lion colony, beach breaks, lighthouse backdrop, sand',10),
('surfing','모리타니아','Nouakchott','MR','West Africa unexplored; consistent swell, remote wild coast, French legacy',15),
('surfing','세네갈 다카르','N''Gor Island','SN','Dakar boat-access right; consistent year-round trade wind swell, local vibe',10),
('surfing','카보 베르데 살','Ponta Preta','CV','Cape Verde world-class; right-hander, strong trade winds, Pro event host',10),
('surfing','남아공 케이프타운','Elands Bay','ZA','West Coast right-hander; kelp forests, cold Atlantic, whales watching',10),
('surfing','나미비아 스켈레톤','Donkey Bay','NA','Namibia cold Atlantic; rare perfect conditions, skeleton coast backdrop,fog',15),
('surfing','코트디부아르','Assinie','CI','Ivory Coast beach break; growing surf scene, warm Gulf of Guinea water',10),
('surfing','가봉 리브레빌','Libreville Surf','GA','Gabon equatorial; warm water, boat access outer reefs, pristine jungle',15);

-- SKIING
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('skiing','샤모니','Chamonix','FR','Mont Blanc massif; extreme off-piste, Vallée Blanche glacier run 20km',15),
('skiing','샹파이','Val d''Isere','FR','French Alps; guaranteed snow, Les Arcs link, Tour de France summit',10),
('skiing','쿠르슈벨','Courchevel 1850','FR','Les Trois Vallees 3 Valleys; biggest linked ski area 600km, luxury chalets',10),
('skiing','체르마트','Zermatt','CH','Matterhorn view; year-round glacier, Klein Matterhorn 3,883m, car-free village',10),
('skiing','장크트 안톤','St Anton am Arlberg','AT','Austria powder capital; Arlberg region, famous après-ski, Rastkogel steep',10),
('skiing','이스크렌','Ischgl','AT','Austria party resort; Silvretta Arena 239km, Paznaun cuisine, season openers',10),
('skiing','기슈타트','Kitzbuehel','AT','Hahnenkamm Streif; steepest downhill race, historic alpine town, Streif run',10),
('skiing','메리벨','Meribel','FR','Heart of Three Valleys; family resort, Altiport ski-in, British favorite',10),
('skiing','베르비에','Verbier','CH','4 Vallees Swiss; steep off-piste, Freeride World Tour, chic village',10),
('skiing','마이어호펜','Mayrhofen','AT','Tyrol steep Harakiri; 78% gradient Austria steepest slope, snowboard culture',10),
('skiing','스위스 다보스','Davos Parsenn','CH','Switzerland largest ski area; Weissfluh 2,844m, World Economic Forum',10),
('skiing','코르티나','Cortina d''Ampezzo','IT','Dolomite queen; 2026 Winter Olympics host, pink Dolomiti backdrop, Tofane',10),
('skiing','마돈나 캄필리오','Madonna di Campiglio','IT','Italian Alps; 3 Tre Tre Cime, FIS Alpine race host, snowboard legends',10),
('skiing','아스펜','Aspen Snowmass','US','Colorado luxury; four mountains 336km, Aspen Mountain Highlands Ajax',15),
('skiing','베일','Vail','US','Colorado Blue Sky Basin; 7 legendary back bowls, gondola village, 5,300ac',10),
('skiing','파크 시티','Park City','US','Utah Greatest Snow on Earth; 2002 Olympics venue, Wasatch powder',10),
('skiing','스쿼밸리','Squaw Valley','US','Lake Tahoe 1960 Olympics; KT-22 expert chutes, Sierra snowpack, views',10),
('skiing','잭슨 홀','Jackson Hole','US','Wyoming most extreme; Corbet Couloir, 4,000ft vertical, 125in annual snow',15),
('skiing','스팀보트','Steamboat Springs','US','Champagne Powder Colorado; cowboy skiing, hot springs after ski, howelsen',10),
('skiing','웨스트레이크','Telluride','US','Box canyon village; no flat skiing all vertical, gondola free to town',10),
('skiing','선밸리','Sun Valley','US','First American ski resort 1936; Dollar Mountain, Bald Mountain, Hemingway',10),
('skiing','레이크 루이스','Lake Louise','CA','Canadian Rockies; turquoise frozen lake backdrop, 4 faces 145 runs',10),
('skiing','밴프','Banff Sunshine','CA','Rocky Mountain powder; 3 mountain area, Sunshine Village gondola ride',10),
('skiing','휘슬러','Whistler Blackcomb','CA','BC biggest 2010 Olympics; 200 runs 8171ac, PEAK 2 PEAK gondola link',10),
('skiing','빅 화이트','Big White','CA','BC interior dry powder; ski-in ski-out village, ghost trees rime ice',10),
('skiing','삿포로 니세코','Niseko','JP','Japan powder capital; Hokkaido light Japow, 4 resorts, onsen après',10),
('skiing','하쿠바','Hakuba','JP','Nagano 1998 Olympics; 10 resorts linked, Happo-One course, Japan Alps',10),
('skiing','마운트 쿡','New Zealand Skiing','NZ','Treble Cone and Cardrona; Southern Alps July-September, Canterbury Plains',10),
('skiing','아르투루','Las Leñas','AR','Argentina extreme; expert terrain south hemisphere, Mendoza access',10),
('skiing','칠레 안데스','Valle Nevado','CL','Andes August powder; near Santiago, linked with Portillo and La Parva',10),
('skiing','포르티요','Portillo','CL','Famous yellow hotel 1966 World Cup; Laguna del Inca, isolated Andes',15),
('skiing','안도라 그랑 발리라','Grandvalira','AD','Andorra largest ski area; 210km duty-free country, Pyrenees south face',10),
('skiing','스페인 시에라 네바다','Sierra Nevada Spain','ES','Southern Europe sunshine ski; near Granada Alhambra, Mediterranean view',10),
('skiing','불가리아 반스코','Bansko','BG','Eastern Europe budget best; Pirin Mountains UNESCO park, gondola village',10),
('skiing','아르메니아 차흐카자','Tsakhkadzor','AM','Caucasus ski resort; 4 lifts, easy Yerevan access, Ararat view days',10),
('skiing','그루지야 구다우리','Gudauri','GE','Georgian Caucasus; heli-skiing available, cross-country, Soviet-era base',10),
('skiing','카자흐스탄 침불락','Shymbulak','KZ','Almaty city ski resort; gondola 3 stations, Heavenly Valley, Soviet race slope',10),
('skiing','러시아 소치','Rosa Khutor','RU','2014 Winter Olympics; Krasnaya Polyana, sea-level mountain resort, warm',10),
('skiing','핀란드 레비','Levi','FI','Lapland ski resort; above Arctic circle, reindeer, northern lights après',10),
('skiing','스웨덴 오레','Are','SE','Scandinavia best; 2019 World Championships, village charm, midnight skiing',10),
('skiing','노르웨이 오슬로','Oslo Holmenkollen','NO','Famous ski jump 1892; 50km city ski trails, FIS World Cup, museum',10),
('skiing','레바논 마사야프','The Cedars','LB','Lebanon Cedar Reserve ski; ancient trees, Mediterranean 1hr, unique combo',10),
('skiing','이란 디잔','Dizin','IR','Tehran 2hrs; 3600m Iran best resort, February-April season, uncrowded',10),
('skiing','일본 묘코고겐','Myoko Kogen','JP','Niigata powder monster; Akakura Kanko area, onsen town, Tokyo 2hrs',10),
('skiing','한국 평창','Alpensia Yongpyong','KR','2018 Winter Olympics; Dragon Valley run, Super G race course, Seoul 2hrs',10),
('skiing','러시아 에루스','Elbrus','RU','Europe''s highest peak 5642m; cable car to 3850m, Kabardino skiing extreme',15),
('skiing','이탈리아 세스트리에레','Sestriere','IT','1988 World Cup; Fiat Agnelli purpose-built resort, Milky Way 400km link',10),
('skiing','오스트리아 론다','Lech','AT','Arlberg prestige Zürs; Weisse Ring loop, celebrity clientele, powder legend',10),
('skiing','오스트리아 쇠르겔','Söll Ski Welt','AT','Tyrol biggest linked; 279km Ski Welt Wilder Kaiser-Brixental, family',10),
('skiing','이탈리아 도로미티','Alta Badia','IT','Dolomite luxury; Sella Ronda 4-valley circuit, Gran Risa slalom stadium',10),
('skiing','스위스 안더마트','Andermatt-Sedrun','CH','Swiss traffic-free; new modern 4-valley development, Urner Alps,year-round',10),
('skiing','오스트리아 바드가슈타인','Bad Gastein','AT','Thermal spa ski; Gasteinertal, classic Victorian architecture, open veins',10),
('skiing','독일 바이에른','Garmisch-Partenkirchen','DE','1936 Olympics Germany; Zugspitze 2962m, Classic FIS DH race course',10),
('skiing','프랑스 라플라뉴','La Plagne','FR','Bobsled track ski resort; former Olympic site, 225km runs, glacier',10),
('skiing','알뱅 레 제트','Les Gets Morzine','FR','Portes du Soleil 650km; French-Swiss link, family resort, moto bike summer',10),
('skiing','스페인 피레네','Formigal','ES','Spanish Pyrenees largest; Aramón partnership, Valle de Tena, Madrid 5hrs',10),
('skiing','핀란드 루카','Ruka','FI','Arctic Circle ski; 760m vertical, reindeer farm nearby, northern lights',10),
('skiing','스위스 그린델발트','Grindelwald Jungfrau','CH','Top of Europe 3454m UNESCO; Eiger Nordwand view, ice palace glacier',10),
('skiing','캐나다 레베크','Mont-Tremblant','CA','Quebec French village resort; Eastern Canada best, 665ac, Laurentians',10),
('skiing','파타고니아 스키','Cerro Catedral','AR','Bariloche Argentina; Andes powder July-Sept, Swiss-style village, condors',10),
('skiing','몰도바 위스킷','Cimislia','MD','Small Balkan surprise; gentle pistes, novice terrain, affordable adventure',10),
('skiing','루마니아 포야나브라쇼브','Poiana Brasov','RO','Transylvania ski resort; Dracula castle day trip, pine forest runs',10),
('skiing','폴란드 자코파네','Zakopane','PL','High Tatras ski; Kasprowy Wierch cable car, traditional highland culture',10),
('skiing','슬로바키아 야스나','Jasna','SK','High Tatras Slovakia; 50km runs, World Cup DH venue, chamois mountain',10),
('skiing','슬로베니아 보힌','Kranjska Gora','SI','Julian Alps; Vitranc Cup WC GS/SL race, ski trails reach Lake Bohinj',10),
('skiing','리히텐슈타인 마루른','Malbun','LI','Worlds smallest ski area in principality; family resort, 23km runs, tiny',10),
('skiing','이스라엘 헤르몬','Mount Hermon','IL','Middle East only ski resort; Golan Heights, short season Dec-March, Syrian view',10),
('skiing','모로코 우카이메든','Oukaimeden','MA','Africa highest ski resort 3258m; Atlas Mountains, mule ski lift, donkey',10),
('skiing','레소토 아프로스키','Afriski','LS','Southern Africa only; Kingdom in the Sky, Maluti Mountains, August peak',10),
('skiing','키르기스스탄 카라콜','Karakol','KG','Central Asia powder; Tian Shan, affordable heli-ski, Silk Road history',10),
('skiing','타지키스탄 팡','Fann Mountains','TJ','Wild Tajikistan backcountry; untouched powder, yurt camps, adventure',15),
('skiing','몽골 재스퍼','Sky Resort Ulaanbaatar','MN','Urban ski Ulaanbaatar; short but authentic, steppes views, camel nearby',10),
('skiing','나미비아 빌더르호크','Drakensberg Ski','ZA','Tiffindell South Africa; Africa East Cape only snow, ephemeral skiing',10),
('skiing','북한 마스크단','Masikryong','KP','North Korea ski resort; Pyongyang 2hrs, modern lifts, few foreign access',15),
('skiing','아프가니스탄 바미안','Bamiyan','AF','Silk Road ski; Hindu Kush, Band-e-Amir lakes backdrop, ski competition',20),
('skiing','방글라데시','Bhutan Skiing','BT','GNH kingdom helicopter ski; Himalayan wilderness, no lift, pure adventure',15),
('skiing','조지아 바크메티','Bakhmaro','GE','Lesser Caucasus; summer flower meadow skiing, Soviet era, untouched',10),
('skiing','파키스탄 나란','Naltar','PK','Pakistan PAF ski club; 3,000m altitude Gilgit, Rainbow lakes nearby',15),
('skiing','이탈리아 아오스타','Cervinia Breuil','IT','Matterhorn Italian side; links Zermatt border, 360km combined area',10),
('skiing','프랑스 아보리아','Avoriaz','FR','Car-free resort Morzine; futuristic buildings, horse-drawn sleigh, kids area',10),
('skiing','스위스 아로사','Arosa Lenzerheide','CH','Family Swiss; heated outdoor pool ski, ibex and chamois sightings',10),
('skiing','오스트리아 힌터룩스','Hintertux Glacier','AT','Only year-round Austrian glacier; 365-day skiing, Tux valley hot spring',10),
('skiing','캐나다 레이크루이스','Marmot Basin','CA','Jasper Alberta; Rocky Mountain remote resort, wolf elk sighting ski',10),
('skiing','미국 매모스','Mammoth Mountain','US','California volcanic; 3500m summit, 3500 acres, season Nov-July sometimes',10),
('skiing','뉴질랜드 퀸스타운','The Remarkables','NZ','Queenstown backdrop; jagged peaks, Auckland-accessible South Island peak',10);

-- SCUBA
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('scuba','그레이트 블루 홀','Great Blue Hole','BZ','UNESCO giant sinkhole 300m wide; bull sharks, stalactites at 40m depth',20),
('scuba','투바타하 리프','Tubbataha Reef','PH','UNESCO Philippine UNESCO; remote atoll, 600 fish species, manta rays',20),
('scuba','코모도','Komodo Dive Sites','ID','Raja Ampat neighbour; manta point, Pink Beach, hammerhead channel drift',15),
('scuba','라자 암팟','Raja Ampat','ID','Coral Triangle heart; 75% worlds coral species, pygmy seahorses, WW2 wreck',20),
('scuba','팔라우 블루 코너','Palau Blue Corner','PW','Drift dive manta wall; hook into reef, grey reef sharks, pelagic parade',20),
('scuba','레드 씨 코드','Red Sea Ras Mohammed','EG','Shark and Yolanda reef; wall dive 60m, glassfish tunnels, jackfish tornado',10),
('scuba','마나타 나이트','Kona Manta Ray Night Dive','US','Hawaii manta ballet; up to 20 mantas feeding on plankton lights, magical',15),
('scuba','시폴라이스 세네갈','Aliwal Shoal','ZA','South Africa shark dive; ragged tooth sharks, oceanic blacktip, October',15),
('scuba','랑기로아','Rangiroa Tiputa Pass','PF','French Polynesia atoll pass; dolphin school, grey reef shark parade, drift',10),
('scuba','마야 리마','Cenotes Yucatan','MX','Underwater cave system; crystal clear freshwater stalactite halocline',15),
('scuba','밀피트','Milne Bay','PG','Papua New Guinea critter; nudibranch heaven, sea horse density world record',20),
('scuba','야프','Yap Manta Ray','FM','Micronesia manta sanctuary; seasonal resident mantas, grey reef sharks',15),
('scuba','트루크 라군','Truk Lagoon','FM','WW2 graveyard; 50+ Japanese wrecks, Zero planes, tanks, coral encrusted',20),
('scuba','코수멜','Cozumel','MX','Caribbean drift dives; Palancar reef wall, Santa Rosa Canyon, turtles',10),
('scuba','하머헤드 샤크','Cocos Island','CR','World class pelagic; hammerhead schools 400, whale sharks, manta rays',20),
('scuba','닝갈루 리프','Ningaloo Reef','AU','WA reef whale shark snorkel; manta cleaning stations, turtle nesting',15),
('scuba','마보울 리프','Mayotte','YT','French territory Indian Ocean; hammerhead sharks, whale sharks, dugongs',15),
('scuba','배타네아 코스타리카','Bat Islands','CR','Bull shark dive Guanacaste; strong current, 50+ bulls, July-December season',15),
('scuba','오스트리아 레이크','Achensee','AT','Alpine freshwater lake dive; 133m visibility, trout, pike, unique inland',10),
('scuba','사이판','Blue Hole Saipan','MP','Micronesia vertical cave; WWII Japanese wreck Zero fighter plane 30m',15),
('scuba','올림픽 레이크','Lake Baikal','RU','Freshwater world unique; Baikal seal nerpa, 1640m deep, winter ice dive',15),
('scuba','플로리다 스프링스','Florida Springs','US','Crystal River cave springs; 72F year-round, manatee winter snorkel,clarity',10),
('scuba','카나리아','Lanzarote MUSA','ES','Underwater museum; 300 sculptures colonized by marine life, Canary Islands',10),
('scuba','솔로몬 아이슬랜드','Solomon Islands','SB','WWII wrecks pristine reef; Tulagi harbor, blue holes, undiscovered dives',15),
('scuba','수비크 베이','Subic Bay Wrecks','PH','WWII US Navy wrecks; El Capitan LSM-169, USS New York 24m, octopus',10),
('scuba','레드 씨 수단','Sudan Red Sea','SD','Deep south Red Sea; Brother Islands hammerheads, Sha ab Rumi Cousteau',20),
('scuba','소말리아 해안','Djibouti Whale Shark','DJ','Bay of Tadjoura aggregation; November-January, whale shark school dive',15),
('scuba','모리셔스','Mauritius','MU','Underwater waterfall illusion; sand silt 300m drop, whale shark season',10),
('scuba','아이슬란드 실프라','Silfra Fissure','IS','Between tectonic plates; glacial meltwater clarity 100m, 2C temperature',15),
('scuba','타이완 소수','Green Island','TW','Taiwan best diving; hot spring underwater, 230 coral species, mantas',10),
('scuba','필리핀 모알보알','Moalboal','PH','Sardine tornado; million sardines school instant, turtle reef, thresher shark',10),
('scuba','마다가스카르','Nosy Be','MG','Madagascar French; whale shark aggregation October, pristine reefs',15),
('scuba','탄자니아 마피아','Mafia Island','TZ','East Africa whale shark; pristine Chole Bay marine park, few visitors',15),
('scuba','세이셸 알다브라','Aldabra','SC','UNESCO atoll remote; nurse shark, hawksbill turtles, pristine reef system',20),
('scuba','에콰도르 갈라파고스','Galapagos Scuba','EC','Darwin and Wolf Islands; whale sharks, hammerheads, marine iguanas swim',20),
('scuba','노퍽 아일랜드','Norfolk Island','NF','Remote Pacific; HMAS Sirius wreck 1790, big fish aggregations, clarity',15),
('scuba','바누아투','Million Dollar Point','VU','WW2 US equipment dump; jeeps, bulldozers, cranes at 30m, history dive',15),
('scuba','통가','Tonga Whale Dive','TO','Humpback mother calf; swim with largest animals, August-October season',20),
('scuba','사이프러스','Cyprus Zenobia','CY','Best Mediterranean wreck; 178m Swedish ferry, 1980 sank on maiden voyage',10),
('scuba','터키 보드룸','Bodrum Castle','TR','Aegean ancient wrecks; Byzantine 7th century, Castle St Peter museum topside',10),
('scuba','그리스 에게해','Santorini Underwater','GR','Caldera dive; volcanic fumaroles, Roman amphora, Mediterranean diversity',10),
('scuba','이집트 다합','Dahab Blue Hole','EG','Sinai deep sinkhole; freedivers, 90m arch temptation, Red Sea classic',15),
('scuba','오만','Muscat Daymaniyat','OM','Oman marine reserve; green turtle nesting, spinner dolphin, dugong sighting',10),
('scuba','태국 심란','Similan Islands','TH','Andaman Sea granite boulders; seasonal November-April only, leopard shark',10),
('scuba','미얀마 메르귀','Mergui Archipelago','MM','Burma 800 islands remote; Andaman Sea pristine, live-aboard only access',20),
('scuba','인도 안다만','Andaman Islands','IN','India Bay of Bengal; Barracuda City, Pilot Whale, pristine reef systems',15),
('scuba','브라질 페르난도','Fernando de Noronha','BR','Atlantic Marine Park; spinner dolphins, lemon sharks, crystal Atlantic water',15),
('scuba','멕시코 바하','Baja California','MX','Sea of Cortez; Cabo Pulmo marine park, mobula rays, sea lions playful',10),
('scuba','캐나다 브리티시컬럼비아','Campbell River','CA','Pacific Northwest cold; giant Pacific octopus, wolf eels, nudibranchs galore',10),
('scuba','노르웨이 피오르드 다이브','Norway Fjord','NO','Cold water visibility; Atlantic halibut, wolf fish, plumose anemones walls',10),
('scuba','영국 스코틀랜드','Scapa Flow','GB','WW1 German naval fleet; 7 warships scuttled 1919, best wreck diving UK',10),
('scuba','아이슬란드 수중','Kleifarvatn','IS','Volcanic crater lake; tectonic active, visibility 30m+, Iceland geothermal',10),
('scuba','스웨덴 오레순','Kosterfjorden','SE','Sweden deepest point; cold clear water, sea fan, nudibranch September-October',10),
('scuba','포르투갈 아조르스','Azores','PT','Atlantic mid-ocean; blue shark cage, sperm whale snorkel, 6 shark species',15),
('scuba','스페인 메노르카','Menorca','ES','Mediterranean sea caves; Byzantine wreck San Nicolau, posidonia meadows',10),
('scuba','이탈리아 폰자','Ponza','IT','Tyrrhenian Sea; Roman fish tanks, amphora fields, Loggerhead turtle nesting',10),
('scuba','프랑스 마르세유','Marseille Calanques','FR','Calanques marine park; hermit crabs, fan corals, octopus, WWII landing craft',10),
('scuba','크로아티아 아드리아','Hvar Croatia','HR','Adriatic diving; blue cave, Vis island WWII wrecks, clear blue water',10),
('scuba','알바니아 사란다','Albanian Riviera','AL','Unexplored Mediterranean; Ottoman-era anchor fields, fan corals, clear water',10),
('scuba','레바논 베이루트','Mediterranean Lebanon','LB','Tyre marine reserve; Byzantine columns 10m deep, Phoenician anchors',10),
('scuba','이스라엘 에일라트','Eilat','IL','Red Sea resort; Moses Rock undercut, Japanese Gardens reef, all year warm',10),
('scuba','요르단 아카바','Aqaba','JO','Red Sea; Cedar Pride wreck, tank wreck 10m, rainbow reef wall dives',10),
('scuba','사우디아라비아 홍해','NEOM Red Sea','SA','New Saudi dive development; pristine Red Sea untouched, reef opening',15),
('scuba','예멘 소코트라','Socotra Dive','YE','Remote Arabian Sea; endemic species, pristine reef, dragon blood tree island',20),
('scuba','에리트레아 마사와','Eritrean Red Sea','ER','Italian colonial wrecks; WW2 ships 5-30m, corals reclaimed, few divers',15),
('scuba','지부티 자나비기','Arta Beach','DJ','East Africa Gulf of Aden; whale shark aggregations, manta ray cleaning',10),
('scuba','케냐 와타무','Watamu','KE','East Africa marine park; coral gardens, whale shark sighting season',10),
('scuba','탄자니아 잔지바르','Zanzibar','TZ','East Africa spice island; Mnemba atoll, manta ray, turtle cleaning station',10),
('scuba','남아공 고든스베이','Gordon''s Bay','ZA','Cape Point cold water; 7-gill sharks, octopus, cold kelp forest ecosystem',10),
('scuba','모잠비크 포도인','Tofo Beach','MZ','East Africa whale shark; Manta Reef, dugong grassbed, 30m wall dives',15),
('scuba','마다가스카르 서해안','Andavadoaka','MG','Remote southwest; pristine reef, octopus fishery zone, whale shark June',20),
('scuba','가봉 로앙고','Loango National Park','GA','Hippos in the sea; humpback whale, mantas, pristine offshore reefs',20),
('scuba','상투메 프린시페','Sao Tome Dive','ST','Gulf of Guinea equatorial; hard coral offshore, whale shark, undiscovered',15),
('scuba','카나리아 엘 에로','El Hierro Marine Reserve','ES','Europe first biosphere reserve dive; angel sharks, barracuda, lava tubes',15),
('scuba','버뮤다 삼각지대','Bermuda','BM','Atlantic Bermuda Triangle; 300+ wrecks, HMHS Britannic style, moray eel',10),
('scuba','케이맨 스팅레이','Stingray City','KY','Cayman Islands; shallow sand bar, hundreds of tame stingrays, snorkel too',10),
('scuba','온두라스 로아탄','Roatan','HN','Bay Islands second barrier reef; whale shark, corals, affordable liveaboard',10),
('scuba','벨리즈','Belize Barrier Reef','BZ','Second largest barrier reef UNESCO; nurse sharks, manatees, 500 fish species',10),
('scuba','코스타리카 코코스','Cocos Island','CR','Pelagic paradise; 300 hammerheads, whale sharks, mobula rays UNESCO',20),
('scuba','에콰도르 갈라파고스 D','Darwin Arch','EC','Galápagos legendary dive; mass whale shark aggregations 40+, school tuna',20),
('scuba','페루 파라카스','Paracas Islas Ballesta','PE','Galapagos poor man; sea lions, Humboldt penguins, guano birds, candelabra',10),
('scuba','아르헨티나 마르','Mar del Plata Wrecks','AR','Atlantic Argentine; coastal wrecks, sea lions, kelp forest cold-water dives',10),
('scuba','칠레 이스터','Easter Island Dive','CL','Remote Pacific clarity; Moai underwater sculpture, endemic Nazca boobies',15),
('scuba','피지 제도','Pacific Harbor Fiji','FJ','Bull shark dive; 80+ sharks sit for bait, banana boat channel drift',15),
('scuba','미국령 버진아일랜드','USVI Wreck Diving','VI','Caribbean RMS Rhone 1867; stern 24m bow 8m, 120 years coral growth',10),
('scuba','미국 플로리다 키스','Florida Keys','US','Continental US reef; John Pennekamp Coral Reef, Christ abyss statue 25m',10),
('scuba','피지 나모카이','Namoca Liveaboard','FJ','Fiji offshore atolls; soft coral capital, shark reef, rainbow reef bligh water',10),
('scuba','파나마 코이바','Coiba','PA','Pacific Panama UNESCO; whale sharks, humpbacks, undiscovered endemic',15);
