-- ================================================================
-- schema-merged-v14-to-v18.sql
-- v14 ~ v18 전체를 한 번에 실행 (복사 후 Supabase SQL Editor에서 Run)
-- ================================================================
-- ※ schema-v13.sql (100 Restaurants 미슐렝 교체) 은 파일이 비어 있어
--   제외했습니다. v13 백업이 있으면 별도로 먼저 실행하세요.
-- ================================================================
-- 실행 순서: v14 → v15 → v16 → v17 → v18
-- ================================================================


-- ###################################################################
-- # schema-v14.sql — 100 Animals: 9개 추가 (91 → 100)
-- ###################################################################

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES

('animals','침팬지','Chimpanzee','TZ',
 'Gombe Stream Jane Goodall legacy; tool use, hunting parties, 98.7% human DNA, politics',20),
('animals','백상아리','Great White Shark','ZA',
 'Gansbaai cage diving; 6m apex predator, breaches 4m, electrical sense ampullae',15),
('animals','아프리카 물소','Cape Buffalo','TZ',
 'Serengeti Big Five; 900kg unpredictable, kills more hunters than any African animal',10),
('animals','세발가락 나무늘보','Three-toed Sloth','CR',
 'Costa Rica cloud forest; sleeps 20hrs, algae-green fur camouflage, upside-down life',10),
('animals','대서양 퍼핀','Atlantic Puffin','IS',
 'Westman Islands Iceland; 60 million world population, dives 60m, beak 10 fish at once',10),
('animals','페넥 여우','Fennec Fox','TN',
 'Sahara sand dunes; worlds smallest fox 1.5kg, ears 15cm radiate heat, night hunter',10),
('animals','아무르 호랑이','Amur Tiger','RU',
 'Far East Russia Ussuri; largest cat 300kg, 500 remaining, -40C Siberian survival',20),
('animals','귀상어','Scalloped Hammerhead Shark','EC',
 'Galápagos Darwin Island schools; 360° vision, electromagnetic prey detection, schooling hundreds',15),
('animals','황금들창코원숭이','Golden Snub-nosed Monkey','CN',
 'Qinling-Sichuan forests; blue-faced, golden-orange fur, -20C mountain survival, China icon',15);


-- ###################################################################
-- # schema-v15.sql — 100 Fishing Spots 전면 교체
-- ###################################################################

DELETE FROM public.challenge_certifications
  WHERE challenge_id IN (
    SELECT id FROM public.challenges WHERE category = 'fishing'
  );
DELETE FROM public.challenges WHERE category = 'fishing';

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES

('fishing','케나이 강 알래스카','Kenai River','US',
 'World record king salmon 44kg; July combat fishing elbow-to-elbow, Soldotna Alaska',20),
('fishing','스케나 강 스틸헤드','Skeena River','CA',
 'Holy grail of fly fishing; wild steelhead to 15kg, Terrace BC wilderness float trip',20),
('fishing','그랜드 캐스카페디아 강','Grand Cascapedia River','CA',
 'Atlantic salmon on private beats; Quebec legend 40lb+ fish, guided canoe traditional',20),
('fishing','플로리다 키스','Florida Keys','US',
 'Grand Slam: tarpon, permit, bonefish same day; flats fly fishing Mecca, year-round',20),
('fishing','코나 하와이','Kona, Hawaii','US',
 'Pacific blue marlin capital; Kona Coast 1000lb marlin, International Billfish Tournament',20),
('fishing','앤드로스 아일랜드 바하마','Andros Island, Bahamas','BS',
 'Bonefish Mecca; shallow sand flats tailing fish, 100-mile bonefishing paradise Nassau',20),
('fishing','하르디네스 데 라 레이나 쿠바','Jardines de la Reina, Cuba','CU',
 'Grand Slam paradise; pristine reef, permit tarpon bonefish in one day, live-aboard only',20),
('fishing','피나스 베이 파나마','Pinas Bay, Panama','PA',
 'World record black marlin & Pacific sailfish; Tropic Star Lodge, most famous Panama',20),
('fishing','이스타파 과테말라','Iztapa, Guatemala','GT',
 'World record Pacific sailfish releases; 50+ fish/day season, Sailfish Oasis Pacific',20),
('fishing','리오 그란데 티에라 델 푸에고','Rio Grande, Tierra del Fuego','AR',
 'World record sea-run brown trout 36kg; wind-swept Patagonia rivers, January-March',20),
('fishing','팔레나 강 파타고니아','Palena River, Chile','CL',
 'Wild rainbow trout in remote Patagonia; helicopter access Aysen wilderness Chile',20),
('fishing','시나루코 강 베네수엘라','Cinaruco River, Venezuela','VE',
 'Payara vampire fish 4-inch fangs; Apure Llanos sabre-tooth predator 25lb+',20),
('fishing','이니리다 강 콜롬비아','Inirida River, Colombia','CO',
 'World record peacock bass habitat; Guainia river system remote Amazon Colombia',20),
('fishing','알타 강 노르웨이','Alta River, Norway','NO',
 'World greatest Atlantic salmon river; Finnmark Norway king of rivers 50lb+ salmon',20),
('fishing','카나리아 제도 참치','Canary Islands, Spain','ES',
 '500kg Atlantic bluefin tuna migration; giant bluefin January-March, El Hierro waters',20),
('fishing','아조레스 포르투갈','Azores, Portugal','PT',
 'Bluefin tuna & blue marlin; mid-Atlantic volcanic islands, world class big game July',20),
('fishing','콜라 반도 러시아','Kola Peninsula, Russia','RU',
 'Atlantic salmon paradise; Varzuga Yokanga rivers, prolific salmon runs June-August',20),
('fishing','포노이 강 러시아','Ponoi River, Russia','RU',
 'Most prolific Atlantic salmon per rod; remote Kola wilderness, helicopter access lodge',20),
('fishing','콩고 강 민주공화국','Congo River, DRC','CD',
 'Goliath tigerfish 50kg; prehistoric predator razor teeth, Congo River rapids Malebo Pool',20),
('fishing','코스몰레도 환초 세이셸','Cosmoledo Atoll, Seychelles','SC',
 'Giant trevally on fly; 40kg GT hunting shallow flats, pristine Indian Ocean atoll',20),
('fishing','캄차카 반도 러시아','Kamchatka Peninsula, Russia','RU',
 'Pacific salmon paradise; 6 species untouched rivers, helicopter lodge, wild Kamchatka',20),
('fishing','얄룽창포 강 티베트','Yarlung Tsangpo, Tibet','CN',
 'World highest river fishing 4,000m; snow trout Himalayan mahseer, roof of the world',20),
('fishing','에그 우르 강 몽골','Eg-Uur River, Mongolia','MN',
 'World largest salmonid taimen 60kg+; horseback access Mongolia wilderness, catch-release',20),
('fishing','치앙콩 태국','Chiang Khong, Thailand','TH',
 'Mekong giant catfish 293kg world record; critically endangered, northern Thailand Mekong',20),
('fishing','마암베라모 강 파푸아','Mamberamo River, Papua','ID',
 'Black bass in untouched Papua rivers; fly-in-only remote Indonesia wilderness fishing',20),
('fishing','매디슨 강 몬태나','Madison River, Montana','US',
 'Blue-ribbon trout stream; 3,000 trout/mile, Yellowstone gateway, nymph dry-fly classic',15),
('fishing','빅혼 강 몬태나','Bighorn River, Montana','US',
 'Trophy tailwater trout; Yellowtail Dam releases, 20-inch brown rainbow, Crow Agency',15),
('fishing','데슈츠 강 오리건','Deschutes River, Oregon','US',
 'Premier steelhead and trout; summer steelhead August-November, Maupin high desert canyon',15),
('fishing','그린 강 와이오밍','Green River, Wyoming','US',
 'Blue-ribbon tailwater; trophy rainbow brown below Flaming Gorge Dam, Seedskadee guide',15),
('fishing','샌 후안 강 뉴멕시코','San Juan River, New Mexico','US',
 'Trophy tailwater trout; Navajo Dam cold release, 20-inch plus rainbows Aztec NM',15),
('fishing','나크넥 강 알래스카','Naknek River, Alaska','US',
 'Sockeye salmon king salmon; Bristol Bay Alaska world largest sockeye run July',15),
('fishing','스네이크 강 아이다호','Snake River, Idaho','US',
 'Steelhead and chinook salmon; wild Snake steelhead September-January, Hell''s Canyon',15),
('fishing','보우 강 앨버타','Bow River, Alberta','CA',
 'World class brown trout; Calgary city river, drift boat brown rainbow, October prime',15),
('fishing','미라미치 강 뉴브런즈윅','Miramichi River, New Brunswick','CA',
 'Atlantic salmon heartland; New Brunswick Canada, crown jewel salmon, summer fall runs',15),
('fishing','니피곤 강 온타리오','Nipigon River, Ontario','CA',
 'World record brook trout 6.57lb 1915; remote fly-in Lake Nipigon system Ontario',15),
('fishing','보카 그란데 패스 플로리다','Boca Grande Pass, Florida','US',
 'Tarpon capital; June tarpon 200lb schooling pass, world famous snook cobia grouper',15),
('fishing','케이프 코드 매사추세츠','Cape Cod, Massachusetts','US',
 'Striped bass surfcasting classic; Montauk Point autumn blitz, bluefish, fall migration',15),
('fishing','에버글레이즈 플로리다','Everglades, Florida','US',
 'Snook and redfish backcountry; Ten Thousand Islands kayak, Florida panhandle flats',15),
('fishing','카보 산 루카스 멕시코','Cabo San Lucas, Mexico','MX',
 'Striped marlin and dorado corridor; November-April billfish, Pisces Fleet Baja California',15),
('fishing','코수멜 멕시코','Cozumel, Mexico','MX',
 'Atlantic blue marlin; Caribbean deep blue Cozumel, 600-800lb marlin July-September',15),
('fishing','푸에르토 바야르타 멕시코','Puerto Vallarta, Mexico','MX',
 'Pacific sailfish season Nov-Jan; striped marlin dorado, El Morro Bank Mexico Pacific',15),
('fishing','코리엔테스 아르헨티나','Corrientes Province, Argentina','AR',
 'Golden dorado acrobatic game fish; Rio Pirapo Corrientes, electric gold in fast water',15),
('fishing','아마존 강 브라질','Amazon River, Brazil','BR',
 'Peacock bass and pirarucu; jungle lodge fly fishing, world''s most prized freshwater',15),
('fishing','판타날 브라질','Pantanal, Brazil','BR',
 'Golden dorado piranha tucunare; world largest wetland fishing, Corumba accessibility',15),
('fishing','과나카스테 코스타리카','Guanacaste, Costa Rica','CR',
 'Roosterfish unique Pacific game fish; dramatic dorsal fin Nosara Samara Peninsula',15),
('fishing','마드레 데 디오스 강 페루','Madre de Dios River, Peru','PE',
 'Peacock bass remote jungle; Inkaterra lodge Amazon Peru, record tucunaré on fly',15),
('fishing','파라나 강 아르헨티나','Parana River, Argentina','AR',
 'Golden dorado and surubi catfish; second longest SA river, Entre Rios province',15),
('fishing','로포텐 제도 노르웨이','Lofoten Islands, Norway','NO',
 'Arctic cod and coalfish; traditional wooden boats Henningsvaer Svolvaer winter drama',15),
('fishing','엘리다르 강 아이슬란드','Ellidaár River, Iceland','IS',
 'Wild Atlantic salmon through capital; Reykjavik urban river salmon, June-September',15),
('fishing','퉁나 강 아이슬란드','Tungnaá River, Iceland','IS',
 'Remote Iceland highland salmon; Tungnafjot system August prime run, wilderness camp',15),
('fishing','테이 강 스코틀랜드','River Tay, Scotland','GB',
 'Scotland premier salmon river; Kenmore Aberfeldy beats, spring salmon, historical record',15),
('fishing','스페이 강 스코틀랜드','River Spey, Scotland','GB',
 'Spey casting technique origin; Grantown-on-Spey Ballindalloch, whisky country salmon',15),
('fishing','트위드 강 스코틀랜드','River Tweed, Scotland','GB',
 'Atlantic salmon border river; Kelso Berwick beats, Scotland-England, autumn powerhouse',15),
('fishing','에브로 강 스페인','Ebro River, Spain','ES',
 'European wels catfish 100kg+; Mequinenza reservoir Spain, monster catfish capital',15),
('fishing','라마간가 강 인도','Ramganga River, India','IN',
 'Golden mahseer 50kg; Jim Corbett NP Uttarakhand, sacred fish India''s greatest game',15),
('fishing','카베리 강 인도','Cauvery River, India','IN',
 'Mahseer fly fishing; humpback mahseer Karnataka Tamil Nadu, Galibore camp classic',15),
('fishing','홋카이도 일본','Hokkaido, Japan','JP',
 'Itou (Japanese taimen) 1m+; Shiretoko UNESCO rivers, brown trout wild hokkaido',15),
('fishing','사라왁 보르네오 말레이시아','Sarawak, Borneo, Malaysia','MY',
 'Toman giant snakehead; Batang Ai jungle lakes, belida, sebarau Borneo Malaysia',15),
('fishing','잠베지 강 짐바브웨','Zambezi River, Zimbabwe','ZW',
 'Tigerfish below Victoria Falls; rapids and pools Zimbabwe Zambia border, September',15),
('fishing','탕가니카 호수 탄자니아','Lake Tanganyika, Tanzania','TZ',
 'World''s longest deepest lake; nile perch tigerfish, Mahale Mountains Kigoma Tanzania',15),
('fishing','바자루토 제도 모잠비크','Bazaruto Archipelago, Mozambique','MZ',
 'Sailfish, blue marlin; Indian Ocean offshore Inhambane, giant trevally reef fishing',15),
('fishing','와타무 케냐','Watamu, Kenya','KE',
 'Billfish capital Kenya coast; Watamu Marine Park March-April striped marlin, grouper',15),
('fishing','잔지바르 해협 탄자니아','Zanzibar Channel, Tanzania','TZ',
 'Blue marlin, yellowfin tuna; Indo-Pacific meeting point, Pemba Island offshore trophy',15),
('fishing','말린디 케냐','Malindi, Kenya','KE',
 'Striped marlin and sailfish; Malindi Marine Reserve, March-April prime season Kenya',15),
('fishing','바이칼 호수 러시아','Lake Baikal, Russia','RU',
 'Baikal omul ice fishing; world''s deepest lake, taimen giant grayling, Listvyanka winter',15),
('fishing','아무르 강 러시아','Amur River, Russia','RU',
 'Itou salmon 100kg+ and taimen; Russian-Chinese border Amur system, extreme remote',15),
('fishing','홋카이도 시레토코','Shiretoko Peninsula, Japan','JP',
 'Wild itou salmon UNESCO wilderness; Shiretoko rivers permit fishing, bear-watching',15),
('fishing','야스와 제도 피지','Yasawa Islands, Fiji','FJ',
 'Giant trevally popping; Fiji remote islands, coral popping bluewater, reef variety',15),
('fishing','팔라우 미크로네시아','Palau, Micronesia','PW',
 'Dogtooth tuna jigging and GT; Ngemelis wall and blue corners, Pacific bluewater',15),
('fishing','모리셔스','Mauritius','MU',
 'Blue marlin and yellowfin tuna; Le Morne peninsula Indian Ocean IGFA records',15),
('fishing','몰디브','Maldives','MV',
 'Giant trevally and wahoo; pristine atolls, popping jigging, bonefish flats Maldives',15),
('fishing','무산담 피요르드 오만','Musandam Fjords, Oman','OM',
 'Dogtooth tuna and GT jigging; Arabian Sea Musandam peninsula, grouper amberjack',15),
('fishing','솔로몬 제도','Solomon Islands','SB',
 'Remote Melanesian GT popping; Munda Ghizo Marovo lagoon, untouched Pacific islands',15),
('fishing','파푸아 뉴기니','Papua New Guinea','PG',
 'Black bass and giant trevally; Cape Vogel Madang, remote PNG pristine reefs',15),
('fishing','레이크 에리','Lake Erie, USA','US',
 'Walleye capital of the world; Great Lakes trophy walleye, perch smallmouth bass Ohio',10),
('fishing','바운더리 워터스 미네소타','Boundary Waters, Minnesota','US',
 'Wilderness canoe fishing; northwoods walleye muskie northern pike, BWCA permit Canada',10),
('fishing','체사피크 만 메릴랜드','Chesapeake Bay, Maryland','US',
 'Striped bass blue crab; Chesapeake Bay largest estuary USA, rockfish surfcasting classic',10),
('fishing','루이지애나 바유','Louisiana Bayou, USA','US',
 'Red drum and speckled trout; Cajun fishing bayou marshes, Atchafalaya Basin Louisiana',10),
('fishing','보카스 델 토로 파나마','Bocas del Toro, Panama','PA',
 'Atlantic tarpon in Caribbean lagoons; snook, jack, Bocas del Toro archipelago Panama',10),
('fishing','케이프 버드 아일랜드','Cape Verde Islands','CV',
 'Atlantic blue marlin migration; mid-ocean archipelago November-February, wahoo dorado',10),
('fishing','모이 강 아일랜드','River Moy, Ireland','IE',
 'Highest rod-catch river Ireland; Ballina County Mayo, prolific salmon July-September',10),
('fishing','코네마라 아일랜드','Connemara, Ireland','IE',
 'Wild brown trout on limestone loughs; Galway Connemara fly fishing, mayfly season May',10),
('fishing','이나리 호수 핀란드','Lake Inari, Finland','FI',
 'Arctic grayling and perch; Lapland Inari August-September, ice fishing winter brown',10),
('fishing','발틱 해 스웨덴','Lake Vänern, Sweden','SE',
 'Swedish record sea trout and pike; world''s third largest freshwater lake, Gothenburg',10),
('fishing','폴란드 부그 강','Bug River, Poland','PL',
 'Trophy pike in lowland rivers; Bug River Polish-Belarusian border, pike perch bream',10),
('fishing','이탈리아 포 강','Po River, Italy','IT',
 'Monster wels catfish; Po Valley Northern Italy Cremona Mantua, 250kg catfish record',10),
('fishing','볼가 강 삼각주 러시아','Volga River Delta, Russia','RU',
 'Giant zander and asp; Astrakhan Caspian mouth, beluga sturgeon once greatest fishery',10),
('fishing','케이프 포인트 남아프리카','Cape Point, South Africa','ZA',
 'Yellowfin tuna and snoek; Cape Point False Bay, cold Benguela Current upwelling rich',10),
('fishing','빅토리아 호수 케냐','Lake Victoria, Kenya','KE',
 'Nile perch 100kg+; Africa''s largest lake, Kisumu Kenya, endemic cichlids crisis habitat',10),
('fishing','말라위 호수','Lake Malawi, Malawi','MW',
 'Tiger fish and endemic cichlids; Nkhata Bay Malawi, crystal clear freshwater lake Africa',10),
('fishing','니아사 보호구역 모잠비크','Niassa Reserve, Mozambique','MZ',
 'Vundu catfish and tiger fish; Lugenda River remote wilderness, fly camp only access',10),
('fishing','왈비스 베이 나미비아','Walvis Bay, Namibia','NA',
 'Offshore tuna and kabeljou; cold Benguela upwelling Namibia, Skeleton Coast richness',10),
('fishing','닝갈루 리프 호주','Ningaloo Reef, Australia','AU',
 'Sailfish and queenfish; World Heritage coral reef Western Australia, April-June peak',10),
('fishing','안다만 제도 인도','Andaman Islands, India','IN',
 'Offshore big game fishing; dogtooth tuna GT, remote Bay of Bengal India, Port Blair',10),
('fishing','케랄라 뒤뜰','Kerala Backwaters, India','IN',
 'Traditional cast-net fishing; Vembanad Lake houseboat, Alappuzha Kerala backwater life',10),
('fishing','메콩 삼각주 베트남','Mekong Delta, Vietnam','VN',
 'River monster fishing; snakehead catfish barb, Can Tho floating market river culture',10),
('fishing','비와 호수 일본','Lake Biwa, Japan','JP',
 'Japan''s largest lake; largemouth bass record, black bass tournament Shiga Prefecture',10),
('fishing','통가','Tonga, South Pacific','TO',
 'Yellowfin tuna and wahoo; Ha''apai remote bluewater, deep drop bottom fishing Pacific',10),
('fishing','크리스마스 아일랜드 키리바시','Christmas Island, Kiribati','KI',
 'Bonefish and giant trevally paradise; Indo-Pacific remote flats, 10kg GT on fly rod',10),
('fishing','뉴칼레도니아','New Caledonia','NC',
 'Coral trout and GT; Pacific largest lagoon UNESCO, Noumea offshore New Caledonia',10);


-- ###################################################################
-- # schema-v16.sql — 100 Golf Courses 전면 교체
-- ###################################################################

DELETE FROM public.challenge_certifications
  WHERE challenge_id IN (
    SELECT id FROM public.challenges WHERE category = 'golf'
  );
DELETE FROM public.challenges WHERE category = 'golf';

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES

('golf','오거스타 내셔널','Augusta National Golf Club','US',
 'Masters Tournament since 1934; Amen Corner 11-12-13, Bobby Jones design, invite-only',20),
('golf','오크몬트 컨트리 클럽','Oakmont Country Club','US',
 'US Open record 9 times; 1927 church pew bunkers, fastest greens on tour, Oakmont PA',20),
('golf','윙드 풋 골프 클럽','Winged Foot Golf Club','US',
 'US Open 6 times (1929-2020); narrow fairways 7,477 yards, Mamaroneck NY, Tillinghast',20),
('golf','시네콕 힐스 골프 클럽','Shinnecock Hills Golf Club','US',
 'US Open 6 times (1896-2018); links-style coastal, Southampton NY, first US Open purpose-built',20),
('golf','파인허스트 2번 코스','Pinehurst No. 2','US',
 'US Open 5 times (1999-2024); Donald Ross 1907, sandhills NC, 2024 both men & women opens',20),
('golf','더 컨트리 클럽','The Country Club','US',
 'US Open 1913 Ouimet miracle, 1988, 1999, 2022; oldest US club Brookline MA, Francis Ouimet',20),
('golf','올림픽 클럽 레이크 코스','Olympic Club Lake Course','US',
 'US Open 5 times (1955-2012); Ben Hogan 1955 shock loss, uphill par-4s San Francisco CA',20),
('golf','베스페이지 블랙','Bethpage Black','US',
 'US Open 2002/2009; PGA 2019; public state park course NY, "Warning: Black is too difficult"',20),
('golf','토리 파인스 사우스','Torrey Pines South Course','US',
 'US Open 2008 Tiger Woods playoff win, 2021 Jon Rahm birdie; Pacific Ocean cliffs La Jolla CA',20),
('golf','페블 비치 골프 링크스','Pebble Beach Golf Links','US',
 'US Open 6 times; 18th cliff over Carmel Bay, public play, most scenic major course',20),
('golf','발할라 골프 클럽','Valhalla Golf Club','US',
 'PGA Championship 1996/2000/2014; Ryder Cup 2024; Jack Nicklaus design Louisville KY',20),
('golf','키아와 아일랜드 오션 코스','Kiawah Island Ocean Course','US',
 'Ryder Cup 1991 War on Shore; PGA Championship 2012/2021; 10 oceanside holes South Carolina',20),
('golf','휘슬링 스트레이츠','Whistling Straits','US',
 'PGA Championship 2004/2010/2020; Ryder Cup 2020; Pete Dye Lake Michigan shore Wisconsin',20),
('golf','TPC 소그래스 스타디움','TPC Sawgrass Stadium Course','US',
 'THE PLAYERS Championship annually; island green 17th par-3, Pete Dye 1982 Ponte Vedra FL',20),
('golf','메디나 컨트리 클럽','Medinah Country Club No.3','US',
 'US Open 3 times; PGA Championship 2 times; Ryder Cup 2012 miracle comeback; Medinah IL',20),
('golf','헤이즐틴 내셔널','Hazeltine National Golf Club','US',
 'US Open 1970; PGA Championship 4 times; Ryder Cup 2016; Robert Trent Jones Sr Chaska MN',20),
('golf','발투스롤 로워 코스','Baltusrol Golf Club Lower Course','US',
 'US Open 7 times (1903-2016); PGA Championship; Robert Trent Jones renovation Springfield NJ',20),
('golf','메리온 이스트 코스','Merion Golf Club East Course','US',
 'US Open 5 times (1934-2013); smallest major venue, red basket flagsticks, Ardmore PA',20),
('golf','퀘일 할로우 클럽','Quail Hollow Club','US',
 'PGA Championship 2017; Ryder Cup 2028 host; Wells Fargo Championship annual Charlotte NC',20),
('golf','세인트 앤드루스 올드 코스','St Andrews Old Course','GB',
 'Home of Golf 600 years; The Open most times, Swilcan Bridge, Road Hole 17th, Fife Scotland',20),
('golf','뮤어필드','Muirfield','GB',
 'The Open 16 times; oldest golf club 1744 Honourable Company, East Lothian Scotland',20),
('golf','카누스티 골프 링크스','Carnoustie Golf Links','GB',
 'The Open 8 times; most feared links course, Barry Burn 18th, windswept Angus Scotland',20),
('golf','로열 버크데일','Royal Birkdale Golf Club','GB',
 'The Open 10 times (last 2017); willow scrub rough, flat lies, Southport Lancashire England',20),
('golf','로열 트룬','Royal Troon Golf Club','GB',
 'The Open 9 times; Postage Stamp 8th tiny par-3 123 yards, South Ayrshire Scotland',20),
('golf','로열 리덤 앤 세인트 앤스','Royal Lytham & St Annes Golf Club','GB',
 'The Open 11 times; 206 bunkers, no sea views but classic links, Lancashire England',20),
('golf','로열 세인트 조지스','Royal St George''s Golf Club','GB',
 'The Open 15 times (2021); hidden dunes Sandwich Kent England, oldest English venue',20),
('golf','로열 포트러시','Royal Portrush Golf Club','GB',
 'The Open 2019/2025; Dunluce Links Northern Ireland, Calamity Corner 14th, Rory McIlroy',20),
('golf','로열 리버풀 (호레이크)','Royal Liverpool Golf Club','GB',
 'The Open 12 times (2006/2014/2023); Hoylake Wirral, Tiger 2006 no bunkers strategy',20),
('golf','턴베리 에일사 코스','Turnberry Ailsa Course','GB',
 'The Open 4 times; 1977 Duel in the Sun Watson/Nicklaus, Ailsa Craig lighthouse Ayrshire',20),
('golf','서던 힐스 컨트리 클럽','Southern Hills Country Club','US',
 'US Open 3 times; PGA Championship 2022 Rory McIlroy; Donald Ross/Gil Hanse Tulsa OK',15),
('golf','오크 힐 이스트 코스','Oak Hill Country Club East Course','US',
 'US Open 5 times; PGA Championship 2023 Brooks Koepka; Donald Ross Rochester NY',15),
('golf','오클랜드 힐스 사우스','Oakland Hills Country Club South','US',
 'US Open 7 times; Ryder Cup 1961; "Monster" nickname, Ben Hogan 1951, Bloomfield Hills MI',15),
('golf','리비에라 컨트리 클럽','Riviera Country Club','US',
 'PGA Championship 1983/1995; Genesis Invitational; Ben Hogan career tied, Pacific Palisades CA',15),
('golf','뮤어필드 빌리지 골프 클럽','Muirfield Village Golf Club','US',
 'Memorial Tournament annually; Presidents Cup 1987/2013; Jack Nicklaus design Dublin OH',15),
('golf','이스트 레이크 골프 클럽','East Lake Golf Club','US',
 'Tour Championship every year; Bobby Jones''s home course, historic Atlanta Georgia',15),
('golf','콩그레셔널 블루 코스','Congressional Country Club Blue Course','US',
 'US Open 1964/1997/2011; KPMG Women''s PGA; Bethesda Maryland, power hitter''s paradise',15),
('golf','아로니민크 골프 클럽','Aronimink Golf Club','US',
 'PGA Championship 1962; BMW Championship; Donald Ross design 1928 Newtown Square PA',15),
('golf','베이 힐 클럽 앤 로지','Bay Hill Club & Lodge','US',
 'Arnold Palmer Invitational annually; Arnold Palmer''s home course Orlando Florida',15),
('golf','하버 타운 골프 링크스','Harbour Town Golf Links','US',
 'RBC Heritage annually; Pete Dye/Jack Nicklaus 1969, lighthouse par-4 18th Hilton Head SC',15),
('golf','카팔루아 플랜테이션 코스','Kapalua Plantation Course','US',
 'The Sentry (Tournament of Champions) annually; Bill Coore/Ben Crenshaw 2007 Maui Hawaii',15),
('golf','파이어스톤 사우스 코스','Firestone Country Club South Course','US',
 'WGC-Bridgestone Invitational (14 years); Robert Trent Jones 1960 renovation Akron Ohio',15),
('golf','벨레리브 컨트리 클럽','Bellerive Country Club','US',
 'US Open 1965; PGA Championship 2018 Brooks Koepka; Robert Trent Jones Sr St. Louis MO',15),
('golf','리버티 내셔널 골프 클럽','Liberty National Golf Club','US',
 'Presidents Cup 2017; FedEx St Jude Invitational; Manhattan skyline views Jersey City NJ',15),
('golf','챔버스 베이 골프 코스','Chambers Bay Golf Course','US',
 'US Open 2015 Jordan Spieth; Robert Trent Jones Jr design Pierce County Washington State',15),
('golf','에린 힐스 골프 코스','Erin Hills Golf Course','US',
 'US Open 2017 Brooks Koepka; Kettle Moraine moraines Wisconsin, wide fairways unique',15),
('golf','TPC 스코츠데일 스타디움','TPC Scottsdale Stadium Course','US',
 'Waste Management Phoenix Open annually; 16th hole 20,000 stadium atmosphere, Arizona',15),
('golf','프레리 듄스 컨트리 클럽','Prairie Dunes Country Club','US',
 'US Women''s Open 1995/2002; US Senior Open; Perry Maxwell 1937 Hutchinson Kansas',15),
('golf','파인 니들스 로지 앤 골프 클럽','Pine Needles Lodge & Golf Club','US',
 'US Women''s Open 1996/2001/2007/2022; Donald Ross design Southern Pines NC',15),
('golf','와이알라에 컨트리 클럽','Waialae Country Club','US',
 'Sony Open in Hawaii annually (since 1965); oceanside private Honolulu Hawaii PGA Tour',15),
('golf','콜로니얼 컨트리 클럽','Colonial Country Club','US',
 'Charles Schwab Challenge annually; Ben Hogan tribute "Hogan''s Alley" Fort Worth Texas',15),
('golf','발데라마 레알 클럽','Real Club Valderrama','ES',
 'Ryder Cup 1997 first continental Europe; Seve legacy cork oak 17th water Andalucia Spain',15),
('golf','더 케이 클럽 라이더 컵','The K Club Palmer Course','IE',
 'Ryder Cup 2006 Europe 18.5-9.5 win; Arnold Palmer design Kildare County Ireland',15),
('golf','셀틱 매너 투엔티텐','Celtic Manor Twenty Ten Course','GB',
 'Ryder Cup 2010; specially built for match play Colin Montgomerie design Newport Wales',15),
('golf','글리니글스 PGA 센테너리','Gleneagles PGA Centenary Course','GB',
 'Ryder Cup 2014; Jack Nicklaus/James Braid design, Perthshire Scotland luxury hotel',15),
('golf','르 골프 내셔널','Le Golf National','FR',
 'Ryder Cup 2018 Europe 17.5-10.5 blowout; French Open annually, Albatros course Paris',15),
('golf','마르코 시모네 골프 클럽','Marco Simone Golf & Country Club','IT',
 'Ryder Cup 2023 Europe 16.5-11.5; Tom and Dana Weiskopf design Rome Italy',15),
('golf','더 벨프리 브라바존','The Belfry Brabazon Course','GB',
 'Ryder Cup 4 times (1985/1989/1993/2002); Europe rediscovered Ryder Cup glory here, Sutton Coldfield',15),
('golf','로열 카운티 다운','Royal County Down Golf Club','IE',
 'Consistently world #1-ranked links; Mourne Mountains backdrop Newcastle Northern Ireland',15),
('golf','로열 몬트리올 블루 코스','Royal Montreal Golf Club','CA',
 'First golf club in Americas 1873; Canadian Open (10 times); Blue Course Ile Bizard Quebec',15),
('golf','글렌 애비 골프 클럽','Glen Abbey Golf Club','CA',
 'Canadian Open most times hosted (25+); Jack Nicklaus design 1976 Oakville Ontario',15),
('golf','가스미가세키 이스트 코스','Kasumigaseki Country Club East Course','JP',
 'Tokyo 2020 Olympics both gold medals; historic 1929 design, Saitama Japan',15),
('golf','나라시노 컨트리 클럽','Narashino Country Club','JP',
 'ZOZO Championship (PGA Tour Japan); Tiger Woods won 2019; Inzai Chiba Japan',15),
('golf','잭 니클라우스 GC 코리아','Jack Nicklaus Golf Club Korea','KR',
 'Presidents Cup 2015 host; Jack Nicklaus design Songdo Incheon South Korea',15),
('golf','나인 브릿지스 골프 클럽','Nine Bridges Golf Club','KR',
 'KLPGA flagship; 9 traditional bridges water features; Jeju Island South Korea autumn',15),
('golf','로열 멜버른 컴포지트','Royal Melbourne Golf Club','AU',
 'Presidents Cup host (2011/2019); composite West+East; top ranked sandbelt Melbourne',15),
('golf','킹스턴 히스 골프 클럽','Kingston Heath Golf Club','AU',
 'Australian Open multiple times; Alister MacKenzie bunkers, sandbelt Melbourne Victoria',15),
('golf','게리 플레이어 컨트리 클럽','Gary Player Country Club','ZA',
 'Nedbank Golf Challenge annually; Sun City North West Province South Africa Lost City',15),
('golf','팬코트 링크스','Fancourt Links','ZA',
 'Presidents Cup 2003; Ernie Els design, Outeniqua Mountains George South Africa',15),
('golf','셰산 인터내셔널 골프 클럽','Sheshan International Golf Club','CN',
 'WGC-HSBC Champions annually (China''s major); Shanghai, first WGC in Asia Pacific',15),
('golf','에미리트 골프 클럽 마질리스','Emirates Golf Club Majlis Course','AE',
 'DP World Tour Championship; first floodlit tournament 1989 Dubai Desert Classic, UAE',15),
('golf','에비앙 리조트 골프 클럽','Evian Resort Golf Club','FR',
 'Evian Championship (5th women''s major) annually; Evian-les-Bains Lake Geneva Alps France',15),
('golf','웬트워스 웨스트 코스','Wentworth Club West Course','GB',
 'BMW PGA Championship annually (DP World Tour flagship); Harry Colt 1924 Surrey England',10),
('golf','서닝데일 올드 코스','Sunningdale Golf Club Old Course','GB',
 'Open Championship qualifying; Walker Cup 1987; Willie Park Jr 1900 Berkshire heathland',10),
('golf','로흐 로먼드 골프 클럽','Loch Lomond Golf Club','GB',
 'Scottish Open (multiple years); Tom Weiskopf design, Loch Lomond Highland Scotland',10),
('golf','킹스반스 골프 링크스','Kingsbarns Golf Links','GB',
 'Alfred Dunhill Links annually; Kyle Phillips 2000, sea views all 18 holes Fife Scotland',10),
('golf','로열 도노흐 골프 클럽','Royal Dornoch Golf Club','GB',
 'Scottish Amateur; European Ladies Amateur; Tom Watson''s favourite, Highlands Scotland',10),
('golf','포트마녹 골프 클럽','Portmarnock Golf Club','IE',
 'Irish Open (multiple); Walker Cup 1991; Dublin peninsula links all-round wind challenge',10),
('golf','라힌치 올드 코스','Lahinch Golf Club Old Course','IE',
 'Irish Open 2019; West of Ireland Championship; goats weather forecast, County Clare',10),
('golf','크랑 쉬르 시에르','Crans-sur-Sierre Golf Club','CH',
 'European Masters annually (DP World Tour); Swiss Alps 1,500m elevation Mont Blanc views',10),
('golf','엘 살레르 골프 클럽','El Saler Golf Club','ES',
 'Spanish Open (multiple); Javier Arana 1968, Mediterranean dunes Albufera park Valencia',10),
('golf','TPC 사우스윈드','TPC Southwind','US',
 'FedEx St Jude Championship annually; Ron Prichard 1989 design Memphis Tennessee',10),
('golf','TPC 디어런','TPC Deere Run','US',
 'John Deere Classic annually; D.A. Weibring 1987 design, Silvis Illinois quad cities',10),
('golf','스파이글래스 힐','Spyglass Hill Golf Course','US',
 'AT&T Pebble Beach Pro-Am; Robert Trent Jones 1966, forest meets ocean Pebble Beach CA',10),
('golf','히로노 골프 클럽','Hirono Golf Club','JP',
 'Japan Open (multiple); Japan Amateur; Charles Alison 1932 masterpiece Kobe, world top 50',10),
('golf','요미우리 컨트리 클럽','Yomiuri Country Club','JP',
 'Japan Open Golf Championship; Japan''s most prestigious open championship Tokyo area',10),
('golf','블루 캐년 컨트리 클럽','Blue Canyon Country Club','TH',
 'Johnnie Walker Classic (European Tour 2000-2002); Canyon Course Phuket Thailand',10),
('golf','우정힐스 컨트리 클럽','Woo Jeong Hills Country Club','KR',
 'CJ Cup at Korea (PGA Tour); Portrush-inspired bentgrass, Cheonan South Korea',10),
('golf','미션 힐스 선전 올드 코스','Mission Hills Golf Club Shenzhen','CN',
 'WGC-HSBC World Match Play; world largest golf facility Guanlan Shenzhen China',10),
('golf','로열 애들레이드 골프 클럽','Royal Adelaide Golf Club','AU',
 'Australian Open (multiple); Alister MacKenzie 1926, sand belt South Australia',10),
('golf','뉴사우스웨일스 골프 클럽','New South Wales Golf Club','AU',
 'Australian Open; Alister MacKenzie clifftop, Botany Bay views Sydney wind factor',10),
('golf','카우리 클리프스 골프 코스','Kauri Cliffs Golf Course','NZ',
 'New Zealand Open; Golf Digest top courses; 15 holes ocean views Bay of Islands NZ',10),
('golf','아부다비 골프 클럽','Abu Dhabi Golf Club','AE',
 'Abu Dhabi HSBC Championship annually; Championship Course Peter Harradine 1997 UAE',10),
('golf','레오파드 크릭 컨트리 클럽','Leopard Creek Country Club','ZA',
 'Alfred Dunhill Championship; Kruger Park border crocodiles hippos holes 3-5, Malelane',10),
('golf','더반 컨트리 클럽','Durban Country Club','ZA',
 'South African Open (multiple); George Waterman 1920 Indian Ocean views Natal',10),
('golf','PGA 카탈루냐 스타디움','PGA Catalunya Stadium Course','ES',
 'Solheim Cup 2023; Spanish Open; Stadium Course water features Girona Catalonia Spain',10),
('golf','골프 클럽 구트 라르헨호프','Golf Club Gut Lärchenhof','DE',
 'BMW International Open (European Tour); Bernhard Langer design Cologne Germany',10),
('golf','엘 카말레온 골프 클럽','El Camaleón Golf Club','MX',
 'World Wide Technology Championship (PGA Tour); Greg Norman design Mayakoba Riviera Maya',10),
('golf','알바니 골프 코스 바하마','Albany Golf Course, Bahamas','BS',
 'Hero World Challenge (Tiger Woods''s event); Ernie Els design New Providence Bahamas',10),
('golf','미드 오션 클럽 버뮤다','Mid Ocean Club','BM',
 'Bermuda Championship qualifying; Charles Blair Macdonald 1921, Tucker''s Town Atlantic',10),
('golf','포트 로열 골프 코스','Port Royal Golf Course','BM',
 'Bermuda Championship PGA Tour host; Robert Trent Jones Sr 1970 Southampton Bermuda',10);


-- ###################################################################
-- # schema-v17.sql — 100 Dive Sites 전면 교체
-- ###################################################################

DELETE FROM public.challenge_certifications
  WHERE challenge_id IN (
    SELECT id FROM public.challenges WHERE category = 'scuba'
  );
DELETE FROM public.challenges WHERE category = 'scuba';

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES

('scuba','라자 암팟','Raja Ampat','ID',
 'World #1 coral biodiversity; 75% world coral species, 1,500+ fish species, pygmy seahorses',20),
('scuba','투바타하 리프','Tubbataha Reef','PH',
 'UNESCO Philippines; remote Sulu Sea atoll, 600 fish species, whale sharks year-round',20),
('scuba','코모도 국립공원','Komodo National Park','ID',
 'UNESCO dive; Manta Point aggregations, pink beach reef, hammerhead channel drift dives',20),
('scuba','시파단 섬','Sipadan Island','MY',
 'Turtle capital of the world; barracuda tornado 1,000+, hammerheads, walls to 600m',20),
('scuba','밀네 베이 파푸아뉴기니','Milne Bay, Papua New Guinea','PG',
 'Critter paradise; world record pygmy seahorse density, nudibranch heaven, WW2 wrecks',20),
('scuba','메르귀 제도 미얀마','Mergui Archipelago, Myanmar','MM',
 '800-island pristine remote; Andaman Sea untouched reefs, live-aboard only access',20),
('scuba','팔라우 블루 코너','Palau Blue Corner','PW',
 'Most famous dive; hook into reef, grey reef sharks current ride, manta wall parade',20),
('scuba','트루크 라군 마이크로네시아','Truk Lagoon, Micronesia','FM',
 'World #1 wreck dive; 50+ Japanese WW2 ships, Zero planes, tanks, coral-encrusted fleet',20),
('scuba','코코스 아일랜드 코스타리카','Cocos Island, Costa Rica','CR',
 'Pelagic paradise; 400 hammerheads, whale sharks, manta rays, UNESCO World Heritage',20),
('scuba','다윈 아치 갈라파고스','Darwin Arch, Galápagos','EC',
 'Whale shark mass aggregations 40+; hammerheads, schools tuna, Ecuador Pacific pinnacle',20),
('scuba','통가 혹등고래 다이브','Tonga Humpback Whale Dive','TO',
 'Swim with humpback mother-calf; largest animals in water, August-October season',20),
('scuba','팔라우 SS 야마구치 난파선','Palau Wrecks, Micronesia','PW',
 'Multiple Japanese WW2 wrecks; Iro tanker, Zero Fighters, Chuyo-Maru coral-encrusted',20),
('scuba','알다브라 환초 세이셸','Aldabra Atoll, Seychelles','SC',
 'UNESCO most remote; nurse sharks, Napoleon wrasse, 100,000 giant tortoise island',20),
('scuba','소다와나 베이 남아공','Sodwana Bay, South Africa','ZA',
 'Coelacanth discovered nearby; whale sharks, humpbacks, iSimangaliso Wetland Park',20),
('scuba','페르난도 데 노로냐 브라질','Fernando de Noronha, Brazil','BR',
 'UNESCO Atlantic Marine Park; spinner dolphins, lemon sharks, crystal blue visibility',20),
('scuba','SS 시스틀레고름 홍해','SS Thistlegorm, Red Sea','EG',
 'World most famous WW2 wreck; motorcycles, trucks, BSA motorcycles 30m Red Sea Egypt',20),
('scuba','브라더스 아일랜드 수단','Brothers Islands, Sudan','SD',
 'Remote Red Sea; hammerhead & thresher sharks, oceanic whitetip, Cousteau territory',20),
('scuba','말로엘 아일랜드 콜롬비아','Malpelo Island, Colombia','CO',
 'UNESCO shark sanctuary; 1,000+ hammerheads, silky sharks, whale sharks, deepest walls',20),
('scuba','그레이트 블루 홀 벨리즈','Great Blue Hole, Belize','BZ',
 'UNESCO giant marine sinkhole 300m wide; stalactites 40m, bull sharks, Jacques Cousteau',20),
('scuba','실프라 열곡 아이슬란드','Silfra Fissure, Iceland','IS',
 'Dive between tectonic plates; 100m+ visibility, 2°C glacial meltwater, crystal clarity',20),
('scuba','스카파 플로 스코틀랜드','Scapa Flow, Scotland','GB',
 'WW1 German Imperial Fleet scuttled 1919; 7 warships intact, best wreck UK diving',20),
('scuba','타이거 비치 바하마','Tiger Beach, Bahamas','BS',
 'Tiger shark capital; reliable 3-5m encounters, lemon sharks, great hammerhead season',20),
('scuba','SS 프레지던트 쿨리지 바누아투','SS President Coolidge, Vanuatu','VU',
 'Largest diveable luxury liner wreck; 22,000 tonne, 180m long, Art Deco interiors, 30m',20),
('scuba','HMHS 브리타닉 난파선 그리스','HMHS Britannic Wreck, Aegean','GR',
 'Titanic''s sister ship; 48,000 tonne largest diveable wreck 120m, Kea Island Greece',20),
('scuba','안다바다오카 마다가스카르','Andavadoaka, Madagascar','MG',
 'Pristine remote SW Madagascar; whale shark season June, octopus fishery, untouched reef',20),
('scuba','누사 페니다 발리','Nusa Penida, Bali','ID',
 'Mola-mola (ocean sunfish) encounters July-Nov; Manta Point cleaning station Bali',15),
('scuba','리슐리외 록 태국','Richelieu Rock, Thailand','TH',
 'Thailand best site; whale shark station, seahorses, mantis shrimp, barracuda schools',15),
('scuba','시밀란 제도 태국','Similan Islands, Thailand','TH',
 'Andaman granite boulder dives; leopard sharks, seasonal Nov-April, UNESCO proposed',15),
('scuba','와카토비 인도네시아','Wakatobi, Indonesia','ID',
 'Remote Sulawesi; pristine house reef, wall diving, pigmy seahorse, tidal channel magic',15),
('scuba','부나켄 인도네시아','Bunaken, Indonesia','ID',
 'Wall diving capital; 90-degree vertical walls 40m, green turtle, barracuda, Napoleon',15),
('scuba','아포 아일랜드 필리핀','Apo Island, Philippines','PH',
 'Community-managed turtle sanctuary; green sea turtles feeding coral, reef recovery model',15),
('scuba','모알보알 필리핀','Moalboal, Philippines','PH',
 'Sardine tornado million fish; thresher sharks nearby, turtle reef, Cebu Visayas',15),
('scuba','코론 베이 필리핀','Coron Bay, Philippines','PH',
 'WW2 Japanese ghost fleet; 24 wrecks, Irako provisioning ship, lotus-covered Akitsushima',15),
('scuba','코타이 태국','Koh Tao, Thailand','TH',
 'World''s 3rd busiest dive certification; whale shark encounters Gulf of Thailand accessible',15),
('scuba','말라파스쿠아 섬 필리핀','Malapascua Island, Philippines','PH',
 'Thresher sharks sunrise; Monad Shoal cleaning station 25m, Cebu Philippines must-dive',15),
('scuba','풀라우 웨 인도네시아','Pulau Weh, Indonesia','ID',
 'Sabang Aceh; Blue Sapphire pinnacle, nudibranch, whaleshark year-round visibility 30m',15),
('scuba','솔로몬 제도','Solomon Islands','SB',
 'WW2 Iron Bottom Sound; 30+ wrecks, USS Aaron Ward, pristine undisturbed reefs Tulagi',15),
('scuba','랑기로아 프랑스령 폴리네시아','Rangiroa, French Polynesia','PF',
 'World''s second largest atoll; Tiputa Pass drift, dolphin school, grey reef shark parade',15),
('scuba','파카라바 프랑스령 폴리네시아','Fakarava, French Polynesia','PF',
 'UNESCO biosphere; grey reef shark wall 700+, grouper spawning, South Pass drift dive',15),
('scuba','퍼시픽 하버 피지','Pacific Harbor, Fiji','FJ',
 'Bull shark dive with 80+; bait feeding ritual, reef sharks, Beqa Lagoon Fiji landmark',15),
('scuba','야프 섬 미크로네시아','Yap Island, Micronesia','FM',
 'Resident manta ray sanctuary; year-round mantas, grey reef sharks, mandarin fish',15),
('scuba','코나 만타 나이트 다이브 하와이','Kona Manta Ray Night Dive, Hawaii','US',
 'Most famous night dive; 20+ mantas feed on plankton in light beam, magical ballet',15),
('scuba','뉴어 태평양','Niue, South Pacific','NU',
 'Clearest ocean visibility 80m+; sea snakes, humpback, spinner dolphins, limestone caves',15),
('scuba','북말레 환초 몰디브','North Malé Atoll, Maldives','MV',
 'Hammerhead pinnacle; tiger sharks, whale sharks, napoleon, Rasdhoo Atoll kandu dive',15),
('scuba','바 환초 몰디브','Baa Atoll, Maldives','MV',
 'Hanifaru Bay UNESCO; manta ray aggregation 200+, whale shark, May-November season',15),
('scuba','안다만 제도 인도','Andaman Islands, India','IN',
 'Barracuda City; Pilot Whale Rock, pristine Bay of Bengal reef, 12 endemic species',15),
('scuba','마피아 아일랜드 탄자니아','Mafia Island, Tanzania','TZ',
 'East Africa whale shark Oct-Mar; Chole Bay marine park pristine, very few visitors',15),
('scuba','토포 비치 모잠비크','Tofo Beach, Mozambique','MZ',
 'Manta reef aggregations; whale shark daily, dugong grassbeds, 30m wall dives Inhambane',15),
('scuba','마요트 인도양','Mayotte, Indian Ocean','YT',
 'French territory Indian Ocean; hammerhead schools, whale shark, dugong turtle nesting',15),
('scuba','노시 베 마다가스카르','Nosy Be, Madagascar','MG',
 'Whale shark aggregation Oct; pristine reefs, whale shark swim, lemur island topside',15),
('scuba','라스 모하메드 이집트','Ras Mohammed, Egypt','EG',
 'Red Sea flagship; Shark & Yolanda Reef wall 60m, glassfish tunnels, jackfish tornado',15),
('scuba','블루 홀 다합 이집트','Blue Hole Dahab, Egypt','EG',
 'Famous sinkhole 130m; 52m arch freedive temptation, canyon entry Dahab Sinai classic',15),
('scuba','지부티 고래상어','Djibouti Whale Shark, Djibouti','DJ',
 'Bay of Tadjoura aggregation; Nov-Jan whale shark school snorkel-dive, warmest sea',15),
('scuba','에일라트 이스라엘','Eilat, Israel','IL',
 'Moses Rock undercut reef; Japanese Gardens, year-round 21°C, accessible Red Sea',15),
('scuba','아카바 요르단','Aqaba, Jordan','JO',
 'Cedar Pride wreck 30m; tank wreck 10m, Rainbow Reef walls, Red Sea affordable gateway',15),
('scuba','알리왈 쇼올 남아공','Aliwal Shoal, South Africa','ZA',
 'Ragged-tooth shark sanctuary; oceanic blacktip, tiger sharks, 3 wrecks offshore KwaZulu',15),
('scuba','와타무 해양 공원 케냐','Watamu Marine Park, Kenya','KE',
 'East Africa coral garden; whale shark season, sea turtles, Turtle Bay protected marine',15),
('scuba','음냄바 환초 잔지바르','Mnemba Atoll, Zanzibar','TZ',
 'East Africa turtle cleaning; spinner dolphin, manta ray, pristine lagoon Tanzania',15),
('scuba','유카탄 세노테 멕시코','Cenotes Yucatan, Mexico','MX',
 'Underwater cave system; crystal freshwater stalactites, halocline curtain, Riviera Maya',15),
('scuba','코수멜 멕시코','Cozumel, Mexico','MX',
 'Caribbean drift classic; Palancar Reef wall, Santa Rosa Canyon, turtle cleaning station',15),
('scuba','하르디네스 데 라 레이나 쿠바','Jardines de la Reina, Cuba','CU',
 'Pristine Caribbean coral; permit, tarpon, silky sharks, grouper density, live-aboard only',15),
('scuba','로아탄 온두라스','Roatan, Honduras','HN',
 'Bay Islands barrier reef; whale shark encounters, Mesoamerican reef second largest',15),
('scuba','벨리즈 배리어 리프','Belize Barrier Reef','BZ',
 'UNESCO second largest reef; nurse sharks sleeping, manatees, 500 fish species coastal',15),
('scuba','배트 아일랜드 코스타리카','Bat Islands, Costa Rica','CR',
 'Bull shark congregation; strong current Guanacaste 50+ bulls July-December season',15),
('scuba','코이바 섬 파나마','Coiba Island, Panama','PA',
 'UNESCO Pacific Panama; whale sharks, humpback whales, endemic species, pristine isolated',15),
('scuba','아조레스 포르투갈','Azores, Portugal','PT',
 'Blue shark cage dive; sperm whale snorkel, 6 shark species, mid-Atlantic volcanic',15),
('scuba','엘 이에로 해양보호구역 스페인','El Hierro Marine Reserve, Spain','ES',
 'Europe first biosphere reserve dive; angel sharks, barracuda, endemic lava tube fish',15),
('scuba','노르웨이 피요르드','Norway Fjord Diving, Norway','NO',
 'Cold water clarity 30m+; Atlantic halibut, wolf fish, plumose anemone walls fjord',15),
('scuba','코스테르피오르덴 스웨덴','Kosterfjorden, Sweden','SE',
 'Sweden deepest point; sea fan meadows, nudibranchs September, cold Nordic fjord',15),
('scuba','이스터 아일랜드 칠레','Easter Island, Chile','CL',
 'Clearest Pacific; underwater Moai sculpture garden, endemic fish, 100 fish species',15),
('scuba','그레이트 배리어 리프 호주','Great Barrier Reef, Australia','AU',
 'World largest reef system; 2,300km UNESCO, Cod Hole potato grouper, Minke whale winter',10),
('scuba','닝갈루 리프 호주','Ningaloo Reef, Australia','AU',
 'Western Australia reef; whale shark snorkel March-July, manta ray cleaning stations',10),
('scuba','로드 하우 아일랜드 호주','Lord Howe Island, Australia','AU',
 'World southernmost coral reef; ball''s pyramid, garibaldi, clear subtropical UNESCO',10),
('scuba','뉴칼레도니아 상어만','New Caledonia Shark Bay','NC',
 'Pacific largest lagoon UNESCO; bull shark feeding Boulari Pass, Napoleon wrasse',10),
('scuba','노퍽 아일랜드 태평양','Norfolk Island, Pacific','NF',
 'HMAS Sirius wreck 1790; big fish aggregations, coral covered, remote Pacific clarity',10),
('scuba','사이판 블루 홀 북마리아나','Saipan Blue Hole, Northern Marianas','MP',
 'Vertical sinkhole 27m; WWII Japanese Zero fighter 30m, Grotto formations crystal clear',10),
('scuba','팔라우 젤리피시 레이크','Jellyfish Lake, Palau','PW',
 'Snorkel among million stingless jellyfish; UNESCO, unique lake ecosystem Eil Malk Island',10),
('scuba','수빅 베이 필리핀','Subic Bay Wrecks, Philippines','PH',
 'WW2 US Navy wrecks; El Capitan, Oryoku Maru, octopus colonies, easy dive training',10),
('scuba','그린 아일랜드 타이완','Green Island, Taiwan','TW',
 'Taiwan best diving; rare underwater hot spring, 230 coral species, manta cleaning',10),
('scuba','코 리페 태국','Koh Lipe, Thailand','TH',
 'Andaman Sea clarity; leopard sharks, giant clam, soft coral, Adang Island archipelago',10),
('scuba','모리셔스','Mauritius','MU',
 'Underwater sand waterfall illusion; whale shark season, 25m Cathedral dive wall',10),
('scuba','코모로 제도','Comoro Islands','KM',
 'Coelacanth sanctuary; living fossil 400M years, Mohéli Marine Park whale shark',10),
('scuba','라카디브 제도 인도','Lakshadweep Islands, India','IN',
 'Pristine Indian Ocean atoll; manta rays, barracuda, 36 atolls untouched reef system',10),
('scuba','무스카트 다이야니야트 오만','Muscat Daymaniyat, Oman','OM',
 'Oman marine reserve; green turtle nesting, spinner dolphin, dugong seasonal sighting',10),
('scuba','사우디아라비아 홍해 네옴','NEOM Red Sea, Saudi Arabia','SA',
 'Untouched Saudi Red Sea; pristine reef opening, endemic species, pristine visibility',10),
('scuba','레바논 티레 해양보호구역','Tyre Marine Reserve, Lebanon','LB',
 'Byzantine columns 10m deep; Phoenician anchors, amphora fields Tyre Mediterranean',10),
('scuba','제노비아 키프로스','Zenobia, Cyprus','CY',
 'Best Mediterranean wreck; 178m Swedish ferry sank 1980 maiden voyage, 40m depth',10),
('scuba','란사로테 MUSA 스페인','Lanzarote MUSA, Spain','ES',
 'Underwater sculpture museum; 300 artworks colonized by sea life, Canary Islands',10),
('scuba','마르세유 칼랑크 프랑스','Marseille Calanques, France','FR',
 'Marine park; fan corals, octopus, gorgonian, WW2 landing craft wreck, rare moray',10),
('scuba','흐바르 크로아티아','Hvar, Croatia','HR',
 'Adriatic sea caves; Vis Island WW2 wrecks, blue cave bioluminescence, clear Adriatic',10),
('scuba','산토리니 칼데라 그리스','Santorini Caldera, Greece','GR',
 'Volcanic dive; fumaroles bubbles, Roman amphora fields, unique Mediterranean geology',10),
('scuba','보드룸 터키','Bodrum Wrecks, Turkey','TR',
 'Aegean ancient wrecks; Byzantine 7th century ships, amphora trails, Castle St Peter',10),
('scuba','메노르카 동굴 스페인','Menorca Sea Caves, Spain','ES',
 'Mediterranean sea caves; 7th century Byzantine wreck San Nicolau, posidonia meadows',10),
('scuba','플로리다 키스 미국','Florida Keys, USA','US',
 'John Pennekamp Coral Reef first underwater park; Christ of the Abyss statue 25m',10),
('scuba','플로리다 스프링스 미국','Florida Springs, USA','US',
 'Crystal River cave springs; 22°C year-round, manatee winter sanctuary, 30m clarity',10),
('scuba','바하 칼리포르니아 멕시코','Baja California Sea of Cortez','MX',
 'Cabo Pulmo Marine Park; mobula ray tornado, playful sea lions, whale shark season',10),
('scuba','RMS 론 영국령 버진 아일랜드','RMS Rhone, British Virgin Islands','VG',
 'Classic Caribbean wreck; 1867 HMS Rhone, 120 years coral growth, bow 8m stern 24m',10),
('scuba','캠벨 강 캐나다','Campbell River, Canada','CA',
 'Giant Pacific octopus; wolf eels, plumose anemones, nudibranchs cold Pacific dive',10),
('scuba','버뮤다','Bermuda','BM',
 'Atlantic wrecks 300+; Bermuda Triangle mystique, moray eel, clear water wreck diving',10),
('scuba','스팅레이 시티 케이만','Stingray City, Cayman Islands','KY',
 'Grand Cayman sandbar; hundreds friendly southern stingrays, snorkel, first-dive spot',10);


-- ###################################################################
-- # schema-v18.sql — 100 Ski Resorts: 15개 추가 (85 → 100)
-- ###################################################################

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES

('skiing','생모리츠','St Moritz','CH',
 'Luxury Alps pioneer; 1928 & 1948 Winter Olympics, bobsled Cresta Run, Engadine valley',15),
('skiing','알프 디에즈 프랑스','Alpe d''Huez','FR',
 'France 245km pistes; 21 hairpin Tour de France descent, Sarenne glacier run 16km',10),
('skiing','티뉴','Tignes','FR',
 'High altitude guaranteed snow 3456m; linked with Val d''Isere Grande Motte glacier',10),
('skiing','메제브','Megève','FR',
 'Elegant Haute-Savoie village; Rothschild family resort, horse-drawn sleigh, 445km linked',10),
('skiing','자스-페','Saas-Fee','CH',
 'Car-free glacier village; year-round skiing 3500m, Alpin Express underground funicular',10),
('skiing','플림스 라악스','Flims Laax','CH',
 'Swiss snowboard capital; biggest halfpipe Europe, Crap Sogn Gion, Disentis linked',10),
('skiing','잘바흐 힌터글렘','Saalbach-Hinterglemm','AT',
 'Ski Circus loop; 270km connected Leogang Fieberbrunn, après-ski Hinterhagalm famous',10),
('skiing','크로플라츠','Kronplatz, South Tyrol','IT',
 'Dolomites Plan de Corones; WC super-G venue, 32 lifts, 119km runs, mountain top panorama',10),
('skiing','바케이라 베레','Baqueira-Beret','ES',
 'Spanish Royal family resort Pyrenees; largest Spain ski area 166km, Val d''Aran village',10),
('skiing','게일로','Geilo','NO',
 'Norway most popular resort; Hardangervidda plateau, husky sledding, cabin culture',10),
('skiing','브레켄릿지','Breckenridge','US',
 'Colorado highest ski resort 12,998ft; historic gold mine town, 187 runs five peaks',10),
('skiing','스토우 버몬트','Stowe','US',
 'Vermont oldest prestige resort; Mt Mansfield 1,339m, classic New England village',10),
('skiing','레벨스톡','Revelstoke','CA',
 'World''s greatest vertical 1,713m; cat-skiing, heli-ski capital British Columbia',10),
('skiing','마운트 불러 호주','Mt Buller','AU',
 'Victoria largest ski area; Melbourne 3hrs, 180km runs, Australian Alpine championship',10),
('skiing','킬링턴 버몬트','Killington','US',
 'East USA largest; 155 runs, longest North American season, K1 Express gondola beast',10);


-- ================================================================
-- 끝. v14(동물 9) → v15(낚시 100) → v16(골프 100) → v17(다이빙 100) → v18(스키 15)
-- ================================================================
