-- schema-v19-descriptions-nature.sql: Extended English descriptions for nature category (world 100)
-- Each description_en 500-700 characters: why world 100, geography, wildlife, best time, where to experience.

UPDATE challenges SET description_en = 'The Amazon Rainforest is the world''s largest tropical rainforest, spanning nine countries and hosting about 10% of known species. It is the planet''s greatest reservoir of biodiversity: pink river dolphins, anacondas, jaguars, and countless birds and insects. Deforestation and climate change threaten it, making responsible travel essential. Experience it via lodges in Brazil, Peru, or Ecuador; river cruises and guided walks reveal the forest''s wonders. The Amazon is irreplaceable and one of the world''s top natural destinations.' WHERE category = 'nature' AND title_en = 'Amazon Rainforest';

UPDATE challenges SET description_en = 'The Grand Canyon in Arizona is one of the world''s most iconic landscapes: 1.8 billion years of geology carved by the Colorado River, nearly 1.6 km deep and up to 29 km wide. South Rim is open year-round; North Rim seasonally. Hiking, rafting, and helicopter tours offer different perspectives. Sunrise and sunset paint the layers in dramatic colours. The Grand Canyon is a UNESCO World Heritage Site and a must-see for any traveller.' WHERE category = 'nature' AND title_en = 'Grand Canyon';

UPDATE challenges SET description_en = 'Iguazu Falls straddles Argentina and Brazil: 275 waterfalls across 2.7 km, wider than Niagara and set in subtropical forest. The Devil''s Throat is the most powerful section. Walkways and boat trips bring you close to the spray; jaguars and toucans live in the surrounding park. Visit from both sides for the full experience. Iguazu is a UNESCO site and one of the world''s most spectacular waterfall systems.' WHERE category = 'nature' AND title_en = 'Iguazu Falls';

UPDATE challenges SET description_en = 'Victoria Falls on the Zambia-Zimbabwe border is one of the world''s largest curtains of water. The Zambezi plunges into a narrow gorge; the spray rises 300 m and can be seen from miles away. The local name Mosi-oa-Tunya means the smoke that thunders. Visit in April or May for peak flow, or in the dry season to see the geology. Devil''s Pool on the Zambian side allows a swim at the edge. Victoria Falls is unforgettable.' WHERE category = 'nature' AND title_en = 'Victoria Falls';

UPDATE challenges SET description_en = 'The Galapagos Islands are a living laboratory of evolution, where Darwin''s finches, marine iguanas, and giant tortoises evolved in isolation. The archipelago belongs to Ecuador; access is by boat or flight. Snorkel with sea lions, walk among blue-footed boobies, and see the famous tortoises. Strict conservation rules protect the ecosystem. The Galapagos are UNESCO World Heritage and one of the world''s premier wildlife and nature destinations.' WHERE category = 'nature' AND title_en = 'Galapagos Islands';

UPDATE challenges SET description_en = 'The Serengeti in Tanzania is the stage for the Great Migration: over 1.5 million wildebeest and hundreds of thousands of zebras and gazelles move in an annual cycle. Lions, cheetahs, and leopards hunt on the open savanna. The Serengeti is one of Africa''s oldest and most important ecosystems. Safari by 4x4 or hot-air balloon; the best time depends on where the herds are. The Serengeti is a bucket-list destination for wildlife lovers.' WHERE category = 'nature' AND title_en = 'Serengeti';

UPDATE challenges SET description_en = 'Yellowstone was the world''s first national park and sits atop a supervolcano. Old Faithful and other geysers, colourful hot springs like Grand Prismatic, and wildlife including bison, wolves, and grizzly bears define the experience. The park spans Wyoming, Montana, and Idaho. Summer is busiest; autumn offers fewer crowds and rutting elk. Yellowstone is a UNESCO site and the template for national parks worldwide.' WHERE category = 'nature' AND title_en = 'Yellowstone';

UPDATE challenges SET description_en = 'Patagonia at the southern tip of South America is the end of the world: Torres del Paine''s granite towers, vast glaciers, and pumas in the steppe. Chile and Argentina share the region. Trek the W or O circuit in Torres del Paine, visit Perito Moreno Glacier, or cruise the fjords. The wind and scale are humbling. Patagonia is one of the world''s last great wildernesses and a top destination for hikers and nature lovers.' WHERE category = 'nature' AND title_en = 'Patagonia';

UPDATE challenges SET description_en = 'Salar de Uyuni in Bolivia is the world''s largest salt flat, over 10,000 km². In the rainy season a thin layer of water creates a perfect mirror of the sky. Train cemeteries, cactus islands, and flamingo lakes dot the region. Tours from Uyuni or San Pedro de Atacama cross the altiplano. The salar is otherworldly and one of South America''s most photographed and iconic landscapes.' WHERE category = 'nature' AND title_en = 'Salar de Uyuni';

UPDATE challenges SET description_en = 'Angel Falls in Venezuela is the world''s highest uninterrupted waterfall, 979 m from the tepui to the jungle. Access is by small plane and boat from Canaima. The falls are named after Jimmy Angel, who crash-landed nearby. The surrounding park is UNESCO-listed. Visiting requires planning due to remote location and local conditions. Angel Falls remains one of the planet''s most dramatic natural wonders.' WHERE category = 'nature' AND title_en = 'Angel Falls';

UPDATE challenges SET description_en = 'Sossusvlei in Namibia is home to the world''s tallest red sand dunes, some over 300 m. Dead Vlei is a white clay pan with ancient petrified trees against the dunes. Dawn and dusk offer the best light and cooler temperatures. The Namib-Naukluft Park is one of Africa''s largest. Sossusvlei is a photographer''s paradise and one of the world''s most striking desert landscapes.' WHERE category = 'nature' AND title_en = 'Sossusvlei';

UPDATE challenges SET description_en = 'Kruger National Park in South Africa is one of Africa''s largest game reserves and home to the Big Five plus over 500 bird species and 147 mammals. The legendary old tuskers (large-eared elephants) are a draw. Self-drive and guided safaris are possible; rest camps and lodges range from budget to luxury. Kruger is accessible and offers some of the best wildlife viewing on the continent.' WHERE category = 'nature' AND title_en = 'Kruger National Park';

UPDATE challenges SET description_en = 'The Northern Lights (aurora borealis) over Iceland are among the world''s most accessible: dance in the sky above glaciers, waterfalls, and lava fields. Winter (September–March) offers long dark nights; clear skies are key. Reykjavik, Thingvellir, and the South Coast are popular bases. Iceland''s geology and lack of light pollution make it a top aurora destination. The lights are a once-in-a-lifetime experience.' WHERE category = 'nature' AND title_en = 'Northern Lights Iceland';

UPDATE challenges SET description_en = 'The Swiss Alps include Mont Blanc (4,808 m) and the Matterhorn, with world-class skiing, glaciers, and climbing. Ibex and chamois roam the peaks; villages like Zermatt and Chamonix offer access. Summer brings hiking and via ferrata; winter is for skiing and snow. The Alps are the heart of European mountain culture and one of the world''s most iconic mountain ranges.' WHERE category = 'nature' AND title_en = 'Swiss Alps';

UPDATE challenges SET description_en = 'The Himalayas stretch across Nepal, India, Bhutan, and Tibet and include eight of the world''s 14 peaks over 8,000 m. Trekking, yak caravans, and Sherpa culture define the experience. Everest Base Camp, Annapurna Circuit, and Bhutan''s trails are legendary. The range is sacred and spectacular. The Himalayas are the roof of the world and a top destination for adventurers and pilgrims.' WHERE category = 'nature' AND title_en = 'Himalayas';

UPDATE challenges SET description_en = 'The Great Barrier Reef off Queensland is the world''s largest coral reef system and home to 1,500 fish species, turtles, and dugongs. Snorkelling and diving reveal colourful corals and marine life. Climate change and bleaching are threats; choose responsible operators. Cairns, Port Douglas, and the Whitsundays are gateways. The reef is UNESCO-listed and one of the seven natural wonders of the world.' WHERE category = 'nature' AND title_en = 'Great Barrier Reef';

UPDATE challenges SET description_en = 'The Namib Desert in Namibia is one of the world''s oldest deserts, about 55 million years. It features quiver tree forests, oryx, and mysterious fairy circles. Sossusvlei and Dead Vlei are within it; the Skeleton Coast is its dramatic Atlantic edge. The Namib is stark, beautiful, and one of Africa''s most unique landscapes. Visit for desert-adapted wildlife and surreal scenery.' WHERE category = 'nature' AND title_en = 'Namib Desert';

UPDATE challenges SET description_en = 'The Sahara is the world''s largest hot desert, spanning North Africa. Sand dunes, camel caravans, and Tuareg culture define the experience. Morocco, Tunisia, and Algeria offer desert camps and 4x4 trips. The Saharan silver ant and other extremophiles survive here. The Sahara is iconic and one of the world''s last great wildernesses. Stargazing and silence are unforgettable.' WHERE category = 'nature' AND title_en = 'Sahara Desert';

UPDATE challenges SET description_en = 'The Borneo Rainforest in Malaysia and Indonesia is one of the oldest tropical forests and home to orangutans, pygmy elephants, and proboscis monkeys. Danum Valley and Kinabatangan offer wildlife encounters. Deforestation for palm oil threatens the habitat; choose eco-certified lodges. Borneo is a top destination for primate and rainforest enthusiasts. The forest is irreplaceable.' WHERE category = 'nature' AND title_en = 'Borneo Rainforest';

UPDATE challenges SET description_en = 'Kakadu National Park in Australia''s Northern Territory holds 50,000-year-old Aboriginal rock art, saltwater crocodiles, and monsoon wetlands. Ubirr and Nourlangie have famous art sites; boat trips on the Yellow Water billabong reveal wildlife. The park is dual World Heritage listed for culture and nature. Visit in the dry season (May–October). Kakadu is one of Australia''s most significant natural and cultural destinations.' WHERE category = 'nature' AND title_en = 'Kakadu National Park';

UPDATE challenges SET description_en = 'Joshua Tree National Park in California is a surreal desert landscape of boulder piles and twisted Joshua trees (yucca). Rock climbers and stargazers flock here; the night sky is exceptional. The park straddles the Mojave and Colorado deserts. Spring brings wildflowers. Joshua Tree is otherworldly and one of America''s most distinctive national parks.' WHERE category = 'nature' AND title_en = 'Joshua Tree';

UPDATE challenges SET description_en = 'The Dolomites in northern Italy are UNESCO-listed pale limestone peaks. Via ferrata routes, dramatic sunsets (alpenglow), and skiing in winter draw visitors. Cortina d''Ampezzo and Alta Badia are bases. The Dolomites are among the most beautiful mountain ranges in Europe and a top destination for hiking and climbing.' WHERE category = 'nature' AND title_en = 'Dolomites';

UPDATE challenges SET description_en = 'Fiordland in New Zealand''s South Island is a wilderness of sheer cliffs, waterfalls, and deep fjords. Milford Sound and Doubtful Sound are the stars; dolphins and penguins are common. Cruises and kayaks explore the waters. Fiordland is UNESCO World Heritage and one of the wettest places on Earth. It is one of New Zealand''s most spectacular regions.' WHERE category = 'nature' AND title_en = 'Fiordland';

UPDATE challenges SET description_en = 'Socotra Island off Yemen is an alien landscape: Dragon Blood Trees and 700 endemic species exist nowhere else. The island is in the Arabian Sea; access has been limited by conflict. When safe, it offers unique botany and geology. Socotra is UNESCO-listed and one of the world''s most biodiverse and unusual islands. Responsible travel is essential.' WHERE category = 'nature' AND title_en = 'Socotra Island';

UPDATE challenges SET description_en = 'The Blue Mountains near Sydney are a eucalyptus-covered plateau where oil haze creates a blue tint. The Three Sisters rock formation and cockatoos are iconic. Scenic World and walking trails offer views. The area is Aboriginal cultural landscape and a popular escape from the city. The Blue Mountains are one of Australia''s most visited natural destinations.' WHERE category = 'nature' AND title_en = 'Blue Mountains';

UPDATE challenges SET description_en = 'Pomerape Valley in Chile''s Atacama highlands is a realm of flamingos, geysers at 4,200 m, and altiplano lakes. The landscape is stark and colourful. Tours from San Pedro de Atacama reach El Tatio geysers and lagoons. The region is one of the best places to experience high-altitude Andean nature and indigenous culture.' WHERE category = 'nature' AND title_en = 'Pomerape Valley';

UPDATE challenges SET description_en = 'Lake Baikal in Siberia is the world''s deepest lake (1,642 m) and holds about 20% of the world''s unfrozen surface freshwater. It is home to the endemic Baikal seal and unique species. The Circum-Baikal Railway and Olkhon Island are popular. Winter brings ice skating and transparent ice. Baikal is a UNESCO site and one of the world''s great natural wonders.' WHERE category = 'nature' AND title_en = 'Lake Baikal';

UPDATE challenges SET description_en = 'Waipoua Forest in New Zealand''s North Island protects ancient kauri trees, including Tane Mahuta, the God of the Forest, over 2,000 years old. The forest is sacred to Maori. Guided night walks and boardwalks protect the roots. Waipoua is one of the last great kauri forests and a must-see for anyone interested in ancient trees and Maori culture.' WHERE category = 'nature' AND title_en = 'Waipoua Forest';

UPDATE challenges SET description_en = 'The Tian Shan Mountains in Kyrgyzstan are a range of nomad summer pastures, eagle hunters, and pristine alpine lakes. Snow leopards live in remote areas. Trekking and homestays offer access to traditional culture. The Tian Shan is a UNESCO site and one of Central Asia''s most beautiful and least crowded mountain regions.' WHERE category = 'nature' AND title_en = 'Tian Shan Mountains';

UPDATE challenges SET description_en = 'Etosha National Park in Namibia centres on a vast salt pan; around it, 3,000 lions, black rhino, giraffe, and elephant herds gather at waterholes. The dry season (May–October) concentrates wildlife. Self-drive is possible; rest camps overlook floodlit waterholes. Etosha is one of Africa''s best parks for game viewing and photography.' WHERE category = 'nature' AND title_en = 'Etosha National Park';

UPDATE challenges SET description_en = 'Bwindi Impenetrable Forest in Uganda is home to roughly half of the world''s remaining mountain gorillas. Trekking to see them is strictly regulated; permits are limited. The forest is misty and dense; over 640 gorillas live here. The experience is emotional and expensive. Bwindi is a UNESCO site and one of the world''s premier primate destinations.' WHERE category = 'nature' AND title_en = 'Bwindi Impenetrable Forest';

UPDATE challenges SET description_en = 'Dong Phayayen-Khao Yai Forest Complex in Thailand is a UNESCO wildlife corridor linking several parks. Siamese crocodile, gaur, and Asiatic black bear are among the species. The area is important for conservation. Trekking and wildlife tours are available from Bangkok. It is one of Southeast Asia''s key forest ecosystems and a haven for rare species.' WHERE category = 'nature' AND title_en = 'Dong Phayayen Forest';

UPDATE challenges SET description_en = 'The Tasmanian Wilderness is a UNESCO World Heritage area of Gondwana-era rainforest, rivers, and unique wildlife including the Tasmanian devil and wombats. Cradle Mountain and the Overland Track are famous. Tasmania is Australia''s wild island. The wilderness is one of the last temperate ancient forests on Earth and a top destination for hikers and nature lovers.' WHERE category = 'nature' AND title_en = 'Tasmanian Wilderness';

UPDATE challenges SET description_en = 'Mount Kinabalu in Malaysian Borneo rises to 4,095 m, the roof of the island. Pitcher plants, rhododendrons, and endemic squirrels live on the slopes. The summit climb requires a permit and guide; it is achievable for fit hikers. Kinabalu Park is UNESCO-listed. The mountain is sacred and one of Southeast Asia''s most iconic peaks.' WHERE category = 'nature' AND title_en = 'Mount Kinabalu';

UPDATE challenges SET description_en = 'Mount Roraima is a table-top tepui on the Venezuela-Guyana-Brazil border. The plateau inspired Arthur Conan Doyle''s The Lost World. Trekking to the top takes several days; black frogs and carnivorous plants live there. The landscape is surreal. Roraima is one of the world''s most dramatic table mountains and a bucket-list trek for adventurers.' WHERE category = 'nature' AND title_en = 'Mount Roraima';

UPDATE challenges SET description_en = 'Namaqualand in South Africa is a desert that explodes in wildflowers each spring (August–September). Over 3,000 plant species, many endemic, turn the landscape orange and purple. The flower route draws visitors from around the world. Namaqualand is one of the world''s great floral spectacles and a must-see for botany and photography lovers.' WHERE category = 'nature' AND title_en = 'Namaqualand';

UPDATE challenges SET description_en = 'Lake Hillier in Western Australia is a pink lake next to the blue Indian Ocean. The colour comes from Dunaliella salina algae and is best seen from the air. Access is by boat or flight from Esperance. The lake is on Middle Island; the contrast with the sea is striking. Lake Hillier is one of the world''s most photogenic natural oddities.' WHERE category = 'nature' AND title_en = 'Lake Hillier';

UPDATE challenges SET description_en = 'Niagara Falls on the Canada-US border carries about 6 million cubic feet of water per minute. Maid of the Mist boats take you into the spray; illumination shows light the falls at night. The Canadian side offers the best views. Niagara is touristy but undeniably impressive. It is one of the world''s most famous waterfalls and a classic North American destination.' WHERE category = 'nature' AND title_en = 'Niagara Falls';

UPDATE challenges SET description_en = 'Plitvice Lakes in Croatia are a UNESCO site: 16 terraced lakes connected by cascades and surrounded by forest. Wooden boardwalks let you walk over the turquoise water. The park is one of Europe''s most beautiful. Visit in spring or autumn for fewer crowds. Plitvice is a must-see in Croatia and one of the world''s most stunning lake systems.' WHERE category = 'nature' AND title_en = 'Plitvice Lakes';

UPDATE challenges SET description_en = 'Hamelin Pool in Western Australia protects stromatolites, living structures built by cyanobacteria over 3 billion years. They are among the oldest life forms on Earth. The hypersaline bay preserves them. Boardwalks protect the site. Hamelin Pool is in Shark Bay, a UNESCO site. It is one of the most significant and humbling natural history sites in the world.' WHERE category = 'nature' AND title_en = 'Hamelin Pool';

UPDATE challenges SET description_en = 'Aconcagua in Argentina is the highest peak in the Americas at 6,962 m. The climb is technical and demands acclimatisation; condors soar in the thermals. Base camp and the normal route are in Mendoza province. Aconcagua is a mountaineering icon and one of the Seven Summits. Only experienced climbers should attempt it.' WHERE category = 'nature' AND title_en = 'Aconcagua';

UPDATE challenges SET description_en = 'Mount Vesuvius near Naples is the active stratovolcano that destroyed Pompeii in AD 79. A hike to the 1,281 m crater offers views of the Bay of Naples and the crater floor. The volcano is monitored; access can be restricted. Vesuvius is one of the world''s most famous and dangerous volcanoes and a key part of any visit to the Naples area.' WHERE category = 'nature' AND title_en = 'Mount Vesuvius';

UPDATE challenges SET description_en = 'Antelope Canyon in Arizona is a slot canyon on Navajo land, carved by water and wind into wave-like sandstone. Light beams pierce the narrow walls at midday. Tours are mandatory and respect the sacred site. Upper and Lower Antelope are the main sections. The canyon is one of the world''s most photographed natural formations and a spiritual place.' WHERE category = 'nature' AND title_en = 'Antelope Canyon';

UPDATE challenges SET description_en = 'The Aurora Borealis over Alaska is among the best in the world; Fairbanks sits under the aurora oval. Winter (September–April) offers long dark nights. Dog sledding, moose, and wolves add to the experience. Chena Hot Springs and remote lodges offer viewing. Alaska''s aurora is a bucket-list experience for anyone chasing the northern lights.' WHERE category = 'nature' AND title_en = 'Aurora Borealis Alaska';

UPDATE challenges SET description_en = 'Corcovado National Park on Costa Rica''s Osa Peninsula is one of the most biodiverse places on Earth. Tapirs, harpy eagles, and jaguars live in the rainforest. Access is by plane or boat; permits and guides are required. The park is remote and humid. Corcovado is a top destination for serious wildlife enthusiasts and one of the world''s last great lowland rainforests.' WHERE category = 'nature' AND title_en = 'Corcovado National Park';

UPDATE challenges SET description_en = 'Urho Kekkonen National Park in Finnish Lapland is a vast wilderness of golden eagles, wolverines, and reindeer herding by the Sami. Hiking and skiing trails cross the park; wilderness huts offer basic shelter. The park is part of the Sámi homeland. Urho Kekkonen is one of Europe''s largest national parks and a place for solitude and Arctic nature.' WHERE category = 'nature' AND title_en = 'Urho Kekkonen NP';

UPDATE challenges SET description_en = 'Dokdo Island (Dokdo) is a small volcanic island in the East Sea, administered by South Korea. It is known for pristine waters and seabird nesting. Access is restricted; boat tours from Ulleungdo are limited. The island is a symbol of national identity. It is one of East Asia''s most politically sensitive and naturally remote islands.' WHERE category = 'nature' AND title_en = 'Dokdo Island';

UPDATE challenges SET description_en = 'Hallasan on Jeju Island is South Korea''s highest peak and a UNESCO biosphere reserve. The volcano has a crater lake; endemic Jeju orchids and roe deer live on the slopes. Hiking to the summit is popular; the trail is well maintained. Hallasan is the centrepiece of Jeju''s natural and cultural landscape and a must-do for visitors to the island.' WHERE category = 'nature' AND title_en = 'Hallasan Volcano';

UPDATE challenges SET description_en = 'Paektu Mountain on the North Korea–China border is a sacred volcano with a crater lake, Cheonji. It is considered the spiritual heartland of Korea. Access from the North Korean side is tightly controlled; the Chinese side allows limited tourism. Paektu is one of the most politically and culturally significant mountains in East Asia.' WHERE category = 'nature' AND title_en = 'Paektu Mountain';

UPDATE challenges SET description_en = 'Mount Everest on the Nepal-Tibet border is the world''s highest peak at 8,849 m. The Khumbu region, Sherpa culture, prayer flags, and the Khumbu Icefall define the approach. Trekking to Base Camp is a major undertaking; climbing requires experience and permits. Everest is the ultimate symbol of human endeavour and one of the world''s most iconic mountains.' WHERE category = 'nature' AND title_en = 'Mount Everest';

UPDATE challenges SET description_en = 'Kangchenjunga on the India-Nepal border is the world''s third-highest peak. The remote trekking circuit passes through red panda and snow leopard habitat. The area is less crowded than Everest. Permits and guides are required. Kangchenjunga is one of the most pristine and challenging Himalayan destinations for trekkers and climbers.' WHERE category = 'nature' AND title_en = 'Kangchenjunga';

UPDATE challenges SET description_en = 'Ama Dablam in Nepal is often called the most beautiful mountain in the Himalayas. It is a technical climb; Sherpa support is standard. The peak is visible from the Everest trek. Ama Dablam is a mountaineering icon and one of the world''s most photogenic and demanding peaks. It is for experienced climbers only.' WHERE category = 'nature' AND title_en = 'Ama Dablam';

UPDATE challenges SET description_en = 'Mount Etna in Sicily is Europe''s most active volcano. Lava flows, ash clouds, and ski slopes coexist. Guided tours reach the craters; the Circumetnea railway circles the mountain. Etna is UNESCO-listed and a living laboratory of volcanology. It is one of the world''s most accessible and dramatic active volcanoes.' WHERE category = 'nature' AND title_en = 'Mount Etna';

UPDATE challenges SET description_en = 'The Gobi Desert in Mongolia and China is a vast desert of Flaming Cliffs (dinosaur eggs), Bactrian camels, and snow leopards in the mountains. Gers (yurts) and nomadic culture define the experience. Tours from Ulaanbaatar reach the dunes and canyons. The Gobi is one of the world''s great deserts and a top destination for adventure and wildlife.' WHERE category = 'nature' AND title_en = 'Gobi Desert';

UPDATE challenges SET description_en = 'Ngorongoro Crater in Tanzania is the world''s largest intact volcanic caldera. About 30,000 animals, including the rare black rhino, live on the floor. Lions, elephants, and flamingos are common. Safaris descend into the crater at dawn. Ngorongoro is UNESCO-listed and one of Africa''s most concentrated and spectacular wildlife destinations.' WHERE category = 'nature' AND title_en = 'Ngorongoro Crater';

UPDATE challenges SET description_en = 'The Okavango Delta in Botswana is a desert river delta: the Okavango River spreads into the Kalahari, creating water lilies, channels, and islands. Mokoro (dugout canoe) trips reveal hippos, leopards, and birds. Lodges and camps offer luxury and access. The delta is UNESCO-listed and one of the world''s most unique and wildlife-rich wetlands.' WHERE category = 'nature' AND title_en = 'Okavango Delta';

UPDATE challenges SET description_en = 'The Daintree Rainforest in Queensland is one of the world''s oldest tropical rainforests, about 135 million years. Cassowaries and green sea turtles live here. The forest meets the reef; Cape Tribulation is the gateway. Eco lodges and guided walks are available. The Daintree is UNESCO-listed and one of Australia''s most important and beautiful natural areas.' WHERE category = 'nature' AND title_en = 'Daintree Rainforest';

UPDATE challenges SET description_en = 'The Ganges River in India is sacred to Hindus. Dawn at the cremation ghats of Varanasi, sadhus, and ritual baths define the experience. The river is polluted but remains the spiritual heart of India. Boat rides and walking the ghats are essential. The Ganges is one of the world''s most culturally and spiritually significant rivers.' WHERE category = 'nature' AND title_en = 'Ganges River';

UPDATE challenges SET description_en = 'The Sacred Valley of the Incas in Peru runs from Cusco to Machu Picchu. Inca terraces, Andean condors, and traditional weavers fill the landscape. Ollantaytambo and Pisac are key sites. The valley is the gateway to Machu Picchu and one of the most historically and scenically rich regions in the Andes.' WHERE category = 'nature' AND title_en = 'Sacred Valley';

UPDATE challenges SET description_en = 'Uluru-Kata Tjuta in Australia''s Red Centre is sacred to the Anangu. Uluru changes colour at sunset; Kata Tjuta (the Olgas) is a second rock formation. Climbing Uluru is prohibited; walking the base and learning Anangu culture are encouraged. The area is UNESCO-listed. Uluru is one of the world''s most iconic and spiritual natural landmarks.' WHERE category = 'nature' AND title_en = 'Uluru-Kata Tjuta';

UPDATE challenges SET description_en = 'White Sands National Park in New Mexico is the world''s largest gypsum dune field. The dunes are blindingly white; kit fox and other species adapt to the harsh environment. The park is near the missile range; hours can vary. Sledding the dunes and sunset photography are popular. White Sands is one of America''s most surreal and beautiful desert landscapes.' WHERE category = 'nature' AND title_en = 'White Sands';

UPDATE challenges SET description_en = 'The Masai Mara in Kenya adjoins the Serengeti and hosts the Big Five year-round. The Great Migration river crossings (July–October) are legendary. Masai warriors and community conservancies are part of the experience. Safari lodges and camps range from budget to ultra-luxury. The Mara is one of Africa''s premier wildlife destinations and a bucket-list safari.' WHERE category = 'nature' AND title_en = 'Masai Mara';

UPDATE challenges SET description_en = 'The Sumatra Rainforest in Indonesia is one of the last places where orangutans, tigers, rhinos, and elephants coexist. Leuser National Park is the stronghold. Deforestation threatens the ecosystem; responsible ecotourism supports conservation. Trekking to see orangutans is a highlight. Sumatra is one of the world''s most important and endangered rainforests.' WHERE category = 'nature' AND title_en = 'Sumatra Rainforest';

UPDATE challenges SET description_en = 'Yosemite Valley in California is a granite cathedral: El Capitan, Half Dome, and the seasonal firefall draw climbers and photographers. The valley is the heart of Yosemite National Park. Crowds are heavy in summer; spring waterfalls and autumn colour are spectacular. Yosemite is a UNESCO site and the birthplace of modern rock climbing.' WHERE category = 'nature' AND title_en = 'Yosemite Valley';

UPDATE challenges SET description_en = 'Bryce Canyon in Utah is a forest of hoodoos: spire-shaped rocks in orange and pink. The world''s largest concentration of hoodoos is here, carved over 200,000 years. Sunrise and sunset from the rim are unforgettable. Hiking trails descend among the formations. Bryce is one of America''s most distinctive national parks and a photographer''s dream.' WHERE category = 'nature' AND title_en = 'Bryce Canyon';

UPDATE challenges SET description_en = 'Fjadrargljufur in Iceland is a 100 m deep canyon nicknamed the Dragon canyon; it featured in Game of Thrones. The hike is moderate; the views are dramatic. The canyon is in the south; access is by car. It has become one of Iceland''s most popular natural attractions. Visit early or late to avoid crowds.' WHERE category = 'nature' AND title_en = 'Fjadrargljufur Canyon';

UPDATE challenges SET description_en = 'Skocjan Caves in Slovenia are a UNESCO site: an underground canyon where the Reka River drops 160 m into the Earth''s crust. The scale is cathedral-like. Guided tours walk through the caves. The park is near the coast and Ljubljana. Skocjan is one of the world''s most impressive cave systems and a must-see in Slovenia.' WHERE category = 'nature' AND title_en = 'Skocjan Caves';

UPDATE challenges SET description_en = 'The Jeju Lava Tube in South Korea is part of a UNESCO natural heritage site: a 160 km network of tubes with 7,000-year-old stalagmites. Manjanggul is the main show cave. The island is volcanic; the tube is one of the longest in the world. Jeju is a popular domestic and international destination. The lava tube is a unique geological wonder.' WHERE category = 'nature' AND title_en = 'Jeju Lava Tube';

UPDATE challenges SET description_en = 'Glacier National Park in Montana is the Crown of the Continent: 700 lakes, grizzly bears, and mountain goats. Going-to-the-Sun Road crosses the park; hiking trails reach alpine meadows. The glaciers are shrinking but the scenery remains stunning. The park is a UNESCO biosphere reserve. Glacier is one of America''s most beautiful and wild national parks.' WHERE category = 'nature' AND title_en = 'Glacier National Park';

UPDATE challenges SET description_en = 'Jiuzhaigou in Sichuan is a valley of five-colour lakes, cascades, and pandas. Tibetan culture and alpine scenery define the area. The park is heavily visited; timed entry and shuttle buses manage crowds. Autumn brings the best colours. Jiuzhaigou is UNESCO-listed and one of China''s most famous and photogenic natural destinations.' WHERE category = 'nature' AND title_en = 'Jiuzhaigou';

UPDATE challenges SET description_en = 'Huanglong in Sichuan is a UNESCO site of multi-colour travertine pools in a mountain setting. Snow leopards and golden snub-nosed monkeys live in the area. The pools are formed by calcium carbonate deposits. Cable cars and walking paths access the valley. Huanglong is one of China''s most beautiful and unique natural landscapes.' WHERE category = 'nature' AND title_en = 'Huanglong';

UPDATE challenges SET description_en = 'Zhangjiajie in Hunan is the land of the Avatar mountains: quartzite-sandstone pillars that rise from the mist. The glass bridge and Bailong elevator are famous. The park inspired the floating mountains in the film Avatar. Crowds are significant. Zhangjiajie is one of China''s most dramatic and iconic natural wonders.' WHERE category = 'nature' AND title_en = 'Zhangjiajie';

UPDATE challenges SET description_en = 'Ha Long Bay in Vietnam is a UNESCO site: 2,000 limestone karsts rising from emerald water. Kayaking and boat cruises explore the bay; floating villages and caves are part of the experience. Overnight junks offer the best access. Ha Long is one of Vietnam''s top tourist destinations and one of the world''s most recognisable seascapes.' WHERE category = 'nature' AND title_en = 'Ha Long Bay';

UPDATE challenges SET description_en = 'Komodo National Park in Indonesia is home to the Komodo dragon, the world''s largest lizard. Pink sand beaches, manta rays, and the Wallace Line add to the appeal. The park is in the Lesser Sundas; access is by boat from Flores. Trekking to see dragons requires a guide. Komodo is UNESCO-listed and one of the world''s most unique wildlife destinations.' WHERE category = 'nature' AND title_en = 'Komodo National Park';

UPDATE challenges SET description_en = 'Mount Pinatubo in the Philippines erupted in 1991 in one of the 20th century''s largest eruptions. The crater is now a turquoise lake. A 4x4 and hike reach the crater; the landscape is otherworldly. The volcano is in Luzon. Pinatubo is a powerful reminder of volcanic force and a popular adventure destination.' WHERE category = 'nature' AND title_en = 'Mount Pinatubo';

UPDATE challenges SET description_en = 'Roraima Tepui is the same table mountain as Mount Roraima, on the Venezuela-Guyana-Brazil border. The Lost World plateau has carnivorous plants and black frogs. Multi-day treks from Venezuela or Guyana reach the top. Roraima is one of the world''s most dramatic and isolated landscapes and a bucket-list trek.' WHERE category = 'nature' AND title_en = 'Roraima Tepui';

UPDATE challenges SET description_en = 'Svalbard is a Norwegian archipelago in the High Arctic: polar bears, midnight sun, bird cliffs, and blue glaciers. Longyearbyen is the main settlement; expeditions go further. The Northern Lights appear in winter. Svalbard is one of the world''s last great wildernesses and a top destination for Arctic wildlife and adventure.' WHERE category = 'nature' AND title_en = 'Svalbard';

UPDATE challenges SET description_en = 'Franz Josef Glacier in New Zealand''s South Island descends from the Southern Alps into rainforest—a rare meeting of ice and rain. Heli-hikes and guided walks access the ice. The glacier has retreated but remains impressive. Franz Josef village is the base. The glacier is one of New Zealand''s most accessible and dramatic natural attractions.' WHERE category = 'nature' AND title_en = 'Franz Josef Glacier';

UPDATE challenges SET description_en = 'Perito Moreno Glacier in Argentina is one of the few advancing glaciers in the world. It calves thunderously into Lake Argentino. Viewing platforms and boat trips bring you close. The glacier is in Los Glaciares National Park, UNESCO-listed. Perito Moreno is one of the world''s most spectacular and accessible glaciers.' WHERE category = 'nature' AND title_en = 'Perito Moreno Glacier';

UPDATE challenges SET description_en = 'The Atacama Desert in Chile is the driest non-polar desert. Flamingos, geysers, and the ALMA telescope dot the landscape. Every 5–7 years a flower bloom carpets parts of the desert. San Pedro de Atacama is the base for Valle de la Luna and high-altitude lakes. The Atacama is one of the world''s most dramatic deserts.' WHERE category = 'nature' AND title_en = 'Atacama Desert';

UPDATE challenges SET description_en = 'The kakapo in Fiordland is the world''s only flightless parrot, nocturnal and critically endangered. It survives only on predator-free islands like Codfish. Viewing is highly restricted to protect the birds. The kakapo is a conservation icon and one of the world''s rarest and most charismatic birds. New Zealand''s Department of Conservation manages the recovery program.' WHERE category = 'nature' AND title_en = 'Kakapo Fiordland';

UPDATE challenges SET description_en = 'The Cordillera Blanca in Peru is the world''s highest tropical mountain range. Turquoise glacial lakes, condors, and trekking routes like the Santa Cruz draw adventurers. Huaraz is the gateway. The range is part of the Andes and offers some of the best alpine hiking and climbing in South America. It is one of the world''s most spectacular mountain ranges.' WHERE category = 'nature' AND title_en = 'Cordillera Blanca';

UPDATE challenges SET description_en = 'The Drakensberg Mountains in South Africa are UNESCO-listed for Bushman rock art and the Amphitheatre cliff. Cape vultures nest here. Hiking and climbing are popular; the uKhahlamba-Drakensberg Park protects the range. The Drakensberg is one of Africa''s most dramatic mountain landscapes and a top destination for hikers.' WHERE category = 'nature' AND title_en = 'Drakensberg Mountains';

UPDATE challenges SET description_en = 'Ayers Rock (Uluru) is the same monolith as Uluru-Kata Tjuta; the name Ayers Rock is the colonial designation. The Anangu prefer Uluru. The rock is sacred; sunrise pilgrimage and cultural tours are the way to experience it. Uluru is one of Australia''s most iconic landmarks and a UNESCO site.' WHERE category = 'nature' AND title_en = 'Ayers Rock (Uluru)';

UPDATE challenges SET description_en = 'The Great Blue Hole off Belize is a marine sinkhole 300 m across, with stalactites and bull sharks in crystal-clear water. It is a top dive site; flyovers show the perfect circle. Jacques Cousteau made it famous. The Blue Hole is one of the world''s most iconic dive sites and a natural wonder of the Caribbean.' WHERE category = 'nature' AND title_en = 'Great Blue Hole';

UPDATE challenges SET description_en = 'Hormuz Island in Iran is the Rainbow Island: colourful mineral soil and unique geology create red, orange, and yellow beaches. The red beach is famous. The island is in the Strait of Hormuz; access is by boat from Bandar Abbas. Hormuz is one of the Middle East''s most unusual and photogenic natural destinations.' WHERE category = 'nature' AND title_en = 'Hormuz Island';

UPDATE challenges SET description_en = 'The Marble Cave (and other Crimean caves) in Ukraine feature 2 km of galleries, crystal formations, and an underground lake. The Marble Cave is in the Chatyr-Dag massif. Tours are guided. The region has been affected by conflict; check travel advisories. The caves are among the most beautiful in Europe.' WHERE category = 'nature' AND title_en = 'Crimean Caves';

UPDATE challenges SET description_en = 'Aldabra Atoll in the Seychelles is a UNESCO site and one of the world''s largest atolls. It hosts about 200,000 giant tortoises—the largest population on Earth. The atoll is remote and largely undisturbed. Access is restricted; cruises and research permits allow visits. Aldabra is one of the world''s most pristine and important island ecosystems.' WHERE category = 'nature' AND title_en = 'Aldabra Atoll';

UPDATE challenges SET description_en = 'Punta Tombo in Argentina is the largest Magellanic penguin colony in the Americas: 500,000 penguins gather to breed. The reserve is on the Patagonian coast; September to April is the season. Walkways let you get close to the birds. Punta Tombo is one of the world''s best places to see penguins and a must for wildlife lovers.' WHERE category = 'nature' AND title_en = 'Punta Tombo';

UPDATE challenges SET description_en = 'Peninsula Valdes in Argentina is a UNESCO site: orcas beach-hunt seals, southern right whales calve in the bays, and Patagonian hares and guanacos roam. The peninsula is in Patagonia; Puerto Madryn is the gateway. Whale season is June–December. Peninsula Valdes is one of the world''s premier marine wildlife destinations.' WHERE category = 'nature' AND title_en = 'Peninsula Valdes';

UPDATE challenges SET description_en = 'Nagarhole National Park in Karnataka, India, is part of the Nilgiri biosphere. Indian leopards, Asiatic wild dogs (dhole), gaur, and elephants live in the coffee estate forests. Safari by jeep is the main way to see wildlife. Nagarhole is less crowded than some Indian parks and offers excellent biodiversity. It is one of South India''s best wildlife destinations.' WHERE category = 'nature' AND title_en = 'Nagarhole National Park';

UPDATE challenges SET description_en = 'The Annapurna Circuit in Nepal is one of the world''s great treks: 230 km through eight ecosystems, crossing the Thorung La pass at 5,416 m. Tea houses line the route; the scenery is Himalayan. The circuit takes two to three weeks. Annapurna is a bucket-list trek and one of the most rewarding long-distance hikes in the world.' WHERE category = 'nature' AND title_en = 'Annapurna Circuit';

UPDATE challenges SET description_en = 'Pulo Cinta Falls in the Philippines is a heart-shaped lake atop a Mindanao mountain, reached by remote trekking through jungle. The site is off the beaten path and rewards determined travellers. The Philippines has many hidden natural gems; Pulo Cinta is one of the most romantic and unusual. Visit with a local guide and respect the environment.' WHERE category = 'nature' AND title_en = 'Pulo Cinta Falls';

UPDATE challenges SET description_en = 'Champagne Pool in New Zealand''s Wai-O-Tapu thermal area is a geothermal pool with an orange rim, 74°C, and arsenic-rich edges. The name comes from the constant effervescence. The park has other colourful pools and geysers. Champagne Pool is one of the most photogenic geothermal features in the world and a highlight of the Taupo volcanic zone.' WHERE category = 'nature' AND title_en = 'Champagne Pool';

UPDATE challenges SET description_en = 'Taroko Gorge in Taiwan is a marble canyon carved by the Liwu River through the mountains of the east coast. The road and trails pass through tunnels and past temples. The gorge is the centrepiece of Taroko National Park. Spring and autumn are the best seasons. Taroko is one of Asia''s most spectacular gorges and a must-see in Taiwan.' WHERE category = 'nature' AND title_en = 'Taroko Gorge';

UPDATE challenges SET description_en = 'Waitomo Glowworm Caves in New Zealand host Arachnocampa luminosa: thousands of glowworms create a Milky Way on the cave ceiling. Boat rides drift through the dark under the bioluminescent display. The caves are on the North Island; tours are well organised. Waitomo is one of the world''s most magical and accessible glowworm experiences.' WHERE category = 'nature' AND title_en = 'Waitomo Glowworm Caves, New Zealand';

UPDATE challenges SET description_en = 'Mount Fuji is Japan''s iconic volcano, 3,776 m high and a UNESCO Cultural Heritage site. The symmetrical cone is reflected in Lake Kawaguchi; cherry blossoms frame it in spring. Climbing season is July–August. Fuji is sacred and artistic; it has inspired centuries of Japanese culture. It is one of the world''s most recognisable and revered mountains.' WHERE category = 'nature' AND title_en = 'Mount Fuji, Japan';

UPDATE challenges SET description_en = 'The Dead Sea between Jordan and Israel is the Earth''s lowest point on land, about 430 m below sea level. Salinity of around 34% allows effortless floating. Mineral-rich mud is used for therapy; the ecosystem is under threat from shrinking water. Resorts on both sides offer access. The Dead Sea is one of the world''s most unique and therapeutic natural phenomena.' WHERE category = 'nature' AND title_en = 'Dead Sea, Jordan';

UPDATE challenges SET description_en = 'Trolltunga (Troll''s Tongue) in Norway is a rock ledge 700 m above Lake Ringedalsvatnet. The 22 km round-trip hike is demanding; the photo is one of Norway''s most dramatic. Summer and early autumn are the best times. Trolltunga has become an icon of adventure travel and one of the world''s most famous viewpoints.' WHERE category = 'nature' AND title_en = 'Trolltunga, Norway';

UPDATE challenges SET description_en = 'Havasu Falls in Arizona is a series of turquoise travertine waterfalls on Havasupai tribal land in the Grand Canyon. A permit is required; the 16 km hike (or helicopter) each way is strenuous. The blue-green water and red rock are stunning. Havasu is one of America''s most beautiful and sought-after wilderness destinations. Book permits well in advance.' WHERE category = 'nature' AND title_en = 'Havasu Falls, Arizona';
