-- schema-v8.sql
-- Fix: attractions, foods, restaurants, golf (100 items each)
-- Sort: points DESC (rarest/best first), then title_en ASC within same tier
-- Points: 10=famous accessible, 15=special/remote/unique, 20=once-in-a-lifetime

DELETE FROM public.challenge_certifications WHERE challenge_id IN (
  SELECT id FROM public.challenges WHERE category IN ('attractions','foods','restaurants','golf')
);
DELETE FROM public.challenges WHERE category IN ('attractions','foods','restaurants','golf');

-- =============================================
-- ATTRACTIONS (20pt > 15pt > 10pt, then A-Z)
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('attractions','Angkor Wat','Angkor Wat','KH','World largest religious monument; 12th-century Khmer empire, 400+ temples',20),
('attractions','Bagan Temples','Bagan Temples','MM','2,000+ Buddhist temples at sunrise on Irrawaddy plain; drone-view spectacle',20),
('attractions','Great Wall of China','Great Wall of China','CN','21,196 km fortification; Ming-era Mutianyu section best preserved',20),
('attractions','Machu Picchu','Machu Picchu','PE','15th-century Inca citadel at 2,430m; Sun Gate trekking via Inca Trail',20),
('attractions','Petra','Petra','JO','Rose-red rock-cut city 2000 years old; Treasury Al-Khazneh at dawn',20),
('attractions','Pyramids of Giza','Pyramids of Giza','EG','Only surviving wonder of the ancient world; built c. 2560 BC',20),
('attractions','Sistine Chapel','Sistine Chapel & Vatican','VA','Michelangelo ceiling frescoes 1508-1512; Last Judgment altarpiece',20),
('attractions','Zhangjiajie Forest','Zhangjiajie National Forest Park','CN','Towering sandstone pillars inspiring Avatar; glass bridge, cable car',20),
('attractions','Abu Simbel','Abu Simbel Temples','EG','Ramesses II twin temples c.1264 BC UNESCO; relocated from Nile flooding',15),
('attractions','Alhambra','Alhambra Palace','ES','14th-century Moorish fortress-palace complex; intricate Nasrid plasterwork',15),
('attractions','Arashiyama Bamboo','Arashiyama Bamboo Grove','JP','Towering bamboo forest in Kyoto mountains; morning light ethereal walk',15),
('attractions','Borobudur','Borobudur Temple','ID','9th-century Buddhist stupa; world largest, 2,672 relief panels UNESCO',15),
('attractions','Cappadocia','Cappadocia','TR','Fairy chimneys and underground cities; hot air balloon at sunrise',15),
('attractions','Chichen Itza','Chichen Itza','MX','Pre-Columbian Maya city UNESCO; El Castillo equinox serpent shadow',15),
('attractions','Great Barrier Reef','Great Barrier Reef','AU','World largest coral system 2,300 km; visible from space, 1,500 species',15),
('attractions','Ha Long Bay','Ha Long Bay','VN','1,600+ limestone karst islands UNESCO; kayaking, floating villages',15),
('attractions','Hiroshima Dome','Hiroshima Peace Memorial (Genbaku Dome)','JP','A-Bomb Dome UNESCO peace symbol; deeply moving pilgrimage site',15),
('attractions','Jungfraujoch','Jungfraujoch Top of Europe','CH','Highest railway station 3,454m in Bernese Alps; glacier panorama',15),
('attractions','Komodo','Komodo National Park','ID','Komodo dragon habitat; pink sand Beach Pantai Merah, pristine reef',15),
('attractions','Maasai Mara','Maasai Mara National Reserve','KE','Big Five year-round; annual wildebeest river crossing July-October',15),
('attractions','Matterhorn','Matterhorn','CH','4,478m iconic pyramidal peak; Zermatt base, most photographed Alpine',15),
('attractions','Meteora','Meteora Monasteries','GR','Byzantine monasteries perched on rock pinnacles UNESCO; sunset views',15),
('attractions','Namib Desert Sossusvlei','Sossusvlei & Namib Desert','NA','Ancient desert 55M years; star dunes 300m, Dead Vlei ghost trees',15),
('attractions','Patagonia Torres','Torres del Paine Patagonia','CL','Granite tower trio W-trek; pumas, condors, glaciers, guanaco herds',15),
('attractions','Serengeti','Serengeti National Park','TZ','1.5 million wildebeest migration; UNESCO biosphere, endless savanna',15),
('attractions','Sigiriya','Sigiriya Rock Fortress','LK','5th-century citadel on 200m granite rock; frescoes, water gardens',15),
('attractions','Stone Forest','Stone Forest Shilin','CN','270 million-year-old karst pillars UNESCO; Sani Yi ethnic culture',15),
('attractions','Tanah Lot','Tanah Lot Temple','ID','Sea temple on rocky islet at sunset; Bali Hindu landmark, tidal access',15),
('attractions','Terracotta Warriors','Terracotta Army','CN','8,000 life-sized clay soldiers guarding Qin Shi Huang tomb in Xi''an',15),
('attractions','Uluru','Uluru (Ayers Rock)','AU','Sacred sandstone monolith 348m; Anangu cultural site, sunrise colour',15),
('attractions','Victoria Falls','Victoria Falls','ZW','World largest waterfall sheet 1,708m wide; Devil''s Pool swim at edge',15),
('attractions','Amalfi Coast','Amalfi Coast','IT','UNESCO-listed dramatic coastal cliffs; colourful villages, limoncello',10),
('attractions','Anne Frank House','Anne Frank House','NL','WWII hiding place museum Amsterdam; Anne''s diary original on display',10),
('attractions','Bali Rice Terraces','Jatiluwih Rice Terraces Bali','ID','UNESCO cultural landscape; subak irrigation system, green staircase',10),
('attractions','Blue Mosque','Sultan Ahmed Mosque (Blue Mosque)','TR','Ottoman masterpiece 1616; six minarets, 20,000 Iznik blue tiles',10),
('attractions','Brandenburg Gate','Brandenburg Gate','DE','18th-century neoclassical triumphal arch; Berlin reunification symbol',10),
('attractions','Burj Khalifa','Burj Khalifa','AE','World tallest building 828m; At the Top Sky outdoor observation deck',10),
('attractions','Chambord Castle','Chateau de Chambord','FR','Largest Loire Valley chateau; Leonardo da Vinci double-helix staircase',10),
('attractions','Christ Redeemer','Christ the Redeemer','BR','30m art deco Jesus on Corcovado 709m; panoramic Rio harbour view',10),
('attractions','Colosseum','Colosseum','IT','Ancient Roman amphitheater 70 AD; capacity 80,000, gladiatorial arena',10),
('attractions','Edinburgh Castle','Edinburgh Castle','GB','Historic fortress on volcanic rock; Crown Jewels, One O''clock Gun',10),
('attractions','Eiffel Tower','Eiffel Tower','FR','330m iron lattice tower 1889; 7 million visitors/year, night light show',10),
('attractions','Ephesus','Ephesus Ancient City','TR','One of best-preserved Greco-Roman ruins; Library of Celsus façade',10),
('attractions','Forbidden City','Forbidden City','CN','600-year-old imperial palace complex; 9,000+ rooms, moat and walls',10),
('attractions','Fushimi Inari','Fushimi Inari Taisha','JP','10,000 vermilion torii gates winding up Mount Inari; dawn hike',10),
('attractions','Golden Gate Bridge','Golden Gate Bridge','US','Iconic 1937 suspension bridge; walk across for bay and city views',10),
('attractions','Grand Canyon','Grand Canyon','US','1.6 km deep canyon 446 km long; South Rim sunset, Bright Angel hike',10),
('attractions','Grand Palace Bangkok','Grand Palace Bangkok','TH','Opulent royal complex; Wat Phra Kaew Emerald Buddha, Chakri Hall',10),
('attractions','Hagia Sophia','Hagia Sophia','TR','Byzantine 537 AD; dome 55m high, gold mosaics, now active mosque',10),
('attractions','Hoi An','Hoi An Ancient Town','VN','UNESCO trading port; Japanese bridge, lantern festival, tailors',10),
('attractions','Kinkaku-ji','Kinkaku-ji Golden Pavilion','JP','Zen Buddhist temple covered in gold leaf; reflected in Mirror Pond',10),
('attractions','Li River','Li River & Guilin','CN','Karst peak reflection cruise; Chinese 20-yuan banknote scenery',10),
('attractions','Louvre','Louvre Museum','FR','World largest museum 35,000 works; Mona Lisa, Venus de Milo',10),
('attractions','Masada','Masada Fortress','IL','Herod''s 1st-century fortress; Roman siege ramp, Dead Sea panorama',10),
('attractions','Moai Easter Island','Moai Statues Easter Island','CL','887 monolithic statues by Rapa Nui; Rano Raraku quarry, volcanic',10),
('attractions','Mont Saint-Michel','Mont Saint-Michel','FR','Tidal island medieval abbey UNESCO; pilgrim causeway, sand flats',10),
('attractions','Mount Fuji','Mount Fuji','JP','Japan iconic 3,776m stratovolcano; UNESCO, climbing season July-Sept',10),
('attractions','Neuschwanstein','Neuschwanstein Castle','DE','Fairy-tale Bavarian castle 1886; inspired Disney''s Sleeping Beauty',10),
('attractions','Niagara Falls','Niagara Falls','CA','Three waterfalls; Maid of the Mist boat, Journey Behind the Falls',10),
('attractions','Notre Dame','Notre Dame Cathedral','FR','Gothic masterpiece 1163; gargoyles, rose windows, reopened 2024',10),
('attractions','Pamukkale','Pamukkale Cotton Castle','TR','Thermal travertine white terraces; Hierapolis ruins, sacred pools',10),
('attractions','Park Guell','Park Guell','ES','Gaudi colourful mosaic park; dragon staircase, Barcelona views',10),
('attractions','Parthenon Acropolis','Parthenon & Acropolis','GR','Ancient Greek temple 5th century BC dedicated to Athena; hilltop',10),
('attractions','Piazza San Marco','Piazza San Marco','IT','Heart of Venice; St Mark''s Basilica Byzantine mosaics, pigeons',10),
('attractions','Pompeii','Pompeii','IT','Ancient Roman city under volcanic ash 79 AD; streets, frescoes intact',10),
('attractions','Prague Old Town','Prague Old Town Square','CZ','Astronomical Clock 1410; Tyn Church, colourful baroque buildings',10),
('attractions','Sagrada Familia','Sagrada Familia','ES','Gaudi unfinished basilica 1882-ongoing; 18 towers, UNESCO 2005',10),
('attractions','Santorini Caldera','Santorini Caldera','GR','Volcanic island; Oia blue-dome sunset, wine tasting, caldera cruise',10),
('attractions','Senso-ji','Senso-ji Temple','JP','Tokyo oldest and most colourful temple; Nakamise shopping street',10),
('attractions','Sheikh Zayed Mosque','Sheikh Zayed Grand Mosque','AE','World 3rd largest mosque; 82 domes, gold-leaf minarets, Abu Dhabi',10),
('attractions','Shwedagon Pagoda','Shwedagon Pagoda','MM','Gilded Buddhist stupa 2,500 years old; 326m, 27 tonnes of gold',10),
('attractions','Sphinx','Great Sphinx of Giza','EG','Limestone monolith 73m long; human-headed lion guarding Khafre',10),
('attractions','St Basil Cathedral','St Basil''s Cathedral','RU','Colourful onion-domed cathedral 1561; Red Square Moscow icon',10),
('attractions','St Peter Basilica','St Peter''s Basilica','VA','Renaissance masterpiece; Michelangelo''s dome, Pieta sculpture',10),
('attractions','Statue of Liberty','Statue of Liberty','US','Copper statue gift from France 1886; Liberty Island crown access',10),
('attractions','Stonehenge','Stonehenge','GB','Prehistoric stone circle c. 3000 BC; summer solstice sunrise alignment',10),
('attractions','Sydney Opera House','Sydney Opera House','AU','Jorn Utzon UNESCO expressionist design; Bennelong Point harbour',10),
('attractions','Taj Mahal','Taj Mahal','IN','White marble UNESCO mausoleum 1653; reflecting pool, inlaid gems',10),
('attractions','Tanah Lot Sunset','Tanah Lot Sunset Tour','ID','Bali sea temple sunset; traditional Kecak fire dance performance',10),
('attractions','Temple of Heaven','Temple of Heaven','CN','Imperial Ming-era sacrificial complex; echo wall, Hall of Prayer',10),
('attractions','Tokyo Skytree','Tokyo Skytree','JP','World tallest tower 634m; two observation decks, Tembo Galleria',10),
('attractions','Tower of London','Tower of London','GB','11th-century castle; Crown Jewels, Beefeater tour, raven legend',10),
('attractions','Uffizi Gallery','Uffizi Gallery','IT','Greatest Renaissance collection; Botticelli Birth of Venus, Raphael',10),
('attractions','Versailles Palace','Palace of Versailles','FR','Royal chateau; Hall of Mirrors, 800-hectare gardens fountain show',10),
('attractions','Victoria Peak HK','Victoria Peak Hong Kong','HK','Peak Tram to summit; city skyline night view, harbour panorama',10),
('attractions','Wailing Wall','Western Wall Jerusalem','IL','Judaism holiest prayer site; prayer notes in cracks, Old Jerusalem',10),
('attractions','Wat Pho','Wat Pho Temple of Reclining Buddha','TH','46m long 15m high gold Buddha; traditional Thai massage school',10),
('attractions','Yellowstone','Yellowstone National Park','US','World first national park; Old Faithful geyser, Grand Prismatic',10);

-- =============================================
-- FOODS (20pt > 15pt > 10pt, then A-Z)
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('foods','Fugu Puffer Fish','Fugu Puffer Fish','JP','Potentially lethal blowfish; licensed chef required, Tokyo Tsukiji area',20),
('foods','Hákarl Fermented Shark','Hakarl Fermented Greenland Shark','IS','Rotten shark 6 months buried; ammonia smell, acquired taste, Iceland tradition',20),
('foods','Kopi Luwak','Kopi Luwak Civet Coffee','ID','World most expensive coffee; beans from civet cat digestion, Bali farms',20),
('foods','Ortolan Bunting','Ortolan Bunting','FR','Illegal French delicacy; tiny songbird eaten whole under napkin, controversial',20),
('foods','Witchetty Grub','Witchetty Grub','AU','Aboriginal bush tucker; large wood-eating larva, nutty taste raw or roasted',20),
('foods','Balut Duck Embryo','Balut Duck Embryo','PH','Developing duck egg delicacy; street food Philippines, broth and crunch',15),
('foods','Beluga Caviar','Beluga Caviar','IR','World most expensive caviar; Caspian Sea sturgeon, pearl-grey, buttery',15),
('foods','Bird Nest Soup','Bird''s Nest Soup','CN','Edible swiftlet nest; harvested from cave walls, Chinese imperial delicacy',15),
('foods','Cuy Roasted Guinea Pig','Cuy Roasted Guinea Pig','PE','Andean Inca staple; whole roasted, crispy skin, Cusco and Quito markets',15),
('foods','Dom Perignon','Dom Perignon Champagne','FR','Prestige cuvee vintage; Epernay cellar tour, blanc and rose, 150+ years',15),
('foods','Durian','Durian King of Fruits','MY','Banned from hotels; complex flavor creamy custard, seasonal Penang feast',15),
('foods','Foie Gras','Foie Gras','FR','Force-fed duck or goose liver; Perigord region, pan-seared, Sauternes pairing',15),
('foods','Iberico Jamon','Iberico Ham','ES','Acorn-fed free-range black pig; Jabugo Extremadura, 36-month cure',15),
('foods','Japanese A5 Wagyu','A5 Wagyu Beef','JP','BMS12 highest marbling; Kobe, Matsusaka, Ohmi beef regions, melt-in-mouth',15),
('foods','Matsutake Mushroom','Matsutake Mushroom','JP','Rarest mushroom world; autumn pine forest, Japan price 2000 USD/kg',15),
('foods','Pata Negra Bellota','Pata Negra Jamon Bellota','ES','Iberian black-hoof pig; mountain air-cured 4 years, 48-hour tasting plate',15),
('foods','Perigord Black Truffle','Perigord Black Truffle','FR','Diamond of the kitchen; Perigord winter truffle, shaved on scrambled eggs',15),
('foods','Peyote Cactus','Peyote Cactus Ceremonial Meal','MX','Sacred Huichol indigenous; ceremonial only, legal for Wixaritari people',15),
('foods','Shark Fin Soup','Shark Fin Soup','HK','Chinese New Year banquet delicacy; traditional but controversial harvest',15),
('foods','Alaskan King Crab','Alaskan King Crab','US','Bering Sea red king crab; winter season, Dutch Harbor Alaska, 5kg legs',10),
('foods','Arancini','Arancini','IT','Sicilian fried stuffed rice balls; ragù, mozzarella, peas, street food Palermo',10),
('foods','Baklava','Baklava','TR','Phyllo pastry layers honey pistachios; Gaziantep capital of baklava Turkey',10),
('foods','Bibimbap','Bibimbap','KR','Korean mixed rice bowl; Dolsot hot stone pot, sesame oil, gochujang sauce',10),
('foods','Bouillabaisse','Bouillabaisse','FR','Marseille fishermen''s stew; rouille croutons, three fish minimum, saffron',10),
('foods','Brazilian Churrasco','Brazilian Churrasco','BR','Rodizio barbecue; 15+ cuts rotating skewers, Fogo de Chao experience',10),
('foods','Ceviche','Ceviche','PE','Fresh fish citrus cure; Lima Central restaurant, leche de tigre tiger milk',10),
('foods','Char Siu BBQ Pork','Char Siu BBQ Pork','HK','Cantonese glazed pork; four-character char siu bao, Causeway Bay',10),
('foods','Chimichanga','Chimichanga','MX','Deep-fried burrito; Arizona or Sonora origin debate, sour cream guac',10),
('foods','Chocolate Tasting','Valrhona Chocolate','FR','Tain-l''Hermitage factory tour; single-origin Madagascar 66%, Dulcey blond',10),
('foods','Congee','Congee Jook','HK','Silky rice porridge; preserved egg pork, Tim Ho Wan early morning dim sum',10),
('foods','Coq au Vin','Coq au Vin','FR','Braised chicken Burgundy wine; Paul Bocuse traditional recipe, Lyon bouchon',10),
('foods','Croissant','French Croissant','FR','Laminated butter pastry; Boulangerie Utopie Paris, bronze competition',10),
('foods','Doner Kebab','Doner Kebab','TR','Rotating meat spit; Karadeniz Pidecisi Istanbul, real beef lamb mix',10),
('foods','Eggs Benedict','Eggs Benedict','US','Hollandaise poached eggs; Delmonico''s New York claimed origin 1894',10),
('foods','Empanada','Empanada','AR','Stuffed pastry; Salta style ground beef olive hard egg, baked or fried',10),
('foods','Escargot','Escargot','FR','Garlic butter snails; Burgundy dozen in shells, aperitif at Paris bistro',10),
('foods','Fish and Chips','Fish and Chips','GB','Battered cod or haddock; Magpie Whitby best award, malt vinegar mushy peas',10),
('foods','Gelato','Gelato','IT','Italian ice cream less fat; Florence Gelateria dei Neri, pistaccio stracciatella',10),
('foods','Goulash','Hungarian Goulash','HU','Paprika beef stew; New York Cafe Budapest, gulyas kettle over fire',10),
('foods','Greek Mezze','Greek Mezze Spread','GR','Ouzo with shared plates; tzatziki, spanakopita, dolmades, feta, Santorini',10),
('foods','Haggis','Haggis','GB','Sheep offal oatmeal suet; Burns Night January 25, whisky pairing Scotland',10),
('foods','Injera Ethiopian','Injera with Wat','ET','Fermented teff flatbread; Addis Ababa communal platter, doro wat tibs',10),
('foods','Jerk Chicken','Jerk Chicken','JM','Scotch bonnet allspice marinated; Boston Bay Jamaica roadside pits',10),
('foods','Jollof Rice','Jollof Rice','GH','West Africa rice dish; Accra chop bars debate Ghana vs Nigeria',10),
('foods','Khachapuri','Khachapuri','GE','Georgian cheese bread boat; Adjarian egg-topped version, Tbilisi bakery',10),
('foods','Kimchi','Kimchi','KR','Fermented napa cabbage; UNESCO intangible heritage, with every Korean meal',10),
('foods','Laksa','Laksa','MY','Coconut curry noodle soup; Penang asam laksa sour tamarind, best hawker',10),
('foods','Lobster Roll','Maine Lobster Roll','US','Cold mayo lobster in toasted bun; Luke''s Lobster New York, Maine coast',10),
('foods','Lomo Saltado','Lomo Saltado','PE','Peruvian stir-fry; beef soy sauce tomatoes fries on rice, Lima fusion',10),
('foods','Masala Dosa','Masala Dosa','IN','Crispy rice crepe potato filling; MTR Bengaluru breakfast institution',10),
('foods','Mole Negro','Mole Negro','MX','Complex 30-ingredient sauce; Oaxaca chocolate chili turkey, Casa Oaxaca',10),
('foods','Momos','Momos','NP','Himalayan dumplings; Kathmandu street food, buff (buffalo) achar dip',10),
('foods','Moules Frites','Moules Frites','BE','Mussels in white wine; Chez Leon Brussels, 1kg pot, frites aioli',10),
('foods','Nasi Goreng','Nasi Goreng','ID','Indonesian fried rice; Warung Babi Guling Bali, fried egg kecap manis',10),
('foods','New England Clam Chowder','New England Clam Chowder','US','Cream potato clam soup; sourdough bread bowl Fisherman''s Wharf SF',10),
('foods','Pad Thai','Pad Thai','TH','Stir-fried rice noodles; Thip Samai Bangkok original, tamarind lime',10),
('foods','Paella','Paella Valenciana','ES','Saffron rice chicken rabbit; La Pepica Valencia beachside restaurant',10),
('foods','Pho','Pho Bo','VN','Beef bone broth rice noodles; Pho Gia Truyen Hanoi, star anise cinnamon',10),
('foods','Pierogi','Pierogi','PL','Stuffed dumplings potato cheese; Krakow Pierogi Krakowianka, fried butter',10),
('foods','Pizza Napoletana','Pizza Napoletana','IT','Wood-fired Neapolitan pizza; L''Antica Pizzeria da Michele Naples, margherita',10),
('foods','Ramen','Ramen','JP','Tonkotsu or shoyu broth; Ichiran Hakata original, chashu egg nori bamboo',10),
('foods','Rendang','Beef Rendang','ID','Slow-cooked coconut beef; Padang Minangkabau recipe, dry rendang style',10),
('foods','Roti Canai','Roti Canai','MY','Flaky flatbread dhal curry; Mamak stall Kuala Lumpur, 24-hour service',10),
('foods','Saltimbocca','Saltimbocca alla Romana','IT','Veal prosciutto sage Roman; Ristorante da Fortunato Rome, Frascati wine',10),
('foods','Samosa','Samosa','IN','Fried pastry potato peas; Old Delhi street, tamarind chutney and raita',10),
('foods','Satay','Satay','MY','Grilled skewers peanut sauce; Jalan Alor KL night market, beef chicken',10),
('foods','Seafood Paella','Seafood Paella','ES','Rice prawns mussels squid; La Barceloneta beach restaurant, bomba rice',10),
('foods','Smorgasbord','Swedish Smorgasbord','SE','Festive buffet; herring gravlax meatballs janssons temptation, julbord',10),
('foods','Som Tam','Som Tam Green Papaya Salad','TH','Mortar-pounded fresh papaya; Isaan spicy sour salty sweet, Chiang Mai',10),
('foods','Sushi Omakase','Sushi Omakase','JP','Chef''s choice sushi; Sukiyabashi Jiro Honten 2-Michelin, nigiri counter',10),
('foods','Tagine','Moroccan Tagine','MA','Slow clay pot lamb prunes; Fes medina restaurant, smen aged butter',10),
('foods','Takoyaki','Takoyaki','JP','Octopus ball snack; Dotonbori Osaka street, mayo bonito flakes dancing',10),
('foods','Tamal','Tamal','MX','Masa corn husk steamed; Oaxacan black bean mole, Christmas tamale fest',10),
('foods','Tandoori Chicken','Tandoori Chicken','IN','Yogurt spice marinated; Moti Mahal Delhi birthplace of dish, naan bread',10),
('foods','Tom Yum Goong','Tom Yum Goong','TH','Spicy sour prawn soup; lemongrass galangal kaffir lime leaves, Bangkok',10),
('foods','Tonkotsu Ramen','Hakata Tonkotsu Ramen','JP','12-hour pork bone broth; Shin-Shin Fukuoka, thin noodles, beni shoga',10),
('foods','Truffle Pasta','Truffle Pasta Alba','IT','White truffle season October; shaved over tajarin egg pasta, Piemonte',10),
('foods','Tsukemen','Tsukemen Dipping Ramen','JP','Cold noodles dipping in concentrated broth; Fuunji Shinjuku Tokyo',10),
('foods','Turkish Breakfast','Full Turkish Breakfast','TR','Weekend kahvalti; 20+ dishes, white cheese olives eggs simit honey',10),
('foods','Tzatziki','Tzatziki','GR','Cucumber yogurt garlic dip; Diporto Athens tavern, pita bread village salad',10),
('foods','Unagi Kabayaki','Unagi Kabayaki','JP','Grilled freshwater eel; Nodaiwa Tokyo, tare sauce, summer stamina food',10),
('foods','Wiener Schnitzel','Wiener Schnitzel','AT','Veal breaded crispy; Gasthaus Poschl Vienna, cranberry sauce preiselbeeren',10),
('foods','Xiaolongbao','Xiaolongbao Soup Dumplings','CN','Soup-filled pork dumplings; Din Tai Fung Taipei original, crab roe version',10),
('foods','Yakitori','Yakitori','JP','Charcoal-grilled chicken skewers; Torikizoku Tokyo all-110-yen original',10),
('foods','Zaatar Manakish','Zaatar Manakish','LB','Lebanese flatbread thyme olive oil; Bouchon Bakery Beirut morning',10),
('foods','Zongzi','Zongzi Dragon Boat Dumplings','CN','Glutinous rice bamboo leaf; Jiaxing most famous, Dragon Boat Festival',10);

-- =============================================
-- RESTAURANTS (20pt > 15pt > 10pt, then A-Z)
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('restaurants','El Bulli','El Bulli (Closed Legend)','ES','Ferran Adria molecular gastronomy; 5x World Best Restaurant, book required',20),
('restaurants','elBulli Foundation','elBulli 1846 Cala Montjoi','ES','Reborn as elBulli 1846; immersive food arts experience, Roses Catalonia',20),
('restaurants','Noma Copenhagen','Noma','DK','Rene Redzepi New Nordic cuisine; 4x World Best, closed Jan 2025 legacy',20),
('restaurants','Alain Ducasse Plaza','Alain Ducasse au Plaza Athenee','FR','3 Michelin stars Paris palace hotel; all-natural cuisine, gold decor',15),
('restaurants','Alchemist','Alchemist','DK','50-course holistic theatre dinner; Copenhagen art installations, 3 Michelin',15),
('restaurants','Allea','Alma de Cuba','PR','San Juan Romanesque church conversion; Pan-Caribbean cuisine, 100+ rum',15),
('restaurants','Atelier Joel Robuchon','L''Atelier de Joel Robuchon','JP','Tokyo 3-Michelin; open kitchen counter L-shape, seasonal kaiseki-French',15),
('restaurants','Azurmendi','Azurmendi','ES','Eneko Atxa Basque Country; 3 Michelin, eco greenhouse dining, garden walk',15),
('restaurants','Boragó','Boragó','CL','Rodolfo Guzmán Santiago; only Chilean endemic ingredients, Andean focus',15),
('restaurants','Brae','Brae','AU','Dan Hunter Birregurra farm-to-table; 30-acre organic farm Victoria',15),
('restaurants','Central','Central','PE','Virgilio Martinez Lima; altitude concept, ingredients 3 metres to 4,500m',15),
('restaurants','Disfrutar','Disfrutar','ES','Barcelona 3 Michelin; El Bulli alumni, avant-garde techniques surprise menu',15),
('restaurants','Dom','D.O.M.','BR','Alex Atala Sao Paulo; Amazon ingredients, alligator piranha on menu',15),
('restaurants','El Celler de Can Roca','El Celler de Can Roca','ES','3 brothers Girona; 3 Michelin, World Best 2013/2015, imagination tasting',15),
('restaurants','Eleven Madison Park','Eleven Madison Park','US','New York plant-based 3 Michelin; World Best 2017, Art Deco dining room',15),
('restaurants','Faviken','Faviken Magasinet (Closed)','SE','Magnus Nilsson remote Swedish; Jarpen 12-seat legendary, 2019 closure',15),
('restaurants','Frantzen','Frantzen','SE','Stockholm 3 Michelin; private dining townhouse, Nordic Japanese fusion',15),
('restaurants','Gaggan Anand','Gaggan Anand','TH','Bangkok 23-course emoji menu; progressive Indian cuisine, Asia Best',15),
('restaurants','Geranium','Geranium','DK','Copenhagen 3 Michelin World Best; Rasmus Kofoed, football stadium top floor',15),
('restaurants','Hiša Franko','Hisa Franko','SI','Ana Ros World Best Female; Kobarid Slovenia farm-to-table, foraging walks',15),
('restaurants','Hof van Cleve','Hof van Cleve','BE','Peter Goossens Kruishoutem; 3 Michelin Belgium, French-Belgian excellence',15),
('restaurants','Ikea Meatballs','N/A - Removed','SE','',10),
('restaurants','Kol','Kol','GB','Santiago Lastra London 1 Michelin; Mexican soul British ingredients',10),
('restaurants','La Maison Troisgros','La Maison Troisgros','FR','Roanne 3 Michelin 50+ years; French haute cuisine dynasty, Lyon nearby',15),
('restaurants','Lasserre','Le Grand Vefour','FR','Paris Palais Royal 1784; historic brasserie with celebrity name plaques',15),
('restaurants','Le Bernardin','Le Bernardin','US','New York 3 Michelin; Eric Ripert seafood temple, power lunch Wall Street',15),
('restaurants','Maido','Maido','PE','Mitsuharu Tsumura Nikkei Lima; Peruvian-Japanese 15-course, Asia Best',15),
('restaurants','Mirazur','Mirazur','FR','Mauro Colagreco Menton; World Best 2019, French Riviera cliff, garden',15),
('restaurants','Mugaritz','Mugaritz','ES','Andoni Aduriz Errenteria; 2 Michelin boundary-pushing 20+ course',15),
('restaurants','Narisawa','Narisawa','JP','Tokyo 2 Michelin; Yoshihiro Narisawa Satoyama Cuisine, soil bread served',15),
('restaurants','Nektar','Restaurant Gordon Ramsay','GB','Chelsea London 3 Michelin; Gordon Ramsay original flagship, beef wellington',15),
('restaurants','Osteria Francescana','Osteria Francescana','IT','Massimo Bottura Modena; 3 Michelin World Best 2016/2018, oops lemon tart',15),
('restaurants','Piazza Duomo','Piazza Duomo','IT','Enrico Crippa Alba; 3 Michelin, salad 21 31 41 ingredients, truffle season',15),
('restaurants','Pujol','Pujol','MX','Enrique Olvera Mexico City; mole madre 1000+ days, World Top 10',15),
('restaurants','Ristorante Cracco','Ristorante Cracco','IT','Carlo Cracco Milan Galleria; 1 Michelin, renovated 1800s arcade space',15),
('restaurants','Septime','Septime','FR','Paris affordable Neo-bistro; Bertrand Grebaut, natural wine, 11th arrond',15),
('restaurants','Seven Rooms Yamazaki','Sushi Saito','JP','Tokyo legendary 6-seat; Takashi Saito impossible reservation, counter',15),
('restaurants','Single Thread','SingleThread Farm','US','Healdsburg Sonoma 3 Michelin; farm inn, 11-course kaiseki-inspired menu',15),
('restaurants','Steirereck','Steirereck','AT','Vienna 2 Michelin City Park; Heinz Reitbauer Austrian regional ingredients',15),
('restaurants','The Fat Duck','The Fat Duck','GB','Heston Blumenthal Bray; 3 Michelin Sound of the Sea, nostalgia time travel',15),
('restaurants','The French Laundry','The French Laundry','US','Thomas Keller Yountville Napa; 3 Michelin, salmon cornets iconic opener',15),
('restaurants','The Test Kitchen','The Test Kitchen','ZA','Luke Dale Roberts Cape Town; molecular SA ingredients, wood-fire section',15),
('restaurants','Ultraviolet','Ultraviolet by Paul Pairet','CN','Shanghai 10-seat only; 20-course multi-sensory dinner, single seating',15),
('restaurants','Vendôme','Restaurant Vendome','DE','Joachim Wissler Bergisch Gladbach; 3 Michelin, woodland estate Bavaria',15),
('restaurants','Amber','Amber','HK','Richard Ekkebus Landmark hotel; 2 Michelin, sustainable luxury seafood',10),
('restaurants','Aponiente','Aponiente','ES','Angel Leon El Puerto de Santa Maria; 3 Michelin marine cuisine, sea greens',10),
('restaurants','Attica','Attica','AU','Ben Shewry Melbourne; native Australian ingredients, Ripponlea garden',10),
('restaurants','Benu','Benu','US','Corey Lee San Francisco 3 Michelin; Korean American tasting, 1000-year egg',10),
('restaurants','Bib Gourmand Ramen','Ichiran Ramen','JP','Hakata solo booth; 2 Michelin Bib, customize tonkotsu broth, pork belly',10),
('restaurants','Blue Hill at Stone Barns','Blue Hill at Stone Barns','US','Dan Barber Pocantico Hills; farm-to-table pioneer, no menu surprise',10),
('restaurants','Chez Panisse','Chez Panisse','US','Alice Waters Berkeley California; farm-to-table founding restaurant 1971',10),
('restaurants','Coi','Coi','US','San Francisco 2 Michelin; New California cuisine, seasonal garden-driven',10),
('restaurants','Cote','Cote Korean Steakhouse','US','New York Michelin; Korean BBQ fine dining hybrid, USDA prime dry-aged',10),
('restaurants','Cut by Nobu','Cut by Wolfgang Puck','US','Beverly Hills 45 Park Lane London; USDA prime wagyu beef temple',10),
('restaurants','Da Dong','Da Dong Roast Duck','CN','Beijing crispy thin-skin Peking duck; theatrical presentation, plum sauce',10),
('restaurants','Dinner by Heston','Dinner by Heston Blumenthal','GB','Mandarin Oriental London 2 Michelin; historic British recipes reimagined',10),
('restaurants','Din Tai Fung','Din Tai Fung','TW','Taipei original xiaolongbao; Michelin starred, 1 Michelin, 18 folds standard',10),
('restaurants','El Paraguas','El Paraguas','ES','Oviedo Asturias; oldest restaurant since 1698, fabada asturiana bean stew',10),
('restaurants','Ferdi','Ferdi','FR','Paris celebrity burger spot; wood-panelled toy collection, secret menu',10),
('restaurants','Flour + Water','Flour + Water','US','San Francisco pasta; fresh pasta Neapolitan pizza, Mission District',10),
('restaurants','Garden Court','Garden Court Palace Hotel','US','San Francisco dome; sourdough French toast, historic atrium breakfast',10),
('restaurants','Ginza Kyubey','Ginza Kyubey','JP','Tokyo sushi institution 1936; omakase counter 4F, toro belly treasure',10),
('restaurants','Gramercy Tavern','Gramercy Tavern','US','Danny Meyer New York; American seasonal cuisine James Beard Award',10),
('restaurants','Hakkasan','Hakkasan Mayfair','GB','London 1 Michelin Cantonese; Hakka noodles, dim sum, celebrity haunt',10),
('restaurants','Harbor City','Harbour City Dim Sum','HK','Hong Kong old school yum cha; trolley service, char siu siu mai har gau',10),
('restaurants','Jiro Roppongi','Sukiyabashi Jiro Roppongi','JP','Jiro Ono son branch; 3 Michelin, 20-piece omakase, advance booking',10),
('restaurants','Joel Robuchon Monaco','Joel Robuchon Restaurant Monaco','MC','2 Michelin Monte Carlo; Joel Robuchon legacy, pomme puree famous',10),
('restaurants','Kanoyama','Kanoyama','US','New York East Village Japanese; omakase counter, seasonal fish sourcing',10),
('restaurants','Katsuya','Katsuya by Starck','US','Philippe Starck LA sushi bar; black cod miso nobu-style, celebrity LA',10),
('restaurants','L Escargot','L''Escargot Montorgueil','FR','Paris historic snail restaurant 1832; escargot bourgignon Rue Montorgueil',10),
('restaurants','La Pergola','La Pergola','IT','Rome hilltop 3 Michelin; Heinz Beck Rome Cavalieri Hilton, pasta view',10),
('restaurants','Langan Brasserie','J Sheekey Atlantic Bar','GB','London Covent Garden; fresh oysters seafood fish pie, theatre crowd',10),
('restaurants','Laperouse','Laperouse','FR','Paris 1766 Seine salon; Napoleon III boudoir private rooms, languoustines',10),
('restaurants','Masa','Masa','US','New York 3 Michelin; Masa Takayama most expensive US tasting counter',10),
('restaurants','Matsuhisa','Nobu Matsuhisa Beverly Hills','US','Original Nobu 1994; black cod miso yellowtail jalapeño invented here',10),
('restaurants','Merrion Hotel','Chapter One','IE','Dublin 1 Michelin; Parnell Square basement French-Irish seasonal tasting',10),
('restaurants','Mezze Restaurant','Taverna Sigalas','GR','Santorini vineyard taverna; fresh catch grilled, sunset with Assyrtiko wine',10),
('restaurants','Minetta Tavern','Minetta Tavern','US','New York West Village; Black Label Burger legendary, cast iron panfried',10),
('restaurants','Momofuku Ko','Momofuku Ko','US','David Chang New York 2 Michelin; counter tasting, inventive American',10),
('restaurants','Narisawa Nature','Narisawa Nature Harmony','JP','Tokyo 2 Michelin; forest floor bread plate, Satoyama essence concept',10),
('restaurants','Nobu Tokyo','Nobu Tokyo','JP','Minato-ku; Nobu Matsuhisa original Japan, wagyu anticuchos, miso black cod',10),
('restaurants','Old Fishmarket','Old Fishmarket Direct','DK','Copenhagen fresh catch; whole fish grilled, Gammel Strand canalside',10),
('restaurants','Palomar','The Palomar','GB','London Jerusalem-style; modern Israeli shuk food, SoHo, shakshuka cod',10),
('restaurants','Pampas','Pampas Argentina','AR','Buenos Aires asado; Palermo open fire pit, provolone, Malbec from barrel',10),
('restaurants','Pialligo Estate','Pialligo Estate','AU','Canberra farmhouse; smoked charcuterie, truffle farm season June-August',10),
('restaurants','Quintonil','Quintonil','MX','Jorge Vallejo Mexico City; modern Mexican native plants, Polanco area',10),
('restaurants','Roka','Roka Charlotte Street','GB','London Japanese robatayaki; cedar wood counter grill, corn fed chicken',10),
('restaurants','Saison','Saison','US','San Francisco 3 Michelin; open hearth live-fire wood, seasonal seafood',10),
('restaurants','Sennyo','Senn','JP','Kyoto kaiseki; seasonal ryokan dinner tofu course, shoyu ponzu clear dashi',10),
('restaurants','Sichuan House','Yu''s Family Kitchen','CN','Chengdu authentic Sichuan; fiery mapo tofu, dan dan noodles, Sichuan pepper',10),
('restaurants','Sketch','Sketch London','GB','Mourad Mazouz London; 5 restaurants one building, The Egg pod toilets',10),
('restaurants','Sukiyabashi Jiro','Sukiyabashi Jiro Honten','JP','Jiro Ono 3 Michelin 10-seat; Ginza basement, Obama dining, Jiro Dreams',10),
('restaurants','Sushi Yoshitake','Sushi Yoshitake','JP','Tokyo 3 Michelin; Masahiro Yoshitake, premium tuna sourcing, Ginza level',10),
('restaurants','Taian Table','Taian Table','CN','Stefan Stiller Shanghai 2 Michelin; German-Chinese fusion, Yanping Road',10),
('restaurants','Tim Raue','Tim Raue','DE','Berlin 2 Michelin; Asian-influenced Berlin cuisine, Rudi Dutschke Strasse',10),
('restaurants','Tipo 00','Tipo 00','AU','Melbourne pasta; fresh handmade Italian, Bourke Street, cacio e pepe',10),
('restaurants','Tofuya Ukai','Tofuya Ukai','JP','Tokyo kaiseki tofu; Shiba Park location, seasonal tofu courses, garden',10),
('restaurants','Ultraviolet 1','Ultraviolet Experience 1','CN','Paul Pairet Shanghai; 20-course wine pairing, single table world famous',10),
('restaurants','Zuma','Zuma','GB','London Japanese izakaya; Knightsbridge, robata grill sashimi sake bar',10);

-- =============================================
-- GOLF COURSES (20pt > 15pt > 10pt, then A-Z)
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('golf','Augusta National','Augusta National Golf Club','US','Masters Tournament home; Amen Corner 11-12-13, only 300 members, invite-only',20),
('golf','Cypress Point','Cypress Point Club','US','Pebble Beach Carmel; 16th over Pacific Ocean, most beautiful hole world',20),
('golf','Pine Valley','Pine Valley Golf Club','US','Clementon NJ; consistently world No.1 course, private all-sand waste areas',20),
('golf','St Andrews Old','St Andrews Old Course','GB','Home of Golf 600 years; Road Hole 17th, Swilcan Bridge, Open Championship',20),
('golf','Shinnecock Hills','Shinnecock Hills Golf Club','US','Southampton NY 1891; US Open host, links-style coastal, deep rough',15),
('golf','Ballybunion Old','Ballybunion Golf Club Old Course','IE','County Kerry Atlantic links; considered best links world, sand dunes',15),
('golf','Cape Kidnappers','Cape Kidnappers','NZ','Hawke''s Bay cliffs; Tom Doak design, 230m above Pacific Ocean, helicopte',15),
('golf','Carnoustie','Carnoustie Golf Links','GB','Scotland Championship; most feared Open links, Barry Burn 18th, wind',15),
('golf','Hirono','Hirono Golf Club','JP','Japan No.1; 1932 Charles Alison design Kobe, private, hardest to access',15),
('golf','Kingsbarns','Kingsbarns Golf Links','GB','Fife Scotland; sea views all 18 holes, 2001 Kidd design, St Andrews neighbor',15),
('golf','Lahinch','Lahinch Golf Club','IE','Clare Atlantic coast; goats weather forecast, Dell blind par 3, links',15),
('golf','Muirfield','The Honourable Company of Edinburgh Golfers','GB','East Lothian; oldest golf club 1744, Open Championship, traditional figure',15),
('golf','Oakmont','Oakmont Country Club','US','Pittsburgh PA; hardest US Open course, church pew bunkers, fast greens',15),
('golf','Pebble Beach','Pebble Beach Golf Links','US','Carmel California; 18th cliff edge Pacific, public play possible, US Open',15),
('golf','Port Rush','Royal Portrush Golf Club','GB','Northern Ireland Antilles; 148th Open 2019, Dunluce links, Calamity Corner',15),
('golf','Prestwick','Prestwick Golf Club','GB','Scotland 1851; 12 original Open Championships held here, historic links',15),
('golf','Royal Birkdale','Royal Birkdale Golf Club','GB','Southport England; Open Championship host, willow scrub, links champion',15),
('golf','Royal County Down','Royal County Down Golf Club','IE','Newcastle Northern Ireland; Mourne Mountains backdrop, considered No.1 links',15),
('golf','Royal Dornoch','Royal Dornoch Golf Club','GB','Scottish Highlands remote; Tom Watson called greatest natural course',15),
('golf','Royal Lytham','Royal Lytham & St Annes','GB','Lancashire England; 206 bunkers, red-brick houses, Open Championship host',15),
('golf','Royal Melbourne','Royal Melbourne Golf Club','GB','Victoria Australia; composite West/East for Pres Cup, sand belt native',15),
('golf','Royal Troon','Royal Troon Golf Club','GB','South Ayrshire Scotland; Postage Stamp 8th tiny par 3, Open history',15),
('golf','Sand Hills','Sand Hills Golf Club','US','Mullen Nebraska; Coore/Crenshaw masterpiece, Sandhills prairie natural',15),
('golf','Seminole','Seminole Golf Club','US','North Palm Beach Florida; Donald Ross 1929, ocean breezes, legendary',15),
('golf','Turnberry Ailsa','Trump Turnberry Ailsa Course','GB','Ayrshire Scotland; lighthouse view, duel in sun Watson/Nicklaus 1977 Open',15),
('golf','Whistling Straits','Whistling Straits','US','Wisconsin Kohler; 2020 Ryder Cup, Pete Dye design along Lake Michigan',15),
('golf','Winged Foot','Winged Foot Golf Club','US','Mamaroneck NY; US Open 1929/1959/1974/2020, narrow fairways tight rough',15),
('golf','Aberdovey','Aberdovey Golf Club','GB','Wales links; James Braid design 1892, estuary and dune holes, history',10),
('golf','Bandon Dunes','Bandon Dunes Golf Resort','US','Oregon Pacific coast; 5 courses Mike Keiser, walking-only traditional',10),
('golf','Black Diamond Ranch','Black Diamond Ranch','US','Florida Quarry; sink holes natural limestone ravines, Tom Fazio unique',10),
('golf','Caves Valley','Caves Valley Golf Club','US','Maryland Baltimore; 2021 BMW Championship host, Rees Jones design',10),
('golf','Chung Shan Hot Spring','Chung Shan Hot Spring Golf Club','CN','Guangdong Arnold Palmer; 1984 first professional China course, resort',10),
('golf','Colonial','Colonial Country Club','US','Fort Worth Texas; Colonial National Invitational, Ben Hogan tribute course',10),
('golf','Congressional','Congressional Country Club','US','Bethesda Maryland; US Open 1964/1997/2011, power and accuracy required',10),
('golf','Coore Crenshaw Sand Hills','Prairie Club','US','Valentine Nebraska; Coore Crenshaw dunes course, high plains prairie',10),
('golf','Cruden Bay','Cruden Bay Golf Club','GB','Aberdeenshire; remote wild links Bullers of Buchan, Finglassie quirky holes',10),
('golf','Desert Highlands','Desert Highlands Golf Club','US','Scottsdale Arizona; Jack Nicklaus mountain desert course, Pinnacle Peak',10),
('golf','Diamond Country Club','Diamond Country Club','AT','Atzenbrugg Austria; European tour venue 2021, Nick Faldo design award',10),
('golf','East Lake','East Lake Golf Club','US','Atlanta Georgia; Tour Championship finale, Bobby Jones home course',10),
('golf','El Saler','El Saler Golf Club','ES','Valencia Spain; Javier Arana design, Mediterranean dunes, Albufera lake',10),
('golf','Emirates Golf Club','Emirates Golf Club Majlis','AE','Dubai; first floodlit tournament 1989, Desert Classic host, skyline views',10),
('golf','Estancia','Estancia Club','US','Scottsdale Arizona; Tom Fazio private mountain hillside, saguaro cacti',10),
('golf','Falsterbo','Falsterbo Golf Club','SE','Sweden oldest links 1909; Baltic sea peninsula, migratory birds, flat',10),
('golf','Friars Head','Friars Head','US','Riverhead Long Island NY; Tom Coore design, heathland style, private',10),
('golf','Garden City','Garden City Golf Club','US','Long Island NY; 1899 Devereux Emmet, original design preserved classic',10),
('golf','Gary Player Country Club','Gary Player Country Club','ZA','Sun City South Africa; Nedbank Golf Challenge, Lost City landscape',10),
('golf','Glen Abbey','Glen Abbey Golf Club','CA','Oakville Ontario; Jack Nicklaus design, Canadian Open host, ravine 11-15',10),
('golf','Gleneagles PGA','Gleneagles PGA Centenary','GB','Perthshire Scotland; 2014 Ryder Cup, James Braid/Jack Nicklaus, resort',10),
('golf','Harbour Town','Harbour Town Golf Links','US','Hilton Head South Carolina; Pete Dye lighthouse par 4 18th, RBC Heritage',10),
('golf','Highlands Links','Highlands Links','CA','Cape Breton NS Canada; Stanley Thompson masterpiece, top in Canada',10),
('golf','Hillside','Hillside Golf Club','GB','Southport England; links neighbor to Birkdale, Ryder Cup qualifier style',10),
('golf','Kingston Heath','Kingston Heath Golf Club','AU','Melbourne sand belt; Alister MacKenzie bunkering, considered No.1 Australia',10),
('golf','Kiawah Island Ocean','Kiawah Island Ocean Course','US','South Carolina Pete Dye; 1991 War on Shore Ryder Cup, 10 coastal holes',10),
('golf','Ko Olina','Ko Olina Golf Club','US','Oahu Hawaii; Ted Robinson design, trade wind challenges, resort paradise',10),
('golf','La Quinta Mountain','La Quinta Mountain Course','US','Coachella Valley Pete Dye design; Stadium Course Tournament of Champions',10),
('golf','Loch Lomond','Loch Lomond Golf Club','GB','Scottish Highlands; Tom Weiskopf/Jay Morrish, Bonnie Banks Highland cow',10),
('golf','Los Angeles Country Club','Los Angeles Country Club North','US','Beverly Hills rare 2023 US Open; Gil Hanse restoration private historic',10),
('golf','Macrihanish','Machrihanish Golf Club','GB','Kintyre Peninsula remote; Mull of Kintyre links, Paul McCartney neighbour',10),
('golf','Madison Club','The Madison Club','US','La Quinta California; Tom Fazio private desert mountain, high-end resort',10),
('golf','Maidstone','Maidstone Club','US','East Hampton Long Island; original links 1891, National Golf Links neighbor',10),
('golf','Meridian','Meridian Golf Club','US','Illinois John Fought design; private, challenging natural Midwestern terrain',10),
('golf','Merion East','Merion Golf Club East','US','Ardmore PA; 2013 US Open, Old Red Books baskets, smallest major venue',10),
('golf','Mid-Ocean','Mid Ocean Club','BM','Tucker''s Town Bermuda; 1921 Charles Blair Macdonald, Atlantic holes unique',10),
('golf','Muirheld Village','Muirfield Village Golf Club','US','Dublin Ohio; Jack Nicklaus design for Memorial Tournament, tree-lined',10),
('golf','National Golf Links','National Golf Links of America','US','Southampton Long Island; 1909 CB Macdonald, Peconic Bay, golf pilgrimage',10),
('golf','New South Wales','New South Wales Golf Club','AU','Sydney; Alister MacKenzie clifftop, Botany Bay views, wind factor',10),
('golf','Nine Bridges','Nine Bridges Golf Club','KR','Jeju Island Korea; 9 traditional bridges over streams, autumn foliage',10),
('golf','Osaka Golf Club','Osaka Golf Club Sotonoike','JP','1930 Osaka course; Japan vintage traditional course, Harland Bartholomew',10),
('golf','Pacific Dunes','Pacific Dunes','US','Bandon Oregon; Tom Doak design links-style, ocean ravines, public',10),
('golf','Palm Beach Par 3','Palm Beach Par 3 Golf Course','US','Florida ocean holes; oceanfront par-3 course sunrise tradition 9-holes',10),
('golf','Paraparaumu Beach','Paraparaumu Beach Golf Club','NZ','Wellington links; considered NZ best, Cook Strait views, natural dunes',10),
('golf','Point Grey','Point Grey Golf and Country Club','CA','Vancouver BC; 1923 private, Pacific Rim mountains ocean backdrop',10),
('golf','Portmarnock','Portmarnock Golf Club','GB','Dublin Ireland; 1894 island links, wind all directions, Emerald Isle',10),
('golf','Prairie Dunes','Prairie Dunes Country Club','US','Hutchinson Kansas; Perry Maxwell wild prairie grass, US Women''s Open',10),
('golf','Punta Espada','Punta Espada Golf Club','DO','Cap Cana Dominican Republic; Jack Nicklaus oceanside Caribbean resort',10),
('golf','Riviera','Riviera Country Club','US','Pacific Palisades LA; Genesis Open Bing Crosby history, Kikuyu grass',10),
('golf','Shoreacres','Shoreacres Club','US','Lake Bluff Illinois; 1921 Seth Raynor, Skokie bluffs ravines, private',10),
('golf','Somerset Hills','Somerset Hills Country Club','US','Bernardsville NJ; A.W. Tillinghast 1917, rolling wooded New Jersey terrain',10),
('golf','Southern Hills','Southern Hills Country Club','US','Tulsa Oklahoma; 2022 PGA Championship, Donald Ross/Gil Hanse renovation',10),
('golf','Spyglass Hill','Spyglass Hill Golf Course','US','Pebble Beach; Robert Trent Jones, AT&T Pro-Am, forest meets ocean holes',10),
('golf','St George''s','Royal St George''s Golf Club','GB','Sandwich Kent England; Open Championship oldest host, Prince''s neighbor',10),
('golf','Sunningdale Old','Sunningdale Golf Club Old Course','GB','Berkshire heathland; Willie Park Jr 1900, John Jacobs Tiger Woods perfect round',10),
('golf','The Concession','The Concession Golf Club','US','Bradenton Florida; Jack Nicklaus/Tony Jacklin Ryder Cup story course',10),
('golf','TPC Sawgrass','TPC Sawgrass Players Stadium','US','Ponte Vedra Florida; island green 17th hole par 3, THE PLAYERS host',10),
('golf','Trump International Doonbeg','Trump International Doonbeg','IE','County Clare Ireland; Greg Norman linksland, White Strand beach holes',10),
('golf','Vale do Lobo Royal','Vale do Lobo Royal Golf Course','PT','Algarve Portugal; clifftop par 3 16th over ravine, resort Atlantic views',10),
('golf','Valderrama','Real Club Valderrama','ES','Andalucia Spain; Ryder Cup 1997, cork oak trees 17th water, Seve legacy',10),
('golf','Wannamoisett','Wannamoisett Country Club','US','Rumford Rhode Island; Donald Ross 1931, tight tree-lined par-70 challenge',10),
('golf','Waterville','Waterville Golf Links','IE','County Kerry Atlantic; Ring of Kerry view, Mass Hole par 3, Jack Nicklaus',10),
('golf','Westchester','Westchester Country Club West','US','Harrison NY; 1922 Walter Travis design, BMW Championship former host',10),
('golf','Wolf Creek','Wolf Creek Golf Club','US','Mesquite Nevada; desert red rock canyon, dramatic elevation changes',10),
('golf','Yale','Yale Golf Course','US','New Haven Connecticut; 1926 CB Macdonald/Seth Raynor, Lake Mamanasco',10);

-- Supplement: additional items to reach exactly 100 per category
-- Remove the placeholder restaurant row
DELETE FROM public.challenges WHERE title_en = 'N/A - Removed';

-- Attractions extras (+11)
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('attractions','Iguazu Falls','Iguazu Falls','AR','275 waterfalls spanning 2.7 km; wider than Niagara, jaguar territory walks',15),
('attractions','Angkor Thom','Angkor Thom Bayon','KH','Khmer Empire walled city; 54 towers each with four giant stone faces',10),
('attractions','Batu Caves','Batu Caves','MY','Hindu cave temples; 272 steps, Lord Murugan 43m gold statue, Thaipusam',10),
('attractions','Halong Village','Cat Ba Island Halong Bay','VN','Floating fishing village; limestone karst overnight cruise, sunrise mist',10),
('attractions','Jeju Island','Jeju Island','KR','UNESCO volcanic island; Hallasan hiking, Lava tubes, Seongsan sunrise',10),
('attractions','Khajuraho','Khajuraho Temples','IN','10th-century erotic temple carvings; UNESCO, Madhya Pradesh, sacred art',10),
('attractions','Mesa Verde','Mesa Verde National Park','US','Cliff Palace Ancestral Puebloan dwellings; 700-year-old cave city Colorado',10),
('attractions','Mont Blanc','Mont Blanc','FR','Western Europe highest peak 4808m; Aiguille du Midi cable car, Chamonix',10),
('attractions','Skellig Michael','Skellig Michael','IE','6th-century beehive monk cells on island peak; UNESCO, Star Wars filming',15),
('attractions','Salar Uyuni','Salar de Uyuni','BO','World largest salt flat 12,000 km2; mirror effect rainy season, train graveyard',15),
('attractions','Waitomo Caves','Waitomo Glowworm Caves','NZ','Bioluminescent glowworm caverns; boat through underground starry ceiling',10);

-- Foods extras (+13)
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('foods','Acai Bowl','Acai Bowl','BR','Amazon acai berry frozen bowl; Rio de Janeiro beach kiosk, granola honey',10),
('foods','Birria Tacos','Birria Tacos','MX','Jalisco stewed goat taco; consomme dipping broth, blue corn tortilla',10),
('foods','Bunny Chow','Bunny Chow','ZA','Durban Indian curry bread bowl; hollowed white loaf, mutton or bean',10),
('foods','Currywurst','Currywurst','DE','Berlin sausage ketchup curry powder; Curry 36 Kreuzberg institution',10),
('foods','Feijoad','Feijoada','BR','Black bean slow-cooked pork stew; Saturday lunch tradition Rio Bahia',10),
('foods','Fugu Shirako','Fugu Shirako','JP','Puffer fish milt (sperm sac); hotpot or grilled, sake pairing Tokyo',15),
('foods','Hu Tieu','Hu Tieu Nam Vang','VN','Cambodian-style clear broth noodles; Ho Chi Minh City Cho Lon pork offal',10),
('foods','Indomie Goreng','Indomie Mi Goreng','ID','World most popular instant noodle; fried version Bali roadside warung',10),
('foods','Katsudon','Katsudon','JP','Tonkatsu egg rice bowl; Ginza Bairin Tokyo, crispy pork cutlet soy mirin',10),
('foods','Khao Niao Mamuang','Khao Niao Mamuang (Mango Sticky Rice)','TH','Summer dessert Chiang Mai market; Kao Niew Ma Muang sticky coconut',10),
('foods','Lamington','Lamington','AU','Sponge cake chocolate desiccated coconut; Queensland state cake, tea time',10),
('foods','Nasi Lemak','Nasi Lemak','MY','Malaysia national dish coconut rice; Jalan Masjid India KL, ikan bilis sambal',10),
('foods','Poutine','Poutine','CA','Quebec fries cheese curds gravy; La Banquise Montreal 24hr, beer pairing',10);

-- Golf extras (+8)
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('golf','Ballesteros Designed','Real Club de Golf de Pedrena','ES','Seve Ballesteros home course Cantabria; Bay of Santander links-style',10),
('golf','Canyon Crest','Canyon Crest Country Club','US','Riverside California; private hills valley views, Thomas Nicoll Jr design',10),
('golf','Cape Cornwall','Cape Cornwall Golf Club','GB','UK westernmost golf; Land''s End peninsula, Atlantic views, 9-holes traditional',10),
('golf','Crans-sur-Sierre','Crans-sur-Sierre Golf Club','CH','Swiss Alps 1,500m elevation; European Masters host, Matterhorn backdrop',10),
('golf','Durban Country Club','Durban Country Club','ZA','South Africa 1920; George Waterman design, Indian Ocean views, Open host',10),
('golf','Fancourt Links','Fancourt Links','ZA','Outeniqua Mountains George; Ernie Els design, Presidents Cup 2003 venue',10),
('golf','Leopard Creek','Leopard Creek Country Club','ZA','Kruger Park border; crocodiles hippos on holes 3-5, Alfred Dunhill venue',15),
('golf','Pelican Hill','Pelican Hill Golf Club','US','Newport Beach California; Robert Trent Jones Jr Pacific Ocean ocean views',10);

-- Final 1 item per category to reach exactly 100 each
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('attractions','Lascaux Caves','Lascaux Cave Paintings','FR','17,000-year-old Paleolithic art; reproduction Lascaux IV centre, Dordogne',15),
('foods','Oysters','Fresh Pacific Oysters','AU','Sydney Rock and Pacific varieties; Coffin Bay SA, lemon & Tabasco shucked',10),
('restaurants','Wolfgat','Wolfgat','ZA','Paternoster South Africa; seaside foraging restaurant, only 20 seats, tasting',15);

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('restaurants','Amass','Amass','DK','Matt Orlando Copenhagen zero-waste; reused ingredients, fermented pantry',10);
