-- schema-v19-descriptions-golf.sql: 100 golf challenges description_en (500-1000 chars each)
-- Run after schema-merged-v14-to-v18.sql. Escape single quotes as ''.

UPDATE challenges SET description_en = 'Augusta National Golf Club ranks among the world''s top 100 courses as the permanent home of the Masters Tournament since 1934. Founded by Bobby Jones and Clifford Roberts, the course was designed by Alister MacKenzie and opened in 1933. Its iconic features include Amen Corner (holes 11, 12, and 13), Rae''s Creek, and the flowering dogwoods and azaleas that define the spring major. The club is invitation-only and has evolved through careful modifications by Jones, Roberts, and later architects while preserving its strategic character. The back nine delivers unmatched drama in major championship golf, and the green jacket tradition makes it a symbol of excellence in the sport.' WHERE category = 'golf' AND title_en = 'Augusta National Golf Club';

UPDATE challenges SET description_en = 'Oakmont Country Club earns its place in the world top 100 as one of the most demanding and historic championship venues. Founded in 1903 and designed by Henry Fownes, it has hosted the U.S. Open a record nine times. The 1927 church pew bunkers on the 3rd and 4th holes are legendary, and Oakmont is renowned for having the fastest, most treacherous greens in championship golf. Located in Oakmont, Pennsylvania, the course has been refined over more than a century and demands precision, nerve, and superb putting. Its legacy includes iconic moments from Hogan, Nicklaus, and Miller, and it remains a benchmark for classic American golf architecture.' WHERE category = 'golf' AND title_en = 'Oakmont Country Club';

UPDATE challenges SET description_en = 'Winged Foot Golf Club is a world top 100 course and one of the most feared U.S. Open venues, having hosted the championship six times from 1929 to 2020. Designed by A.W. Tillinghast and opened in 1923, the West Course at Mamaroneck, New York, is famous for its narrow fairways, deep rough, and demanding green complexes. At 7,477 yards it tests every aspect of the game. The phrase "massacre at Winged Foot" entered golf lore after the 1974 U.S. Open. The club''s dual courses (East and West) and timeless Tillinghast design continue to define championship golf in the Northeast and represent the golden age of American golf architecture.' WHERE category = 'golf' AND title_en = 'Winged Foot Golf Club';

UPDATE challenges SET description_en = 'Shinnecock Hills Golf Club is among the world''s elite courses and the first U.S. Open venue built specifically for championship play. Located in Southampton, New York, it has hosted the U.S. Open six times from 1896 to 2018. The links-style layout sits on coastal terrain with wind, fescue, and strategic bunkering defining the challenge. Willie Davis, then C.B. Macdonald and later William Flynn, contributed to a design that blends classic links principles with American championship demands. Shinnecock is one of the five founding clubs of the USGA and remains a model of minimalist, wind-swept design that has stood the test of time and technology.' WHERE category = 'golf' AND title_en = 'Shinnecock Hills Golf Club';

UPDATE challenges SET description_en = 'Pinehurst No. 2 is a cornerstone of the world top 100 and the defining Donald Ross design. Built in 1907 in the sandhills of North Carolina, it has hosted the U.S. Open five times, including both the men''s and women''s opens in 2024. The course is famous for its domed, wiregrass-edged greens and strategic bunkering. A Coore-Crenshaw restoration in 2011 removed rough in favor of natural sand and native areas, restoring the original character. Pinehurst embodies strategic, ground-game golf and southern golf heritage, and the resort village and No. 2 together represent the soul of American golf in the Sandhills.' WHERE category = 'golf' AND title_en = 'Pinehurst No. 2';

UPDATE challenges SET description_en = 'The Country Club in Brookline, Massachusetts, is one of the oldest and most storied clubs in America and a permanent member of the world top 100. Founded in 1882, it hosted the 1913 U.S. Open when Francis Ouimet, a local amateur, defeated Harry Vardon and Ted Ray in a playoff, transforming American golf. The club has since hosted the U.S. Open in 1988, 1999, and 2022, plus the 1999 Ryder Cup. The composite championship course weaves over rolling, wooded terrain with small greens and classic New England character. Its history and architectural variety make it a pilgrimage site for golf historians and fans alike.' WHERE category = 'golf' AND title_en = 'The Country Club';

UPDATE challenges SET description_en = 'Olympic Club Lake Course in San Francisco has hosted the U.S. Open five times and is famous for its brutal uphill par-fours and history of underdog winners. The 1955 Open saw Ben Hogan lose a playoff to Jack Fleck; in 1966 Arnold Palmer lost a seven-shot lead, and in 2012 Webb Simpson emerged from the pack. The course sits on dramatic, wooded terrain with small greens and demanding approaches. Founded in 1860, the Olympic Club is one of the oldest athletic clubs in the United States. The Lake Course''s character and its role in championship drama secure its place among the world''s top 100 courses.' WHERE category = 'golf' AND title_en = 'Olympic Club Lake Course';

UPDATE challenges SET description_en = 'Bethpage Black in Farmingdale, New York, is one of the world''s top 100 courses and the most famous public championship layout. A warning sign at the first tee reads that the Black Course is extremely difficult and recommended only for highly skilled players. Designed by A.W. Tillinghast and opened in 1936, it has hosted the U.S. Open in 2002 and 2009 and the PGA Championship in 2019. Part of Bethpage State Park, it is accessible to the public through a ballot system. Its length, rough, and demanding greens make it a rare public venue that tests the best in the world and symbolizes accessible championship golf.' WHERE category = 'golf' AND title_en = 'Bethpage Black';

UPDATE challenges SET description_en = 'Torrey Pines South Course in La Jolla, California, sits on cliffs above the Pacific Ocean and ranks among the world''s top 100 public and championship venues. It has hosted the U.S. Open twice: in 2008, when Tiger Woods won in a playoff on a broken leg, and in 2021, when Jon Rahm birdied the final two holes to claim his first major. The course was designed by William Bell and later refined by Rees Jones for the 2008 Open. Municipal ownership and dramatic ocean views make it one of the most accessible and scenic major championship courses in the world, and the annual Farmers Insurance Open keeps it in the spotlight every year.' WHERE category = 'golf' AND title_en = 'Torrey Pines South Course';

UPDATE challenges SET description_en = 'Pebble Beach Golf Links is routinely ranked among the top five courses in the world and has hosted the U.S. Open six times. Built in 1919 by Jack Neville and Douglas Grant along the cliffs of Carmel Bay, California, it is famous for the oceanfront holes 7, 8, 9, and 10 and the iconic 18th playing along the Pacific. Unlike many top courses, Pebble Beach is open to the public. Its small greens, wind, and strategic design have produced unforgettable major moments, from Nicklaus''s 1-iron in 1972 to Watson''s chip-in in 1982 and Tiger''s 2000 dominance. Scenery, history, and accessibility make it the most celebrated public course in golf.' WHERE category = 'golf' AND title_en = 'Pebble Beach Golf Links';

UPDATE challenges SET description_en = 'Valhalla Golf Club in Louisville, Kentucky, has hosted the PGA Championship three times and the 2024 Ryder Cup, securing its place among the world''s top 100 courses. Designed by Jack Nicklaus and opened in 1986, the course is known for risk-reward par-fives and dramatic finishes: Mark Brooks won in a playoff in 1996, Tiger Woods in 2000, and Rory McIlroy in 2014. The 2024 Ryder Cup brought team match-play drama to a layout built for excitement. Valhalla''s blend of modern championship length and Nicklaus strategy, plus its role in defining moments in golf, makes it a must-play destination for fans of major championship golf.' WHERE category = 'golf' AND title_en = 'Valhalla Golf Club';

UPDATE challenges SET description_en = 'Kiawah Island Ocean Course in South Carolina is one of the world''s most demanding and scenic courses, with ten holes along the Atlantic Ocean. Designed by Pete Dye for the 1991 Ryder Cup (the "War on the Shore"), it has since hosted the PGA Championship in 2012 and 2021. The 2012 PGA featured Rory McIlroy''s record-setting win in brutal wind. The course is long, exposed, and features Dye''s signature bulkheads, waste areas, and strategic bunkering. Its role in Ryder Cup history and major championships, combined with ocean views and relentless difficulty, place it firmly in the global top 100 and among the best resort courses in America.' WHERE category = 'golf' AND title_en = 'Kiawah Island Ocean Course';

UPDATE challenges SET description_en = 'Whistling Straits in Kohler, Wisconsin, sits on two miles of Lake Michigan shoreline and ranks among the world''s top 100 for its links-style drama and championship pedigree. Designed by Pete Dye, the Straits Course has hosted the PGA Championship in 2004, 2010, and 2020, and the Ryder Cup in 2021 (played in 2020). The course features over 1,000 bunkers, fescue, and massive dunes, evoking Irish links in the American Midwest. Memorable moments include Martin Kaymer''s 2010 PGA win and the 2020 Ryder Cup. Its unique setting and Dye''s bold design make it a bucket-list course and a symbol of modern American links-style golf.' WHERE category = 'golf' AND title_en = 'Whistling Straits';

UPDATE challenges SET description_en = 'TPC Sawgrass Stadium Course in Ponte Vedra Beach, Florida, is home to THE PLAYERS Championship and the most famous par-three in golf: the island green 17th. Designed by Pete Dye and opened in 1982, the course was groundbreaking in stadium-style mounding and risk-reward design. The 17th hole, playing to a green surrounded by water, has decided countless championships and remains an iconic test of nerve. The rest of the course demands accuracy and strategy, with water and bunkers defining many holes. As the permanent home of the PGA Tour''s flagship event and a public-accessible venue, Sawgrass earns its place among the world''s top 100 and in the imagination of every golfer.' WHERE category = 'golf' AND title_en = 'TPC Sawgrass Stadium Course';

UPDATE challenges SET description_en = 'Medinah Country Club No. 3 in Medinah, Illinois, has hosted the U.S. Open three times and the PGA Championship twice, and was the stage for the 2012 Ryder Cup "Miracle at Medinah," when Europe came back from 10-6 down. The No. 3 course was designed by Tom Bendelow and later revised by Rees Jones. Its tree-lined fairways, strategic bunkering, and demanding greens have tested the world''s best for decades. The club''s Middle Eastern-inspired clubhouse and the 2012 Ryder Cup drama have made Medinah synonymous with team golf at the highest level. Its championship history and classic American parkland design secure its place in the world top 100.' WHERE category = 'golf' AND title_en = 'Medinah Country Club No.3';

UPDATE challenges SET description_en = 'Hazeltine National Golf Club in Chaska, Minnesota, has hosted the U.S. Open, multiple PGA Championships, and the 2016 Ryder Cup, where the United States won decisively. Designed by Robert Trent Jones Sr. and opened in 1962, the course has been refined over the years to remain a stern championship test. Long, demanding par-fours and strategic water hazards define the layout. Hazeltine''s role in the Ryder Cup and its reputation as a fair but tough championship venue make it a pillar of American golf. The 2016 Ryder Cup victory on home soil and the club''s commitment to hosting the game''s biggest events place it among the world''s top 100 courses.' WHERE category = 'golf' AND title_en = 'Hazeltine National Golf Club';

UPDATE challenges SET description_en = 'Baltusrol Golf Club Lower Course in Springfield, New Jersey, has hosted the U.S. Open seven times and the PGA Championship, placing it among the world''s most storied venues. The Lower Course was designed by A.W. Tillinghast and later renovated by Robert Trent Jones. Its rolling terrain, strategic bunkering, and classic green complexes have witnessed triumphs by Nicklaus, Mickelson, and others. The club was founded in 1895 and named after Baltus Roll, a farmer who lived on the property. The combination of history, major championship pedigree, and timeless architecture makes Baltusrol a cornerstone of the world top 100 and of American golf heritage.' WHERE category = 'golf' AND title_en = 'Baltusrol Golf Club Lower Course';

UPDATE challenges SET description_en = 'Merion Golf Club East Course in Ardmore, Pennsylvania, is the smallest venue in modern major championship golf and one of the world''s most revered courses. It has hosted the U.S. Open five times, most recently in 2013, and is famous for its wicker basket flagsticks, red sandstone bunkers, and strategic design. Designed by Hugh Wilson and opened in 1912, Merion packs enormous challenge into a compact property. Bobby Jones completed the Grand Slam at Merion in 1930, and the 2013 Open saw Justin Rose claim his first major. Its blend of history, intimacy, and shot-making demand secures Merion''s place in the world top 100 and in the hearts of golf purists.' WHERE category = 'golf' AND title_en = 'Merion Golf Club East Course';

UPDATE challenges SET description_en = 'Quail Hollow Club in Charlotte, North Carolina, hosts the Wells Fargo Championship annually and will host the Ryder Cup in 2028, cementing its status among the world''s top 100 courses. The course was designed by George Cobb and later refined by Tom Fazio. Its tree-lined fairways, difficult closing stretch ("Green Mile"), and immaculate conditioning have made it a player favorite on the PGA Tour. The 2017 PGA Championship was held here, won by Justin Thomas. Quail Hollow''s blend of modern championship setup, southern character, and commitment to hosting the game''s biggest events makes it a must-visit for fans and a fixture in the global top 100.' WHERE category = 'golf' AND title_en = 'Quail Hollow Club';

UPDATE challenges SET description_en = 'St Andrews Old Course is the Home of Golf and the most iconic course in the world, hosting The Open more times than any other venue. Golf has been played on the links at St Andrews for over 600 years, and the Old Course''s double greens, vast fairways, and strategic bunkers have defined the game. The Swilcan Bridge on 18 and the Road Hole 17th are among the most photographed spots in golf. The course is public and remains the spiritual home of the game. Its history, influence on course design, and role in The Open Championship make it the undisputed number one pilgrimage for golfers and a permanent member of the world top 100.' WHERE category = 'golf' AND title_en = 'St Andrews Old Course';

UPDATE challenges SET description_en = 'Muirfield in East Lothian, Scotland, is the home of the Honourable Company of Edinburgh Golfers, the oldest recorded golf club in the world (1744). It has hosted The Open 16 times and is consistently ranked among the world''s top 20 courses. The layout is a classic out-and-back links with two loops of nine, ensuring that wind is faced from every direction. The course demands strategic play, precise iron shots, and superb putting. Its strict membership policies and timeless design have made it a symbol of tradition and excellence. Muirfield''s history, the quality of its design, and its Open pedigree secure its place in the world top 100.' WHERE category = 'golf' AND title_en = 'Muirfield';

UPDATE challenges SET description_en = 'Carnoustie Golf Links in Angus, Scotland, is often called the most difficult links course in the world and has hosted The Open eight times. The Barry Burn winds through the closing holes and has decided many championships, most famously the 1999 Open when Jean Van de Velde triple-bogeyed the 72nd hole. Designed by Allan Robertson and Old Tom Morris and later extended by James Braid, Carnoustie is long, windswept, and bunker-strewn. Its reputation for difficulty and its classic links character make it a bucket-list course and a fixture in the world top 100. The Open returns here regularly, and the course remains one of the sternest tests in championship golf.' WHERE category = 'golf' AND title_en = 'Carnoustie Golf Links';

UPDATE challenges SET description_en = 'Royal Birkdale Golf Club in Southport, England, has hosted The Open ten times, most recently in 2017, and is renowned for its willow scrub rough, flat lies, and classic links character. The course is set among dunes that frame each hole and provide natural definition. Designed by George Lowe and later refined by Fred Hawtree and others, Royal Birkdale has witnessed triumphs by Watson, Palmer, and Padraig Harrington. The club''s tradition, the quality of the championship test, and the consistency of the layout place it among the world''s top 100 courses and make it one of the finest Open venues in England.' WHERE category = 'golf' AND title_en = 'Royal Birkdale Golf Club';

UPDATE challenges SET description_en = 'Royal Troon Golf Club in South Ayrshire, Scotland, has hosted The Open nine times and is famous for the Postage Stamp 8th hole, a par-three of only 123 yards that can play into a fierce wind. The course offers a classic links test with a demanding back nine. The Open has been held here since 1923, and champions include Arnold Palmer, Tom Weiskopf, and Henrik Stenson. Royal Troon''s blend of history, the Postage Stamp''s notoriety, and the quality of the full eighteen holes secure its place in the world top 100 and make it one of the most recognizable links courses in Scotland.' WHERE category = 'golf' AND title_en = 'Royal Troon Golf Club';

UPDATE challenges SET description_en = 'Royal Lytham & St Annes Golf Club in Lancashire, England, has hosted The Open 11 times and is unique among Open venues for having no sea views; the course is set inland among dunes and 206 bunkers. Designed by George Lowe and Harry Colt, it demands accuracy and strategic play. Bobby Jones won here in 1926, and the list of champions includes Seve Ballesteros and Ernie Els. The club''s tradition and the sheer number of bunkers make it a distinctive and demanding test. Royal Lytham''s place in Open history and its classic links design earn it a permanent spot in the world top 100.' WHERE category = 'golf' AND title_en = 'Royal Lytham & St Annes Golf Club';

UPDATE challenges SET description_en = 'Royal St George''s Golf Club in Sandwich, Kent, England, is the oldest English venue to host The Open and has done so 15 times, most recently in 2021. The course is set among hidden dunes and features blind shots, deep bunkers, and fast-running fairways. Designed by Dr. Laidlaw Purves and opened in 1887, it was the first course outside Scotland to host The Open. Its character is distinctly English links: subtle, strategic, and demanding. The 2021 Open saw Collin Morikawa claim the Claret Jug. Royal St George''s history, unique terrain, and Open pedigree place it firmly in the world top 100.' WHERE category = 'golf' AND title_en = 'Royal St George''s Golf Club';

UPDATE challenges SET description_en = 'Royal Portrush Golf Club on the Dunluce Links in Northern Ireland has hosted The Open in 2019 and 2025 and is consistently ranked among the world''s top 20 courses. The course features Calamity Corner (the 14th), stunning views of the North Atlantic, and a design that weaves through dunes and valleys. It is the only club in Ireland to have hosted The Open. Rory McIlroy grew up nearby and set the course record as a teenager. The 2019 Open saw Shane Lowry win in front of passionate home crowds. Royal Portrush''s drama, scenery, and championship pedigree make it a must-play and a permanent member of the world top 100.' WHERE category = 'golf' AND title_en = 'Royal Portrush Golf Club';

UPDATE challenges SET description_en = 'Royal Liverpool Golf Club at Hoylake in Wirral, England, has hosted The Open 12 times, including in 2006 when Tiger Woods famously hit no drivers and relied on iron play to win. The course was redesigned by Harry Colt and has been updated for modern Opens. Its flat, links-style terrain and strategic bunkering demand precision. The 2014 Open saw Rory McIlroy win, and the 2023 Open returned here. Royal Liverpool''s history, its role in defining strategic championship golf, and its place in Open rotation secure its position in the world top 100 and make Hoylake one of the game''s great venues.' WHERE category = 'golf' AND title_en = 'Royal Liverpool Golf Club';

UPDATE challenges SET description_en = 'Turnberry Ailsa Course in South Ayrshire, Scotland, has hosted The Open four times and is famous for the 1977 "Duel in the Sun" between Tom Watson and Jack Nicklaus. The course sits along the Firth of Clyde with views of Ailsa Craig and the lighthouse that frames the iconic 9th hole. The layout was redesigned by Mackenzie & Ebert and remains one of the most scenic in championship golf. Turnberry''s combination of beauty, history, and strategic challenge places it in the world top 100. Its future as an Open venue and its status as a luxury resort course make it a bucket-list destination for golfers worldwide.' WHERE category = 'golf' AND title_en = 'Turnberry Ailsa Course';

UPDATE challenges SET description_en = 'Southern Hills Country Club in Tulsa, Oklahoma, has hosted the U.S. Open three times and the 2022 PGA Championship, won by Rory McIlroy. The course was originally designed by Perry Maxwell and later refined by Donald Ross and Gil Hanse. Its tree-lined fairways, strategic bunkering, and demanding greens have tested the best for decades. Southern Hills has hosted multiple PGA Championships and U.S. Opens, and the 2022 PGA confirmed its return to the major rotation. The club''s blend of classic design, championship history, and southern hospitality secures its place in the world top 100 and among the finest courses in the American heartland.' WHERE category = 'golf' AND title_en = 'Southern Hills Country Club';

UPDATE challenges SET description_en = 'Oak Hill Country Club East Course in Rochester, New York, has hosted the U.S. Open five times and the 2023 PGA Championship, won by Brooks Koepka. Designed by Donald Ross and later revised by Robert Trent Jones and Tom Fazio, the East Course is a classic American parkland test with tree-lined fairways and demanding green complexes. The 2023 PGA confirmed Oak Hill''s place in the modern major rotation. The club''s history, the quality of the Ross design, and its consistent ability to identify the best players in the world place it among the world''s top 100 courses and the finest in the Northeast.' WHERE category = 'golf' AND title_en = 'Oak Hill Country Club East Course';

UPDATE challenges SET description_en = 'Oakland Hills Country Club South Course in Bloomfield Hills, Michigan, has hosted the U.S. Open seven times and the Ryder Cup in 1961. Ben Hogan famously called it "The Monster" after winning the 1951 U.S. Open. Designed by Donald Ross and later renovated by Robert Trent Jones, the South Course is long, demanding, and lined with trees and bunkers. Its reputation for difficulty and its role in American championship history make it a pillar of the world top 100. The club has hosted numerous USGA and PGA events, and the "Monster" nickname endures as a symbol of classic American championship golf.' WHERE category = 'golf' AND title_en = 'Oakland Hills Country Club South';

UPDATE challenges SET description_en = 'Riviera Country Club in Pacific Palisades, California, hosts the Genesis Invitational annually and has hosted the PGA Championship twice. Ben Hogan won the Los Angeles Open five times here, and the course is often called "Hogan''s Alley." Designed by George Thomas and opened in 1926, Riviera features kikuyu grass, barrancas, and the famous par-four 10th hole. Its classic design and Hollywood setting have made it a favorite of players and fans. Riviera''s place in PGA Tour history, its timeless architecture, and its role as a perennial stop on the tour secure its position in the world top 100 and among the best courses in California.' WHERE category = 'golf' AND title_en = 'Riviera Country Club';

UPDATE challenges SET description_en = 'Muirfield Village Golf Club in Dublin, Ohio, hosts the Memorial Tournament annually and was the site of the Presidents Cup in 1987 and 2013. Designed by Jack Nicklaus and opened in 1974, the course is a testament to Nicklaus''s design philosophy: risk-reward, strategic options, and immaculate conditioning. The club honors the game''s legends and has become a pilgrimage for fans of Nicklaus and of tournament golf. Muirfield Village''s role as the permanent home of the Memorial and its status as one of Nicklaus''s finest designs place it in the world top 100 and at the heart of the PGA Tour calendar.' WHERE category = 'golf' AND title_en = 'Muirfield Village Golf Club';

UPDATE challenges SET description_en = 'East Lake Golf Club in Atlanta, Georgia, hosts the Tour Championship every year and is the home course of Bobby Jones. The club was founded in 1904 and has been restored to reflect its golden-age character. The Tour Championship determines the FedEx Cup winner and has produced dramatic finishes. East Lake''s connection to Jones, its role in the PGA Tour playoffs, and its place in Atlanta''s history make it one of the most significant courses in American golf. The club''s commitment to the East Lake community and its championship pedigree secure its place in the world top 100.' WHERE category = 'golf' AND title_en = 'East Lake Golf Club';

UPDATE challenges SET description_en = 'Congressional Country Club Blue Course in Bethesda, Maryland, has hosted the U.S. Open three times (1964, 1997, 2011) and the KPMG Women''s PGA Championship. Designed by Devereux Emmet and later revised by Rees Jones, the Blue Course is long and demanding, often favoring power hitters. Rory McIlroy''s record-setting 2011 U.S. Open win here announced his arrival as a major champion. The club''s history, its role in Washington-area golf, and its championship setup place it among the world''s top 100 courses and the finest in the Mid-Atlantic.' WHERE category = 'golf' AND title_en = 'Congressional Country Club Blue Course';

UPDATE challenges SET description_en = 'Aronimink Golf Club in Newtown Square, Pennsylvania, has hosted the PGA Championship and the BMW Championship. Designed by Donald Ross and opened in 1928, the course is a classic parkland layout with rolling terrain and strategic bunkering. Aronimink has been restored to reflect Ross''s original vision and remains one of the finest examples of his work. The club''s commitment to hosting professional events and the quality of the design place it in the world top 100. Its proximity to Philadelphia and its timeless character make it a sought-after venue for both members and championship golf.' WHERE category = 'golf' AND title_en = 'Aronimink Golf Club';

UPDATE challenges SET description_en = 'Bay Hill Club & Lodge in Orlando, Florida, hosts the Arnold Palmer Invitational annually and was Arnold Palmer''s home course. Palmer purchased the club in the 1970s and oversaw design changes that created the modern championship test. The course features water, strategic bunkering, and a demanding finish. Bay Hill''s connection to Palmer, its role on the PGA Tour calendar, and its status as a resort and tournament venue make it one of the most recognizable courses in golf. The King''s legacy and the quality of the layout secure Bay Hill''s place in the world top 100.' WHERE category = 'golf' AND title_en = 'Bay Hill Club & Lodge';

UPDATE challenges SET description_en = 'Harbour Town Golf Links on Hilton Head Island, South Carolina, hosts the RBC Heritage annually and is one of the most distinctive courses on the PGA Tour. Designed by Pete Dye with Jack Nicklaus and opened in 1969, the course is known for narrow fairways, small greens, and the iconic lighthouse par-four 18th. Harbour Town demands accuracy over power and rewards strategic play. Its placement the week after the Masters and its coastal setting make it a player and fan favorite. The course''s design quality and its role in Tour history place it firmly in the world top 100.' WHERE category = 'golf' AND title_en = 'Harbour Town Golf Links';

UPDATE challenges SET description_en = 'Kapalua Plantation Course on Maui, Hawaii, hosts The Sentry (Tournament of Champions) annually, opening the PGA Tour season. Designed by Bill Coore and Ben Crenshaw and opened in 1991, the course sits on dramatic slopes with ocean views and wide fairways. The par-five 18th is one of the most dramatic closing holes in golf. Kapalua''s role as the season opener, its Coore-Crenshaw design, and its Hawaiian setting make it a bucket-list course and a fixture in the world top 100. The Plantation Course embodies resort championship golf at its finest.' WHERE category = 'golf' AND title_en = 'Kapalua Plantation Course';

UPDATE challenges SET description_en = 'Firestone Country Club South Course in Akron, Ohio, hosted the WGC-Bridgestone Invitational for 14 years and has hosted multiple PGA Championships and Senior PGA Championships. Designed by Robert Trent Jones and renovated in 1960, the South Course is long, tree-lined, and demanding. The "Monster" 16th hole is one of the most difficult par-fives in championship golf. Firestone''s history as a regular tour stop and its reputation as a stern test place it in the world top 100. The course remains a benchmark for classic American parkland design and championship conditioning.' WHERE category = 'golf' AND title_en = 'Firestone Country Club South Course';

UPDATE challenges SET description_en = 'Bellerive Country Club in St. Louis, Missouri, has hosted the U.S. Open and the 2018 PGA Championship, won by Brooks Koepka. Designed by Robert Trent Jones Sr., the course features tree-lined fairways, strategic water hazards, and demanding greens. Bellerive''s return to the major championship rotation in 2018 confirmed its status as one of America''s premier venues. The club''s history and the quality of the Jones design place it among the world''s top 100 courses. Its role in identifying major champions and its Midwestern character make it a significant stop in championship golf.' WHERE category = 'golf' AND title_en = 'Bellerive Country Club';

UPDATE challenges SET description_en = 'Liberty National Golf Club in Jersey City, New Jersey, has hosted the Presidents Cup and the FedEx Cup playoffs, and offers stunning views of the Manhattan skyline and Statue of Liberty. Designed by Bob Cupp and Tom Kite and opened in 2006, the course was built on a reclaimed industrial site and features modern design with dramatic water features and strategic bunkering. Liberty National''s unique setting and its role in team and playoff golf place it in the world top 100. The course represents the best of modern American golf architecture and urban golf.' WHERE category = 'golf' AND title_en = 'Liberty National Golf Club';

UPDATE challenges SET description_en = 'Chambers Bay Golf Course in University Place, Washington, hosted the 2015 U.S. Open, won by Jordan Spieth in dramatic fashion. Designed by Robert Trent Jones Jr., the course is a links-style layout built on a former sand and gravel mine with views of Puget Sound. Chambers Bay is a public course and was controversial for its fescue greens and firm conditions during the Open, but it provided a unique and memorable test. Its role in bringing a U.S. Open to the Pacific Northwest and its bold design secure its place in the world top 100 and in the conversation about modern public championship golf.' WHERE category = 'golf' AND title_en = 'Chambers Bay Golf Course';

UPDATE challenges SET description_en = 'Erin Hills Golf Course in Erin, Wisconsin, hosted the 2017 U.S. Open, won by Brooks Koepka. The course is set on glacial moraines in the Kettle Moraine region and features wide fairways, fescue, and massive greens. Designed by Michael Hurdzan, Dana Fry, and Ron Whitten, Erin Hills was built with the U.S. Open in mind and offers a different kind of test: strategic off the tee and demanding on approach. Its public accessibility and its success as a first-time Open venue place it in the world top 100 and make it a model for modern American public championship golf.' WHERE category = 'golf' AND title_en = 'Erin Hills Golf Course';

UPDATE challenges SET description_en = 'TPC Scottsdale Stadium Course in Scottsdale, Arizona, hosts the Waste Management Phoenix Open annually and is famous for the par-three 16th hole, which is surrounded by grandstands and holds over 20,000 fans. The 16th has become the most electric hole in golf, with raucous crowds and dramatic moments. The rest of the course is a desert layout with risk-reward holes and stunning views. TPC Scottsdale''s role in creating the "Greatest Show on Grass" and its place on the PGA Tour calendar secure its position in the world top 100 and make it a must-see for fans of tournament golf.' WHERE category = 'golf' AND title_en = 'TPC Scottsdale Stadium Course';

UPDATE challenges SET description_en = 'Prairie Dunes Country Club in Hutchinson, Kansas, has hosted the U.S. Women''s Open twice and the U.S. Senior Open. Designed by Perry Maxwell and opened in 1937, the course is set among rolling sand dunes and native grasses, offering a links-style experience in the heartland. Prairie Dunes is consistently ranked among the top courses in America and the world. Its unique setting, Maxwell''s design genius, and its role in women''s and senior championship golf place it in the world top 100. The course is a hidden gem and a testament to the variety of American golf architecture.' WHERE category = 'golf' AND title_en = 'Prairie Dunes Country Club';

UPDATE challenges SET description_en = 'Pine Needles Lodge & Golf Club in Southern Pines, North Carolina, has hosted the U.S. Women''s Open four times (1996, 2001, 2007, 2022). Designed by Donald Ross, the course has been restored by Kyle Franz to reflect Ross''s original vision. Pine Needles is part of the sandhills golf tradition and has been a leader in women''s golf under the ownership of the Bell family. The 2022 U.S. Women''s Open saw Minjee Lee win in dominant fashion. The course''s history, its Ross design, and its commitment to the women''s game secure its place in the world top 100.' WHERE category = 'golf' AND title_en = 'Pine Needles Lodge & Golf Club';

UPDATE challenges SET description_en = 'Waialae Country Club in Honolulu, Hawaii, has hosted the Sony Open in Hawaii since 1965, making it one of the longest-running venues on the PGA Tour. The course is an oceanside private club that opens its doors to the tour each January. Designed by Seth Raynor and later revised, Waialae features strategic bunkering and a classic layout. Its role in opening the calendar year and its Hawaiian setting make it a favorite of players and fans. Waialae''s tradition and its place in Tour history secure its position in the world top 100 and among the best courses in the Pacific.' WHERE category = 'golf' AND title_en = 'Waialae Country Club';

UPDATE challenges SET description_en = 'Colonial Country Club in Fort Worth, Texas, hosts the Charles Schwab Challenge annually and is known as "Hogan''s Alley" because Ben Hogan won the event five times. The course is a classic layout with narrow fairways, strategic bunkers, and demanding approaches. Colonial has been a PGA Tour stop since 1946 and has maintained its character through the decades. The club''s connection to Hogan and its commitment to traditional championship golf place it in the world top 100. Colonial represents the best of Texas golf and American tournament tradition.' WHERE category = 'golf' AND title_en = 'Colonial Country Club';

UPDATE challenges SET description_en = 'Real Club Valderrama in Andalucia, Spain, hosted the 1997 Ryder Cup, the first held in continental Europe, and is the crown jewel of Spanish golf. The course is set among cork oaks and features the famous 17th hole with water and strategic challenge. Designed by Robert Trent Jones Sr. and refined over the years, Valderrama has hosted numerous European Tour events and is synonymous with Seve Ballesteros and European golf. The 1997 Ryder Cup victory for Europe was a turning point in the competition. Valderrama''s design, history, and role in European golf secure its place in the world top 100.' WHERE category = 'golf' AND title_en = 'Real Club Valderrama';

UPDATE challenges SET description_en = 'The K Club Palmer Course in County Kildare, Ireland, hosted the 2006 Ryder Cup, when Europe won 18.5-9.5 in one of the most decisive victories in the event''s history. Designed by Arnold Palmer, the course is set along the River Liffey and features water, strategic bunkering, and parkland character. The K Club has become a symbol of Irish hospitality and championship golf. Its role in the Ryder Cup and its place in Ireland''s golf boom secure its position in the world top 100. The Palmer Course remains a bucket-list destination for fans of team golf and Irish golf.' WHERE category = 'golf' AND title_en = 'The K Club Palmer Course';

UPDATE challenges SET description_en = 'Celtic Manor Twenty Ten Course in Newport, Wales, was built specifically to host the 2010 Ryder Cup, the first held in Wales. Designed with match play in mind, the course saw Colin Montgomerie captain Europe to a narrow victory. The Twenty Ten Course was the first in history to be built specifically for the Ryder Cup and features dramatic water hazards and risk-reward holes. Celtic Manor''s role in the 2010 matches and its status as a purpose-built Ryder Cup venue place it in the world top 100. The course represents Wales''s commitment to hosting the world''s best in team golf.' WHERE category = 'golf' AND title_en = 'Celtic Manor Twenty Ten Course';

UPDATE challenges SET description_en = 'Gleneagles PGA Centenary Course in Perthshire, Scotland, hosted the 2014 Ryder Cup, when Europe won under Paul McGinley''s captaincy. Designed by Jack Nicklaus in collaboration with the legacy of James Braid, the course is part of the Gleneagles resort and offers stunning Highland scenery. The Centenary Course was built to host major events and has delivered drama and quality. Gleneagles''s combination of luxury, history, and championship golf place it in the world top 100. The resort and the Centenary Course together represent the best of Scottish golf and hospitality.' WHERE category = 'golf' AND title_en = 'Gleneagles PGA Centenary Course';

UPDATE challenges SET description_en = 'Le Golf National near Paris, France, hosted the 2018 Ryder Cup, when Europe won 17.5-10.5 in a dominant performance. The Albatros course is the flagship layout and hosts the French Open annually. Designed to create drama and spectator excitement, the course features the famous closing stretch around the lake, where matches have been decided. Le Golf National has become the home of French professional golf and a symbol of European team golf. Its role in the 2018 Ryder Cup and its design secure its place in the world top 100 and make it a must-play in France.' WHERE category = 'golf' AND title_en = 'Le Golf National';

UPDATE challenges SET description_en = 'Marco Simone Golf & Country Club in Rome, Italy, hosted the 2023 Ryder Cup, when Europe won 16.5-11.5 in front of passionate home crowds. Designed by Tom and Dana Weiskopf, the course was extensively renovated to prepare for the Ryder Cup and features dramatic elevation changes and strategic design. Marco Simone brought the Ryder Cup to Italy for the first time and showcased the growth of golf in Europe. The course''s role in the 2023 matches and its Roman setting place it in the world top 100 and at the forefront of European championship golf.' WHERE category = 'golf' AND title_en = 'Marco Simone Golf & Country Club';

UPDATE challenges SET description_en = 'The Belfry Brabazon Course in Sutton Coldfield, England, has hosted the Ryder Cup four times (1985, 1989, 1993, 2002) and is where Europe rediscovered Ryder Cup glory. The 1985 victory broke a long American winning streak and began the modern era of the competition. The Brabazon Course was designed by Dave Thomas and Peter Alliss and features the famous 10th hole, a risk-reward par-four over water. The Belfry''s place in Ryder Cup history and its role in British golf make it a pilgrimage site. The course secures its position in the world top 100 through tradition and drama.' WHERE category = 'golf' AND title_en = 'The Belfry Brabazon Course';

UPDATE challenges SET description_en = 'Royal County Down Golf Club in Newcastle, Northern Ireland, is consistently ranked number one in the world by various publications. The course is set against the Mourne Mountains and features blind shots, deep bunkers, and links turf. Designed by Old Tom Morris and later refined by Harry Colt, Royal County Down is the pinnacle of links golf. The course is private but has hosted the Irish Open and numerous amateur championships. Its beauty, difficulty, and timeless design make it the dream destination for many golfers and a permanent member of the world top 100.' WHERE category = 'golf' AND title_en = 'Royal County Down Golf Club';

UPDATE challenges SET description_en = 'Royal Montreal Golf Club in Ile Bizard, Quebec, is the oldest golf club in North America, founded in 1873. The Blue Course has hosted the Canadian Open ten times and is a classic parkland layout. Royal Montreal represents the birth of organized golf in the Americas and has maintained its tradition and quality for over 150 years. The club''s history and its role in Canadian golf place it in the world top 100. The Blue Course remains a benchmark for classic design and a symbol of Canadian golf heritage.' WHERE category = 'golf' AND title_en = 'Royal Montreal Golf Club';

UPDATE challenges SET description_en = 'Glen Abbey Golf Club in Oakville, Ontario, has hosted the Canadian Open more times than any other course (25-plus) and is one of the most famous courses in Canada. Designed by Jack Nicklaus and opened in 1976, the course features the "Valley Holes" (11 through 15) that play through a dramatic ravine. Glen Abbey has witnessed multiple Canadian Open playoffs and historic moments. Its role in Canadian golf and its Nicklaus design place it in the world top 100. The course remains a symbol of Canadian professional golf and public-access championship golf.' WHERE category = 'golf' AND title_en = 'Glen Abbey Golf Club';

UPDATE challenges SET description_en = 'Kasumigaseki Country Club East Course in Saitama, Japan, hosted the golf events of the Tokyo 2020 Olympics, where Xander Schauffele and Nelly Korda won the gold medals. The club was founded in 1929 and the East Course has been updated to meet modern championship standards. Kasumigaseki is one of Japan''s most prestigious clubs and the Olympics brought global attention to Japanese golf. The course''s history, its role in the Olympics, and its place in Asian golf secure its position in the world top 100 and make it a landmark in the growth of golf in Japan.' WHERE category = 'golf' AND title_en = 'Kasumigaseki Country Club East Course';

UPDATE challenges SET description_en = 'Narashino Country Club in Inzai, Chiba, Japan, hosts the ZOZO Championship, a PGA Tour event, and was the site of Tiger Woods''s victory in 2019 in his comeback tournament. The course is a classic Japanese layout with tree-lined fairways and strategic design. Narashino has been a leader in bringing top-level professional golf to Japan and has hosted the Japan Open multiple times. The ZOZO Championship and Tiger''s win there brought global attention. Narashino''s role in the PGA Tour and its quality place it in the world top 100 and at the forefront of Asian golf.' WHERE category = 'golf' AND title_en = 'Narashino Country Club';

UPDATE challenges SET description_en = 'Jack Nicklaus Golf Club Korea in Songdo, Incheon, South Korea, hosted the 2015 Presidents Cup and is one of the premier courses in Asia. Designed by Jack Nicklaus, the course was built to host the game''s best and features modern championship design with strategic options and immaculate conditioning. The 2015 Presidents Cup brought team golf to Korea and showcased the growth of the game in the region. Jack Nicklaus Golf Club Korea''s role in the Presidents Cup and its design secure its place in the world top 100 and make it a symbol of Korean golf ambition.' WHERE category = 'golf' AND title_en = 'Jack Nicklaus Golf Club Korea';

UPDATE challenges SET description_en = 'Nine Bridges Golf Club on Jeju Island, South Korea, is the flagship course of the KLPGA and one of the most scenic courses in Asia. The course features nine traditional bridges and extensive water features, with autumn foliage providing a stunning backdrop. Nine Bridges has hosted professional events and is consistently ranked among the best courses in Asia. Its design, setting, and role in Korean golf place it in the world top 100. The course represents the best of resort and championship golf in South Korea and the Pacific Rim.' WHERE category = 'golf' AND title_en = 'Nine Bridges Golf Club';

UPDATE challenges SET description_en = 'Royal Melbourne Golf Club in Melbourne, Australia, is the crown jewel of the famed sandbelt and has hosted the Presidents Cup in 2011 and 2019. The composite course used for the Presidents Cup combines the West and East courses designed by Alister MacKenzie and others. Royal Melbourne is consistently ranked among the top 10 courses in the world and is the benchmark for sandbelt golf. Its strategic design, firm conditions, and history place it in the world top 100 and make it the must-play course in Australia.' WHERE category = 'golf' AND title_en = 'Royal Melbourne Golf Club';

UPDATE challenges SET description_en = 'Kingston Heath Golf Club in Melbourne, Australia, has hosted the Australian Open multiple times and is one of the finest courses in the sandbelt. Designed with input from Alister MacKenzie, the course features his signature bunkering and strategic options. Kingston Heath is consistently ranked among the world''s top 50 courses and offers a pure golf experience. Its design quality and its place in Australian golf history secure its position in the world top 100. The course is a model of sandbelt architecture and strategic design.' WHERE category = 'golf' AND title_en = 'Kingston Heath Golf Club';

UPDATE challenges SET description_en = 'Gary Player Country Club at Sun City, South Africa, hosts the Nedbank Golf Challenge annually and is part of the Lost City resort complex. Designed by Gary Player, the course is set in the North West Province and features dramatic terrain and risk-reward holes. The Nedbank has been a highlight of the European Tour schedule and has attracted the world''s best. Gary Player Country Club''s role in African golf and its unique setting place it in the world top 100. The course represents the best of South African resort and championship golf.' WHERE category = 'golf' AND title_en = 'Gary Player Country Club';

UPDATE challenges SET description_en = 'Fancourt Links in George, South Africa, hosted the 2003 Presidents Cup and is one of the most acclaimed courses in Africa. Designed by Ernie Els, the course is set against the Outeniqua Mountains and offers links-style golf in a stunning setting. Fancourt has been at the forefront of South African golf and has hosted numerous professional and amateur events. The 2003 Presidents Cup brought team golf to Africa. Fancourt Links'' design, setting, and history place it in the world top 100 and make it a bucket-list course for golfers visiting South Africa.' WHERE category = 'golf' AND title_en = 'Fancourt Links';

UPDATE challenges SET description_en = 'Sheshan International Golf Club in Shanghai, China, hosts the WGC-HSBC Champions annually, the first World Golf Championship in the Asia-Pacific region. The tournament is often called "China''s major" and has brought the world''s best to Shanghai. Sheshan is a modern championship layout that has been refined to test the game''s elite. The club''s role in the growth of golf in China and its place in the WGC series secure its position in the world top 100. Sheshan represents the ambition and growth of golf in China and Asia.' WHERE category = 'golf' AND title_en = 'Sheshan International Golf Club';

UPDATE challenges SET description_en = 'Emirates Golf Club Majlis Course in Dubai, UAE, was the site of the first floodlit tournament in 1989 (Dubai Desert Classic) and now hosts the DP World Tour Championship, the season finale of the European Tour. The course is a desert layout with lush fairways and strategic design. The Majlis has become synonymous with Middle Eastern golf and the growth of the game in the UAE. Its role in the European Tour and its unique setting place it in the world top 100. The course is a symbol of Dubai''s place in global golf and luxury sport.' WHERE category = 'golf' AND title_en = 'Emirates Golf Club Majlis Course';

UPDATE challenges SET description_en = 'Evian Resort Golf Club in Evian-les-Bains, France, hosts the Evian Championship annually, the fifth women''s major championship. The course is set above Lake Geneva in the Alps and offers stunning views and challenging terrain. The Evian Championship has become a cornerstone of women''s golf and attracts the best players in the world. Evian Resort''s commitment to the women''s game and its spectacular setting place it in the world top 100. The course represents the best of European resort golf and the growth of women''s professional golf.' WHERE category = 'golf' AND title_en = 'Evian Resort Golf Club';

UPDATE challenges SET description_en = 'Wentworth Club West Course in Surrey, England, hosts the BMW PGA Championship annually, the flagship event of the DP World Tour. Designed by Harry Colt and opened in 1924, the West Course has been revised by Ernie Els and others. Wentworth is synonymous with European Tour golf and has been the scene of countless dramatic finishes. The course''s heathland character, its place in the European Tour calendar, and its history place it in the world top 100. Wentworth remains the home of the Tour''s most prestigious regular event and a benchmark for English heathland golf.' WHERE category = 'golf' AND title_en = 'Wentworth Club West Course';

UPDATE challenges SET description_en = 'Sunningdale Golf Club Old Course in Berkshire, England, is a classic heathland course designed by Willie Park Jr. in 1900. The Old Course has hosted Open Championship qualifying and the Walker Cup in 1987. Sunningdale is consistently ranked among the best courses in the world and is famous for its heather, pine, and strategic design. Tom Watson has called the 10th hole one of the best par-fours in the world. Sunningdale''s place in English golf and its timeless design secure its position in the world top 100. The Old Course is a model of heathland architecture.' WHERE category = 'golf' AND title_en = 'Sunningdale Golf Club Old Course';

UPDATE challenges SET description_en = 'Loch Lomond Golf Club in Scotland hosted the Scottish Open for multiple years and is set on the shores of Loch Lomond. Designed by Tom Weiskopf, the course weaves through woodland and along the loch, offering stunning Highland scenery. Loch Lomond is one of the most exclusive and scenic courses in Scotland. Its role in the Scottish Open and its design quality place it in the world top 100. The course represents the best of modern Scottish golf and the marriage of natural beauty and championship design.' WHERE category = 'golf' AND title_en = 'Loch Lomond Golf Club';

UPDATE challenges SET description_en = 'Kingsbarns Golf Links in Fife, Scotland, hosts the Alfred Dunhill Links Championship and is a modern links that offers sea views from all 18 holes. Designed by Kyle Phillips and opened in 2000, Kingsbarns was built on farmland and created a links experience that rivals the classics. The course is long, strategic, and spectacularly set along the North Sea. Kingsbarns'' role in the Dunhill Links and its design have made it one of the most sought-after rounds in Scotland. The course secures its place in the world top 100 through quality and setting.' WHERE category = 'golf' AND title_en = 'Kingsbarns Golf Links';

UPDATE challenges SET description_en = 'Royal Dornoch Golf Club in the Scottish Highlands is Tom Watson''s favorite course and has hosted the Scottish Amateur and European Ladies Amateur. The course is a classic links set in a remote and beautiful part of Scotland. Royal Dornoch is consistently ranked among the world''s top 20 courses and is famous for its natural contours and strategic design. The course has influenced golf architecture worldwide. Royal Dornoch''s purity, history, and design quality place it in the world top 100 and make it a pilgrimage for golfers seeking the essence of links golf.' WHERE category = 'golf' AND title_en = 'Royal Dornoch Golf Club';

UPDATE challenges SET description_en = 'Portmarnock Golf Club on the Dublin peninsula in Ireland has hosted the Irish Open multiple times and the Walker Cup in 1991. The course is a classic links with no two holes playing in the same direction, ensuring a full test of wind. Portmarnock has been the benchmark for Irish links golf for over a century. Its role in the Irish Open and amateur golf, combined with its design quality, place it in the world top 100. The course represents the best of Irish links and the challenge of seaside golf.' WHERE category = 'golf' AND title_en = 'Portmarnock Golf Club';

UPDATE challenges SET description_en = 'Lahinch Golf Club Old Course in County Clare, Ireland, has hosted the Irish Open and is famous for its goats used as a traditional weather forecast. The Old Course is a classic links with blind shots, dramatic dunes, and the famous Dell hole. Lahinch has been a favorite of golfers visiting the west of Ireland for over a century. The course''s character, its role in Irish golf, and its unique features place it in the world top 100. Lahinch represents the fun and challenge of Irish links golf at its best.' WHERE category = 'golf' AND title_en = 'Lahinch Golf Club Old Course';

UPDATE challenges SET description_en = 'Crans-sur-Sierre Golf Club in Switzerland hosts the European Masters annually on the DP World Tour and is set at 1,500 meters in the Alps with views of Mont Blanc. The course offers a unique high-altitude golf experience and has been a fixture on the European Tour for decades. Crans-sur-Sierre combines Alpine scenery with championship golf and has seen many of the game''s greats compete. The course''s setting and its role in European Tour history place it in the world top 100. It represents the best of Swiss and Alpine golf.' WHERE category = 'golf' AND title_en = 'Crans-sur-Sierre Golf Club';

UPDATE challenges SET description_en = 'El Saler Golf Club near Valencia, Spain, has hosted the Spanish Open multiple times and was designed by Javier Arana in 1968. The course is set among Mediterranean dunes in the Albufera Natural Park and offers a links-style experience in Spain. El Saler has been a leader in Spanish golf and environmental stewardship. The course''s design, setting, and role in Spanish golf place it in the world top 100. El Saler represents the best of Mediterranean golf and the integration of course and nature.' WHERE category = 'golf' AND title_en = 'El Saler Golf Club';

UPDATE challenges SET description_en = 'TPC Southwind in Memphis, Tennessee, hosts the FedEx St Jude Championship annually, the first event of the PGA Tour playoffs. Designed by Ron Prichard and opened in 1989, the course features water on many holes and demands accuracy. TPC Southwind has been the scene of dramatic playoff moments and has raised millions for St. Jude Children''s Research Hospital. The course''s role in the FedEx Cup and its charitable impact place it in the world top 100. TPC Southwind represents the best of tour golf and community engagement.' WHERE category = 'golf' AND title_en = 'TPC Southwind';

UPDATE challenges SET description_en = 'TPC Deere Run in Silvis, Illinois, hosts the John Deere Classic annually and was designed by D.A. Weibring in 1987. The course is set in the Quad Cities region and has been a consistent stop on the PGA Tour. TPC Deere Run has seen multiple first-time winners and has been a springboard for young talent. The course''s role in the Tour calendar and its design place it in the world top 100. TPC Deere Run represents the heartland of American golf and the partnership between the Tour and its host communities.' WHERE category = 'golf' AND title_en = 'TPC Deere Run';

UPDATE challenges SET description_en = 'Spyglass Hill Golf Course in Pebble Beach, California, is part of the AT&T Pebble Beach Pro-Am rotation and was designed by Robert Trent Jones in 1966. The course starts in forest and descends toward the ocean, offering a unique blend of woodland and links-style holes. Spyglass is often considered the toughest of the Pebble Beach courses and has been a favorite of players. The course''s design, its role in the Pro-Am, and its setting place it in the world top 100. Spyglass represents the variety and quality of golf on the Monterey Peninsula.' WHERE category = 'golf' AND title_en = 'Spyglass Hill Golf Course';

UPDATE challenges SET description_en = 'Hirono Golf Club near Kobe, Japan, has hosted the Japan Open multiple times and is a Charles Alison masterpiece from 1932. The course is consistently ranked among the world''s top 50 and is considered one of the finest in Asia. Hirono features strategic bunkering, subtle greens, and classic design principles. The course has been preserved and refined with care. Hirono''s design quality and its place in Japanese golf history secure its position in the world top 100. The course is a model of classic architecture and a must-play in Japan.' WHERE category = 'golf' AND title_en = 'Hirono Golf Club';

UPDATE challenges SET description_en = 'Yomiuri Country Club in the Tokyo area hosts the Japan Open Golf Championship, Japan''s most prestigious open championship. The course has been the stage for many of the greatest moments in Japanese golf. Yomiuri is one of the most exclusive and respected clubs in Japan. The course''s role in the Japan Open and its place in Japanese golf place it in the world top 100. Yomiuri represents the pinnacle of Japanese club golf and the tradition of the Japan Open.' WHERE category = 'golf' AND title_en = 'Yomiuri Country Club';

UPDATE challenges SET description_en = 'Blue Canyon Country Club Canyon Course in Phuket, Thailand, hosted the Johnnie Walker Classic on the European Tour from 2000 to 2002. The course is set in a tropical landscape with dramatic elevation changes and strategic design. Blue Canyon brought international professional golf to Thailand and has remained one of the country''s premier courses. The course''s role in Asian golf and its design place it in the world top 100. Blue Canyon represents the growth of golf in Southeast Asia and the quality of Thai resort golf.' WHERE category = 'golf' AND title_en = 'Blue Canyon Country Club';

UPDATE challenges SET description_en = 'Woo Jeong Hills Country Club in Cheonan, South Korea, has hosted the CJ Cup, a PGA Tour event, and was designed with inspiration from Royal Portrush. The course features bentgrass surfaces and strategic design that tests the world''s best. Woo Jeong Hills has been at the forefront of bringing the PGA Tour to Korea. The course''s role in the CJ Cup and its design quality place it in the world top 100. Woo Jeong Hills represents the ambition of Korean golf and the growth of the game in Asia.' WHERE category = 'golf' AND title_en = 'Woo Jeong Hills Country Club';

UPDATE challenges SET description_en = 'Mission Hills Golf Club in Shenzhen, China, has hosted the WGC-HSBC World Match Play and is part of the world''s largest golf facility in Guanlan, Shenzhen. The resort has multiple courses and has been a leader in the growth of golf in China. Mission Hills has hosted numerous professional and amateur events and has brought global attention to Chinese golf. The facility''s scale and its role in Asian golf place it in the world top 100. Mission Hills represents the ambition and growth of golf in China.' WHERE category = 'golf' AND title_en = 'Mission Hills Golf Club Shenzhen';

UPDATE challenges SET description_en = 'Royal Adelaide Golf Club in South Australia has hosted the Australian Open multiple times and was designed by Alister MacKenzie in 1926. The course is a classic sand-belt layout with strategic bunkering and firm conditions. Royal Adelaide is consistently ranked among the best courses in Australia and the world. The course''s design heritage and its place in Australian golf secure its position in the world top 100. Royal Adelaide represents the best of Australian sand-belt golf and MacKenzie''s influence in the region.' WHERE category = 'golf' AND title_en = 'Royal Adelaide Golf Club';

UPDATE challenges SET description_en = 'New South Wales Golf Club in Sydney, Australia, has hosted the Australian Open and was designed by Alister MacKenzie on clifftop land with views of Botany Bay. The course is exposed to wind and offers dramatic ocean views. New South Wales is consistently ranked among the best courses in Australia and the world. The course''s setting and its MacKenzie design place it in the world top 100. New South Wales represents the best of Australian links-style golf and the beauty of Sydney''s coastline.' WHERE category = 'golf' AND title_en = 'New South Wales Golf Club';

UPDATE challenges SET description_en = 'Kauri Cliffs Golf Course in the Bay of Islands, New Zealand, has hosted the New Zealand Open and is consistently ranked by Golf Digest among the world''s top courses. The course offers 15 holes with ocean views and dramatic clifftop terrain. Kauri Cliffs is one of the most scenic courses in the world and has become a bucket-list destination. The course''s design, setting, and role in New Zealand golf place it in the world top 100. Kauri Cliffs represents the best of Pacific golf and the natural beauty of New Zealand.' WHERE category = 'golf' AND title_en = 'Kauri Cliffs Golf Course';

UPDATE challenges SET description_en = 'Abu Dhabi Golf Club in the UAE hosts the Abu Dhabi HSBC Championship annually on the DP World Tour. The Championship Course was designed by Peter Harradine in 1997 and features desert landscaping and strategic design. Abu Dhabi has been at the forefront of Middle Eastern golf and has attracted the world''s best. The course''s role in the European Tour and its setting place it in the world top 100. Abu Dhabi Golf Club represents the growth of golf in the UAE and the fusion of desert and championship golf.' WHERE category = 'golf' AND title_en = 'Abu Dhabi Golf Club';

UPDATE challenges SET description_en = 'Leopard Creek Country Club in Malelane, South Africa, hosts the Alfred Dunhill Championship and borders Kruger National Park. The course is famous for holes 3, 4, and 5, which run along the Crocodile River where crocodiles and hippos are often seen. Leopard Creek is one of the most unique settings in world golf. The course''s wildlife, design, and role in South African golf place it in the world top 100. Leopard Creek represents the best of African safari golf and the marriage of golf and conservation.' WHERE category = 'golf' AND title_en = 'Leopard Creek Country Club';

UPDATE challenges SET description_en = 'Durban Country Club in KwaZulu-Natal, South Africa, has hosted the South African Open multiple times and was designed by George Waterman in 1920. The course offers Indian Ocean views and has been a pillar of South African golf for over a century. Durban Country Club has hosted numerous professional and amateur championships. The course''s history, design, and role in South African golf place it in the world top 100. Durban represents the best of Natal golf and the tradition of South African championship golf.' WHERE category = 'golf' AND title_en = 'Durban Country Club';

UPDATE challenges SET description_en = 'PGA Catalunya Stadium Course in Girona, Spain, hosted the Solheim Cup in 2023 and the Spanish Open. The Stadium Course features extensive water features and modern championship design. PGA Catalunya has become one of the premier golf destinations in Spain and Europe. The course''s role in the Solheim Cup and its design place it in the world top 100. PGA Catalunya represents the best of modern Spanish golf and the growth of the game in Catalonia.' WHERE category = 'golf' AND title_en = 'PGA Catalunya Stadium Course';

UPDATE challenges SET description_en = 'Golf Club Gut Lärchenhof in Cologne, Germany, hosts the BMW International Open on the European Tour. The course was designed by Bernhard Langer and offers a modern championship test. Gut Lärchenhof has been a fixture on the European Tour and has brought top-level golf to Germany. The course''s role in German golf and its design place it in the world top 100. Gut Lärchenhof represents the best of German golf and the growth of the game in central Europe.' WHERE category = 'golf' AND title_en = 'Golf Club Gut Lärchenhof';

UPDATE challenges SET description_en = 'El Camaleón Golf Club at Mayakoba in Mexico hosts the World Wide Technology Championship on the PGA Tour. Designed by Greg Norman, the course is set in the Riviera Maya and features mangrove and tropical landscape. El Camaleón was the first PGA Tour venue in Mexico and has been a pioneer for golf in Latin America. The course''s role in the Tour and its unique setting place it in the world top 100. El Camaleón represents the growth of golf in Mexico and the Caribbean.' WHERE category = 'golf' AND title_en = 'El Camaleón Golf Club';

UPDATE challenges SET description_en = 'Albany Golf Course in New Providence, Bahamas, hosts the Hero World Challenge, Tiger Woods''s annual event that attracts a small field of the world''s best. Designed by Ernie Els, the course is part of an exclusive resort community. Albany has become a winter destination for elite players and has been the site of comebacks and season-ending drama. The course''s role in the Hero World Challenge and its design place it in the world top 100. Albany represents the best of Caribbean golf and the intersection of luxury and championship golf.' WHERE category = 'golf' AND title_en = 'Albany Golf Course, Bahamas';

UPDATE challenges SET description_en = 'Mid Ocean Club in Tucker''s Town, Bermuda, was designed by Charles Blair Macdonald in 1921 and has been used for Bermuda Championship qualifying. The course is a classic design set along the Atlantic with ocean views and strategic bunkering. Mid Ocean is one of the oldest and most respected courses in the Atlantic and has hosted numerous amateur and professional events. The course''s history and design place it in the world top 100. Mid Ocean represents the best of Bermuda golf and the golden age of golf architecture.' WHERE category = 'golf' AND title_en = 'Mid Ocean Club';

UPDATE challenges SET description_en = 'Port Royal Golf Course in Southampton, Bermuda, hosts the Bermuda Championship on the PGA Tour. Designed by Robert Trent Jones Sr. and opened in 1970, the course is set along the ocean with dramatic views and strategic design. Port Royal has brought the PGA Tour to Bermuda and has become a favorite of players for its beauty and challenge. The course''s role in the Tour and its setting place it in the world top 100. Port Royal represents the best of Bermuda golf and the growth of the game in the Atlantic.' WHERE category = 'golf' AND title_en = 'Port Royal Golf Course';
