-- schema-v19-descriptions-museums.sql: Extended English descriptions for museums category (world 100)
-- Each description_en 500-1000 characters: why among world 100, collections, history, unique features.

UPDATE challenges SET description_en = 'The Louvre is the world''s largest art museum and a historic monument in Paris. It is the world''s most visited museum, with over 35,000 works from antiquity to the 21st century. Housed in the Louvre Palace, originally a fortress from the late 12th century, it became a public museum during the French Revolution. Its collections include the Mona Lisa, the Venus de Milo, the Winged Victory of Samothrace, and countless masterpieces of Western art. The glass pyramid entrance by I. M. Pei has become an icon. The museum''s breadth—Egyptian antiquities, Near Eastern and Islamic art, Greek and Roman, European painting and sculpture—makes it essential to any list of the world''s top museums.' WHERE category = 'museums' AND title_en = 'Louvre Museum';

UPDATE challenges SET description_en = 'The British Museum in London holds over 8 million objects spanning two million years of human history. Founded in 1753, it was one of the first national public museums in the world. Highlights include the Rosetta Stone, which unlocked Egyptian hieroglyphs; the Parthenon (Elgin) Marbles; Egyptian mummies and the Lewis Chessmen. The collection was largely formed during the British Empire and represents every continent. The Great Court, with its Norman Foster–designed glass roof over the former Reading Room, is a landmark. Free admission and its role in scholarship and public education secure its place among the world''s greatest museums.' WHERE category = 'museums' AND title_en = 'British Museum';

UPDATE challenges SET description_en = 'The Metropolitan Museum of Art, or the Met, on Fifth Avenue in New York City is the largest art museum in the Americas. Its permanent collection exceeds two million works spanning 5,000 years. The Met was founded in 1870 and moved to its current Beaux-Arts building in 1880. It holds major holdings of Egyptian art, arms and armour, European paintings (including Vermeer, Rembrandt, and Velázquez), American decorative arts, and modern and contemporary art. The Temple of Dendur and the American Wing are visitor favourites. The Met''s scope and quality make it a cornerstone of the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'The Met (Metropolitan Museum of Art)';

UPDATE challenges SET description_en = 'The Smithsonian National Museum of Natural History in Washington, D.C., is one of the most visited natural history museums in the world. It holds over 148 million specimens and objects—plants, fossils, minerals, rocks, meteorites, and cultural artefacts. Highlights include the Hope Diamond, the world''s most famous gem; a permanent dinosaur hall with a Tyrannosaurus rex; and the Hall of Human Origins. Founded in 1910, the museum is part of the Smithsonian Institution and offers free admission. Its research and public exhibitions on evolution, biodiversity, and the natural world justify its inclusion among the world''s top museums.' WHERE category = 'museums' AND title_en = 'Smithsonian National Museum of Natural History';

UPDATE challenges SET description_en = 'The State Hermitage Museum in Saint Petersburg is one of the largest and oldest museums in the world. It was founded in 1764 by Catherine the Great and occupies the Winter Palace and several adjacent buildings. The collection comprises over three million items, including the world''s largest collection of paintings and one of the finest collections of Rembrandt (33 works). It holds masterpieces of Italian, Dutch, and Flemish art, antiquities, and decorative arts. The palace interiors and the scale of the collection make the Hermitage unmissable among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'State Hermitage Museum';

UPDATE challenges SET description_en = 'The Vatican Museums in Vatican City comprise 54 galleries and some of the most significant art and antiquities in the world. They originated from the papal collections and include the Sistine Chapel with Michelangelo''s ceiling and Last Judgment, the Raphael Rooms, the Gallery of Maps, and classical sculpture such as the Laocoön. The museums are housed in part of the Apostolic Palace. The sheer concentration of Renaissance and classical masterpieces, combined with the spiritual and historical importance of the site, places the Vatican Museums firmly among the world''s top museums.' WHERE category = 'museums' AND title_en = 'Vatican Museums';

UPDATE challenges SET description_en = 'The National Palace Museum in Taipei holds one of the finest collections of Chinese imperial art and artefacts in the world—around 700,000 pieces spanning 8,000 years. Many objects were moved from the Forbidden City in Beijing to Taiwan in the mid-20th century. Highlights include the Jadeite Cabbage, the Meat-shaped Stone, and countless bronzes, calligraphy, and paintings. The collection represents the essence of Chinese cultural heritage. Its role as the premier repository of Chinese imperial collections outside mainland China secures its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Palace Museum';

UPDATE challenges SET description_en = 'The Egyptian Museum in Cairo, on Tahrir Square, houses the world''s largest collection of Pharaonic antiquities—over 120,000 items. Opened in 1902, it is famous for the treasures of Tutankhamun, including the gold mask and coffins. The Royal Mummies Hall holds the remains of pharaohs and queens. The museum''s collection spans from the Predynastic period to the Roman era. Despite the move of many objects to the Grand Egyptian Museum, the Egyptian Museum remains iconic and central to any list of the world''s greatest museums.' WHERE category = 'museums' AND title_en = 'Egyptian Museum, Cairo';

UPDATE challenges SET description_en = 'The National Museum of India in New Delhi is the country''s largest museum, with over 200,000 works of art and archaeology. It was established in 1949 and is located on Janpath. The collection includes Harappan seals and artefacts, Mughal paintings, Buddhist and Hindu sculpture, textiles, and arms. The Bronze Gallery and the Central Asian Antiquities collection are notable. As the flagship museum of Indian heritage, it represents 5,000 years of Indian history and culture and belongs among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of India, New Delhi';

UPDATE challenges SET description_en = 'The National Archaeological Museum in Athens is the largest archaeological museum in Greece and among the most important in the world for ancient Greek art. It holds artefacts from prehistory to late antiquity. Highlights include the gold mask of Agamemnon from Mycenae, the Antikythera mechanism (an ancient analogue computer), the Artemision Bronze, and the Marathon youth. The museum was founded in the 19th century. Its concentration of Greek masterpieces makes it essential to any list of the world''s top museums.' WHERE category = 'museums' AND title_en = 'National Archaeological Museum Athens';

UPDATE challenges SET description_en = 'The Pergamon Museum on Berlin''s Museum Island is one of the world''s most visited museums. It houses monumental reconstructions of ancient architecture: the Pergamon Altar (2nd century BC), the Ishtar Gate and Processional Way of Babylon, and the Market Gate of Miletus. The collection also includes Islamic art and the Aleppo Room. The museum was built in the early 20th century to display large-scale excavations. Its unique combination of monumental antiquities and immersive displays secures its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Pergamon Museum, Berlin';

UPDATE challenges SET description_en = 'The Prado Museum in Madrid is Spain''s national art museum and one of the world''s finest collections of European art. It holds masterpieces by Goya, Velázquez (including Las Meninas), El Greco, Rubens, and Titian. The collection was formed by the Spanish Crown and focuses on the 12th to early 20th centuries. The building, designed by Juan de Villanueva, opened as a museum in 1819. The Prado''s depth in Spanish and Flemish painting and its role as guardian of Spain''s artistic heritage place it among the world''s top museums.' WHERE category = 'museums' AND title_en = 'Prado Museum';

UPDATE challenges SET description_en = 'The Uffizi Gallery in Florence is one of the oldest and most famous art museums in the world. Housed in a 16th-century palazzo built for the Medici, it holds the core of the Italian Renaissance: Botticelli''s Birth of Venus and Primavera, works by Raphael, Michelangelo, Leonardo, and Caravaggio. The collection was bequeathed to the city by the Medici family. The Uffizi''s concentration of Renaissance masterpieces and its role in the history of collecting make it indispensable among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Uffizi Gallery';

UPDATE challenges SET description_en = 'The Natural History Museum in London is one of the world''s leading natural history museums. Its Victorian Romanesque building in South Kensington houses over 80 million specimens. Highlights include the blue whale skeleton in Hintze Hall, dinosaur galleries (including Dippy and a blue whale model), the Darwin Centre, and the Hope meteorite. The museum was founded in 1881 and is free to visit. Its scientific research, public engagement, and iconic architecture secure its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Natural History Museum, London';

UPDATE challenges SET description_en = 'The Victoria and Albert Museum in London is the world''s leading museum of art, design, and performance. It holds over 4.5 million objects spanning 5,000 years: sculpture, ceramics, furniture, fashion, textiles, metalwork, and photography. Founded in 1852 and named after Queen Victoria and Prince Albert, the V&A occupies a vast Victorian and Edwardian building in South Kensington. Admission to the permanent collection is free. Its breadth and depth in decorative arts and design justify its inclusion among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Victoria and Albert Museum';

UPDATE challenges SET description_en = 'The Tokyo National Museum in Ueno Park is Japan''s oldest and largest national museum, founded in 1872. It holds over 120,000 objects of Japanese and Asian art and archaeology, including Buddhist sculpture, swords, ceramics, ukiyo-e, and archaeological finds. The Honkan (Japanese Gallery), Toyokan (Asian Gallery), and the Gallery of Horyu-ji Treasures are major wings. The museum''s role as the premier repository of Japanese cultural heritage and its scholarly exhibitions place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Tokyo National Museum';

UPDATE challenges SET description_en = 'The National Museum of Korea in Yongsan, Seoul, is the flagship museum of Korean history and art. It holds over 220,000 objects, including the Gyeongcheonsa Pagoda, celadon ware, gold crowns from Silla, and Buddhist art. The museum moved to its current building in 2005 and offers free permanent exhibitions. Its mission is to preserve and present Korean cultural heritage from prehistory to the modern era. Its collection and free access make it essential among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Korea';

UPDATE challenges SET description_en = 'The National Museum of China on the eastern side of Tiananmen Square in Beijing is one of the largest museums in the world. It was formed in 2003 by merging the Museum of the Chinese Revolution and the National Museum of Chinese History. The collection of over 1.4 million objects includes Bronze Age vessels, jade burial suits, imperial treasures, and modern historical artefacts. The building was expanded for the 2011 reopening. Its role as the national narrative of Chinese civilisation places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of China';

UPDATE challenges SET description_en = 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (formerly Prince of Wales Museum) in Mumbai is one of India''s premier museums. Housed in a striking Indo-Saracenic building completed in 1915, it holds collections of Indian art, archaeology, and natural history. Highlights include Mughal miniatures, decorative arts, armour, and the natural history section. The museum was renamed in honour of the Maratha king Shivaji. Its building and collections of Indian and colonial-era material secure its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya';

UPDATE challenges SET description_en = 'The Istanbul Archaeological Museums comprise three institutions near Topkapi Palace: the Archaeological Museum, the Museum of the Ancient Orient, and the Tiled Kiosk. They hold over one million objects from the ancient Near East, Greece, Rome, and Byzantium. Highlights include the Alexander Sarcophagus and the Treaty of Kadesh (one of the oldest known peace treaties). The museums were founded in the late 19th century. Their unique position at the crossroads of civilisations places them among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Istanbul Archaeological Museums';

UPDATE challenges SET description_en = 'The Grand Egyptian Museum (GEM) near the Giza pyramids is the world''s largest archaeological museum dedicated to a single civilisation. It was designed to house the full Tutankhamun collection (over 5,000 items) and tens of thousands of other Egyptian antiquities. The building and exhibitions use modern technology and conservation standards. Its scale, focus on ancient Egypt, and location at the doorstep of the pyramids secure its place among the world''s top 100 museums despite its recent opening.' WHERE category = 'museums' AND title_en = 'Grand Egyptian Museum (GEM)';

UPDATE challenges SET description_en = 'The Field Museum in Chicago is one of the largest natural history museums in the world. It holds over 40 million specimens and cultural objects. Sue, the most complete Tyrannosaurus rex ever found, is the star of the dinosaur hall. Other highlights include Egyptian mummies, Pacific Islander and Native American collections, and the Grainger Hall of Gems. The museum was founded in 1893 for the World''s Columbian Exposition. Its research and public exhibitions place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Field Museum, Chicago';

UPDATE challenges SET description_en = 'The American Museum of Natural History on the Upper West Side of New York City is one of the world''s largest natural history museums. It comprises over 34 million specimens and cultural artefacts. Highlights include the blue whale model in the Hall of Ocean Life, dinosaur halls (including Tyrannosaurus and Apatosaurus), the Rose Center for Earth and Space with the Hayden Planetarium, and the Margaret Mead Hall of Pacific Peoples. Founded in 1869, the museum''s research and iconic dioramas secure its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'American Museum of Natural History';

UPDATE challenges SET description_en = 'The Smithsonian National Air and Space Museum in Washington, D.C., holds the world''s largest collection of aviation and space artefacts. Highlights include the Wright Brothers'' Flyer, the Apollo 11 command module Columbia, the Spirit of St. Louis, and an SR-71 Blackbird. The museum is part of the Smithsonian and offers free admission. A second location, the Steven F. Udvar-Hazy Center in Virginia, displays larger aircraft. Its role in telling the story of flight and space exploration places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Smithsonian Air & Space Museum';

UPDATE challenges SET description_en = 'The Royal Ontario Museum (ROM) in Toronto is Canada''s largest museum of world cultures and natural history. It holds over one million objects: dinosaurs, minerals and gems, Indigenous Canadian and Asian art, and Egyptian and Near Eastern antiquities. The crystal-shaped Michael Lee-Chin Crystal addition opened in 2007. The ROM was formed in 1912. Its breadth of collections and role as Canada''s premier encyclopedic museum place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Royal Ontario Museum';

UPDATE challenges SET description_en = 'The Australian Museum in Sydney is Australia''s first museum, founded in 1827. It is the country''s leading natural history and cultural institution, with collections of minerals, fossils, Indigenous Australian and Pacific Islander culture, and biodiversity. Highlights include dinosaur and wildlife exhibitions and the Pacific Spirit gallery. The museum has undergone major renewal in the 21st century. Its history and role in Australian and Pacific scholarship place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Australian Museum, Sydney';

UPDATE challenges SET description_en = 'The Melbourne Museum is the largest museum in the Southern Hemisphere and is located in the Carlton Gardens. It holds collections of natural history, Indigenous culture (Bunjilaka Aboriginal Cultural Centre), history, and technology. Highlights include the exhibition on Phar Lap, the famous racehorse, and the Forest Gallery. The building opened in 2000. The museum''s focus on Victoria and Australia, combined with its scale and design, secures its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Melbourne Museum';

UPDATE challenges SET description_en = 'The de Young Museum in San Francisco''s Golden Gate Park is one of the city''s premier art museums. It holds American art from the 17th through 21st centuries, as well as significant collections of African, Oceanic, and textile art. The building, redesigned by Herzog & de Meuron and opened in 2005, features a copper-clad tower. The de Young was founded in 1895. Its collections and setting in Golden Gate Park place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'de Young Museum, San Francisco';

UPDATE challenges SET description_en = 'The Rijksmuseum in Amsterdam is the national museum of the Netherlands, dedicated to Dutch art and history. Its collection includes Rembrandt''s The Night Watch, Vermeer''s The Milkmaid, and masterpieces of the Dutch Golden Age. The building, restored and reopened in 2013, is a landmark of Dutch Neo-Renaissance architecture. The museum was founded in 1800. The Rijksmuseum''s concentration of Dutch masterpieces and its role as the keeper of the nation''s artistic heritage place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Rijksmuseum, Amsterdam';

UPDATE challenges SET description_en = 'The Anne Frank House in Amsterdam is the building where Anne Frank and her family hid from Nazi persecution during World War II. Visitors see the secret annex and the original diary. The museum was established in 1960 to preserve the hiding place and to promote Anne''s message of tolerance. It is one of the most visited sites in the Netherlands. Its unique role in Holocaust memory and human rights education secures its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Anne Frank House';

UPDATE challenges SET description_en = 'The Auschwitz-Birkenau State Museum in Oświęcim, Poland, preserves the former Nazi German concentration and extermination camp. It is a UNESCO World Heritage Site and the most visited Holocaust memorial in the world. The museum preserves barracks, ruins of gas chambers and crematoria, and personal belongings of victims. It was established in 1947. Its role in remembrance, education, and warning against genocide places it among the world''s top 100 museums, despite the gravity of its subject.' WHERE category = 'museums' AND title_en = 'Auschwitz-Birkenau State Museum';

UPDATE challenges SET description_en = 'The Warsaw Rising Museum commemorates the 1944 Warsaw Uprising against Nazi occupation. Opened in 2004, it uses multimedia, reconstructions, and personal testimonies to tell the story of the 63-day uprising and its suppression. The museum is housed in a former tram power station. Its immersive approach and importance to Polish memory of World War II secure its place among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Warsaw Rising Museum';

UPDATE challenges SET description_en = 'The Reina Sofía Museum in Madrid is Spain''s national museum of 20th-century art. It is best known for Picasso''s Guernica, as well as major works by Dalí, Miró, and Spanish and international modern and contemporary artists. The museum is housed in a former hospital and was expanded with a new building by Jean Nouvel. Founded in 1992, the Reina Sofía''s holdings and role in Spanish modern art place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Reina Sofia Museum, Madrid';

UPDATE challenges SET description_en = 'Tate Modern in London is the United Kingdom''s national museum of international modern and contemporary art. Housed in the former Bankside Power Station, it opened in 2000 and has become one of the world''s most visited art museums. The collection includes works by Rothko, Warhol, Dalí, and Hockney. The Turbine Hall hosts large-scale installations. Admission to the permanent collection is free. Tate Modern''s building, collection, and impact on contemporary culture place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Tate Modern, London';

UPDATE challenges SET description_en = 'The Centre Pompidou in Paris houses the Musée National d''Art Moderne and is one of the world''s leading institutions for modern and contemporary art. The building, with its exposed structure and coloured ducts, was designed by Renzo Piano and Richard Rogers and opened in 1977. The collection includes works by Kandinsky, Matisse, Chagall, and many 20th- and 21st-century artists. The Centre also has a public library and performance spaces. Its architecture and collection place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Centre Pompidou, Paris';

UPDATE challenges SET description_en = 'The Oceanographic Museum of Monaco is a marine science museum built on the cliff of Monaco. It was inaugurated in 1910 and was directed by Jacques-Yves Cousteau from 1957 to 1988. The museum houses aquariums, collections of marine specimens, and exhibits on oceanography and maritime history. The building itself is an architectural landmark. Its history, association with Cousteau, and focus on the sea place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Oceanographic Museum of Monaco';

UPDATE challenges SET description_en = 'The Natural History Museum Vienna is one of the largest natural history museums in the world. It holds over 30 million objects and is housed in a palatial building on the Ringstraße, opened in 1889. Highlights include the Venus of Willendorf (c. 28,000 BC), an extensive meteorite collection, and the Hall of Dinosaurs. The museum''s historical collections, including those of Maria Theresa, and its research role place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Natural History Museum Vienna';

UPDATE challenges SET description_en = 'The Gold Museum (Museo del Oro) in Bogotá holds one of the world''s finest collections of pre-Columbian gold—over 55,000 pieces from indigenous cultures of Colombia. The exhibition explores the techniques, symbolism, and cultural context of goldworking and is linked to the legend of El Dorado. The museum is part of the Banco de la República. Its unique focus on pre-Columbian gold and its quality place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Gold Museum (Museo del Oro), Bogota';

UPDATE challenges SET description_en = 'The Larco Museum in Lima is a private museum of pre-Columbian art housed in an 18th-century vice regal building in Pueblo Libre. It holds one of the world''s largest collections of Peruvian antiquities: ceramics (including the famous erotic ceramics gallery), textiles, and gold and silver. The museum was founded by Rafael Larco Hoyle in 1926. Its comprehensive presentation of pre-Columbian Peru and its beautiful setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Larco Museum, Lima';

UPDATE challenges SET description_en = 'The Museo Nacional de Antropología in Mexico City is Mexico''s largest and most visited museum. It holds archaeological and ethnographic collections from pre-Columbian and indigenous cultures of Mexico. Highlights include the Aztec Sun Stone (Calendar Stone), the reconstruction of Pakal''s tomb from Palenque, and the model of Tenochtitlan. The building, with its famous umbrella fountain, opened in 1964. Its role as the guardian of Mexico''s ancient heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Museo Nacional de Antropologia, Mexico City';

UPDATE challenges SET description_en = 'The Palenque Archaeological Museum is the site museum for the Maya ruins of Palenque in Chiapas. It houses finds from the site, including the jade funeral mask of K''inich Janaab'' Pakal and other treasures from the Temple of the Inscriptions. The museum provides context for the ruins and protects fragile objects. Its intimate connection to one of the greatest Maya sites places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Palenque Archaeological Museum';

UPDATE challenges SET description_en = 'MASP (Museu de Arte de São Paulo) on Avenida Paulista is one of Latin America''s most important art museums. Its collection includes European masters (Raphael, Van Gogh, Renoir) and Brazilian art. The building, designed by Lina Bo Bardi, is famous for displaying paintings in clear glass frames so both sides are visible. MASP was founded in 1947. Its collection, architecture, and iconic status in São Paulo place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'MASP (Sao Paulo Museum of Art)';

UPDATE challenges SET description_en = 'MALBA (Museo de Arte Latinoamericano de Buenos Aires) in Palermo holds one of the finest collections of Latin American art from the 20th and 21st centuries. It includes works by Frida Kahlo, Diego Rivera, Antonio Berni, and other masters. The building was designed for the museum and opened in 2001. MALBA''s focus on Latin American modern and contemporary art and its role in the region''s cultural life place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'MALBA, Buenos Aires';

UPDATE challenges SET description_en = 'The Sydney Jewish Museum in Darlinghurst is dedicated to the history of the Holocaust and Australian Jewish life. It was founded by survivors and combines historical exhibitions with testimony from survivors, many of whom have volunteered at the museum. The museum educates on the Holocaust, antisemitism, and human rights. Its unique combination of memory, education, and survivor presence places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Sydney Jewish Museum';

UPDATE challenges SET description_en = 'The Picasso Museum in Barcelona holds one of the most comprehensive collections of Pablo Picasso''s work, with emphasis on his early years and connection to the city. It is housed in several medieval palaces in the El Born district. The collection includes paintings, drawings, and ceramics. The museum opened in 1963. Its focus on Picasso''s formative period and its setting in Barcelona place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Picasso Museum, Barcelona';

UPDATE challenges SET description_en = 'The Deutsches Museum in Munich is one of the world''s largest museums of science and technology. It holds around 73,000 objects and covers fields such as physics, chemistry, mining, transport, and musical instruments. Exhibitions are hands-on and include full-size aircraft, submarines, and historical machinery. The museum was founded in 1903 and is housed on an island in the Isar. Its scale and approach to science and technology place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Deutsches Museum, Munich';

UPDATE challenges SET description_en = 'The Leonardo da Vinci Museum of Science and Technology in Milan is housed in a former monastery. It holds over 500 models and reconstructions based on Leonardo''s drawings, including flying machines, war engines, and anatomical studies. The museum also covers Italian science and industry, with sections on railways and shipping. Founded in 1953, it is the largest science and technology museum in Italy. Its focus on Leonardo and Italian innovation place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Leonardo da Vinci Museum of Science';

UPDATE challenges SET description_en = 'The Science Museum in London is one of the world''s leading science museums. It holds collections on science, technology, medicine, and industry. Highlights include the Stephenson Rocket, Apollo 10 command module, and a model of the DNA structure by Crick and Watson. The museum was founded in 1857 and is free to visit. Its interactive galleries and historical objects place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Science Museum, London';

UPDATE challenges SET description_en = 'The Museum of Science and Industry in Chicago is one of the largest science museums in the world. It is housed in the former Palace of Fine Arts from the 1893 World''s Columbian Exposition. Highlights include the captured German U-505 submarine, the Coal Mine exhibit, and the baby chick hatchery. The museum covers transport, energy, and communications. Its scale and iconic exhibits place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Museum of Science and Industry, Chicago';

UPDATE challenges SET description_en = 'The Getty Center in Los Angeles is an art museum and research campus on a hilltop in Brentwood. The collection includes European paintings (Van Gogh''s Irises, works by Rembrandt and Monet), sculpture, decorative arts, and photography. The complex, designed by Richard Meier, includes gardens and sweeping views of Los Angeles. Admission is free; parking is paid. The Getty Trust''s resources, the quality of the collection, and the setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Getty Center, Los Angeles';

UPDATE challenges SET description_en = 'The Guggenheim Museum in New York is one of the world''s most famous art museums, in part because of its building—a spiral design by Frank Lloyd Wright completed in 1959. The collection includes modern and contemporary art: Kandinsky, Pollock, Picasso, and many others. The museum was established by the Solomon R. Guggenheim Foundation. Its architecture and collection place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Guggenheim Museum, New York';

UPDATE challenges SET description_en = 'The Guggenheim Museum Bilbao is a museum of modern and contemporary art designed by Frank Gehry. The building, with its titanium curves, has become an icon of Bilbao and of contemporary architecture. The collection includes works by Richard Serra, Jeff Koons (including the Puppy flower sculpture outside), and other international artists. Opened in 1997, the museum transformed Bilbao''s image. Its architecture and role in the Guggenheim network place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Guggenheim Museum Bilbao';

UPDATE challenges SET description_en = 'The Vasa Museum in Stockholm is dedicated to the Vasa, a 17th-century Swedish warship that sank on its maiden voyage in 1628 and was raised in 1961. The ship is preserved to an exceptional degree (about 95% original) and is displayed in a custom-built museum on Djurgården. Exhibitions cover the ship''s construction, crew, and the historical context. The Vasa Museum is one of Scandinavia''s most visited museums and belongs among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Vasa Museum, Stockholm';

UPDATE challenges SET description_en = 'The Viking Ship Museum in Oslo (on the Bygdøy peninsula) displays the Oseberg, Gokstad, and Tune Viking ships—burial vessels from the 9th century. The Oseberg ship is one of the best-preserved Viking ships in the world. The museum also holds grave goods from the ship burials. The museum has been a major tourist attraction since the early 20th century. A new museum building is planned. Its unique Viking ship collection places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Viking Ship Museum, Oslo';

UPDATE challenges SET description_en = 'The National Museum of Denmark in Copenhagen is the country''s largest museum of cultural history and archaeology. It holds the Tollund Man (a well-preserved bog body), Viking artefacts, the Sun Chariot, and collections from prehistory to the present. The museum is housed in the former Prince''s Palace. Its comprehensive coverage of Danish and Nordic history and its iconic objects place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Denmark';

UPDATE challenges SET description_en = 'The National Museum of Finland in Helsinki presents Finnish history from prehistory to the present. The building, in National Romantic style, dates from 1916. The collections include archaeological finds, ethnography, and cultural history. The museum is part of the National Museum of Finland organisation. Its role as the premier repository of Finnish heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Finland';

UPDATE challenges SET description_en = 'The Kunsthistorisches Museum in Vienna houses the art collections of the Habsburg dynasty. The building on the Ringstraße opened in 1891. The picture gallery includes Vermeer''s The Art of Painting, works by Raphael, Bruegel, and Caravaggio, and one of the world''s finest collections of Old Masters. The museum also holds antiquities, decorative arts, and the Imperial Armoury. Its collection and architecture place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Kunsthistorisches Museum Vienna';

UPDATE challenges SET description_en = 'The Dresden State Art Collections (Staatliche Kunstsammlungen Dresden) comprise several museums in Dresden. The most famous include the Gemäldegalerie Alte Meister (Old Masters Picture Gallery), with Raphael''s Sistine Madonna, and the Grünes Gewölbe (Green Vault), with treasures of the Saxon electors and kings. The collections were largely formed in the 18th century. Their quality and the reconstruction after wartime damage place them among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Dresden State Art Collections';

UPDATE challenges SET description_en = 'The Thyssen-Bornemisza Museum in Madrid holds the former private collection of the Thyssen-Bornemisza family, now state-owned. It spans from medieval and Renaissance art to 20th-century masters (Van Eyck, Dürer, Caravaggio, Hopper, and many others). The collection fills a gap between the Prado''s historical focus and the Reina Sofía''s modern art. The museum opened in 1992. Its breadth and quality place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Thyssen-Bornemisza Museum, Madrid';

UPDATE challenges SET description_en = 'The Bargello Museum in Florence is Italy''s national museum of sculpture and decorative arts. Housed in a medieval palace that once served as a prison, it holds Renaissance masterpieces: Donatello''s David, Michelangelo''s Bacchus, and works by Giambologna and Cellini. The collection also includes maiolica, ivory, and arms. The Bargello is essential for understanding Renaissance sculpture and belongs among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Bargello Museum, Florence';

UPDATE challenges SET description_en = 'The National Archaeological Museum of Naples holds one of the world''s finest collections of Roman antiquities, especially from Pompeii and Herculaneum. It includes the Farnese Hercules, the Alexander Mosaic, and the Secret Cabinet (erotic antiquities). The museum was founded in the 18th century when the Bourbon kings assembled antiquities from the Vesuvian sites. Its unique concentration of Roman and Greek material from the Bay of Naples places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Archaeological Museum Naples';

UPDATE challenges SET description_en = 'The Borghese Gallery in Rome is housed in the Villa Borghese and holds the Borghese collection of paintings and sculpture. It includes major works by Bernini (Apollo and Daphne, David), Caravaggio, and Raphael. Access is by timed ticket with a two-hour limit to manage crowds. The villa and gardens are part of the experience. The quality of the collection and the controlled visit place the Borghese among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Borghese Gallery, Rome';

UPDATE challenges SET description_en = 'The National Museum of Iran in Tehran holds artefacts from Iran''s ancient and Islamic past. The collection spans the Achaemenid, Parthian, Sassanid, and Islamic periods and includes pottery, metalwork, and sculpture. The museum was founded in the early 20th century. Despite political challenges, it remains the primary repository of Iranian antiquities. Its role in preserving and presenting Iran''s heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Iran, Tehran';

UPDATE challenges SET description_en = 'The Topkapi Palace Museum in Istanbul was the main residence of the Ottoman sultans for nearly 400 years. It now houses imperial collections: armour, manuscripts, ceramics, and the famous treasury (including the Spoonmaker''s Diamond and the Topkapi Dagger). The Sacred Trusts section holds relics important to Islam. The palace complex and its collections offer a unique window on Ottoman court life and place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Topkapi Palace Museum';

UPDATE challenges SET description_en = 'The Coptic Museum in Cairo holds the world''s largest collection of Coptic Christian art and artefacts. It includes textiles, icons, manuscripts, and stonework from the Coptic period in Egypt. The museum was founded in 1910 and is located in Coptic Cairo. The Nag Hammadi codices were once stored here. The museum''s unique focus on Coptic heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Coptic Museum, Cairo';

UPDATE challenges SET description_en = 'The Bardo National Museum in Tunis holds one of the world''s finest collections of Roman mosaics, with over 3,000 square metres of mosaics from sites across Tunisia. It is housed in a former beylic palace. The collection also includes Punic, Roman, and Islamic artefacts. The Bardo has been a museum since the late 19th century. Its mosaic collection and setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Bardo National Museum, Tunis';

UPDATE challenges SET description_en = 'The Museum of Black Civilizations in Dakar opened in 2018 and is one of the first major museums built in Africa to present pan-African civilisations from an African perspective. The building and concept were developed by Senegal and the African Union. The museum aims to reclaim and showcase African heritage and contributions to world civilisation. Its symbolic and cultural importance places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Museum of Black Civilizations, Dakar';

UPDATE challenges SET description_en = 'The National Museum of Ghana in Accra is the country''s flagship museum of history and culture. It holds collections of Ashanti regalia, kente cloth, traditional art, and archaeological finds. The museum was established in 1957, the year of Ghana''s independence. It plays a key role in preserving and presenting Ghanaian heritage. Its importance to West African museology places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Ghana';

UPDATE challenges SET description_en = 'The Iziko South African Museum in Cape Town is one of South Africa''s oldest and largest museums. It holds collections of natural history (including a whale skeleton), San rock art, and Cape history. The museum is part of the Iziko Museums of South Africa. Its role in documenting South African natural and cultural heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Iziko South African Museum';

UPDATE challenges SET description_en = 'The National Museum of Kenya in Nairobi holds collections of palaeontology, ethnography, and history. It is associated with the work of Louis Leakey and holds fossils from the Rift Valley. The museum also displays works by Joy Adamson and artefacts of Kenyan cultures. Its role in human evolution research and Kenyan heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Kenya';

UPDATE challenges SET description_en = 'The National Museum of Tanzania in Dar es Salaam holds collections of palaeontology (including the Zinjanthropus skull), archaeology, and ethnography. It is linked to the Leakey discoveries at Olduvai Gorge and presents Tanzania''s natural and cultural history. The museum plays a key role in East African heritage. Its scientific and cultural importance places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Tanzania';

UPDATE challenges SET description_en = 'The National Museum Bangkok (on Na Phra That Road) is Thailand''s main national museum. It holds collections of Thai art and archaeology: sculpture, gold regalia, weapons, royal funeral carriages, and ethnographic material. The museum is housed in former palace buildings. Its role as the premier repository of Thai heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum Bangkok';

UPDATE challenges SET description_en = 'The Vietnam National Museum of History in Hanoi presents Vietnamese history from prehistory to the mid-20th century. It holds Dong Son drums, Cham sculpture, and imperial and colonial-era artefacts. The museum is housed in a French colonial building. Its comprehensive coverage of Vietnamese history places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Vietnam National Museum of History';

UPDATE challenges SET description_en = 'The National Museum of Singapore is the country''s oldest museum and tells the story of Singapore from its early history (including the 14th-century Temasek) to the present. The building has a distinctive glass rotunda, and the permanent galleries are free. The museum combines history, culture, and design. Its role as the national narrative museum places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Singapore';

UPDATE challenges SET description_en = 'The Islamic Arts Museum Malaysia in Kuala Lumpur is one of the world''s largest museums dedicated to Islamic art. It holds over 7,000 objects: calligraphy, textiles, jewellery, arms, and architectural elements from across the Islamic world. The museum is located near the Perdana Botanical Garden. Its comprehensive and well-displayed collection places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Islamic Arts Museum Malaysia';

UPDATE challenges SET description_en = 'The National Museum of Indonesia (Museum Nasional) in Jakarta is the country''s principal museum of history and culture. It holds archaeological finds (including the famous Ganesha statue), Majapahit gold, kris daggers, and ethnographic collections. The museum is known as the Elephant Building after the bronze elephant in the forecourt. Its role as the guardian of Indonesian heritage places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Indonesia';

UPDATE challenges SET description_en = 'The National Museum of the Philippines in Manila holds collections of Philippine art, archaeology, and ethnography. Highlights include Juan Luna''s Spoliarium and exhibits on Philippine history and indigenous cultures. The museum is located near Rizal Park (Luneta). Its role as the national museum of the Philippines places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of the Philippines';

UPDATE challenges SET description_en = 'The Palace Museum (Forbidden City) in Beijing is housed in the former imperial palace of the Ming and Qing dynasties. It holds about 1.8 million objects of Chinese imperial art and is one of the most visited museums in the world. The complex of palaces, halls, and gardens is a UNESCO World Heritage Site. The museum''s collection and setting make it essential among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Palace Museum (Forbidden City)';

UPDATE challenges SET description_en = 'The Shanghai Museum in People''s Square is one of China''s leading museums of ancient art. The collection focuses on Chinese bronzes, ceramics, calligraphy, painting, jade, and minority arts. The building, in the shape of an ancient ding, opened in 1996. The museum''s quality and breadth of Chinese art place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Shanghai Museum';

UPDATE challenges SET description_en = 'The Hong Kong Museum of History in Tsim Sha Tsui tells the story of Hong Kong from prehistory (about 6,000 years ago) to the present. Exhibitions cover natural history, folk culture, and the development of the city. Admission to the permanent exhibition is free. The museum''s role in presenting Hong Kong''s identity places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Hong Kong Museum of History';

UPDATE challenges SET description_en = 'The National Taiwan Museum in Taipei is the oldest museum in Taiwan, founded in 1908 during the Japanese colonial period. It holds collections of natural history, ethnography (including indigenous Taiwanese cultures), and regional history. The building is a historic landmark. The museum''s history and role in Taiwanese heritage place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Taiwan Museum';

UPDATE challenges SET description_en = 'The National Folk Museum of Korea is located within the grounds of Gyeongbokgung Palace in Seoul. It presents Korean traditional life, customs, and culture through artefacts, reconstructions, and seasonal displays. Exhibits include jangseung (village guardian poles), clothing, and household items. The museum''s focus on everyday heritage and its setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Folk Museum of Korea';

UPDATE challenges SET description_en = 'The Jewish Museum Berlin is dedicated to German-Jewish history and the Holocaust. The building, designed by Daniel Libeskind, is a powerful example of deconstructivist architecture, with its zigzag plan and voids. The permanent exhibition traces two millennia of Jewish life in Germany and the rupture of the Holocaust. The museum opened in 2001. Its architecture and subject matter place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Jewish Museum Berlin';

UPDATE challenges SET description_en = 'The Powerhouse Museum in Sydney (Ultimo) is one of Australia''s leading museums of applied arts, sciences, and design. It holds the James Watt steam engine and collections of transport, technology, and decorative arts. The museum is housed in a former power station. Its focus on innovation and design places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Powerhouse Museum, Sydney';

UPDATE challenges SET description_en = 'Te Papa Tongarewa (Museum of New Zealand) in Wellington is the national museum of New Zealand. It holds collections of Māori taonga (treasures), natural history (including the Colossal Squid), and Pacific and New Zealand history and art. The building opened in 1998. Te Papa''s bicultural approach and its role as New Zealand''s national museum place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Te Papa Tongarewa, Wellington';

UPDATE challenges SET description_en = 'Museo Soumaya in Mexico City (Polanco) is a private museum founded by Carlos Slim. It holds over 65,000 objects, including the largest collection of Rodin sculpture outside France, as well as European and Mexican art. The building, with its distinctive curved silver facade, was designed by Fernando Romero. The museum offers free admission. Its collection and architecture place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Museo Soumaya, Mexico City';

UPDATE challenges SET description_en = 'The Acropolis Museum in Athens opened in 2009 at the foot of the Acropolis. It was built to house finds from the Acropolis site and to present the Parthenon sculptures in context (with casts of those still in London). The glass floors reveal ancient ruins beneath. The collection spans the Archaic to Roman periods. Its direct relationship to the Parthenon and its modern design place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Acropolis Museum, Athens';

UPDATE challenges SET description_en = 'The Botero Museum in Bogotá holds the personal art collection donated by the Colombian artist Fernando Botero. It includes his own paintings and sculptures as well as works by Picasso, Dalí, Matisse, and other international artists. The museum is in the La Candelaria neighbourhood and offers free admission. Its combination of Botero''s work and the donated masterpieces place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Botero Museum, Bogota';

UPDATE challenges SET description_en = 'The Musée de la Civilisation in Quebec City is a museum of human history and culture. It presents the history of Quebec, First Nations cultures, and world civilisations. The museum is located near Place Royale in Old Quebec and includes archaeological displays. Its focus on Quebec identity and its setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Musee de la Civilisation, Quebec';

UPDATE challenges SET description_en = 'The Canadian War Museum in Ottawa is Canada''s national museum of military history. It holds artefacts from Canada''s wars, including the First and Second World Wars (e.g. Hitler''s Mercedes, D-Day and Vimy Ridge material). The building, designed by Raymond Moriyama, opened in 2005. The museum''s comprehensive treatment of Canadian military history places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Canadian War Museum, Ottawa';

UPDATE challenges SET description_en = 'The United States Holocaust Memorial Museum in Washington, D.C., is the national memorial to the Holocaust. It combines historical documentation, personal testimonies, and artefacts to tell the story of the genocide and to educate on the dangers of hatred and indifference. The museum is located near the National Mall. Its role in American and global Holocaust remembrance places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'US Holocaust Memorial Museum';

UPDATE challenges SET description_en = 'The 9/11 Memorial & Museum at the World Trade Center site in New York City commemorates the attacks of September 11, 2001, and the 1993 bombing. The museum displays artefacts from the Twin Towers, survivor testimonies, and the stories of victims. The memorial pools mark the footprints of the towers. The site''s importance to recent history and memory places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = '9/11 Memorial & Museum';

UPDATE challenges SET description_en = 'The Musée d''Orsay in Paris is housed in a former railway station (Gare d''Orsay) and holds the world''s finest collection of Impressionist and Post-Impressionist art. It includes masterpieces by Monet, Renoir, Degas, Van Gogh, and Cézanne. The museum covers the period 1848–1914. The building was converted into a museum and opened in 1986. Its concentration of Impressionist works places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Musee d Orsay, Paris';

UPDATE challenges SET description_en = 'The Wien Museum (formerly Vienna Museum) is the city museum of Vienna. It holds collections on the history of Vienna from the Middle Ages to the present, including the study for Klimt''s The Kiss and works by Schiele. The main building is on Karlsplatz. The museum''s focus on Viennese history and culture places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Wien Museum, Vienna';

UPDATE challenges SET description_en = 'The Amsterdam Museum tells the story of Amsterdam from its origins (around 1275) to the present. It holds collections of paintings, objects, and documents related to the city''s history, including medieval sculpture and maps. The museum is housed in a former orphanage. Its role as the city''s memory places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Amsterdam Museum';

UPDATE challenges SET description_en = 'The Barcelona History Museum (MUHBA) preserves and presents the history of Barcelona. Its flagship site is in the Gothic Quarter, where visitors can walk through Roman Barcino and medieval remains beneath the city. The museum has several other sites across Barcelona. Its unique underground archaeological presentation places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Barcelona History Museum (MUHBA)';

UPDATE challenges SET description_en = 'The Nordic Museum in Stockholm is Sweden''s largest museum of cultural history. It presents 400 years of life in Sweden and the Nordic region through textiles, silverware, furniture, and exhibitions on Sami culture. The museum is housed in a striking building on Djurgården. Its coverage of Nordic everyday life and culture places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Nordic Museum, Stockholm';

UPDATE challenges SET description_en = 'The National Museum of Scotland in Edinburgh presents the history of Scotland from geological origins to the present. Highlights include Dolly the Sheep (the first cloned mammal), the Lewis Chessmen, and the Galloway Hoard. The museum is in the Old Town and offers free admission. Its role as the national museum of Scotland places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'National Museum of Scotland';

UPDATE challenges SET description_en = 'NGMA (National Gallery of Modern Art) in New Delhi is India''s premier museum of modern and contemporary art. It holds works by Raja Ravi Varma, Amrita Sher-Gil, and many Indian and international modern artists. The museum was established in 1954. Its role in defining and displaying Indian modern art places it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'NGMA New Delhi';

UPDATE challenges SET description_en = 'The Museum of Turkish and Islamic Arts in Istanbul holds one of the world''s finest collections of Turkish and Islamic art: carpets, manuscripts (including Qurans), metalwork, and ceramics. It is housed in the Ibrahim Pasha Palace near the Hippodrome. The museum was founded in the early 20th century. Its collection and setting place it among the world''s top 100 museums.' WHERE category = 'museums' AND title_en = 'Museum of Turkish and Islamic Arts';
