-- schema-v19-descriptions-foods.sql: Extended English descriptions for foods category (world 100)
-- Each description_en 500-700 characters: why world 100, origin, taste. No specific locations (doable anywhere).

UPDATE challenges SET description_en = 'Fugu (puffer fish) is one of the world''s most dangerous delicacies. The fish contains tetrodotoxin, a poison that can be fatal if incorrectly prepared. In Japan only licensed chefs may serve fugu after years of training. The flesh is delicate, slightly chewy, and often served as sashimi in paper-thin slices. Licensed restaurants worldwide offer it where legal. Eating fugu is a rite of passage for adventurous eaters and a testament to Japanese culinary precision and risk culture.' WHERE category = 'foods' AND title_en = 'Fugu Puffer Fish';

UPDATE challenges SET description_en = 'Hakarl is fermented Greenland shark, an Icelandic tradition dating back centuries. The shark is buried in gravel for six to twelve weeks, then hung to dry for several months. The process breaks down toxic urea and trimethylamine, producing a strong ammonia smell and a pungent, cheese-like flavour that is an acquired taste. It is often served in small cubes with a shot of brennavin. Traditional Nordic restaurants and festivals offer it seasonally. It remains a symbol of Icelandic resilience and heritage.' WHERE category = 'foods' AND title_en = 'Hakarl Fermented Greenland Shark';

UPDATE challenges SET description_en = 'Kopi luwak is the world''s most expensive coffee, made from beans that have passed through the digestive system of the Asian palm civet. The civet''s enzymes are said to alter the beans and reduce bitterness. Ethical concerns over caged civets have led to demand for wild-sourced or certified options. The taste is smooth, less acidic, with earthy and caramel notes. Choose certified or wild-sourced options that prioritise animal welfare. It remains a bucket-list experience for coffee enthusiasts despite controversy.' WHERE category = 'foods' AND title_en = 'Kopi Luwak Civet Coffee';

UPDATE challenges SET description_en = 'Ortolan bunting is a small songbird that was traditionally eaten whole in France under a napkin, supposedly to capture the aroma and to hide the act from God. The practice is now illegal in the EU, but the dish remains a controversial symbol of French haute cuisine and excess. Historically it was prized for its rich, gamey flavour. We do not encourage consumption; it is listed here for its cultural and culinary notoriety as one of the world''s most debated delicacies.' WHERE category = 'foods' AND title_en = 'Ortolan Bunting';

UPDATE challenges SET description_en = 'Witchetty grub is a traditional Aboriginal bush tucker: the larva of the cossid moth, found in roots of acacia and other trees. Eaten raw or lightly roasted, it has a nutty, egg-like flavour and is high in protein. It is central to Indigenous Australian food culture and storytelling. Bush tucker experiences and guided tours offer it in appropriate settings. It represents one of the oldest continuous food traditions on Earth and a direct connection to Country.' WHERE category = 'foods' AND title_en = 'Witchetty Grub';

UPDATE challenges SET description_en = 'Balut is a fertilised duck egg incubated until the embryo is developed, then boiled and eaten in the shell. A street-food staple in the Philippines, it is enjoyed with salt, vinegar, or chili. The broth inside is sipped first; then the yolk and embryo are eaten, offering a mix of textures and rich, savoury flavour. It is widely available where Southeast Asian street food is served. Balut is a cultural icon and a test of culinary courage for many travellers.' WHERE category = 'foods' AND title_en = 'Balut Duck Embryo';

UPDATE challenges SET description_en = 'Beluga caviar is the most prized caviar in the world, from the beluga sturgeon of the Caspian Sea. The eggs are large, pearl-grey, and have a buttery, delicate flavour that melts on the tongue. Overfishing and poaching have made wild beluga rare; most supply is farmed. It is traditionally served with blini, crème fraîche, and vodka. Fine-dining and specialty restaurants worldwide serve it. It remains the ultimate luxury seafood and a symbol of indulgence.' WHERE category = 'foods' AND title_en = 'Beluga Caviar';

UPDATE challenges SET description_en = 'Bird''s nest soup is made from the dried saliva nests of swiftlets, harvested from caves in Southeast Asia. It has been a Chinese imperial delicacy for centuries, valued for its supposed health benefits and gelatinous, silky texture when cooked. The flavour is mild and subtle; the nests are often prepared with rock sugar in a sweet soup or in savoury broths. Available at Chinese and Southeast Asian restaurants globally. It is one of the world''s most expensive ingredients by weight.' WHERE category = 'foods' AND title_en = 'Bird''s Nest Soup';

UPDATE challenges SET description_en = 'Cuy (guinea pig) is a traditional Andean protein, raised and eaten in Peru, Ecuador, and Bolivia since Inca times. Whole roasted cuy has crispy skin and tender, gamey meat similar to rabbit or dark poultry. It is often served with potatoes and ají. Andean and South American restaurants and markets serve it. Cuy is central to highland identity and a must-try for anyone exploring the Andes and indigenous foodways.' WHERE category = 'foods' AND title_en = 'Cuy Roasted Guinea Pig';

UPDATE challenges SET description_en = 'Dom Pérignon is the prestige cuvée of Champagne house Moët & Chandon, named after the Benedictine monk who helped develop sparkling wine. Only vintage years are released; the wine is known for complexity, finesse, and ageing potential. Blanc and rosé versions are produced. Cellar tours and tastings are available in Champagne and at fine wine merchants worldwide. Dom Pérignon has defined luxury Champagne for over 150 years and is a benchmark for celebratory drinking worldwide.' WHERE category = 'foods' AND title_en = 'Dom Perignon Champagne';

UPDATE challenges SET description_en = 'Durian is known as the King of Fruits in Southeast Asia. Its spiky shell encloses creamy, custard-like flesh with a potent smell that has led to bans on public transport and in hotels. Fans describe a complex, sweet, and savoury flavour with notes of almond and onion. The fruit is seasonal and exported to many countries. Love it or hate it, durian is an essential experience and one of the world''s most polarising and iconic fruits.' WHERE category = 'foods' AND title_en = 'Durian King of Fruits';

UPDATE challenges SET description_en = 'Foie gras is the fattened liver of duck or goose, produced by force-feeding (gavage). It is a cornerstone of French gastronomy, especially in Périgord. Served pan-seared or in terrines, it is rich, buttery, and often paired with Sauternes or fruit. The practice is banned in several countries on animal-welfare grounds. In France and many other countries it remains legal and celebrated at traditional restaurants. It is among the world''s most controversial luxury foods.' WHERE category = 'foods' AND title_en = 'Foie Gras';

UPDATE challenges SET description_en = 'Iberico ham comes from the black Iberian pig, raised in Spain and Portugal. The finest grade is bellota: pigs fattened on acorns in the dehesa, producing nutty, marbled meat. The ham is dry-cured for up to 36 months. Jabugo in Extremadura is the most famous denomination. Served in thin slices, it melts on the tongue. Tapas bars and specialty shops worldwide stock it. Iberico ham is widely considered the best cured ham in the world.' WHERE category = 'foods' AND title_en = 'Iberico Ham';

UPDATE challenges SET description_en = 'A5 Wagyu is the highest grade of Japanese beef, with exceptional marbling (BMS up to 12). The fat melts at low temperature, giving a buttery, melt-in-the-mouth texture. The main regions are Kobe, Matsusaka, and Ohmi. It is served as steak, shabu-shabu, or sukiyaki. Japanese and fine-dining restaurants globally offer it. A5 Wagyu represents the pinnacle of beef and one of the most sought-after culinary experiences globally.' WHERE category = 'foods' AND title_en = 'A5 Wagyu Beef';

UPDATE challenges SET description_en = 'Matsutake is a highly prized Japanese mushroom that grows in association with red pine roots. It has a distinctive spicy, piney aroma and firm texture. The season is brief (autumn), and wild harvests have declined, pushing prices to thousands of dollars per kilogram. It is used in clear soups, rice, and dobin mushi. Japanese restaurants serve it in autumn when in season. Matsutake is a symbol of autumn in Japan and one of the world''s most expensive mushrooms.' WHERE category = 'foods' AND title_en = 'Matsutake Mushroom';

UPDATE challenges SET description_en = 'Pata negra jamón bellota is the finest Iberian ham: from acorn-fed black-hoof pigs, cured for up to four years in mountain air. The name refers to the black hoof left on the leg. The flavour is deep, nutty, and complex. Multi-grade tastings and top tapas bars and charcuterie shops offer it worldwide. It is the ultimate expression of Spanish charcuterie and terroir.' WHERE category = 'foods' AND title_en = 'Pata Negra Jamon Bellota';

UPDATE challenges SET description_en = 'The black truffle of Périgord is called the diamond of the kitchen. It grows in symbiosis with oak and hazel in southwest France and is harvested in winter with the help of dogs or pigs. Shaved over pasta, eggs, or risotto, it delivers an intense, earthy, musky aroma. Truffle markets and festivals and fine restaurants feature it in season. Périgord black truffle is one of the world''s most coveted and expensive ingredients.' WHERE category = 'foods' AND title_en = 'Perigord Black Truffle';

UPDATE challenges SET description_en = 'Peyote is a small cactus used in sacred ceremonies by the Wixaritari (Huichol) and other indigenous peoples of Mexico. Its consumption is legal only for registered members of the Native American Church and certain Mexican indigenous groups in ritual context. We list it for its cultural and botanical significance, not to encourage recreational use. It represents the deep connection between indigenous spirituality and native plants in the Americas.' WHERE category = 'foods' AND title_en = 'Peyote Cactus Ceremonial Meal';

UPDATE challenges SET description_en = 'Shark fin soup is a traditional Chinese banquet dish, especially at weddings and New Year. The fin itself is largely texture; the broth is the focus. Harvesting fins has driven shark populations down and is banned or restricted in many places. Sustainable alternatives and faux fins exist. The dish remains controversial; we note it for its historical and cultural role in Chinese cuisine. Ethical and sustainable alternatives are increasingly available worldwide.' WHERE category = 'foods' AND title_en = 'Shark Fin Soup';

UPDATE challenges SET description_en = 'Alaskan king crab from the Bering Sea is among the world''s largest and most prized crustaceans. The legs can weigh several kilograms; the meat is sweet, tender, and best simply steamed or boiled with butter. The season runs in winter. Seafood restaurants and cruises in cold-water regions serve it. Alaskan king crab has become a luxury staple on fine-dining menus and a symbol of cold-water seafood excellence.' WHERE category = 'foods' AND title_en = 'Alaskan King Crab';

UPDATE challenges SET description_en = 'Arancini are Sicilian fried rice balls, typically stuffed with ragù, mozzarella, and peas. The name means little oranges; the exterior is crisp and golden, the interior creamy. They are street food and trattoria staples, with regional variations. Markets, kiosks, and Italian restaurants serve them. Arancini embody Sicilian comfort food and the island''s Arab and Norman influences. They are a must-eat in southern Italy.' WHERE category = 'foods' AND title_en = 'Arancini';

UPDATE challenges SET description_en = 'Baklava is layers of phyllo pastry filled with chopped nuts and soaked in honey or syrup. Gaziantep in Turkey is considered the capital of baklava, with protected designation. The best versions balance crisp layers, fragrant nuts (pistachio or walnut), and syrup without excess sweetness. Available across the Middle East, Balkans, and at Middle Eastern bakeries worldwide. Baklava is one of the world''s great pastries and a shared heritage of Ottoman cuisine.' WHERE category = 'foods' AND title_en = 'Baklava';

UPDATE challenges SET description_en = 'Bibimbap is a Korean mixed rice bowl topped with vegetables, egg, meat, and gochujang. The classic version is served in a hot stone pot (dolsot), which crisps the rice at the bottom. Sesame oil and a raw or fried egg complete the dish. Korean restaurants worldwide serve it; the dolsot (hot stone pot) version is especially popular. It is healthy, colourful, and central to Korean everyday dining and tourism.' WHERE category = 'foods' AND title_en = 'Bibimbap';

UPDATE challenges SET description_en = 'Bouillabaisse is Marseille''s iconic fishermen''s stew, originally made from the catch that did not sell. It includes at least three types of fish and shellfish, saffron, and is served with rouille and croutons. Authentic versions follow a traditional charter. Provençal and French seafood restaurants serve it. Bouillabaisse is the soul of Provençal seafood and one of France''s most celebrated dishes.' WHERE category = 'foods' AND title_en = 'Bouillabaisse';

UPDATE challenges SET description_en = 'Brazilian churrasco is rodízio-style barbecue: servers bring skewers of meat to your table and slice portions until you signal stop. Cuts include picanha, linguiça, and chicken hearts. The experience is all-you-can-eat with sides and salads. Churrascarias and Brazilian steakhouses worldwide offer the full rodízio experience. Churrasco is central to Brazilian culture and one of the world''s most festive meat experiences.' WHERE category = 'foods' AND title_en = 'Brazilian Churrasco';

UPDATE challenges SET description_en = 'Ceviche is raw fish or seafood cured in citrus (usually lime) with onion, chili, and cilantro. Peru claims it as national dish; fine-dining and casual spots have elevated it globally. Leche de tigre is the citrus marinade, often drunk as a shot. Latin American and fusion restaurants worldwide serve it. Ceviche is fresh, bright, and emblematic of Latin American coastal cuisine and the Pacific larder.' WHERE category = 'foods' AND title_en = 'Ceviche';

UPDATE challenges SET description_en = 'Char siu is Cantonese barbecued pork, glazed with honey, hoisin, and five-spice. It is red on the outside, tender and slightly sweet inside. Served over rice, in buns (char siu bao), or with noodles. Char siu is a pillar of Cantonese cooking and comfort food. Cantonese and dim sum restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Char Siu BBQ Pork';

UPDATE challenges SET description_en = 'Chimichanga is a deep-fried burrito, claimed by both Arizona and Sonora. The filling is typically meat, beans, rice, and cheese. It is served with sour cream, guacamole, and salsa. Tex-Mex and Mexican restaurants in many regions serve it. The chimichanga is a Tex-Mex and Sonoran staple and a favourite for its crispy exterior and hearty filling. It has become an American-Mexican icon.' WHERE category = 'foods' AND title_en = 'Chimichanga';

UPDATE challenges SET description_en = 'Valrhona is a French premium chocolate maker based in Tain-l''Hermitage. Factory tours and tastings introduce single-origin and blended bars, including Dulcey blond and Grand Cru ranges. Madagascar 66% and other origins showcase terroir. Valrhona is used by many top pastry chefs worldwide. Factory tours and tastings are available; Valrhona is also sold at premium grocers and chocolatiers. It is one of the world''s most respected professional and tasting chocolates.' WHERE category = 'foods' AND title_en = 'Valrhona Chocolate';

UPDATE challenges SET description_en = 'Congee (jook) is silky rice porridge cooked long until the grains break down. In Hong Kong it is breakfast and comfort food, often with preserved egg and pork, or fish. Dim sum spots and Asian breakfast cafés serve it. Congee is found across Asia with endless variations. It is soothing, digestible, and central to Cantonese and broader Asian breakfast culture.' WHERE category = 'foods' AND title_en = 'Congee Jook';

UPDATE challenges SET description_en = 'Coq au vin is chicken braised in red wine (traditionally Burgundy) with mushrooms, bacon, and pearl onions. The dish is a French classic, associated with Lyon bouchons and home cooking. Paul Bocuse and others have codified the recipe. French bistros and brasseries worldwide serve it. Coq au vin embodies French rustic elegance and the marriage of wine and poultry. It remains a benchmark of traditional French cuisine.' WHERE category = 'foods' AND title_en = 'Coq au Vin';

UPDATE challenges SET description_en = 'The French croissant is a laminated butter pastry, crisp and flaky outside, soft inside. The best are made with pure butter and careful folding. The croissant is the symbol of French breakfast and bakery craft. Enjoy it with coffee at cafés and boulangeries worldwide. It is one of the world''s most recognised and beloved pastries.' WHERE category = 'foods' AND title_en = 'French Croissant';

UPDATE challenges SET description_en = 'Doner kebab is meat (typically lamb and beef) roasted on a vertical spit and sliced into thin pieces. It is served in bread or on a plate with salad and sauce. Turkey is the homeland; doner has spread globally as street food. The Turkish original, with quality meat and fresh bread, is available at kebab shops and Turkish restaurants worldwide.' WHERE category = 'foods' AND title_en = 'Doner Kebab';

UPDATE challenges SET description_en = 'Eggs Benedict is poached eggs on English muffin with Canadian bacon and hollandaise sauce. Delmonico''s in New York claimed to have invented it in 1894. The dish is a brunch staple in America and beyond. The key is runny yolk and silky hollandaise. Classic brunch spots and cafés worldwide serve it. Eggs Benedict is an enduring symbol of American brunch culture.' WHERE category = 'foods' AND title_en = 'Eggs Benedict';

UPDATE challenges SET description_en = 'Empanadas are stuffed pastries, baked or fried, found across Latin America and Spain. In Argentina the Salta style with ground beef, olive, and hard egg is iconic. Fillings vary by region: cheese, chicken, ham, or fruit. Street stalls, markets, and Latin American restaurants serve them. Empanadas are portable, satisfying, and central to Argentine and South American snacking and sharing.' WHERE category = 'foods' AND title_en = 'Empanada';

UPDATE challenges SET description_en = 'Escargot are land snails cooked in garlic butter, often served in their shells. A dozen in Burgundy style is a classic French appetiser. French bistros and brasseries serve them with bread to mop up the sauce. The texture is tender, the flavour dominated by garlic and parsley butter. Escargot are a symbol of French culinary daring and bistro tradition; they are available at French restaurants worldwide.' WHERE category = 'foods' AND title_en = 'Escargot';

UPDATE challenges SET description_en = 'Fish and chips is battered cod or haddock with thick-cut chips, often with malt vinegar and mushy peas. Britain''s national takeaway has spread worldwide. The fish should be flaky inside and crisp outside; the chips golden and fluffy. Fish and chip shops and pubs in Britain and beyond serve it. Fish and chips is comfort food and a pillar of British food culture.' WHERE category = 'foods' AND title_en = 'Fish and Chips';

UPDATE challenges SET description_en = 'Gelato is Italian ice cream, denser and lower in fat than American ice cream, with intense flavour. It is churned slowly and served at slightly higher temperature. Pistachio, stracciatella, and fruit flavours are classics. Gelato is a daily ritual in Italy and a benchmark for frozen desserts; gelaterias worldwide serve it.' WHERE category = 'foods' AND title_en = 'Gelato';

UPDATE challenges SET description_en = 'Hungarian goulash is a paprika-based beef stew, originally cooked in a kettle over fire by herdsmen. It is thick, warming, and flavoured with caraway and vegetables. Traditional Central European and Hungarian restaurants serve it with bread or dumplings. Goulash is the soul of Hungarian cuisine and Central European comfort food.' WHERE category = 'foods' AND title_en = 'Hungarian Goulash';

UPDATE challenges SET description_en = 'Greek mezze is a spread of small dishes shared with ouzo or wine: tzatziki, spanakopita, dolmades, feta, grilled meats, and more. It is social dining at its best. Santorini, Athens, and seaside tavernas offer full spreads. Mezze reflects Greek hospitality and the Mediterranean diet. A long lunch or dinner with mezze by the sea is one of Greece''s defining experiences.' WHERE category = 'foods' AND title_en = 'Greek Mezze Spread';

UPDATE challenges SET description_en = 'Haggis is Scotland''s national dish: sheep offal (heart, liver, lungs) mixed with oatmeal, suet, and spices, traditionally boiled in the stomach. It is served with neeps and tatties, especially on Burns Night (25 January), with whisky. Scottish pubs, Burns suppers, and British restaurants serve it. Haggis is hearty, historical, and central to Scottish identity.' WHERE category = 'foods' AND title_en = 'Haggis';

UPDATE challenges SET description_en = 'Injera is a spongy, slightly sour flatbread made from teff, used as both plate and utensil in Ethiopian dining. It is served with wats (stews) such as doro wat and tibs. Ethiopian restaurants offer communal platters for sharing. Injera is gluten-free and unique in texture and flavour. Ethiopian restaurants worldwide offer communal platters; injera is the foundation of Ethiopian cuisine.' WHERE category = 'foods' AND title_en = 'Injera with Wat';

UPDATE challenges SET description_en = 'Jerk chicken is chicken marinated in Scotch bonnet peppers, allspice, thyme, and other spices, then slow-cooked over pimento wood. It is a Jamaican icon. Boston Bay in Portland is the birthplace; roadside pits and restaurants across the island serve it with rice and peas. Jerk is smoky, spicy, and aromatic. Try it in Jamaica for the authentic experience. Jerk chicken has put Jamaican flavours on the world map.' WHERE category = 'foods' AND title_en = 'Jerk Chicken';

UPDATE challenges SET description_en = 'Jollof rice is a one-pot West African dish of rice cooked in tomato, onion, and spices. Ghana and Nigeria famously debate whose version is best. The rice is orange-red, slightly smoky, and often served with chicken or fish. Jollof is the soul of West African celebration and everyday eating. West African and African restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Jollof Rice';

UPDATE challenges SET description_en = 'Khachapuri is Georgian cheese bread, often in a boat shape (Adjarian style) with an egg baked in the middle. The bread is soft, the cheese stringy and salty. Multiple regional varieties exist. Khachapuri is the ultimate Georgian comfort food and a symbol of hospitality; Georgian restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Khachapuri';

UPDATE challenges SET description_en = 'Kimchi is fermented napa cabbage (and other vegetables) with chili, garlic, and ginger. It is a Korean staple at every meal and UNESCO intangible heritage. The flavour is tangy, spicy, and umami. Homemade and commercial varieties abound. Korean restaurants and grocers worldwide offer it. Kimchi is the backbone of Korean cuisine and one of the world''s most iconic fermented foods.' WHERE category = 'foods' AND title_en = 'Kimchi';

UPDATE challenges SET description_en = 'Laksa is a Southeast Asian noodle soup in coconut curry or sour tamarind broth. Penang asam laksa is the famous sour version; curry laksa is creamier. Laksa is warming, complex, and deeply satisfying. Malaysian and Singaporean restaurants and hawker-style spots worldwide serve it. It represents the fusion of Malay, Chinese, and Indian influences.' WHERE category = 'foods' AND title_en = 'Laksa';

UPDATE challenges SET description_en = 'The Maine lobster roll is cold lobster meat mixed with a little mayo, served in a toasted split-top bun. The lobster should be sweet and tender, the bun buttery. It is the iconic New England seafood sandwich. Seafood restaurants and lobster shacks in many regions serve it.' WHERE category = 'foods' AND title_en = 'Maine Lobster Roll';

UPDATE challenges SET description_en = 'Lomo saltado is a Peruvian stir-fry of beef, tomatoes, onions, and french fries over rice, with soy sauce and vinegar. It reflects Chinese-Peruvian (chifa) influence. Peruvian and chifa (Chinese-Peruvian) restaurants serve it as a national comfort dish. The mix of stir-fry and fries is unique and satisfying. Lomo saltado is a perfect example of Peru''s fusion cuisine.' WHERE category = 'foods' AND title_en = 'Lomo Saltado';

UPDATE challenges SET description_en = 'Masala dosa is a crisp rice crepe filled with spiced potato, served with sambar and chutney. It is a South Indian breakfast institution. The dosa should be crisp and golden, the filling fragrant. South Indian and Indian restaurants worldwide serve it. Masala dosa has become a global ambassador for Indian breakfast.' WHERE category = 'foods' AND title_en = 'Masala Dosa';

UPDATE challenges SET description_en = 'Mole negro is Oaxaca''s complex sauce of up to 30 ingredients, including chocolate, chili, nuts, and spices. It is slow-cooked and served over turkey or chicken. Casa Oaxaca and traditional restaurants in Oaxaca city offer the definitive experience. Mole is the soul of Oaxacan cuisine and one of Mexico''s greatest culinary achievements. A trip to Oaxaca is incomplete without mole negro.' WHERE category = 'foods' AND title_en = 'Mole Negro';

UPDATE challenges SET description_en = 'Momos are Himalayan dumplings, usually filled with meat (buffalo or chicken) or vegetables, steamed or fried. They are served with achar (spicy sauce). Momos are cheap, filling, and addictive. They have spread from Nepal and Tibet across South Asia and beyond; Himalayan, Tibetan, and Nepalese restaurants worldwide serve them.' WHERE category = 'foods' AND title_en = 'Momos';

UPDATE challenges SET description_en = 'Moules frites is mussels cooked in white wine with shallots and parsley, served with fries. Belgium and northern France claim it. A one-kilogram pot with frites and aioli is the classic order. Belgian and French brasseries worldwide serve it. Moules frites is simple, communal, and deeply satisfying. It is one of the world''s great bistro dishes.' WHERE category = 'foods' AND title_en = 'Moules Frites';

UPDATE challenges SET description_en = 'Nasi goreng is Indonesian fried rice with kecap manis, shallots, and often a fried egg on top. It is the national comfort food of Indonesia. The best versions are wok-fired and slightly smoky. Indonesian and Asian restaurants worldwide serve it. Nasi goreng is the taste of Indonesia in one plate.' WHERE category = 'foods' AND title_en = 'Nasi Goreng';

UPDATE challenges SET description_en = 'New England clam chowder is a creamy soup of clams, potatoes, and sometimes salt pork, in a milk or cream base. The chowder should be thick and briny. It is the defining soup of the American Northeast. Seafood restaurants and clam shacks in many regions serve it.' WHERE category = 'foods' AND title_en = 'New England Clam Chowder';

UPDATE challenges SET description_en = 'Pad Thai is stir-fried rice noodles with tamarind, fish sauce, egg, and peanuts. The dish is sweet, sour, and savoury, often with shrimp or tofu. Thai restaurants and street-food spots worldwide serve it. Pad Thai is Thailand''s most famous export dish and a gateway to Thai flavours.' WHERE category = 'foods' AND title_en = 'Pad Thai';

UPDATE challenges SET description_en = 'Paella valenciana is saffron rice with chicken, rabbit, and sometimes snails, cooked in a wide pan. The socarrat (crispy bottom layer) is prized. Paella is Spain''s most famous rice dish and a symbol of communal dining. Spanish and Mediterranean restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Paella Valenciana';

UPDATE challenges SET description_en = 'Pho bo is Vietnamese beef noodle soup: long-simmered bone broth with star anise and cinnamon, rice noodles, and thin beef. The broth is clear and aromatic; add herbs and lime at the table. Pho is Vietnam''s national dish and a global comfort food. Vietnamese restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Pho Bo';

UPDATE challenges SET description_en = 'Pierogi are Polish dumplings filled with potato and cheese, meat, or fruit, then boiled or fried. They are served with sour cream, fried onion, or butter. Pierogi are the soul of Polish home cooking and festival food. Polish and Eastern European restaurants worldwide serve them.' WHERE category = 'foods' AND title_en = 'Pierogi';

UPDATE challenges SET description_en = 'Pizza Napoletana is wood-fired pizza with a puffy, charred crust, simple toppings, and minimal cheese. VPN (Vera Pizza Napoletana) certification marks authentic Neapolitan pizzerias. Margherita is the benchmark. The pizza should be soft in the centre and crisp at the edge. Neapolitan pizzerias worldwide serve it. Neapolitan pizza is UNESCO-recognised intangible heritage.' WHERE category = 'foods' AND title_en = 'Pizza Napoletana';

UPDATE challenges SET description_en = 'Ramen is Japanese noodle soup in tonkotsu (pork bone), shoyu (soy), or miso broth, with chashu, egg, nori, and bamboo. Regional styles vary from Sapporo to Tokyo. Ramen is a Japanese obsession and a global phenomenon. Ramen shops and Japanese restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Ramen';

UPDATE challenges SET description_en = 'Beef rendang is slow-cooked coconut beef from West Sumatra, Indonesia. The sauce is reduced until dry and the meat is tender and richly spiced. It is served with rice and other dishes. Rendang has been voted one of the world''s best foods. Indonesian and Minang restaurants worldwide serve it. It is one of the great slow-cooked dishes of the world.' WHERE category = 'foods' AND title_en = 'Beef Rendang';

UPDATE challenges SET description_en = 'Roti canai is a flaky, layered flatbread served with dhal or curry. It is a Mamak (Indian-Malay) staple in Malaysia, The bread is soft inside and crisp outside. Roti canai is breakfast, snack, and comfort food. Malaysian and Mamak-style restaurants worldwide serve it. It is one of Malaysia''s most beloved and accessible foods.' WHERE category = 'foods' AND title_en = 'Roti Canai';

UPDATE challenges SET description_en = 'Saltimbocca alla romana is Roman veal with prosciutto and sage, cooked in white wine and butter. The name means jump into the mouth. Traditional Italian trattorias serve it with white wine. Saltimbocca is simple Roman elegance; Italian restaurants worldwide offer it.' WHERE category = 'foods' AND title_en = 'Saltimbocca alla Romana';

UPDATE challenges SET description_en = 'Samosa is a fried pastry filled with spiced potato and peas (or meat). It is street food across India and South Asia. Samosas are crisp, golden, and addictive, served with tamarind chutney and raita. Indian and South Asian restaurants and street stalls worldwide serve them. The samosa is one of the world''s most popular snacks.' WHERE category = 'foods' AND title_en = 'Samosa';

UPDATE challenges SET description_en = 'Satay is grilled meat skewers (chicken, beef, or lamb) with peanut sauce. The meat is marinated and charred; the sauce is sweet, nutty, and spicy. Satay is essential Southeast Asian street food. Malaysian, Indonesian, and Thai restaurants worldwide serve it.' WHERE category = 'foods' AND title_en = 'Satay';

UPDATE challenges SET description_en = 'Seafood paella is rice with prawns, mussels, squid, and sometimes lobster, in saffron broth. Bomba rice absorbs the stock and stays firm. Spanish and Mediterranean restaurants worldwide serve it in large pans. Seafood paella is the taste of the Mediterranean coast.' WHERE category = 'foods' AND title_en = 'Seafood Paella';

UPDATE challenges SET description_en = 'Swedish smörgåsbord is a festive buffet of herring, gravlax, meatballs, Jansson''s temptation, and more. The julbord at Christmas is the peak. It is a feast of small dishes and traditions. Swedish and Nordic restaurants offer it, especially during the holidays. Smörgåsbord is the soul of Swedish celebration and one of the world''s great buffet traditions.' WHERE category = 'foods' AND title_en = 'Swedish Smorgasbord';

UPDATE challenges SET description_en = 'Som tam is Thai green papaya salad, pounded in a mortar with chili, lime, fish sauce, and peanuts. It is spicy, sour, salty, and sweet. Isaan (northeastern) style is the classic. Som tam is refreshing and addictive, often served with sticky rice and grilled chicken. Thai restaurants worldwide serve it. It is one of Thailand''s most iconic dishes.' WHERE category = 'foods' AND title_en = 'Som Tam Green Papaya Salad';

UPDATE challenges SET description_en = 'Sushi omakase is chef''s choice sushi: the chef selects and prepares each piece in sequence. The fish is the finest; the rice is seasoned with care. Omakase is the pinnacle of sushi dining. Top sushi counters and Japanese restaurants in major cities worldwide offer it.' WHERE category = 'foods' AND title_en = 'Sushi Omakase';

UPDATE challenges SET description_en = 'Moroccan tagine is a slow-cooked stew in a conical clay pot: lamb with prunes, chicken with lemon, or fish. Smen (aged butter) and complex spices are traditional. The tagine keeps everything moist and aromatic. Moroccan and North African restaurants worldwide serve it. Tagine is the soul of Moroccan home and restaurant cooking.' WHERE category = 'foods' AND title_en = 'Moroccan Tagine';

UPDATE challenges SET description_en = 'Takoyaki are ball-shaped snacks of batter with a piece of octopus inside, topped with mayo and bonito flakes. They are an Osaka street food icon. The balls are crisp outside and soft inside. Japanese restaurants and street-food spots worldwide serve them. Takoyaki are fun, cheap, and essential to the Osaka food experience.' WHERE category = 'foods' AND title_en = 'Takoyaki';

UPDATE challenges SET description_en = 'Tamal (tamale) is masa steamed in a corn husk or banana leaf, with fillings such as black bean, mole, or pork. Christmas tamale feasts are traditional. Tamales are portable and filling. Mexican and Latin American restaurants and markets worldwide serve them. The tamal is one of the oldest and most beloved dishes in the Americas.' WHERE category = 'foods' AND title_en = 'Tamal';

UPDATE challenges SET description_en = 'Tandoori chicken is chicken marinated in yogurt and spices, cooked in a tandoor (clay oven). The chicken is charred and tender, served with naan and raita. Tandoori is the gateway to North Indian restaurant cuisine. Indian restaurants worldwide serve it. It is one of India''s most famous exports.' WHERE category = 'foods' AND title_en = 'Tandoori Chicken';

UPDATE challenges SET description_en = 'Tom yum goong is Thai hot and sour prawn soup with lemongrass, galangal, kaffir lime, and chili. It is aromatic, spicy, and refreshing. Tom yum is the taste of Thailand in a bowl. Thai restaurants worldwide serve it as a staple. It is one of the world''s most recognisable and beloved soups.' WHERE category = 'foods' AND title_en = 'Tom Yum Goong';

UPDATE challenges SET description_en = 'Hakata tonkotsu ramen is ramen in a rich, milky pork bone broth, simmered for many hours. Thin noodles, chashu, and beni shoga (pickled ginger) are standard. The broth is the star: creamy and deeply porky. Tonkotsu ramen is the defining style of Kyushu; ramen shops worldwide serve it. It is the defining style of Kyushu ramen.' WHERE category = 'foods' AND title_en = 'Hakata Tonkotsu Ramen';

UPDATE challenges SET description_en = 'Truffle pasta in Alba style features white truffles from Piedmont shaved over fresh egg pasta (tajarin). White truffle season is October; the aroma is intoxicating. It is one of the world''s most luxurious pasta dishes. Italian and fine-dining restaurants serve it in white truffle season (autumn).' WHERE category = 'foods' AND title_en = 'Truffle Pasta Alba';

UPDATE challenges SET description_en = 'Tsukemen is dipping ramen: cold or room-temperature noodles served with a separate bowl of concentrated hot broth for dipping. The noodles are chewy; you dip, slurp, and optionally add broth to drink at the end. Tsukemen is a Tokyo invention. Ramen shops and Japanese restaurants in many cities serve it.' WHERE category = 'foods' AND title_en = 'Tsukemen Dipping Ramen';

UPDATE challenges SET description_en = 'Full Turkish breakfast (kahvaltı) is a weekend spread of 20 or more dishes: white cheese, olives, eggs, simit, honey, jam, tomatoes, cucumber, and more. Turkish cafés and restaurants worldwide offer lavish versions. It is social, leisurely, and a celebration of Turkish produce. Turkish breakfast is one of the world''s best morning meals.' WHERE category = 'foods' AND title_en = 'Full Turkish Breakfast';

UPDATE challenges SET description_en = 'Tzatziki is a Greek dip of yogurt, cucumber, garlic, and olive oil. It is served with grilled meat, pita, or as part of mezze. Tzatziki is cool, fresh, and essential to Greek dining, often served with village salad and souvlaki. Greek and Mediterranean restaurants worldwide offer it. It is one of the Mediterranean''s great condiments.' WHERE category = 'foods' AND title_en = 'Tzatziki';

UPDATE challenges SET description_en = 'Unagi kabayaki is grilled freshwater eel glazed with sweet soy tare. It is a summer stamina food in Japan. The eel is tender and the sauce caramelises on the grill. Unagi is traditionally eaten on the Day of the Ox in summer. Japanese and unagi-specialist restaurants worldwide serve it. It is a Japanese classic and a delicacy.' WHERE category = 'foods' AND title_en = 'Unagi Kabayaki';

UPDATE challenges SET description_en = 'Wiener schnitzel is veal (or pork) pounded thin, breaded, and fried until golden. It is Austria''s national dish. Traditional Gasthäuser and Austrian restaurants serve it with potato salad or cranberry (Preiselbeeren). The schnitzel should be crisp and thin. Austrian and Central European restaurants worldwide offer it. Wiener schnitzel is the soul of Austrian comfort food.' WHERE category = 'foods' AND title_en = 'Wiener Schnitzel';

UPDATE challenges SET description_en = 'Xiaolongbao are soup dumplings: thin-skinned dumplings filled with pork and savoury broth that bursts when bitten. The crab roe version is a luxury. Eat with ginger and black vinegar. Dim sum and Chinese restaurants worldwide serve them. Xiaolongbao are one of the world''s most perfect dumplings.' WHERE category = 'foods' AND title_en = 'Xiaolongbao Soup Dumplings';

UPDATE challenges SET description_en = 'Yakitori is charcoal-grilled chicken skewers: various cuts including thigh, skin, and meatballs, with salt or tare sauce. Yakitori is casual, drink-friendly, and deeply Japanese. Yakitori-ya and Japanese restaurants worldwide serve it. Yakitori is the taste of Japanese pub culture and one of the world''s great grilled foods.' WHERE category = 'foods' AND title_en = 'Yakitori';

UPDATE challenges SET description_en = 'Zaatar manakish is Lebanese flatbread topped with zaatar (thyme, sumac, sesame) and olive oil, baked in a hot oven. It is breakfast and snack food. Zaatar manakish is fragrant, simple, and addictive. Lebanese and Middle Eastern bakeries and restaurants worldwide serve it fresh. It is a pillar of Levantine breakfast.' WHERE category = 'foods' AND title_en = 'Zaatar Manakish';

UPDATE challenges SET description_en = 'Zongzi are glutinous rice dumplings wrapped in bamboo leaves, often with fillings such as pork, beans, or dates. They are eaten at the Dragon Boat Festival. The rice is sticky and fragrant; the leaves impart aroma. Chinese bakeries and restaurants serve them, especially around the Dragon Boat Festival. Zongzi are one of China''s oldest festival foods.' WHERE category = 'foods' AND title_en = 'Zongzi Dragon Boat Dumplings';
