-- schema-v7.sql: 신규 5개 카테고리 100개씩 추가
-- museums, art_galleries, fishing, drinks, islands

-- =============================================
-- 기존 category CHECK 제약 삭제 후 16개 카테고리로 재생성
-- =============================================
ALTER TABLE public.challenges DROP CONSTRAINT IF EXISTS challenges_category_check;

ALTER TABLE public.challenges
  ADD CONSTRAINT challenges_category_check
  CHECK (category IN (
    'attractions','foods','golf','countries','restaurants',
    'animals','festivals','nature','surfing','skiing','scuba',
    'museums','art_galleries','fishing','drinks','islands'
  ));

-- =============================================
-- MUSEUMS: 세계 100대 박물관
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('museums','루브르 박물관','Louvre Museum','FR','World largest museum; 35,000 works, Mona Lisa, Venus de Milo, Paris',10),
('museums','대영 박물관','British Museum','GB','8 million objects; Rosetta Stone, Elgin Marbles, Egyptian mummies, London',10),
('museums','메트로폴리탄 미술관','The Met (Metropolitan Museum of Art)','US','2 million objects; 5,000 years of art, 5th Avenue New York City',10),
('museums','스미소니언 자연사 박물관','Smithsonian National Museum of Natural History','US','148 million specimens; Hope Diamond, T-Rex skeleton, Washington DC free',10),
('museums','에르미타주 박물관','State Hermitage Museum','RU','3 million+ objects; 33 Rembrandts, Catherine the Great collection, St Petersburg',10),
('museums','바티칸 박물관','Vatican Museums','VA','Sistine Chapel ceiling, Raphael Rooms, 54 galleries, Vatican City Rome',15),
('museums','국립 고궁 박물원 (타이베이)','National Palace Museum','TW','700,000 imperial Chinese artifacts; Jade Cabbage, Meat-shaped Stone, Taipei',15),
('museums','카이로 이집트 박물관','Egyptian Museum, Cairo','EG','Tutankhamun gold mask, Royal Mummies, 120,000 ancient artifacts, Tahrir',10),
('museums','국립 박물관 인도','National Museum of India, New Delhi','IN','Harappan seals, Mughal paintings, 200,000 objects, Janpath New Delhi',10),
('museums','아테네 국립 고고학 박물관','National Archaeological Museum Athens','GR','Mycenaean gold mask of Agamemnon, Antikythera mechanism, Athens Greece',10),
('museums','베를린 페르가몬 박물관','Pergamon Museum, Berlin','DE','Reconstructed Pergamon Altar, Ishtar Gate of Babylon, Market Gate Miletus',15),
('museums','프라도 미술관','Prado Museum','ES','Goya, Velazquez, El Greco masterpieces; Spain national treasure, Madrid',10),
('museums','우피치 미술관','Uffizi Gallery','IT','Botticelli Birth of Venus, Raphael, Michelangelo, Renaissance art, Florence',10),
('museums','자연사 박물관 (런던)','Natural History Museum, London','GB','Blue Whale skeleton, dinosaurs, Hope meteorite, free admission, London',10),
('museums','빅토리아 알버트 박물관','Victoria and Albert Museum','GB','World greatest decorative arts museum; 4.5 million objects, London free',10),
('museums','국립 도쿄 박물관','Tokyo National Museum','JP','Japan oldest national museum; 120,000 objects, Ueno Park since 1872',10),
('museums','경복궁 국립 박물관','National Museum of Korea','KR','Gyeongcheonsa Pagoda, Celadon, gold crowns; free, Yongsan Seoul',10),
('museums','중국 국가 박물관','National Museum of China','CN','1.4 million objects; Bronze Age vessels, jade suits, Tiananmen Square',10),
('museums','인도 국립 박물관 뭄바이','Chhatrapati Shivaji Maharaj Vastu Sangrahalaya','IN','Mumbai natural history and Indian art; colonial Gothic building, Mumbai',10),
('museums','이스탄불 고고학 박물관','Istanbul Archaeological Museums','TR','Sarcophagus of Alexander, Treaty of Kadesh oldest peace treaty; Istanbul',10),
('museums','카이로 그랜드 이집트 박물관','Grand Egyptian Museum (GEM)','EG','World largest archaeological museum; Tutankhamun complete collection, Giza',20),
('museums','시카고 자연사 박물관','Field Museum, Chicago','US','Sue the most complete T-Rex; Egyptian mummies, Pacific Islands, Chicago',10),
('museums','미국 자연사 박물관 (뉴욕)','American Museum of Natural History','US','Blue Whale, planetarium, dinosaur halls, Margaret Mead collection, NYC',10),
('museums','스미소니언 항공우주 박물관','Smithsonian Air & Space Museum','US','Wright Brothers Flyer, Apollo 11 capsule, SR-71 Blackbird, DC free',10),
('museums','로얄 온타리오 박물관','Royal Ontario Museum','CA','1 million objects; crystals, indigenous culture, Asian art, Toronto',10),
('museums','호주 박물관 (시드니)','Australian Museum, Sydney','AU','Dinosaurs, Pacific Islander culture, minerals; oldest museum in Australia',10),
('museums','멜버른 박물관','Melbourne Museum','AU','Bunjilaka Aboriginal gallery, Phar Lap racehorse, dinosaurs, Melbourne',10),
('museums','샌프란시스코 드 영 박물관','de Young Museum, San Francisco','US','American art, textiles, African, Oceanic collections; Golden Gate Park',10),
('museums','라이크스뮤지엄 (암스테르담)','Rijksmuseum, Amsterdam','NL','Rembrandt Night Watch, Vermeer Milkmaid, Delftware, Amsterdam Netherlands',10),
('museums','안네 프랑크 하우스','Anne Frank House','NL','Secret annex where Anne Frank hid 1942-1944; original diary, Amsterdam',10),
('museums','아우슈비츠 박물관','Auschwitz-Birkenau State Museum','PL','UNESCO; Holocaust memorial and warning, Oswiecim Poland most visited',15),
('museums','바르샤바 봉기 박물관','Warsaw Rising Museum','PL','1944 Warsaw Uprising; multimedia immersive experience, Warsaw Poland',10),
('museums','마드리드 레이나 소피아','Reina Sofia Museum, Madrid','ES','Picasso Guernica, Dali, Miro; Spain national museum of modern art',10),
('museums','테이트 모던 (런던)','Tate Modern, London','GB','Bankside Power Station converted; Rothko, Warhol, Dali, free London',10),
('museums','퐁피두 센터','Centre Pompidou, Paris','FR','Inside-out building; Kandinsky, Matisse, Chagall, modern art, Paris',10),
('museums','모나코 해양 박물관','Oceanographic Museum of Monaco','MC','Jacques Cousteau directorship; sharks, coral, deep sea, Monaco cliff',10),
('museums','빈 자연사 박물관','Natural History Museum Vienna','AT','Venus of Willendorf 28,000 BC, meteorites, maria Theresa collection',10),
('museums','무세오 델 오로 (보고타)','Gold Museum (Museo del Oro), Bogota','CO','55,000 pre-Columbian gold pieces; El Dorado myth origin, Bogota Colombia',15),
('museums','페루 라르코 박물관','Larco Museum, Lima','PE','Pre-Columbian gold, textiles, erotic ceramics; Pueblo Libre Lima Peru',10),
('museums','아즈텍 박물관','Museo Nacional de Antropologia, Mexico City','MX','Aztec Sun Stone, Maya Palenque mask, 1 million visitors/year, Mexico City',10),
('museums','마야 박물관 팔렝케','Palenque Archaeological Museum','MX','Jade funeral mask of Pakal; site museum at ruins, Chiapas Mexico',10),
('museums','상파울루 미술관','MASP (Sao Paulo Museum of Art)','BR','Van Gogh, Renoir, Raphael suspended in glass; landmark Paulista Avenue',10),
('museums','부에노스 아이레스 라틴아메리카 박물관','MALBA, Buenos Aires','AR','Frida Kahlo, Rivera, Latin American masters; Palermo Buenos Aires',10),
('museums','시드니 유대인 박물관','Sydney Jewish Museum','AU','Holocaust testimonies; Sydney Darlinghurst, living survivors',10),
('museums','바르셀로나 피카소 박물관','Picasso Museum, Barcelona','ES','Early Picasso works; medieval palace complex, El Born Barcelona',10),
('museums','뮌헨 독일 박물관','Deutsches Museum, Munich','DE','World largest science museum; 73,000 objects, electricity, aviation, Munich',10),
('museums','다빈치 박물관 밀라노','Leonardo da Vinci Museum of Science','IT','500 da Vinci models; flying machines, Renaissance genius, Milan',10),
('museums','런던 과학 박물관','Science Museum, London','GB','Stephenson Rocket, Apollo 10, Crick/Watson DNA model, free London',10),
('museums','시카고 과학 산업 박물관','Museum of Science and Industry, Chicago','US','U-505 WWII submarine, Coal Mine, baby chick hatching, Chicago',10),
('museums','로스앤젤레스 게티 센터','Getty Center, Los Angeles','US','Van Gogh Irises, Monet, Rembrandt; hilltop campus with city views, free',10),
('museums','뉴욕 구겐하임 박물관','Guggenheim Museum, New York','US','Frank Lloyd Wright spiral; Kandinsky, Pollock, Picasso, 5th Ave NYC',10),
('museums','빌바오 구겐하임','Guggenheim Museum Bilbao','ES','Frank Gehry titanium building; Puppy flower topiary; Bilbao Spain',10),
('museums','스톡홀름 바사 박물관','Vasa Museum, Stockholm','SE','1628 warship sank on first voyage; 95% original timber, Stockholm',15),
('museums','오슬로 바이킹 선박 박물관','Viking Ship Museum, Oslo','NO','Oseberg Viking burial ship; 1,200-year-old vessel, Bygdoy Oslo',10),
('museums','코펜하겐 국립 박물관','National Museum of Denmark','DK','Tollund Man bog body, Viking sword, prehistoric Sun Chariot, Copenhagen',10),
('museums','헬싱키 국립 박물관','National Museum of Finland','FI','Finnish prehistory to modern; Art Nouveau building 1916, Helsinki',10),
('museums','빈 미술사 박물관','Kunsthistorisches Museum Vienna','AT','Vermeer Art of Painting, Raphael, Bruegel; Habsburg imperial art, Vienna',10),
('museums','드레스덴 국립 박물관','Dresden State Art Collections','DE','Sistine Madonna Raphael, Green Vault treasures, Dresden Germany',10),
('museums','마드리드 티센 보르네미사','Thyssen-Bornemisza Museum, Madrid','ES','Van Eyck to Pop Art; private collection masterpieces, Madrid Spain',10),
('museums','피렌체 바르젤로 박물관','Bargello Museum, Florence','IT','Donatello David, Michelangelo Bacchus, Renaissance sculpture capital',10),
('museums','나폴리 국립 고고학 박물관','National Archaeological Museum Naples','IT','Pompeii artifacts; Secret Cabinet, Farnese Hercules, Naples Italy',10),
('museums','로마 보르게세 박물관','Borghese Gallery, Rome','IT','Bernini masterpieces; timed-entry 360 visitors max, Villa Borghese Rome',15),
('museums','테헤란 이란 국립 박물관','National Museum of Iran, Tehran','IR','Achaemenid, Sassanid, Islamic periods; Tehran Iran ancient artifacts',10),
('museums','이스탄불 토프카프 궁전','Topkapi Palace Museum','TR','Ottoman sultans treasury; Sancak-i Serif, Spoonmaker Diamond, Istanbul',10),
('museums','카이로 코프트 박물관','Coptic Museum, Cairo','EG','World finest Coptic art collection; Nag Hammadi Gospels, Coptic Cairo',10),
('museums','튀니스 바르도 박물관','Bardo National Museum, Tunis','TN','World finest Roman mosaic collection; 3,000 sq m mosaics, Tunis',15),
('museums','다카르 아프리카 문명 박물관','Museum of Black Civilizations, Dakar','SN','First Africa-built pan-African museum; opened 2018 Dakar Senegal',10),
('museums','아크라 국립 박물관','National Museum of Ghana','GH','Ashanti regalia, kente cloth, traditional artifacts; Accra Ghana',10),
('museums','케이프 타운 이주자 박물관','Iziko South African Museum','ZA','San rock art, whale skeleton, Cape geography; Cape Town South Africa',10),
('museums','나이로비 국립 박물관','National Museum of Kenya','KE','Louis Leakey collection, Joy Adamson Elsa paintings; Nairobi Kenya',10),
('museums','다르에스살람 국립 박물관','National Museum of Tanzania','TZ','Zinjanthropus skull, Leakey findings, Shirazi history; Dar es Salaam',10),
('museums','방콕 국립 박물관','National Museum Bangkok','TH','Gold regalia, ancient weapons, royal funeral carriages; Na Phra That',10),
('museums','하노이 역사 박물관','Vietnam National Museum of History','VN','Vietnamese dynastic history; Dong Son drums, imperial seals, Hanoi',10),
('museums','싱가포르 국립 박물관','National Museum of Singapore','SG','Singapore history from 1299; glass rotunda, free permanent galleries',10),
('museums','쿠알라룸푸르 이슬람 예술 박물관','Islamic Arts Museum Malaysia','MY','World largest Islamic art museum; 7,000 objects, Perdana Botanical Garden',10),
('museums','자카르타 국립 박물관','National Museum of Indonesia','ID','Ganesha statue, Majapahit gold, kris daggers; Museum Nasional Jakarta',10),
('museums','마닐라 국립 박물관','National Museum of the Philippines','PH','Juan Luna Spoliarium, Banaue Rice Terraces model; Manila Luneta Park',10),
('museums','베이징 고궁 박물원','Palace Museum (Forbidden City)','CN','1.8 million imperial artifacts; most visited museum globally, Beijing',15),
('museums','상하이 박물관','Shanghai Museum','CN','Bronze vessels, calligraphy, jade; People Square Shanghai China',10),
('museums','홍콩 역사 박물관','Hong Kong Museum of History','HK','Hong Kong story from 6,000 years; Tsimshatsui, free admission',10),
('museums','대만 국립 역사 박물관','National Taiwan Museum','TW','Oldest museum in Taiwan 1908; natural history, indigenous tribes, Taipei',10),
('museums','서울 국립 민속 박물관','National Folk Museum of Korea','KR','Korean traditional life, Jangseung totem poles; Gyeongbokgung Palace compound',10),
('museums','베를린 유대인 박물관','Jewish Museum Berlin','DE','Daniel Libeskind deconstructivist building; Holocaust memory, Berlin',10),
('museums','시드니 파워하우스 박물관','Powerhouse Museum, Sydney','AU','James Watt steam engine; applied arts, science, design, Ultimo Sydney',10),
('museums','웰링턴 테 파파 박물관','Te Papa Tongarewa, Wellington','NZ','National museum of NZ; Maori taonga, Colossal Squid, Wellington',10),
('museums','멕시코 시티 소우마야 박물관','Museo Soumaya, Mexico City','MX','65,000 objects; largest Rodin collection outside France, Polanco Mexico',10),
('museums','아테네 아크로폴리스 박물관','Acropolis Museum, Athens','GR','Parthenon marbles context; glass floor over ancient ruins, Athens Greece',10),
('museums','보고타 보테로 박물관','Botero Museum, Bogota','CO','Fernando Botero donation; Picasso, Dali, Matisse, free Candelaria Bogota',10),
('museums','퀘백 문명 박물관','Musee de la Civilisation, Quebec','CA','Place Royale archaeology, First Nations culture; Old Quebec waterfront',10),
('museums','오타와 캐나다 전쟁 박물관','Canadian War Museum, Ottawa','CA','Hitler Mercedes, D-Day artifacts, Vimy Ridge memorial; Ottawa Canada',10),
('museums','워싱턴 홀로코스트 박물관','US Holocaust Memorial Museum','US','Evocative Holocaust documentation; Washington DC near National Mall',15),
('museums','뉴욕 911 추모 박물관','9/11 Memorial & Museum','US','Twin Tower artifacts, survivor testimonies; Ground Zero New York',15),
('museums','박물관 오르세 (파리)','Musee d Orsay, Paris','FR','Impressionist masterpieces; Monet, Renoir, Van Gogh in converted railway station',10),
('museums','빈 제체시온 박물관','Wien Museum, Vienna','AT','Vienna city history; Klimt Kiss study, Schiele drawings, Vienna Austria',10),
('museums','암스테르담 국립 박물관','Amsterdam Museum','NL','Amsterdam city history 1275 to present; medieval sculpture, maps',10),
('museums','바르셀로나 역사 박물관','Barcelona History Museum (MUHBA)','ES','Roman Barcino underground; medieval city ruins beneath Gothic Quarter',10),
('museums','스톡홀름 노르딕 박물관','Nordic Museum, Stockholm','SE','400 years Scandinavian life; textiles, silverware, Sami culture, Djurgarden',10),
('museums','에든버러 스코틀랜드 국립 박물관','National Museum of Scotland','GB','Dolly the Sheep, Lewis Chessmen, Scotland story; Old Town Edinburgh free',10),
('museums','뉴델리 국립 현대 미술관','NGMA New Delhi','IN','Raja Ravi Varma, Amrita Sher-Gil; Indian modern art since 1954',10),
('museums','이스탄불 이슬람 예술 박물관','Museum of Turkish and Islamic Arts','TR','Anatolian carpets, Quran manuscripts; Ibrahim Pasha Palace Istanbul',10),
('museums','카사블랑카 하산 2세 박물관','Abderrahman Slaoui Foundation Museum','MA','Vintage Moroccan posters, art nouveau, perfume flacons; Casablanca',10);

-- =============================================
-- ART GALLERIES: 세계 100대 미술관/갤러리
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('art_galleries','모마 (뉴욕)','MoMA – Museum of Modern Art','US','Starry Night, Warhol, Pollock; modern art temple, 54th St Midtown NYC',10),
('art_galleries','테이트 모던','Tate Modern, London','GB','Turbine Hall installations, Warhol, Rothko, free entry, Bankside London',10),
('art_galleries','구겐하임 뉴욕','Guggenheim Museum, New York','US','Frank Lloyd Wright spiral; Chagall, Picasso, Braque, 5th Avenue NYC',10),
('art_galleries','구겐하임 빌바오','Guggenheim Bilbao','ES','Jeff Koons Puppy, Richard Serra; Gehry titanium masterpiece, Bilbao Spain',10),
('art_galleries','테이트 브리튼','Tate Britain, London','GB','Turner Prize, Pre-Raphaelites, British art 1500 to now; Millbank London',10),
('art_galleries','퐁피두 파리','Centre Pompidou, Paris','FR','Matisse, Dali, Duchamp; inside-out coloured pipes building, Paris',10),
('art_galleries','국립 현대 미술관 (파리)','Musee National d Art Moderne, Paris','FR','Europe largest modern art collection inside Pompidou, Paris France',10),
('art_galleries','라 팔레스 드 도쿄','Palais de Tokyo, Paris','FR','Cutting-edge contemporary art; largest contemporary art centre in Europe',10),
('art_galleries','아르세날레 베니스','Venice Arsenale & Giardini','IT','Venice Biennale pavilions; world most prestigious art event biennial',20),
('art_galleries','마드리드 카이샤 포럼','CaixaForum Madrid','ES','Patrick Blanc vertical garden; Herzog de Meuron conversion, Madrid',10),
('art_galleries','밀라노 트리에날레','Triennale di Milano','IT','Design and contemporary art; Parco Sempione Milan Italy triennial',10),
('art_galleries','취리히 미술관','Kunsthaus Zurich','CH','Van Gogh, Munch, Giacometti; Switzerland national collection, Zurich',10),
('art_galleries','암스테르담 반 고흐 미술관','Van Gogh Museum, Amsterdam','NL','200 paintings, 500 drawings; Almond Blossom, Sunflowers originals',15),
('art_galleries','암스테르담 스테델레이크','Stedelijk Museum, Amsterdam','NL','Mondrian, Malevich, Appel; Dutch CoBrA movement collection, Amsterdam',10),
('art_galleries','뮌헨 피나코테크 3관','Alte/Neue/Moderne Pinakothek, Munich','DE','Rubens, Raphael, Cezanne; three centuries of European art, Munich',10),
('art_galleries','베를린 알테스 나치오날갤러리','Alte Nationalgalerie, Berlin','DE','Friedrich, Menzel, Schinkel; German Romantic masters, Berlin Museum Island',10),
('art_galleries','베를린 함부르거 반호프','Hamburger Bahnhof, Berlin','DE','Beuys, Warhol, Twombly; contemporary art railway station, Berlin',10),
('art_galleries','드레스덴 게말데 갤러리','Gemaldegalerie Alte Meister, Dresden','DE','Raphael Sistine Madonna; old masters gallery, Zwinger Palace Dresden',10),
('art_galleries','비엔나 알베르티나','Albertina, Vienna','AT','Monet, Modigliani, Klimt; Habsburg graphics collection, Vienna',10),
('art_galleries','빈 벨베데레','Belvedere, Vienna','AT','Klimt Kiss original; Schiele, Kokoschka; Baroque palace gardens, Vienna',15),
('art_galleries','스톡홀름 현대 미술관','Moderna Museet, Stockholm','SE','Duchamp, Picabia, Swedish masters; Skeppsholmen island Stockholm',10),
('art_galleries','오슬로 국립 미술관','National Museum, Oslo','NO','Munch Scream original; Cezanne, Matisse; new building 2022, Oslo',15),
('art_galleries','헬싱키 아테네움','Ateneum Art Museum, Helsinki','FI','Gallen-Kallela, Edelfelt, Schjerfbeck; Finnish national collection',10),
('art_galleries','코펜하겐 글립토테크','Ny Carlsberg Glyptotek, Copenhagen','DK','Gauguin, Rodin, Degas; Carl Jacobsen collection, Copenhagen',10),
('art_galleries','코펜하겐 루이지애나','Louisiana Museum of Modern Art','DK','Giacometti, Picasso, Calder; clifftop Oresund views, Humlebaek Denmark',15),
('art_galleries','리스본 베라르도 컬렉션','Berardo Collection Museum, Lisbon','PT','Warhol, Picasso, Duchamp, Klein; Belem free entry, Lisbon Portugal',10),
('art_galleries','포르투 세라베스','Serralves Museum of Contemporary Art','PT','Alvaro Siza building; large garden, contemporary, Porto Portugal',10),
('art_galleries','마드리드 카이샤 포럼 바르셀로나','Fundacio Joan Miro, Barcelona','ES','Miro universe; hilltop Montjuic building, Barcelona Catalonia Spain',10),
('art_galleries','바르셀로나 카탈루냐 미술관','MNAC, Barcelona','ES','Romanesque frescoes, Modernisme; Montjuic National Palace, Barcelona',10),
('art_galleries','뉴욕 휘트니 미술관','Whitney Museum of American Art','US','Hopper Nighthawks study, Basquiat, Koons; Meatpacking District NYC',10),
('art_galleries','샌프란시스코 현대 미술관','SFMOMA, San Francisco','US','Frida Kahlo, Warhol, Matisse; 7-story expansion 2016, SF California',10),
('art_galleries','시카고 미술관','Art Institute of Chicago','US','Seurat Sunday, Wood American Gothic, Hopper Nighthawks; Magnificent Mile',10),
('art_galleries','LA 카운티 미술관','LACMA, Los Angeles','US','Largest US West Coast art museum; Urban Light lamp post forest, LA',10),
('art_galleries','워싱턴 국립 미술관','National Gallery of Art, Washington DC','US','Da Vinci only in Americas; Vermeer, Raphael, Rembrandt; free DC',10),
('art_galleries','보스턴 미술관','Museum of Fine Arts, Boston','US','Monet, Renoir, Japanese prints; second largest US art museum, Boston',10),
('art_galleries','캐나다 국립 미술관','National Gallery of Canada, Ottawa','CA','Emily Carr, Group of Seven; stained glass Rideau Chapel, Ottawa free',10),
('art_galleries','몬트리올 미술관','Montreal Museum of Fine Arts','CA','Largest museum in Canada; Egyptian mummies, Gauguin, Montreal Quebec',10),
('art_galleries','멜버른 NGV 국제','NGV International, Melbourne','AU','Asia-Pacific largest art museum; Tiepolo, Rembrandt, free entry Melbourne',10),
('art_galleries','시드니 현대 미술관','Museum of Contemporary Art, Sydney','AU','MCA on Circular Quay; Australian Indigenous, Aboriginal dot painting',10),
('art_galleries','도쿄 국립 근대 미술관','Tokyo National Museum of Modern Art','JP','Yokoyama Taikan, Kuroda Seiki; next to Imperial Palace, Chiyoda Tokyo',10),
('art_galleries','도쿄 모리 미술관','Mori Art Museum, Tokyo','JP','53rd floor Roppongi Hills; panoramic Tokyo views plus contemporary art',10),
('art_galleries','도쿄 오페라시티 갤러리','Tokyo Opera City Art Gallery','JP','Japanese contemporary masters; chamber music venue complex, Shinjuku',10),
('art_galleries','나오시마 섬 미술관','Chichu Art Museum, Naoshima','JP','Tadao Ando underground museum; Monet Water Lilies in situ, Naoshima',20),
('art_galleries','서울 국립 현대 미술관','MMCA National Museum of Modern Art','KR','Deoksugung, Gwacheon, Seoul, Cheongju four branches; free Sundays',10),
('art_galleries','서울 리움 미술관','Leeum Samsung Museum of Art','KR','Kansai Siza Nouvel Koolhaas; celadon to contemporary, Hannam Seoul',15),
('art_galleries','상하이 현대 미술관','Power Station of Art, Shanghai','CN','National pavilion Shanghai Biennale; converted power station Huangpu',10),
('art_galleries','베이징 UCCA','UCCA Center for Contemporary Art, Beijing','CN','Anish Kapoor, Ai Weiwei; 798 Art District factory complex, Beijing',10),
('art_galleries','홍콩 M+','M+ Museum, West Kowloon','HK','Asia largest visual culture museum; Herzog de Meuron building 2021',10),
('art_galleries','싱가포르 국립 미술관','National Gallery Singapore','SG','Colonial Civic District buildings; Southeast Asian art 1900 to now',10),
('art_galleries','무하 미술관 프라하','Mucha Museum, Prague','CZ','Alphonse Mucha Art Nouveau; Slav Epic, Rue detail, Old Town Prague',10),
('art_galleries','부다페스트 미술관','Museum of Fine Arts, Budapest','HU','El Greco, Raphael, Goya; Egyptian collection, Heroes Square Budapest',10),
('art_galleries','바르샤바 국립 박물관 미술','National Museum Warsaw (art)','PL','Faras Nubian frescoes, Rubens, Polish masters; Warsaw Poland',10),
('art_galleries','프라하 국립 미술관','National Gallery Prague','CZ','Cranach, Rubens, Klimt Kiss copy; Veletrzni Palac building, Prague',10),
('art_galleries','키예프 우크라이나 국립 미술관','National Art Museum of Ukraine','UA','Ukrainian Baroque icons, Shevchenko; Grushevsky Street Kyiv',10),
('art_galleries','상트페테르부르크 러시아 미술관','Russian Museum, St Petersburg','RU','Repin, Aivazovsky, Kandinsky; Mikhailovsky Palace, St Petersburg',10),
('art_galleries','카이로 현대 이집트 미술관','Museum of Modern Egyptian Art','EG','Mahmoud Said, Ragheb Ayad; Opera Square Garden, Cairo Egypt',10),
('art_galleries','테헤란 현대 미술관','Tehran Museum of Contemporary Art','IR','Warhol, Pollock, Miro; hid from revolution 1979; now showing, Tehran',15),
('art_galleries','이스탄불 현대 미술관','Istanbul Modern','TR','Turkish contemporary art; Tophane waterfront, Bosphorus view Istanbul',10),
('art_galleries','텔아비브 미술관','Tel Aviv Museum of Art','IL','Impressionism, Cobra, Israeli Expressionism; Helena Rubinstein Pavilion',10),
('art_galleries','두바이 잠 엘 아트','Jameel Arts Centre, Dubai','AE','Contemporary Middle Eastern art; waterfront Dubai Creek Jaddaf',10),
('art_galleries','아부다비 루브르','Louvre Abu Dhabi','AE','Jean Nouvel star-pierced dome; Da Vinci, Pissarro, Magritte; Saadiyat',20),
('art_galleries','요하네스버그 게르투르트 포케 갤러리','Johannesburg Art Gallery','ZA','Rodin, Modigliani, African prints; Joubert Park largest in South Africa',10),
('art_galleries','나이로비 나즈마 미술관','Nairobi National Museum (art)','KE','Kenyan contemporary art, Joy Adamson wildlife paintings; Kenya',10),
('art_galleries','상파울루 MASP','MASP Sao Paulo','BR','Botticelli to Van Gogh suspended in glass; Paulista Avenue icon Brazil',10),
('art_galleries','부에노스 아이레스 국립 미술관','Museo Nacional de Bellas Artes, Buenos Aires','AR','Rodin, Renoir, Gauguin; largest collection in Latin America, Recoleta',10),
('art_galleries','멕시코 팔라시오 데 벨라스 아르테스','Palacio de Bellas Artes, Mexico City','MX','Rivera, Orozco, Siqueiros murals; Art Deco marble, Alameda Park',15),
('art_galleries','멕시코 프리다 칼로 뮤지엄','Frida Kahlo Museum (Casa Azul), Mexico City','MX','Blue House where Frida was born and died; Coyoacan, Mexico City',15),
('art_galleries','리마 아르코 갤러리','MALI (Museo de Arte de Lima)','PE','Pre-Columbian to Republican; largest collection in Peru, Lima Paseo Colon',10),
('art_galleries','보고타 루이스 앙헬 아랑고','Banco de la Republica Art Collection, Bogota','CO','Botero paintings and sculptures; free admission La Candelaria Bogota',10),
('art_galleries','산티아고 칠레 현대 미술관','MAC, Santiago de Chile','CL','Chilean contemporary masters; Parque Forestal riverside Santiago',10),
('art_galleries','하바나 국립 미술관','Museo Nacional de Bellas Artes, Havana','CU','European masters and Cuban art; two buildings Old Havana Cuba',10),
('art_galleries','뉴질랜드 크라이스트처치 갤러리','Christchurch Art Gallery','NZ','Post-earthquake icon; New Zealand art, international contemporary',10),
('art_galleries','런던 서펜타인 갤러리','Serpentine Galleries, London','GB','Annual Pavilion architect commission; Hyde Park free, London',10),
('art_galleries','뉴욕 뉴 미술관','New Museum, New York','US','SANAA building; cutting-edge emerging artists, Lower East Side NYC',10),
('art_galleries','LA 게티 빌라','Getty Villa, Malibu','US','Greek and Roman antiquities; Malibu clifftop, Pacific views, LA',10),
('art_galleries','시애틀 미술관','Seattle Art Museum','US','Charles and Emma Frye; Hammering Man sculpture, Seattle Washington',10),
('art_galleries','덴버 미술관','Denver Art Museum','US','Native American, Asian, Western American; Daniel Libeskind addition',10),
('art_galleries','아틀란타 하이 미술관','High Museum of Art, Atlanta','US','Richard Meier white building; Impressionism, Southern American art',10),
('art_galleries','런던 화이트채플 갤러리','Whitechapel Gallery, London','GB','Picasso Guernica UK debut 1938; East End London contemporary free',10),
('art_galleries','뉴욕 가고시안 갤러리','Gagosian Gallery, New York','US','Damien Hirst, Jeff Koons, Cy Twombly; global flagship art gallery NYC',10),
('art_galleries','런던 화이트큐브','White Cube, London','GB','Damien Hirst, Tracey Emin; Bermondsey and Mayfair locations London',10),
('art_galleries','도쿄 하라 미술관','Hara Museum of Contemporary Art, Tokyo','JP','Francis Bacon, George Segal; Shinagawa garden villa 1938, Tokyo',10),
('art_galleries','오사카 현대 미술관','National Museum of Art Osaka','JP','Underground museum; Japanese post-war, international contemporary',10),
('art_galleries','교토 국립 근대 미술관','National Museum of Modern Art Kyoto','JP','Kyoto Nihonga painting tradition; bamboo-themed Okazaki building',10),
('art_galleries','제주 이중섭 미술관','Lee Jung-seob Museum, Jeju','KR','Bull paintings; Korea most beloved modern artist, Seogwipo Jeju',10),
('art_galleries','광주 아시아 문화 전당','Asia Culture Center, Gwangju','KR','ACC underground complex; May 18 memorial, Asian culture research',10),
('art_galleries','타이베이 당대 예술관','Taipei Contemporary Art Center','TW','Former municipal hall; Taiwan contemporary art, Datong district',10),
('art_galleries','하노이 베트남 미술관','Vietnam Museum of Fine Arts, Hanoi','VN','Nguyen Phan Chanh lacquer works, Dong Son bronze, French-colonial building',10),
('art_galleries','콜롬보 국립 미술관','National Art Gallery of Sri Lanka','LK','Sri Lankan colonial and contemporary; Lipton Circus Colombo',10),
('art_galleries','인도 국립 현대 미술관','National Gallery of Modern Art, Mumbai','IN','Jamini Roy, Rabindranath Tagore; King George V building, Mumbai',10),
('art_galleries','모스크바 현대 미술관','Moscow Museum of Modern Art','RU','Zurab Tsereteli collection; multiple venues, Russian contemporary art',10),
('art_galleries','부쿠레슈티 국립 미술관','National Museum of Art Romania','RO','El Greco, Rubens; former Royal Palace, Calea Victoriei Bucharest',10),
('art_galleries','아테네 고나리스 갤러리','National Gallery, Athens','GR','El Greco Return of the Prodigal; Greek masters, Vassileos Konstantinou',10),
('art_galleries','리가 라트비아 국립 미술관','Latvian National Museum of Art','LV','Latvian Romantic masters; neoclassical palace, Riga Latvia',10);

-- =============================================
-- FISHING: 세계 100대 낚시 스팟
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('fishing','알래스카 케나이 강','Kenai River, Alaska','US','World record king salmon 44kg; combat fishing elbow-to-elbow July Alaska',20),
('fishing','몬태나 빅홀 강','Big Hole River, Montana','US','Blue-ribbon trout stream; arctic grayling and trophy brown trout, Montana',15),
('fishing','몬태나 매디슨 강','Madison River, Montana','US','One of US premier fly fishing rivers; 3,000 trout/mile near Yellowstone',15),
('fishing','노르웨이 알타 강','Alta River, Norway','NO','World greatest Atlantic salmon river; Norway Finnmark, king of rivers',20),
('fishing','아이슬란드 엘리다 강','Ellidaar River, Reykjavik','IS','Wild Atlantic salmon runs through capital city; Reykjavik urban fishing',15),
('fishing','뉴질랜드 타라웨라','Lake Taupo, New Zealand','NZ','World rainbow trout capital; 700 tons caught annually, Waikato NZ',15),
('fishing','캐나다 캠벨 강','Campbell River, BC','CA','Salmon capital of the world; chinook, coho, pink, sockeye, chum BC',15),
('fishing','캐나다 썬더 베이','Lake Nipigon, Ontario','CA','World record brook trout; remote fly-in lake, north Ontario Canada',15),
('fishing','파타고니아 강','Rio Grande, Tierra del Fuego','AR','World record sea-run brown trout 36kg; Patagonia Argentina/Chile',20),
('fishing','칠레 팔레나 강','Palena River, Chile','CL','Remote Patagonia rainbow trout; wilderness fly fishing, Aysen Chile',20),
('fishing','오스트레일리아 배스','Macquarie Perch, Murray River','AU','Australian bass river system; Murray-Darling Basin endemic species',10),
('fishing','오스트레일리아 도미','Barramundi, Top End NT','AU','Northern Territory barramundi; flats sight-fishing, Darwin Kakadu area',15),
('fishing','호주 그레이트 배리어 리프 낚시','Giant Black Marlin, Cairns','AU','600-1000lb black marlin; heavy tackle big game, September-November Cairns',20),
('fishing','일본 이나와시로 호수','Lake Inawashiro, Fukushima','JP','Japanese record rainbow trout; sakura trout seasonal fishing Japan',10),
('fishing','일본 비와 호수','Lake Biwa, Shiga','JP','Japan largest lake; largemouth bass, Japanese trout, Shiga Prefecture',10),
('fishing','일본 아부 가와','Abu River, Yamaguchi','JP','Sweetfish (ayu) traditional fishing; cormorant fishing Ukai ceremony',15),
('fishing','한국 낙동강','Nakdong River, Korea','KR','Korea largest river; flathead catfish, eel, mandarin fish, Korea',10),
('fishing','한국 양양 연어','Yangyang Salmon Return','KR','Pacific salmon run October-November; Namdae River Gangwon Korea',10),
('fishing','중국 야루강','Yarlung Tsangpo, Tibet','CN','World highest river fishing; Snow Trout, Himalayan mahseer, Tibet 4,000m',20),
('fishing','러시아 캄차카','Kamchatka Peninsula, Russia','RU','Pacific salmon paradise; 6 species in untouched rivers, helicopter access',20),
('fishing','카리브 바하마','Bonefish, Bahamas','BS','Bonefish capital of world; deep water cays, wading flats, Andros Bahamas',15),
('fishing','카리브 쿠바','Permit Fishing, Cuba','CU','Grand slam: bonefish permit tarpon in one day; Jardines de la Reina',20),
('fishing','멕시코 칸쿤 마르린','Blue Marlin, Cozumel','MX','600-1,000 lb Atlantic blue marlin; Cozumel deep blue, Mexico',15),
('fishing','코스타리카 과나카스테','Roosterfish, Guanacaste','CR','Unique Pacific game fish with dramatic dorsal; Nosara peninsula Costa Rica',15),
('fishing','파나마 피나스 베이','Tuna, Pinas Bay','PA','World record black marlin and Pacific sailfish; most famous Panama',20),
('fishing','에콰도르 만타','Pacific Sailfish, Manta','EC','Fastest fish; 110 km/h; record sailfish and dorado Ecuadorian Pacific',15),
('fishing','베네수엘라 파야라','Payara (Vampire Fish), Venezuela','VE','4-inch fangs predator; Cinaruco River Apure, sabre-tooth vampire fish',20),
('fishing','브라질 피라루쿠','Pirarucu (Arapaima), Amazon','BR','World largest freshwater fish 200kg; Amazon tributaries Brazil',20),
('fishing','브라질 골든 도라도','Dorado, Pantanal Brazil','BR','Golden dorado acrobatic game fish; Corrientes Province Pirapo River',15),
('fishing','페루 아마존','Peacock Bass, Amazon Peru','PE','World most prized freshwater; remote jungle lodges Madre de Dios Peru',15),
('fishing','콜롬비아 라 마카레나','Peacock Bass, Inirida','CO','World record peacock bass habitat; Guainia river system Colombia',20),
('fishing','에티오피아 나일 퍼치','Nile Perch, Lake Turkana','KE','World record 104kg Nile Perch; 6,000 year old fish, Kenya-Ethiopia border',15),
('fishing','탄자니아 잠베지','Tiger Fish, Lake Tanganyika','TZ','Fierce tiger fish; fang-toothed predator, Nyasa Lake Tanzania',15),
('fishing','짐바브웨 잠베지 강','Tigerfish, Zambezi River','ZW','African tiger fish; rapids below Victoria Falls, Zimbabwe Zambia',15),
('fishing','남아프리카 케이프 타운 튜나','Yellowfin Tuna, Cape Town','ZA','Big game tuna off Cape Point; False Bay Hout Bay Cape Peninsula',10),
('fishing','인도 갠지스 강','Mahseer, Ramganga River','IN','Golden mahseer 50kg; Corbett National Park, Uttarakhand India rivers',15),
('fishing','인도 케랄라 뒤뜰','Backwater Fishing, Kerala','IN','Traditional cast net fishing; Vembanad Lake houseboat, Kerala India',10),
('fishing','스리랑카 마항가마','Murray Cod, Sri Lanka','LK','Jungle perch in highland tea country streams; Ella, Nuwara Eliya area',10),
('fishing','태국 카오 섬 왕','Giant Snakehead, Kanchanaburi','TH','Predator ambush monster; jungle fishing Thailand near Myanmar border',10),
('fishing','태국 차오프라야','Mekong Giant Catfish, Thailand','TH','World largest catfish 293kg; critically endangered, Chiang Khong area',20),
('fishing','베트남 메콩 강','Mekong Giant Catfish, Vietnam','VN','Legendary river monster; Tra Vinh Province Mekong delta Vietnam',15),
('fishing','필리핀 도라도','Dorado (Mahi-mahi), Philippines','PH','Blue-water day trips from Batangas; Philippine Sea dorado fishing',10),
('fishing','인도네시아 파푸아','Black Bass, Papua Indonesia','ID','Fly fishing remote rivers for black bass; Mamberamo River Papua',20),
('fishing','말레이시아 보르네오','Toman (Giant Snakehead), Borneo','MY','Monster snakehead in jungle lakes; Sarawak Borneo Malaysia',15),
('fishing','영국 투이드 강','River Tweed Salmon, Scotland','GB','Scotland premier salmon river; Kelso, Berwick, beats, Atlantic salmon',15),
('fishing','아일랜드 코네마라','Wild Brown Trout, Connemara','IE','Limestone loughs; wild Irish brown trout, Galway Connemara rivers',10),
('fishing','스코틀랜드 스페이 강','River Spey Salmon, Speyside','GB','Smooth Spey cast technique; Grantown-on-Spey, Ballindalloch beats',15),
('fishing','노르웨이 세계 피요르드 대구','Arctic Cod, Lofoten','NO','Lofoten winter cod fishing; traditional wooden boats Henningsvaer',10),
('fishing','스웨덴 모랄라 강','Vanern Sea Trout, Sweden','SE','Swedish record sea trout; Lake Vanern tributaries, Vastergotland',10),
('fishing','아이슬란드 스케야라','Skjalfandafljot River','IS','Multiple salmon river system Iceland; Laxa í Kjos brown trout famous',15),
('fishing','핀란드 루오나야','Simojoki River, Lapland','FI','Finland record Atlantic salmon; Lapland rivers, Rovaniemi area',15),
('fishing','캐나다 BC 스틸헤드','Skeena River Steelhead, BC','CA','Holy grail of fly fishing; wild steelhead, Terrace BC wilderness',20),
('fishing','캐나다 유콘 강','Yukon River King Salmon','CA','Chinook to 30kg+ in remote wilderness; Whitehorse Dawson City Yukon',15),
('fishing','미국 플로리다 타폰','Tarpon, Florida Keys','US','Silver King 100lb+; Boca Grande Pass flats, fly fishing Florida',15),
('fishing','미국 플로리다 바다농어','Snook, Everglades','US','Snook and redfish in backcountry; Everglades City Ten Thousand Islands',10),
('fishing','미국 코드 케이프','Striped Bass, Cape Cod','US','Northeast surfcasting classic; Montauk Point Long Island stripers',10),
('fishing','미국 그랜드 레이크 스트림','Brook Trout, Maine','US','Trophy brook trout in remote fly-only ponds; Grand Lake Stream Maine',15),
('fishing','미국 여섯 강','Green River, Wyoming','US','Blue-ribbon tailwater; rainbow and brown trout below Flaming Gorge Dam',15),
('fishing','미국 플랫헤드 강','Flathead River, Montana','US','Bull trout in Wild and Scenic River; Glacier NP backcountry fishing',15),
('fishing','미국 델라웨어 강','Delaware River Shad','US','American shad springtime run; spawning migration Delaware Water Gap',10),
('fishing','미국 체사피크 만','Chesapeake Blue Crab','US','Crabbing with chicken necks; world biggest blue crab habitat, Maryland',10),
('fishing','포르투갈 알가르베 도라도','Algarve Offshore Big Game','PT','Bluefin tuna, swordfish, mahi-mahi; Vilamoura Portimao Portugal offshore',10),
('fishing','스페인 에브로 강','Catfish, Ebro River','ES','European catfish 100kg+; Mequinenza Spain monster catfish destination',15),
('fishing','크로아티아 얌마 호','Eel Fishing, Neretva Delta','HR','Traditional eel trapping; Neretva River Delta Croatia Adriatic coast',10),
('fishing','이탈리아 포 강 메기','Wels Catfish, Po River','IT','Monster wels catfish; Po Valley Northern Italy, Cremona Mantua area',10),
('fishing','폴란드 부흐 강','Pike Fishing, Bug River','PL','Trophy pike in lowland rivers; Bug River Polish-Belarusian border',10),
('fishing','러시아 바이칼 호수','Omul Fishing, Lake Baikal','RU','Baikal endemic omul whitefish; ice fishing winter, Listvyanka Russia',10),
('fishing','몽골 강 티곤','Taimen (Mongolian Trout)','MN','World largest salmonid 60kg+; Eg-Ur river system Mongolia, horseback access',20),
('fishing','중국 허베이 강','Hucho perryi, Amur River','CN','Itou salmon 100kg+; Russian-Chinese border Amur system, critically rare',20),
('fishing','카나리아 제도 참치','Giant Bluefin Tuna, Canaries','ES','500kg bluefin Atlantic crossing; Canary Islands January-March run',20),
('fishing','세이셸 보네피쉬','Giant Trevally, Seychelles','SC','GTs over 30kg on fly rod; Cosmoledo Astove atolls remote Seychelles',20),
('fishing','모잠비크 세일피쉬','Sailfish, Bazaruto','MZ','Indian Ocean grand slam; Bazaruto Archipelago Mozambique offshore',15),
('fishing','탄자니아 잔지바르 마르린','Blue Marlin, Zanzibar','TZ','Atlantic and Indo-Pacific blue marlin meeting point; Zanzibar Channel',15),
('fishing','케냐 말린디 마르린','Striped Marlin, Malindi','KE','Kenya coast billfish capital; Watamu Marine Park, March-April run',15),
('fishing','모리셔스 화이트 마르린','White Marlin, Mauritius','MU','IGFA world record white marlin; Le Morne Peninsula, Mauritius',15),
('fishing','마다가스카르 베이라 섬','Bonefish, Cosmoledo Atoll','MG','Remote atoll bonefish paradise; Madagascar outer islands',20),
('fishing','오만 게임피싱','Dogtooth Tuna, Oman','OM','Huge dogtooth in Arabian Sea; Musandam Fjords jigging, Oman Gulf',15),
('fishing','UAE 바다낚시','Queen Fish, Dubai','AE','Jigging and popping in Persian Gulf; Fujairah east coast Dubai UAE',10),
('fishing','피지 야기','Giant Trevally, Yasawa','FJ','Fiji remote island GT popping; Yasawa group flats and bluewater',15),
('fishing','팔라우 바다 낚시','Dogtooth Tuna, Palau','PW','Palau deep drop and jigging; Micronesia blue water game fishing',15),
('fishing','파나마 카리브 타폰','Tarpon, Bocas del Toro','PA','Atlantic tarpon in Caribbean lagoons; Bocas del Toro Panama province',10),
('fishing','과테말라 마야','Pacific Sailfish, Guatemala','GT','World record sailfish releases; Iztapa Pacific Guatemala 50 fish/day',20),
('fishing','솔로몬 아일랜드 GT','Giant Trevally, Solomon Islands','SB','Remote Melanesian island GT popping; Munda Ghizo Marovo lagoon',20),
('fishing','파푸아 뉴기니 GT','Giant Trevally, PNG','PG','Cape Vogel untouched GT habitat; Papua New Guinea remote fishing',20),
('fishing','캐나다 처칠 강 파이크','Northern Pike, Manitoba','CA','Monster pike in remote fly-in lakes; Thompson Manitoba Canada',15),
('fishing','미국 루이지애나 크랩','Red Drum (Redfish), Louisiana','US','Sight-casting reds in coastal marshes; Cajun fishing Louisiana bayou',10),
('fishing','미국 가이드 스트림','Permit, Florida Keys','US','Holy grail of fly fishing; tailing permit on the flats, Florida Keys',20),
('fishing','아르헨티나 도라도','Golden Dorado, Corrientes','AR','Argentina golden dorado; Rio Pirapo, Corrientes Province trophy',15),
('fishing','우루과이 강','Tararira, Montevideo','UY','Local freshwater game fish; Rio de la Plata tributaries, Uruguay',10),
('fishing','아이슬란드 퉁나','Tungna River Salmon','IS','Remote Iceland highland salmon river; Tungnafjot system, August run',15),
('fishing','핀란드 이나리 호수','Lake Inari Grayling','FI','European grayling in Arctic lake; Inari Lapland August September Finland',10);

-- =============================================
-- DRINKS: 세계 100대 유명한 술 & 음료
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('drinks','돔 페리뇽','Dom Perignon Champagne','FR','Prestige cuvee of Moet Chandon; cellars beneath Hautvillers Abbey, Champagne',20),
('drinks','크루그 샴페인','Krug Grande Cuvee Champagne','FR','Most complex non-vintage champagne; 6 to 10 year average age, Reims',20),
('drinks','로마네 콩티','Romanee-Conti Grand Cru','FR','World most expensive wine; 1.8 hectares Cote de Nuits Burgundy Pinot Noir',20),
('drinks','페트루스','Petrus Pomerol','FR','100% Merlot right bank Bordeaux; tiny production, world most sought label',20),
('drinks','오퍼스 원','Opus One, Napa Valley','US','Mondavi-Rothschild prestige cuvee; sculptural winery Oakville California',15),
('drinks','스크리밍 이글','Screaming Eagle Cabernet','US','Cult Napa Cabernet; mailing list only, Oakville AVA, California',20),
('drinks','하프로즈 위스키','The Macallan 18 Year','GB','Sherry oak matured Highland single malt; Easter Elchies House, Speyside',15),
('drinks','보모어 25년','Bowmore 25 Year Old','GB','Islay peat smoke and sherry; sea-salt Atlantic air, oldest Islay distillery',15),
('drinks','발베니 더블우드','Balvenie DoubleWood 17 Year','GB','American oak then European sherry finish; Dufftown Speyside Scotland',15),
('drinks','글렌피딕 21년','Glenfiddich 21 Year Gran Reserva','GB','Caribbean rum cask finish; William Grant original distillery, Dufftown',15),
('drinks','야마자키 12년 싱글 몰트','Yamazaki 12 Year Single Malt','JP','First Japanese single malt; cherry blossom aroma, Mizunara oak finish',15),
('drinks','하쿠슈 18년','Hakushu 18 Year Single Malt','JP','Forest distillery; herbal alpine character, Suntory Southern Alps Japan',15),
('drinks','히비키 21년','Hibiki 21 Year Blended','JP','21 malt and grain whisky blend; 24-faceted crystal decanter, Suntory',20),
('drinks','니카 요이치','Nikka Yoichi Single Malt','JP','Masataka Taketsuru founded; Hokkaido coast, coal-fired stills, peat smoke',15),
('drinks','아이리쉬 위스키 레드브레스트','Redbreast 21 Year Single Pot Still','IE','Pure pot still Irish whiskey; IDL Midleton Distillery, Cork Ireland',15),
('drinks','헤네시 XO','Hennessy XO Cognac','FR','First XO cognac 1870; 100 eaux-de-vie blended, Grande Champagne Cognac',15),
('drinks','레미 마르탱 루이 13세','Remy Martin Louis XIII','FR','40-year maturation Tiercon decanter; 1,200 eaux-de-vie, Grande Champagne',20),
('drinks','아르마냑 다라쥐','Darroze Armagnac 40 Year','FR','Single domaine vintage Armagnac; Gascony Bas-Armagnac, oldest eau-de-vie',15),
('drinks','아보카도 메즈칼','Papalometl Ancestral Mezcal','MX','Wild agave ancestral process; clay pot distilled, San Luis Potosi Mexico',15),
('drinks','도스 페스카도스 살마이드','Clase Azul Ultra Mezcal','MX','Hand-painted ceramic decanter; ultra-premium blue agave tequila Oaxaca',20),
('drinks','파트론 엔 랩라도라','Patron Gran Platinum Tequila','MX','Triple-distilled Highlands blue agave; platinum label ultra-premium',15),
('drinks','페루 피스코','Peruvian Pisco Sour (original)','PE','National cocktail; Quebranta grapes, Ica Valley pisco, lime key froth',10),
('drinks','칠레 카르메네레','Carmenere, Concha y Toro Don Melchor','CL','Chile signature grape saved from extinction; Puente Alto Maipo Valley',10),
('drinks','아르헨티나 말베크','Achaval-Ferrer Malbec Quimera','AR','Lujan de Cuyo Mendoza icon; old vine blends, Argentina prestige malbec',10),
('drinks','이탈리아 수퍼 투스칸','Sassicaia DOC Bolgheri','IT','First Super Tuscan 1968; Cabernet in Tuscany, Bolgheri coastal hills',20),
('drinks','이탈리아 바롤로','Barolo Monfortino Giacomo Conterno','IT','King of Italian wines; Nebbiolo Serralunga, aged 8+ years in botte',15),
('drinks','이탈리아 아마로네','Amarone della Valpolicella Classico','IT','Dried grape wine; Corvina Rondinella 15%+ alcohol, Verona Veneto',10),
('drinks','스페인 베가 시실리아','Vega Sicilia Unico','ES','Spain legendary wine; Tempranillo Cabernet aged 10+ years, Ribera del Duero',20),
('drinks','스페인 핑구스','Dominio de Pingus, Ribera del Duero','ES','Peter Sisseck cult Tempranillo; tiny 4-5,000 bottles, Spain top wine',20),
('drinks','포르투 그라함스','Graham 1963 Vintage Port','PT','Legendary vintage; black strap molasses dark berry, Douro Valley Portugal',15),
('drinks','마데이라 블랑디','Blandy 1920 Malmsey Madeira','PT','Century-old fortified wine; volcanic island magic oxidation aging',20),
('drinks','그리스 비노 산토','Vinsanto, Santorini','GR','Sun-dried Assyrtiko dessert wine; volcanic pumice soil, Santorini',10),
('drinks','독일 트로켄베에렌아우스레제','Egon Muller Scharzhofberger TBA','DE','World most expensive dessert wine; Mosel Riesling botrytis concentrate',20),
('drinks','오스트리아 아이스바인','Alois Kracher TBA Collection','AT','Hungarian border Burgenland; Trockenbeerenauslese and Eiswein legacy',15),
('drinks','헝가리 토카이','Tokaji Aszu 6 Puttonyos','HU','Royal Tokaj; botrytis aszú grapes 1630 vintage; Hungary national treasure',15),
('drinks','잼메이카 럼','Appleton Estate 50 Year Jamaica Rum','JM','World oldest aged rum blend; Nassau Valley copper pot stills Jamaica',20),
('drinks','바르바도스 럼','Mount Gay 1703 Rum','BB','World oldest rum brand; coral limestone filtered water, Barbados 1703',15),
('drinks','쿠바 론 산티아고','Ron Santiago de Cuba 50 Years','CU','Cuban aged rum; Santiago de Cuba distillery, aged in American oak',15),
('drinks','마르티니크 론 클레망','Rhum Clement XO Martinique','MQ','AOC Martinique rhum agricole; fresh cane juice Column still, French Caribbean',15),
('drinks','하와이 오콜레하오','Okolehao Hawaiian Spirit','US','Fermented ti root distillate; indigenous Hawaiian moonshine tradition',10),
('drinks','일본 사케','Dassai 23 Junmai Daiginjo','JP','23% rice polishing ratio; Asahi Shuzo, premium rice wine Yamaguchi',15),
('drinks','한국 전통주','Andong Soju (Distilled Traditional)','KR','Traditional Korean distilled soju; 45% ABV Andong Gyeongbuk origin',10),
('drinks','한국 막걸리','Premium Makgeolli (Korean Rice Wine)','KR','Milky fermented rice wine; Sanseongmakgeolli Gyeonggi artisanal',10),
('drinks','중국 바이주','Moutai (Kweichow Maotai)','CN','China most prestigious baijiu; sauce-aroma sorghum Guizhou, 53% ABV',15),
('drinks','중국 오량예','Wuliangye Baijiu','CN','Five-grain strong-aroma baijiu; sorghum rice corn wheat glutinous, Sichuan',10),
('drinks','인도 싱글 몰트','Amrut Fusion Single Malt','IN','Indian and Scotch barley blend; Bangalore high altitude, world awards',10),
('drinks','인도 헬라스 오크','Paul John Mithuna','IN','Rare Goan single malt; limited edition expression, India premium whisky',10),
('drinks','네팔 로키시 럭서리','Khokana Aila','NP','Traditional Newar fermented millet; Khokana village south Kathmandu',10),
('drinks','에티오피아 테지','Tej Ethiopian Honey Wine','ET','Ancient honey-hop wine; gesho buckthorn flavoring, Addis Ababa tej bars',10),
('drinks','남아프리카 피노타쥬','Kanonkop Estate Pinotage','ZA','South Africa signature grape; Simonsberg-Stellenbosch old vine vines',10),
('drinks','이스라엘 카넬','Domaine du Castel Grand Vin','IL','First Israeli fine wine; Judean Hills Cabernet Sauvignon pioneer',10),
('drinks','조지아 암포라 와인','Pheasant Tears Rkatsiteli Qvevri','GE','8,000-year wine tradition; skin-contact orange wine clay amphora Georgia',15),
('drinks','아르메니아 코냑','Ararat 50 Year Nairi Brandy','AM','Armenian brandy aged 50 years; Yerevan Ararat Brandy Factory UNESCO',15),
('drinks','멕시코 할라파네뇨 테킬라','Clase Azul Reposado Tequila','MX','Hand-crafted ceramic bottle; organic agave 2-month oak rest Mexico',10),
('drinks','맥주 바이에른 헤페바이젠','Weihenstephan Hefeweissbier','DE','World oldest brewery 1040 AD; banana-clove yeast notes, Freising Bavaria',10),
('drinks','체코 필스너','Pilsner Urquell Original','CZ','World first pale lager 1842; Pilsen Czech Republic golden revolution',10),
('drinks','벨기에 트라피스트 웨스트말레','Westmalle Tripel Trappist','BE','Defining Trappist tripel recipe; Malle monastery Belgium, golden abbey',15),
('drinks','벨기에 바이젠 로체포르','Rochefort 10 Trappist','BE','Darkest most complex Trappist; quadrupel style, Rochefort Abbey Belgium',15),
('drinks','아이리쉬 기네스','Guinness Stout (at source)','IE','Nitrogen-poured Dublin black gold; St James Gate Brewery tour 1759 Dublin',10),
('drinks','독일 옥토버페스트 마르젠','Paulaner Oktoberfest Marzen','DE','Munich original Marzen lager; Bavarian strength amber, Oktoberfest tent',10),
('drinks','에스토니아 바나 탈린','Vana Tallinn Liqueur','EE','Estonian rum-based liqueur; exotic spice blend, amber label since 1960',10),
('drinks','라플란드 아쿠아비트','Linie Aquavit','NO','Caraway-dill spirit crossing equator twice in sherry cask; Norway Norway',10),
('drinks','스웨덴 압솔루트','Absolut Elyx Single Estate Vodka','SE','Copper pot still wheat vodka; Ahus estate Sweden luxury expression',10),
('drinks','폴란드 주브로프카','Zubrowka Bison Grass Vodka','PL','Bialowieza bison grass infused; green label Poland iconic spirit',10),
('drinks','핀란드 코스케넨코르바','Koskenkorva Viina','FI','Finland most traditional spirit; barley from Koskenkorva farm since 1953',10),
('drinks','아이슬란드 브렌니빈','Brennivin Black Death Schnapps','IS','Caraway-flavored aquavit; Iceland national spirit since 1935, Reykjavik',10),
('drinks','노르웨이 리니에','Lysholm Linie Aquavit 2 Year','NO','Aged in Oloroso sherry casks; crossed equator twice on ocean voyage',10),
('drinks','네덜란드 예네버','Bols Genever 1820 Barrel-Aged','NL','Ancestor of modern gin; malt wine base, Amsterdam 1820 recipe restored',10),
('drinks','터키 라키','Raki Yeni Raki','TR','Anise spirit of Turkey; double-distilled grape raki, turns white with water',10),
('drinks','그리스 우조','Ouzo 12','GR','Anise-flavored Greek spirit; Plomari Lesvos island artisan best quality',10),
('drinks','레바논 아라크','Arak Chateau Ksara','LB','Lebanese triple-distilled arak; anise grape spirit, Bekaa Valley Lebanon',10),
('drinks','이란 토디','Arak Sefid','IR','Clear Iranian spirit; anise base, illegal but culturally ubiquitous',10),
('drinks','인도 펜자브 위스키','Royal Stag Barrel Select','IN','India biggest selling whisky; Pernod Ricard grain and Scotch blend India',10),
('drinks','캐나다 아이스와인','Inniskillin Vidal Icewine','CA','Canada invented icewine legally; frozen grapes -8C harvest, Niagara',15),
('drinks','미국 부어본 퍼피','Pappy Van Winkle 23 Year','US','Holy grail bourbon; Buffalo Trace 23-year wheated mashbill, Kentucky',20),
('drinks','미국 줄리에트','Elijah Craig Barrel Proof','US','Heaven Hill single barrel; natural proof old rye bourbon, Kentucky',15),
('drinks','미국 이오와 위스키','Templeton Rye Whiskey','US','Al Capone favorite rye; Iowa small town prohibition-era recipe revival',10),
('drinks','아이티 클레랑','Barbancourt 15 Year Reserve Speciale','HT','Sugarcane juice rhum agricole; aging French Limousin oak, Haiti',10),
('drinks','에콰도르 카냐조','Espiritu del Ecuador Cana','EC','Ecuadorian sugar cane spirit; Andean highlands artisan small batch',10),
('drinks','브라질 카샤사','Avua Amburana Cachaca','BR','Aged in rare amburana wood; unique vanilla-cinnamon profile, Brazil',10),
('drinks','볼리비아 싱가니','Rujero Gran Reserva Singani','BO','Bolivia white Muscat grape spirit; Andean high altitude terroir',10),
('drinks','베트남 쌀 와인','Ruou Nep Cam (Sticky Rice Wine)','VN','Purple glutinous rice fermented; Moc Chau highland specialty, Vietnam',10),
('drinks','필리핀 람바녹','Lambanog Coconut Spirit','PH','Philippine distilled coconut sap; Quezon Province artisanal label',10),
('drinks','태국 쌀 위스키','Mekhong Original','TH','Thailand rum-whisky hybrid; sugarcane and rice 35% ABV Thai classic',10),
('drinks','인도네시아 아락','Batavia Arrack van Oosten','ID','Sugarcane and red rice ferment; Java island colonial spirit tradition',10),
('drinks','마다가스카르 토마시나','Three Horses Beer Madagascar','MG','Madagascar premium lager; Three Horses Brewery since 1958, Antananarivo',10),
('drinks','케냐 투스커 맥주','Tusker Lager Kenya','KE','Kenya iconic beer; George Hurst killed by elephant 1923 lager label',10),
('drinks','남아프리카 믈라가지','Amarula Cream Liqueur','ZA','Marula fruit elephant favorite; South Africa iconic export since 1989',10),
('drinks','말라위 목카','Malawi Gin (Ndola)','MW','Quinine bark botanicals; sub-Saharan Africa artisan small batch gin',10),
('drinks','이탈리아 그라파','Nonino Grappa Monovitigno','IT','Pomace distillate from single grape variety; Friuli Italy finest grappa',15),
('drinks','스페인 셰리','Alvear Pedro Ximenez 1927 Solera','ES','World oldest Pedro Ximenez solera; Montilla-Moriles Spain raisin wine',15);

-- =============================================
-- ISLANDS: 세계 100대 아름다운 섬 (16번째 카테고리)
-- =============================================
INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points) VALUES
('islands','몰디브 바 아톨','Baa Atoll, Maldives','MV','UNESCO Biosphere; manta rays Hanifaru Bay, gin-clear lagoons overwater',20),
('islands','보라보라','Bora Bora, French Polynesia','PF','Turquoise lagoon, Mount Otemanu; luxury overwater villas, Society Islands',20),
('islands','팔라완','Palawan, Philippines','PH','World Best Island magazine; El Nido limestone, Coron wrecks, Puerto Princesa',15),
('islands','코모도','Komodo Island, Indonesia','ID','Dragon country; Pink Beach, coral-fringed volcanic island, Flores Indonesia',15),
('islands','갈라파고스 섬','Santa Cruz, Galapagos','EC','Giant tortoises up close; Charles Darwin Research Station, Ecuador Pacific',20),
('islands','마다가스카르 노시베','Nosy Be, Madagascar','MG','Ylang ylang perfume island; whale sharks October-December, Indian Ocean',15),
('islands','잔지바르','Zanzibar, Tanzania','TZ','Stone Town UNESCO, spice tours, Nungwi beach, dolphin snorkel, Tanzania',10),
('islands','세이셸 프라슬랭','Praslin, Seychelles','SC','Vallee de Mai UNESCO; coco de mer palm only here, Anse Lazio beach',20),
('islands','아오라키 마운트쿡','Stewart Island (Rakiura), New Zealand','NZ','Kiwi bird 85% of NZ kiwi population; southern aurora, Foveaux Strait',15),
('islands','피지 야사와','Yasawa Islands, Fiji','FJ','Blue Lagoon caves, Sawa-i-lau limestone, traditional village, remote',15),
('islands','타히티','Tahiti, French Polynesia','PF','Gauguin paintings; Teahupo''o surf, Faarumai waterfall, Papeete market',15),
('islands','모레아','Moorea, French Polynesia','PF','Heart-shaped volcanic island; dolphin watching, snorkel stingray city',15),
('islands','하와이 빅 아일랜드','Big Island, Hawaii','US','Active lava flow, Mauna Kea stargazing, black/green/white beaches',15),
('islands','마우이','Maui, Hawaii','US','Road to Hana waterfall, Haleakala crater sunrise, whale watching Jan-Mar',15),
('islands','카우아이','Kauai, Hawaii','US','Na Pali Coast cliffs, Waimea Canyon, Hanalei Bay, jurassic landscape',15),
('islands','오아후','Oahu, Hawaii','US','Pearl Harbor, North Shore Pipeline, Waikiki, Diamond Head crater',10),
('islands','코스타 리카 코코스 섬','Cocos Island, Costa Rica','CR','UNESCO uninhabited island; schooling hammerheads, whale sharks, remote',20),
('islands','쿠바 까요 코코','Cayo Coco, Cuba','CU','Pink flamingos on beach; unspoiled coral reef, cayeria norte Cuba',10),
('islands','자메이카','Jamaica','JM','Seven Mile Beach, Bob Marley culture, Blue Mountain coffee, jerk chicken',10),
('islands','바르바도스','Barbados','BB','Coral architecture, flying fish, Harrison Cave, rum distillery tours',10),
('islands','세인트 루시아','St Lucia','LC','Piton volcano twins from sea; Sulphur Springs drive-in volcano, sailing',15),
('islands','도미니카','Dominica','DM','Nature island; boiling lake trek, Trafalgar Falls, sperm whale capital',15),
('islands','앤티가','Antigua','AG','365 beaches; English Harbour Nelson Dockyard, sailing regatta paradise',10),
('islands','BVI 브리티시 버진 아일랜드','British Virgin Islands','VG','RMS Rhone wreck, Tortola, Jost Van Dyke Soggy Dollar, sailing mecca',10),
('islands','아조레스 상 미겔','Sao Miguel, Azores','PT','Seven lakes island; Sete Cidades twin crater, whale watching, thermal baths',10),
('islands','마데이라','Madeira, Portugal','PT','Levada walks, toboggan sledge, Blandy wine lodge, botanical garden',10),
('islands','카나리아 라 고메라','La Gomera, Canary Islands','ES','Garajonay rainforest UNESCO; Silbo whistle language, remote Atlantic island',10),
('islands','카나리아 엘 에이로','El Hierro, Canary Islands','ES','UNESCO Biosphere; Mar de las Calmas marine reserve, dragon tree forest',15),
('islands','란사로테','Lanzarote, Canary Islands','ES','Volcanic moonscape; Timanfaya lava, Jameos del Agua caves, wind art',10),
('islands','사르디니아','Sardinia, Italy','IT','Costa Smeralda emerald water, nuraghe bronze towers, cannonau wine',10),
('islands','코르시카','Corsica, France','FR','Napoleon birthplace; Scandola UNESCO reserve, marquis granite landscape',10),
('islands','시칠리아','Sicily, Italy','IT','Mount Etna active volcano, Valley of Temples, Taormina theater, arancini',10),
('islands','이비자','Ibiza, Spain','ES','Club culture, sunset at Cafe del Mar, Es Vedra rock, salt flats',10),
('islands','마요르카','Mallorca, Spain','ES','Tramuntana UNESCO mountains, Valldemossa Chopin, crystal coves, cycling',10),
('islands','에비사','Formentera, Spain','ES','Ibiza quieter neighbor; Ses Illetes transparent sea, hippie markets',15),
('islands','산토리니','Santorini, Greece','GR','Caldera sunset Oia, white dome churches, black sand Perissa beach',10),
('islands','미코노스','Mykonos, Greece','GR','Windmills, Little Venice, Delos archaeology, cosmopolitan Cyclades',10),
('islands','크레타','Crete, Greece','GR','Minoan Palace Knossos, Samaria Gorge, Balos lagoon, raki Cretan food',10),
('islands','코르푸','Corfu, Greece','GR','Achilleion palace, old fort UNESCO, olive groves, Paleokastritsa monastery',10),
('islands','팍소스','Paxos, Greece','GR','Tiny Ionian jewel; olive-fringed sea caves Ipapanti, anti-Paxos boat day',15),
('islands','크로아티아 흐바르','Hvar, Croatia','HR','Lavender fields, Fortica fortress, clear Adriatic, celebrity yachts',10),
('islands','비스 섬','Vis, Croatia','HR','Remote Dalmatian island; Blue Grotto, Bisevo mussels, Tito Cave bunker',15),
('islands','두브로브니크 부근 코르쿨라','Korcula, Croatia','HR','Marco Polo birthplace; medieval walled town, moreska sword dance',10),
('islands','몬테네그로 스브치아이 아일랜드','Our Lady of the Rocks, Montenegro','ME','Artificial island church in Bay of Kotor; silver ex-voto collection',10),
('islands','몰타','Malta Island','MT','Valletta UNESCO capital, Azure Window (pre-collapse), Hypogeum 5000BC',10),
('islands','고조','Gozo, Malta','MT','Azure Window site, Xlendi Bay, salt pans Marsalforn, limestone rural',10),
('islands','사이프러스','Cyprus','CY','Aphrodite birthplace; Troodos mountains, Paphos mosaics, Akamas peninsula',10),
('islands','아이슬란드','Iceland (island nation)','IS','Volcanic island; geysers, aurora, glaciers, Landmannalaugar rhyolite',15),
('islands','페로 제도','Faroe Islands, Denmark','FO','Dramatic cliffs, grass-roofed houses, puffin colonies, UNESCO fjords',20),
('islands','스발바르 제도','Svalbard, Norway','NO','80N polar bears outnumber humans; glaciers, midnight sun, Arctic',20),
('islands','그린란드 일루리삿','Ilulissat, Greenland','GL','UNESCO Icefjord; icebergs as tall as buildings, dogsled, aurora',20),
('islands','아이슬란드 헤이마에이','Heimaey, Westman Islands','IS','1973 volcanic eruption buried half town; puffin capital of world',15),
('islands','타스마니아','Tasmania, Australia','AU','Cradle Mountain, Bay of Fires, MONA gallery, quolls and devils',15),
('islands','로드 하우 섬','Lord Howe Island, Australia','AU','World rarest island; 400 residents max visitors, Balls Pyramid sea stack',20),
('islands','프레이저 섬','Fraser Island (K gari), Australia','AU','World largest sand island; freshwater lakes, dingo, shipwrecks, QLD',10),
('islands','코코스 키링','Cocos (Keeling) Islands','CC','Australian territory; pristine atoll, great frigate birds, turtle nesting',20),
('islands','크리스마스 섬','Christmas Island','CX','Red crab migration; robber crabs, Abbott booby, Indian Ocean Australia',15),
('islands','솔로몬 제도 말라이타','Malaita, Solomon Islands','SB','Traditional lagoon villages, artificial islands, shark callers, Melanesia',20),
('islands','바누아투 타나','Tanna, Vanuatu','VU','Yasur active volcano at night; custom villages, John Frum cargo cult',20),
('islands','뉴 칼레도니아 바다','Lifou, New Caledonia','NC','UNESCO lagoon biggest; pink sand, endemic birds, French Pacific',15),
('islands','통가 하파이','Ha apai, Tonga','TO','Humpback whale mother-calf snorkel; uninhabited pink-sand atolls',20),
('islands','사모아 우폴루','Upolu, Samoa','WS','Robert Louis Stevenson grave; To-Sua trench swim, fale by ocean',10),
('islands','니우에','Niue Island','NU','World smallest self-governing island nation; chasms, coral arches, turtles',20),
('islands','쿡 아일랜드 아이투타키','Aitutaki, Cook Islands','CK','World most beautiful lagoon; One Foot Island, gin-clear turquoise',20),
('islands','키리바시 타라와','Tarawa, Kiribati','KI','WWII Battle of Tarawa; equatorial atoll, Line Islands, Phoenix Islands',15),
('islands','마셜 군도 마주로','Majuro, Marshall Islands','MH','WWII history; bikini atoll UNESCO, atolls and reef, Micronesia Pacific',15),
('islands','팔라우 록 아일랜드','Rock Islands, Palau','PW','UNESCO limestone mushroom islands; Jellyfish Lake, WWII wrecks',20),
('islands','야프 섬','Yap, Micronesia','FM','Stone money Rai; manta rays at Yap Caverns, Bechiyal Cultural Center',15),
('islands','나우루','Nauru','NR','World third smallest nation; phosphate mining moonscape, isolated Pacific',15),
('islands','투발루 푸나푸티','Funafuti, Tuvalu','TV','World most remote nation; disappearing atoll, climate change front line',20),
('islands','세인트 헬레나','St Helena, British territory','SH','Napoleon exile island; most remote inhabited island, endemic wire bird',20),
('islands','트리스탄 다 쿠냐','Tristan da Cunha','GB','Most remote permanently inhabited island; 240 people, no airport',20),
('islands','어센션 섬','Ascension Island','GB','Green turtle nesting; Wideawake Terns, equatorial South Atlantic',20),
('islands','포클랜드','Falkland Islands','FK','Penguin colonies, sea lions, albatross; remote South Atlantic islands',15),
('islands','사우스 조지아','South Georgia','GS','King penguin colony 500,000; elephant seals, albatross, Shackleton grave',20),
('islands','앤틸레스 세인트 마르텐','Sint Maarten/Saint Martin','SX','Two nations one island; Maho Beach planes land 10m over sunbathers',10),
('islands','카리브 소시에다 쿠아드라','Saba, Dutch Caribbean','NL','Smallest Caribbean island; lush volcanic peak, best diving in Antilles',10),
('islands','레위니옹','Reunion Island, France','RE','Piton de la Fournaise active volcano; Piton des Neiges 3,070m, cirques',15),
('islands','모리셔스','Mauritius','MU','Seven Colored Earth Chamarel, Ile aux Cerfs, swimming with dolphins',10),
('islands','로드리게스','Rodrigues, Mauritius','MU','Last wilderness Mauritian island; kite surfing, endemic species, Francois',15),
('islands','마요트','Mayotte, France','YT','Lagoon second largest barrier reef; hammerhead nursery, turtles, dhow',15),
('islands','페르난도 드 노로냐','Fernando de Noronha, Brazil','BR','UNESCO; spinner dolphins, sea turtles, pristine Atlantic archipelago Brazil',20),
('islands','일랴 그란데','Ilha Grande, Brazil','BR','Atlantic Forest reserve; Lopes Mendes beach, no cars, Rio state Brazil',10),
('islands','산 안드레스','San Andres, Colombia','CO','Sea of Seven Colors; coral atoll Caribbean, Colombia territory Honduras',10),
('islands','구아달루페','Guadeloupe, France','MQ','Butterfly-shaped Antilles; Soufriere volcano, Falls Carbet, Creole culture',10),
('islands','도미니카 앤틸리스','Marie-Galante, Guadeloupe','FR','Unspoiled sugar island; rum distilleries, Grand Bourg carnival, Antilles',10),
('islands','쿠바 까요 산타 마리아','Cayo Santa Maria, Cuba','CU','White sand causeway island; all-inclusive coral reef Cuba north coast',10),
('islands','바하마 에셀루스라','Eleuthera, Bahamas','BS','Glass Window Bridge; Atlantic meets Caribbean, world pineapple capital',10),
('islands','터크스 앤 케이코스','Providenciales, Turks and Caicos','TC','Grace Bay infinite turquoise; third largest barrier reef, Caribbean',15),
('islands','앤귈라','Anguilla','AI','Shoal Bay best Caribbean beach; 33 pristine beaches, luxury seclusion',15);
