-- Art Galleries: 100개 복구 (갑자기 안 나올 때 / DB 리셋 후)
-- art_galleries가 0건일 때만 삽입 (기존 데이터 보존)
-- CHECK 제약에 art_galleries 포함되어 있어야 함 (없으면 아래로 추가 후 INSERT)

ALTER TABLE public.challenges DROP CONSTRAINT IF EXISTS challenges_category_check;
ALTER TABLE public.challenges
  ADD CONSTRAINT challenges_category_check
  CHECK (category IN (
    'attractions','foods','golf','countries','restaurants',
    'animals','festivals','nature','surfing','skiing','scuba',
    'museums','art_galleries','fishing','drinks','islands'
  ));

INSERT INTO public.challenges (category, title_ko, title_en, country_code, description_en, points)
SELECT t.cat, t.title_ko, t.title_en, t.country_code, t.description_en, t.points
FROM (VALUES
  ('art_galleries','모마 (뉴욕)','MoMA – Museum of Modern Art','US','Starry Night, Warhol, Pollock; modern art temple, 54th St Midtown NYC',10),
  ('art_galleries','테이트 모던','Tate Modern, London','GB','Turbine Hall installations, Warhol, Rothko, free entry, Bankside London',10),
  ('art_galleries','구겐하임 뉴욕','Guggenheim Museum, New York','US','Frank Lloyd Wright spiral; Chagall, Picasso, Braque, 5th Avenue NYC',10),
  ('art_galleries','구겐하임 빌바오','Guggenheim Bilbao','ES','Jeff Koons Puppy, Richard Serra; Gehry titanium masterpiece, Bilbao Spain',10),
  ('art_galleries','테이트 브리튼','Tate Britain, London','GB','Turner Prize, Pre-Raphaelites, British art 1500 to now; Millbank London',10),
  ('art_galleries','퐁피두 파리','Centre Pompidou, Paris','FR','Matisse, Dali, Duchamp; inside-out coloured pipes building, Paris',10),
  ('art_galleries','국립 현대 미술관 (파리)','Musee National d Art Moderne, Paris','FR','Europe largest modern art collection inside Pompidou, Paris France',10),
  ('art_galleries','라 팔레스 드 도쿄','Palais de Tokyo, Paris','FR','Cutting-edge contemporary art; largest contemporary art centre in Europe',10),
  ('art_galleries','아르세날레 베니스','Venice Arsenale & Giardini','IT','Venice Biennale pavilions; world most prestigious art event biennial',20),
  ('art_galleries','마드리드 카이샤 포럼','CaixaForum Madrid','ES','Patrick Blanc vertical garden; Herzog de Meuron conversion, Madrid',10),
  ('art_galleries','밀라노 트리에날레','Triennale di Milano','IT','Design and contemporary art; Parco Sempione Milan Italy triennial',10),
  ('art_galleries','취리히 미술관','Kunsthaus Zurich','CH','Van Gogh, Munch, Giacometti; Switzerland national collection, Zurich',10),
  ('art_galleries','암스테르담 반 고흐 미술관','Van Gogh Museum, Amsterdam','NL','200 paintings, 500 drawings; Almond Blossom, Sunflowers originals',15),
  ('art_galleries','암스테르담 스테델레이크','Stedelijk Museum, Amsterdam','NL','Mondrian, Malevich, Appel; Dutch CoBrA movement collection, Amsterdam',10),
  ('art_galleries','뮌헨 피나코테크 3관','Alte/Neue/Moderne Pinakothek, Munich','DE','Rubens, Raphael, Cezanne; three centuries of European art, Munich',10),
  ('art_galleries','베를린 알테스 나치오날갤러리','Alte Nationalgalerie, Berlin','DE','Friedrich, Menzel, Schinkel; German Romantic masters, Berlin Museum Island',10),
  ('art_galleries','베를린 함부르거 반호프','Hamburger Bahnhof, Berlin','DE','Beuys, Warhol, Twombly; contemporary art railway station, Berlin',10),
  ('art_galleries','드레스덴 게말데 갤러리','Gemaldegalerie Alte Meister, Dresden','DE','Raphael Sistine Madonna; old masters gallery, Zwinger Palace Dresden',10),
  ('art_galleries','비엔나 알베르티나','Albertina, Vienna','AT','Monet, Modigliani, Klimt; Habsburg graphics collection, Vienna',10),
  ('art_galleries','빈 벨베데레','Belvedere, Vienna','AT','Klimt Kiss original; Schiele, Kokoschka; Baroque palace gardens, Vienna',15),
  ('art_galleries','스톡홀름 현대 미술관','Moderna Museet, Stockholm','SE','Duchamp, Picabia, Swedish masters; Skeppsholmen island Stockholm',10),
  ('art_galleries','오슬로 국립 미술관','National Museum, Oslo','NO','Munch Scream original; Cezanne, Matisse; new building 2022, Oslo',15),
  ('art_galleries','헬싱키 아테네움','Ateneum Art Museum, Helsinki','FI','Gallen-Kallela, Edelfelt, Schjerfbeck; Finnish national collection',10),
  ('art_galleries','코펜하겐 글립토테크','Ny Carlsberg Glyptotek, Copenhagen','DK','Gauguin, Rodin, Degas; Carl Jacobsen collection, Copenhagen',10),
  ('art_galleries','코펜하겐 루이지애나','Louisiana Museum of Modern Art','DK','Giacometti, Picasso, Calder; clifftop Oresund views, Humlebaek Denmark',15),
  ('art_galleries','리스본 베라르도 컬렉션','Berardo Collection Museum, Lisbon','PT','Warhol, Picasso, Duchamp, Klein; Belem free entry, Lisbon Portugal',10),
  ('art_galleries','포르투 세라베스','Serralves Museum of Contemporary Art','PT','Alvaro Siza building; large garden, contemporary, Porto Portugal',10),
  ('art_galleries','마드리드 카이샤 포럼 바르셀로나','Fundacio Joan Miro, Barcelona','ES','Miro universe; hilltop Montjuic building, Barcelona Catalonia Spain',10),
  ('art_galleries','바르셀로나 카탈루냐 미술관','MNAC, Barcelona','ES','Romanesque frescoes, Modernisme; Montjuic National Palace, Barcelona',10),
  ('art_galleries','뉴욕 휘트니 미술관','Whitney Museum of American Art','US','Hopper Nighthawks study, Basquiat, Koons; Meatpacking District NYC',10),
  ('art_galleries','샌프란시스코 현대 미술관','SFMOMA, San Francisco','US','Frida Kahlo, Warhol, Matisse; 7-story expansion 2016, SF California',10),
  ('art_galleries','시카고 미술관','Art Institute of Chicago','US','Seurat Sunday, Wood American Gothic, Hopper Nighthawks; Magnificent Mile',10),
  ('art_galleries','LA 카운티 미술관','LACMA, Los Angeles','US','Largest US West Coast art museum; Urban Light lamp post forest, LA',10),
  ('art_galleries','워싱턴 국립 미술관','National Gallery of Art, Washington DC','US','Da Vinci only in Americas; Vermeer, Raphael, Rembrandt; free DC',10),
  ('art_galleries','보스턴 미술관','Museum of Fine Arts, Boston','US','Monet, Renoir, Japanese prints; second largest US art museum, Boston',10),
  ('art_galleries','캐나다 국립 미술관','National Gallery of Canada, Ottawa','CA','Emily Carr, Group of Seven; stained glass Rideau Chapel, Ottawa free',10),
  ('art_galleries','몬트리올 미술관','Montreal Museum of Fine Arts','CA','Largest museum in Canada; Egyptian mummies, Gauguin, Montreal Quebec',10),
  ('art_galleries','멜버른 NGV 국제','NGV International, Melbourne','AU','Asia-Pacific largest art museum; Tiepolo, Rembrandt, free entry Melbourne',10),
  ('art_galleries','시드니 현대 미술관','Museum of Contemporary Art, Sydney','AU','MCA on Circular Quay; Australian Indigenous, Aboriginal dot painting',10),
  ('art_galleries','도쿄 국립 근대 미술관','Tokyo National Museum of Modern Art','JP','Yokoyama Taikan, Kuroda Seiki; next to Imperial Palace, Chiyoda Tokyo',10),
  ('art_galleries','도쿄 모리 미술관','Mori Art Museum, Tokyo','JP','53rd floor Roppongi Hills; panoramic Tokyo views plus contemporary art',10),
  ('art_galleries','도쿄 오페라시티 갤러리','Tokyo Opera City Art Gallery','JP','Japanese contemporary masters; chamber music venue complex, Shinjuku',10),
  ('art_galleries','나오시마 섬 미술관','Chichu Art Museum, Naoshima','JP','Tadao Ando underground museum; Monet Water Lilies in situ, Naoshima',20),
  ('art_galleries','서울 국립 현대 미술관','MMCA National Museum of Modern Art','KR','Deoksugung, Gwacheon, Seoul, Cheongju four branches; free Sundays',10),
  ('art_galleries','서울 리움 미술관','Leeum Samsung Museum of Art','KR','Kansai Siza Nouvel Koolhaas; celadon to contemporary, Hannam Seoul',15),
  ('art_galleries','상하이 현대 미술관','Power Station of Art, Shanghai','CN','National pavilion Shanghai Biennale; converted power station Huangpu',10),
  ('art_galleries','베이징 UCCA','UCCA Center for Contemporary Art, Beijing','CN','Anish Kapoor, Ai Weiwei; 798 Art District factory complex, Beijing',10),
  ('art_galleries','홍콩 M+','M+ Museum, West Kowloon','HK','Asia largest visual culture museum; Herzog de Meuron building 2021',10),
  ('art_galleries','싱가포르 국립 미술관','National Gallery Singapore','SG','Colonial Civic District buildings; Southeast Asian art 1900 to now',10),
  ('art_galleries','무하 미술관 프라하','Mucha Museum, Prague','CZ','Alphonse Mucha Art Nouveau; Slav Epic, Rue detail, Old Town Prague',10),
  ('art_galleries','부다페스트 미술관','Museum of Fine Arts, Budapest','HU','El Greco, Raphael, Goya; Egyptian collection, Heroes Square Budapest',10),
  ('art_galleries','바르샤바 국립 박물관 미술','National Museum Warsaw (art)','PL','Faras Nubian frescoes, Rubens, Polish masters; Warsaw Poland',10),
  ('art_galleries','프라하 국립 미술관','National Gallery Prague','CZ','Cranach, Rubens, Klimt Kiss copy; Veletrzni Palac building, Prague',10),
  ('art_galleries','키예프 우크라이나 국립 미술관','National Art Museum of Ukraine','UA','Ukrainian Baroque icons, Shevchenko; Grushevsky Street Kyiv',10),
  ('art_galleries','상트페테르부르크 러시아 미술관','Russian Museum, St Petersburg','RU','Repin, Aivazovsky, Kandinsky; Mikhailovsky Palace, St Petersburg',10),
  ('art_galleries','카이로 현대 이집트 미술관','Museum of Modern Egyptian Art','EG','Mahmoud Said, Ragheb Ayad; Opera Square Garden, Cairo Egypt',10),
  ('art_galleries','테헤란 현대 미술관','Tehran Museum of Contemporary Art','IR','Warhol, Pollock, Miro; hid from revolution 1979; now showing, Tehran',15),
  ('art_galleries','이스탄불 현대 미술관','Istanbul Modern','TR','Turkish contemporary art; Tophane waterfront, Bosphorus view Istanbul',10),
  ('art_galleries','텔아비브 미술관','Tel Aviv Museum of Art','IL','Impressionism, Cobra, Israeli Expressionism; Helena Rubinstein Pavilion',10),
  ('art_galleries','두바이 잠 엘 아트','Jameel Arts Centre, Dubai','AE','Contemporary Middle Eastern art; waterfront Dubai Creek Jaddaf',10),
  ('art_galleries','아부다비 루브르','Louvre Abu Dhabi','AE','Jean Nouvel star-pierced dome; Da Vinci, Pissarro, Magritte; Saadiyat',20),
  ('art_galleries','요하네스버그 게르투르트 포케 갤러리','Johannesburg Art Gallery','ZA','Rodin, Modigliani, African prints; Joubert Park largest in South Africa',10),
  ('art_galleries','나이로비 나즈마 미술관','Nairobi National Museum (art)','KE','Kenyan contemporary art, Joy Adamson wildlife paintings; Kenya',10),
  ('art_galleries','상파울루 MASP','MASP Sao Paulo','BR','Botticelli to Van Gogh suspended in glass; Paulista Avenue icon Brazil',10),
  ('art_galleries','부에노스 아이레스 국립 미술관','Museo Nacional de Bellas Artes, Buenos Aires','AR','Rodin, Renoir, Gauguin; largest collection in Latin America, Recoleta',10),
  ('art_galleries','멕시코 팔라시오 데 벨라스 아르테스','Palacio de Bellas Artes, Mexico City','MX','Rivera, Orozco, Siqueiros murals; Art Deco marble, Alameda Park',15),
  ('art_galleries','멕시코 프리다 칼로 뮤지엄','Frida Kahlo Museum (Casa Azul), Mexico City','MX','Blue House where Frida was born and died; Coyoacan, Mexico City',15),
  ('art_galleries','리마 아르코 갤러리','MALI (Museo de Arte de Lima)','PE','Pre-Columbian to Republican; largest collection in Peru, Lima Paseo Colon',10),
  ('art_galleries','보고타 루이스 앙헬 아랑고','Banco de la Republica Art Collection, Bogota','CO','Botero paintings and sculptures; free admission La Candelaria Bogota',10),
  ('art_galleries','산티아고 칠레 현대 미술관','MAC, Santiago de Chile','CL','Chilean contemporary masters; Parque Forestal riverside Santiago',10),
  ('art_galleries','하바나 국립 미술관','Museo Nacional de Bellas Artes, Havana','CU','European masters and Cuban art; two buildings Old Havana Cuba',10),
  ('art_galleries','뉴질랜드 크라이스트처치 갤러리','Christchurch Art Gallery','NZ','Post-earthquake icon; New Zealand art, international contemporary',10),
  ('art_galleries','런던 서펜타인 갤러리','Serpentine Galleries, London','GB','Annual Pavilion architect commission; Hyde Park free, London',10),
  ('art_galleries','뉴욕 뉴 미술관','New Museum, New York','US','SANAA building; cutting-edge emerging artists, Lower East Side NYC',10),
  ('art_galleries','LA 게티 빌라','Getty Villa, Malibu','US','Greek and Roman antiquities; Malibu clifftop, Pacific views, LA',10),
  ('art_galleries','시애틀 미술관','Seattle Art Museum','US','Charles and Emma Frye; Hammering Man sculpture, Seattle Washington',10),
  ('art_galleries','덴버 미술관','Denver Art Museum','US','Native American, Asian, Western American; Daniel Libeskind addition',10),
  ('art_galleries','아틀란타 하이 미술관','High Museum of Art, Atlanta','US','Richard Meier white building; Impressionism, Southern American art',10),
  ('art_galleries','런던 화이트채플 갤러리','Whitechapel Gallery, London','GB','Picasso Guernica UK debut 1938; East End London contemporary free',10),
  ('art_galleries','뉴욕 가고시안 갤러리','Gagosian Gallery, New York','US','Damien Hirst, Jeff Koons, Cy Twombly; global flagship art gallery NYC',10),
  ('art_galleries','런던 화이트큐브','White Cube, London','GB','Damien Hirst, Tracey Emin; Bermondsey and Mayfair locations London',10),
  ('art_galleries','도쿄 하라 미술관','Hara Museum of Contemporary Art, Tokyo','JP','Francis Bacon, George Segal; Shinagawa garden villa 1938, Tokyo',10),
  ('art_galleries','오사카 현대 미술관','National Museum of Art Osaka','JP','Underground museum; Japanese post-war, international contemporary',10),
  ('art_galleries','교토 국립 근대 미술관','National Museum of Modern Art Kyoto','JP','Kyoto Nihonga painting tradition; bamboo-themed Okazaki building',10),
  ('art_galleries','제주 이중섭 미술관','Lee Jung-seob Museum, Jeju','KR','Bull paintings; Korea most beloved modern artist, Seogwipo Jeju',10),
  ('art_galleries','광주 아시아 문화 전당','Asia Culture Center, Gwangju','KR','ACC underground complex; May 18 memorial, Asian culture research',10),
  ('art_galleries','타이베이 당대 예술관','Taipei Contemporary Art Center','TW','Former municipal hall; Taiwan contemporary art, Datong district',10),
  ('art_galleries','하노이 베트남 미술관','Vietnam Museum of Fine Arts, Hanoi','VN','Nguyen Phan Chanh lacquer works, Dong Son bronze, French-colonial building',10),
  ('art_galleries','콜롬보 국립 미술관','National Art Gallery of Sri Lanka','LK','Sri Lankan colonial and contemporary; Lipton Circus Colombo',10),
  ('art_galleries','인도 국립 현대 미술관','National Gallery of Modern Art, Mumbai','IN','Jamini Roy, Rabindranath Tagore; King George V building, Mumbai',10),
  ('art_galleries','모스크바 현대 미술관','Moscow Museum of Modern Art','RU','Zurab Tsereteli collection; multiple venues, Russian contemporary art',10),
  ('art_galleries','부쿠레슈티 국립 미술관','National Museum of Art Romania','RO','El Greco, Rubens; former Royal Palace, Calea Victoriei Bucharest',10),
  ('art_galleries','아테네 고나리스 갤러리','National Gallery, Athens','GR','El Greco Return of the Prodigal; Greek masters, Vassileos Konstantinou',10),
  ('art_galleries','리가 라트비아 국립 미술관','Latvian National Museum of Art','LV','Latvian Romantic masters; neoclassical palace, Riga Latvia',10)
) AS t(cat, title_ko, title_en, country_code, description_en, points)
WHERE (SELECT count(*) FROM public.challenges WHERE category = 'art_galleries') = 0;
